-- impl/cemit_emit.lua
-- Methods on Cemit.*, Core.*, and C.* schema_v2 types for final C text emission.
-- Rewritten: CEmitMachine operates on LalinC.CBackendUnit, not CodeModule+LowerModule.

require("lalin.schema_v2")

local Cemit = require("lalin.schema_v2.cemit")
local C     = require("lalin.schema_v2.c")
local Core  = require("lalin.schema_v2.core")

-- Target capabilities are owned by the canonical concrete dialect leaves.
function C.CBackendC99:c_emit_supports_c11_atomics() return false end
function C.CBackendC11:c_emit_supports_c11_atomics() return true end
function C.CBackendGnuC:c_emit_supports_c11_atomics() return true end
function C.CBackendClangC:c_emit_supports_c11_atomics() return true end

function C.CBackendUnit:c_emit_sig_projection()
  local entries = {}
  for i = 1, #self.sigs do entries[i] = C.CBackendFuncSigEntry(self.sigs[i].id, self.sigs[i]) end
  return C.CBackendFuncSigProjection(entries)
end
function C.CBackendFuncSigProjection:c_emit_sig_lookup(id)
  for i = 1, #self.entries do if self.entries[i].id == id then return C.CBackendFuncSigFound(self.entries[i]) end end
  return C.CBackendFuncSigMissing(id)
end

local function func_params(params)
  local out = {}
  if not params or #params == 0 then return "void" end
  for i, p in ipairs(params) do
    out[i] = p.ty:c_emit_decl(p.id.text)
  end
  return table.concat(out, ", ")
end

-- Sanitize a string for use as a C identifier
local function sanitize(s)
  s = tostring(s or "x"):gsub("[^%w_]", "_")
  if s:match("^%d") then s = "_" .. s end
  if s == "" then s = "x" end
  return s
end

----------------------------------------------------------------------
-- CEmitMachine → emit_module / emit_source / emit_header
----------------------------------------------------------------------

function Cemit.CEmitMachine:emit_module(c_unit)
  local source = self:emit_source(c_unit)
  local header = self:emit_header(c_unit)
  return { source = source, header = header }
end

function Cemit.CEmitMachine:emit_source(c_unit)
  local lines = {}
  lines[#lines + 1] = '/* generated by lalin C backend */'

  -- Includes
  lines[#lines + 1] = '#include <stdint.h>'
  lines[#lines + 1] = '#include <stddef.h>'
  lines[#lines + 1] = '#include <stdbool.h>'
  lines[#lines + 1] = '#include <string.h>'
  lines[#lines + 1] = '#include <stdlib.h>'
  lines[#lines + 1] = ''

  -- Type declarations
  if c_unit.types and #c_unit.types > 0 then
    lines[#lines + 1] = ''
    lines[#lines + 1] = '/* type declarations */'
    for _, td in ipairs(c_unit.types) do
      td:c_emit_type_decl(lines)
    end
  end

  -- Helpers
  if c_unit.helpers and #c_unit.helpers > 0 then
    for _, h in ipairs(c_unit.helpers) do
      for _, hl in ipairs(h:c_emit_helper_lines()) do
        lines[#lines + 1] = hl
      end
      lines[#lines + 1] = ''
    end
  end

  -- Function bodies
  local signatures = c_unit:c_emit_sig_projection()
  if c_unit.funcs then
    for _, func in ipairs(c_unit.funcs) do
      func:c_emit_func_source(signatures, lines)
      lines[#lines + 1] = ''
    end
  end

  return table.concat(lines, '\n')
end

function Cemit.CEmitMachine:emit_header(c_unit)
  local module_name = c_unit.module_name or "lalin"
  local guard = sanitize(module_name .. "_h"):upper()
  local lines = {}
  lines[#lines + 1] = '/* generated by lalin C backend */'
  lines[#lines + 1] = '#ifndef ' .. guard
  lines[#lines + 1] = '#define ' .. guard
  lines[#lines + 1] = ''
  lines[#lines + 1] = '#include <stdint.h>'
  lines[#lines + 1] = '#include <stddef.h>'
  lines[#lines + 1] = '#include <stdbool.h>'
  lines[#lines + 1] = ''

  -- Type declarations
  if c_unit.types and #c_unit.types > 0 then
    lines[#lines + 1] = '/* type declarations */'
    for _, td in ipairs(c_unit.types) do
      td:c_emit_type_decl(lines)
    end
    lines[#lines + 1] = ''
  end

  -- Function prototypes

  local signatures = c_unit:c_emit_sig_projection()
  if c_unit.funcs then
    for _, func in ipairs(c_unit.funcs) do
      signatures:c_emit_sig_lookup(func.sig):c_emit_prototype(func, lines)
    end
  end
  lines[#lines + 1] = ''
  lines[#lines + 1] = '#endif /* ' .. guard .. ' */'
  return table.concat(lines, '\n')
end

----------------------------------------------------------------------
-- Core.Scalar → c_emit_scalar_name
----------------------------------------------------------------------

function Core.Scalar:c_emit_scalar_name()
  error("missing c_emit_scalar_name leaf method", 2)
end
function Core.ScalarBool:c_emit_scalar_name() return "uint8_t" end
function Core.ScalarI8:c_emit_scalar_name() return "int8_t" end
function Core.ScalarI16:c_emit_scalar_name() return "int16_t" end
function Core.ScalarI32:c_emit_scalar_name() return "int32_t" end
function Core.ScalarI64:c_emit_scalar_name() return "int64_t" end
function Core.ScalarU8:c_emit_scalar_name() return "uint8_t" end
function Core.ScalarU16:c_emit_scalar_name() return "uint16_t" end
function Core.ScalarU32:c_emit_scalar_name() return "uint32_t" end
function Core.ScalarU64:c_emit_scalar_name() return "uint64_t" end
function Core.ScalarF32:c_emit_scalar_name() return "float" end
function Core.ScalarF64:c_emit_scalar_name() return "double" end
function Core.ScalarRawPtr:c_emit_scalar_name() return "void*" end
function Core.ScalarIndex:c_emit_scalar_name() return "size_t" end
function Core.ScalarVoid:c_emit_scalar_name() return "void" end

-- Core.Literal → c_emit_literal_value
function Core.Literal:c_emit_literal_value()
  error("missing c_emit_literal_value leaf method", 2)
end
function Core.LitInt:c_emit_literal_value() return self.raw end
function Core.LitFloat:c_emit_literal_value() return self.raw end
function Core.LitBool:c_emit_literal_value() return self.value and "1" or "0" end
function Core.LitNil:c_emit_literal_value() return "0" end
function Core.LitString:c_emit_literal_value()
  return '"' .. self.bytes:gsub('"', '\\"') .. '"'
end

-- Core.CmpOp → c_emit_cmp_op
function Core.CmpOp:c_emit_cmp_op()
  error("missing c_emit_cmp_op leaf method", 2)
end
function Core.CmpEq:c_emit_cmp_op() return "==" end
function Core.CmpNe:c_emit_cmp_op() return "!=" end
function Core.CmpLt:c_emit_cmp_op() return "<" end
function Core.CmpLe:c_emit_cmp_op() return "<=" end
function Core.CmpGt:c_emit_cmp_op() return ">" end
function Core.CmpGe:c_emit_cmp_op() return ">=" end

-- Core helper suffix methods for helper name generation
function Core.Scalar:c_helper_suffix() error("missing c_helper_suffix leaf method for Scalar", 2) end
function Core.ScalarVoid:c_helper_suffix() return "void" end
function Core.ScalarBool:c_helper_suffix() return "bool8" end
function Core.ScalarI8:c_helper_suffix() return "i8" end
function Core.ScalarI16:c_helper_suffix() return "i16" end
function Core.ScalarI32:c_helper_suffix() return "i32" end
function Core.ScalarI64:c_helper_suffix() return "i64" end
function Core.ScalarU8:c_helper_suffix() return "u8" end
function Core.ScalarU16:c_helper_suffix() return "u16" end
function Core.ScalarU32:c_helper_suffix() return "u32" end
function Core.ScalarU64:c_helper_suffix() return "u64" end
function Core.ScalarF32:c_helper_suffix() return "f32" end
function Core.ScalarF64:c_helper_suffix() return "f64" end
function Core.ScalarRawPtr:c_helper_suffix() return "ptr" end
function Core.ScalarIndex:c_helper_suffix() return "index" end

function Core.UnaryOp:c_helper_suffix() error("missing c_helper_suffix leaf method for UnaryOp", 2) end
function Core.UnaryNeg:c_helper_suffix() return "neg" end
function Core.UnaryNot:c_helper_suffix() return "not" end
function Core.UnaryBitNot:c_helper_suffix() return "bitnot" end

function Core.BinaryOp:c_helper_suffix() error("missing c_helper_suffix leaf method for BinaryOp", 2) end
function Core.BinAdd:c_helper_suffix() return "add" end
function Core.BinSub:c_helper_suffix() return "sub" end
function Core.BinMul:c_helper_suffix() return "mul" end
function Core.BinDiv:c_helper_suffix() return "div" end
function Core.BinRem:c_helper_suffix() return "rem" end
function Core.BinBitAnd:c_helper_suffix() return "and" end
function Core.BinBitOr:c_helper_suffix() return "or" end
function Core.BinBitXor:c_helper_suffix() return "xor" end
function Core.BinShl:c_helper_suffix() return "shl" end
function Core.BinLShr:c_helper_suffix() return "lshr" end
function Core.BinAShr:c_helper_suffix() return "ashr" end

function Core.BinaryOp:c_helper_expr(a, b) error("missing c_helper_expr leaf method for BinaryOp", 2) end
function Core.BinAdd:c_helper_expr(a, b) return a .. " + " .. b end
function Core.BinSub:c_helper_expr(a, b) return a .. " - " .. b end
function Core.BinMul:c_helper_expr(a, b) return a .. " * " .. b end
function Core.BinDiv:c_helper_expr(a, b) return a .. " / " .. b end
function Core.BinRem:c_helper_expr(a, b) return a .. " % " .. b end
function Core.BinBitAnd:c_helper_expr(a, b) return a .. " & " .. b end
function Core.BinBitOr:c_helper_expr(a, b) return a .. " | " .. b end
function Core.BinBitXor:c_helper_expr(a, b) return a .. " ^ " .. b end
function Core.BinShl:c_helper_expr(a, b) return a .. " << " .. b end
function Core.BinLShr:c_helper_expr(a, b) return a .. " >> " .. b end
function Core.BinAShr:c_helper_expr(a, b) return a .. " >> " .. b end

----------------------------------------------------------------------
-- C.CBackendType → c_emit_type / c_emit_decl
----------------------------------------------------------------------

function C.CBackendType:c_emit_type()
  error("missing c_emit_type leaf method for " .. tostring(self), 2)
end
function C.CBackendVoid:c_emit_type() return "void" end
function C.CBackendBool8:c_emit_type() return "bool" end
function C.CBackendScalar:c_emit_type() return self.scalar:c_emit_scalar_name() end
function C.CBackendIndex:c_emit_type() return "size_t" end
function C.CBackendDataPtr:c_emit_type()
  if self.pointee then return self.pointee:c_emit_type() .. "*" end
  return "void*"
end
function C.CBackendQualifiedDataPtr:c_emit_type()
  local q = {}
  if self.const_pointee then q[#q + 1] = "const" end
  if self.volatile_pointee then q[#q + 1] = "volatile" end
  local base = self.pointee and self.pointee:c_emit_type() or "void"
  return table.concat(q, " ") .. " " .. base .. "*"
end
function C.CBackendCodePtr:c_emit_type()
  return self.sig and self.sig.text or "void(*)(void)"
end
function C.CBackendImportedCodePtr:c_emit_type()
  return self.sig and self.sig.text or "void(*)(void)"
end
function C.CBackendNamed:c_emit_type()
  return sanitize(self.id.module_name .. "_" .. self.id.spelling)
end
function C.CBackendArray:c_emit_type()
  return self.elem:c_emit_type() .. "[" .. tostring(self.count) .. "]"
end
function C.CBackendSliceDescriptor:c_emit_type() return "lalin_slice_t" end
function C.CBackendByteSpanDescriptor:c_emit_type() return "lalin_bytespan_t" end
function C.CBackendViewDescriptor:c_emit_type() return "lalin_view_t" end
function C.CBackendClosureDescriptor:c_emit_type() return "lalin_closure_t" end
function C.CBackendAbiHiddenOutPtr:c_emit_type()
  if self.result then return self.result:c_emit_type() .. "*" end
  return "void*"
end
function C.CBackendVector:c_emit_type()
  return self.elem:c_emit_type() .. " __attribute__((vector_size(" .. tostring(self.lanes * 4) .. ")))"
end

----------------------------------------------------------------------
-- named_type_name: produce the C identifier for a CTypeId
----------------------------------------------------------------------

local function named_type_name(id)
  return sanitize(id.module_name .. "_" .. id.spelling)
end

----------------------------------------------------------------------
-- C.CBackendField → c_emit_field_decl
----------------------------------------------------------------------

function C.CBackendField:c_emit_field_decl()
  local attr = (self.align and self.align > 1) and (" __attribute__((aligned(" .. tostring(self.align) .. ")))") or ""
  return "    " .. self.ty:c_emit_decl(self.name.text) .. attr .. ";"
end
function C.CBackendType:c_emit_decl(name)
  return self:c_emit_type() .. " " .. (name or "")
end

function C.CBackendType:c_helper_suffix() error("missing c_helper_suffix leaf method for CBackendType", 2) end
function C.CBackendVoid:c_helper_suffix() return "void" end
function C.CBackendBool8:c_helper_suffix() return "bool8" end
function C.CBackendScalar:c_helper_suffix() return self.scalar:c_helper_suffix() end
function C.CBackendIndex:c_helper_suffix() return "index" end
function C.CBackendDataPtr:c_helper_suffix() return "ptr" end
function C.CBackendQualifiedDataPtr:c_helper_suffix() return "ptr" end
function C.CBackendCodePtr:c_helper_suffix() return "codeptr" end
function C.CBackendImportedCodePtr:c_helper_suffix() return "codeptr" end
function C.CBackendNamed:c_helper_suffix() return sanitize(self.id.module_name .. "_" .. self.id.spelling) end
function C.CBackendArray:c_helper_suffix() return "arr" .. tostring(self.count) .. "_" .. self.elem:c_helper_suffix() end

----------------------------------------------------------------------
-- C.CBackendFuncSig → c_emit_signature
----------------------------------------------------------------------

function C.CBackendFuncSig:c_emit_signature(name)
  local ret = self.result:c_emit_type()
  local params = {}
  for _, p in ipairs(self.params or {}) do
    params[#params + 1] = p:c_emit_type()
  end
  if #params == 0 then params[1] = "void" end
  return ret .. " " .. (name or "fn") .. "(" .. table.concat(params, ", ") .. ")"
end

----------------------------------------------------------------------
-- C.CBackendTypeDecl → c_emit_type_decl
----------------------------------------------------------------------

function C.CBackendTypeDecl:c_emit_type_decl(out)
  error("missing c_emit_type_decl leaf method", 2)
end

function C.CBackendTypedef:c_emit_type_decl(out)
  local name = named_type_name(self.id)
  out[#out + 1] = "typedef " .. self.ty:c_emit_decl(name) .. ";"
end

function C.CBackendStructDecl:c_emit_type_decl(out)
  local name = named_type_name(self.id)
  out[#out + 1] = "typedef struct " .. name .. " {"
  for i = 1, #self.fields do
    out[#out + 1] = self.fields[i]:c_emit_field_decl()
  end
  out[#out + 1] = "} " .. name .. ";"
  if self.size ~= nil then
    out[#out + 1] = "typedef char ml_assert_size_" .. name .. "[(sizeof(" .. name .. ") == " .. tostring(self.size) .. ") ? 1 : -1];"
  end
  if self.align ~= nil then
    out[#out + 1] = "typedef char ml_assert_align_" .. name .. "[(offsetof(struct { char c; " .. name .. " x; }, x) == " .. tostring(self.align) .. ") ? 1 : -1];"
  end
end

function C.CBackendUnionDecl:c_emit_type_decl(out)
  local name = named_type_name(self.id)
  out[#out + 1] = "typedef union " .. name .. " {"
  for i = 1, #self.fields do
    out[#out + 1] = self.fields[i]:c_emit_field_decl()
  end
  out[#out + 1] = "} " .. name .. ";"
  if self.size ~= nil then
    out[#out + 1] = "typedef char ml_assert_size_" .. name .. "[(sizeof(" .. name .. ") == " .. tostring(self.size) .. ") ? 1 : -1];"
  end
  if self.align ~= nil then
    out[#out + 1] = "typedef char ml_assert_align_" .. name .. "[(offsetof(struct { char c; " .. name .. " x; }, x) == " .. tostring(self.align) .. ") ? 1 : -1];"
  end
end

function C.CBackendOpaqueDecl:c_emit_type_decl(out)
  local name = named_type_name(self.id)
  out[#out + 1] = "typedef struct " .. name .. " " .. name .. ";"
end

----------------------------------------------------------------------
-- C.CBackendFunc → c_emit_func_source
----------------------------------------------------------------------

function C.CBackendFunc:c_emit_func_source(signatures, out)
  signatures:c_emit_sig_lookup(self.sig):c_emit_func_open(self, out)
  for _, loc in ipairs(self.locals or {}) do
    out[#out + 1] = "  " .. loc.ty:c_emit_decl(loc.id.text) .. ";"
  end
  self.body:c_emit_body(out, "  ")
  out[#out + 1] = "}"
end
function C.CBackendFuncSigFound:c_emit_func_open(func, out)
  out[#out + 1] = self.entry.sig.result:c_emit_type() .. " " .. func.name.text .. "(" .. func_params(func.params) .. ") {"
end
function C.CBackendFuncSigMissing:c_emit_func_open(func, out)
  out[#out + 1] = "/* function " .. func.name.text .. " missing signature */"
  out[#out + 1] = "void " .. func.name.text .. "(void) {"
end
function C.CBackendFuncSigFound:c_emit_prototype(func, out)
  out[#out + 1] = self.entry.sig.result:c_emit_type() .. " " .. func.name.text .. "(" .. func_params(func.params) .. ");"
end
function C.CBackendFuncSigMissing:c_emit_prototype(func, out)
  out[#out + 1] = "/* omitted prototype for " .. func.name.text .. ": missing signature */"
end

----------------------------------------------------------------------
-- C.CBackendFuncBody → c_emit_body
----------------------------------------------------------------------

function C.CBackendFuncBody:c_emit_body(out, indent)
  error("missing c_emit_body leaf method", 2)
end

function C.CBackendBodyBlocks:c_emit_body(out, indent)
  for _, block in ipairs(self.blocks or {}) do block:c_emit_block(out, indent) end
end

function C.CBackendBodyExec:c_emit_body(out, indent)
  out[#out + 1] = indent .. "/* exec fragment */"
  out[#out + 1] = indent .. "return;"
end

function C.CBackendBodyMixed:c_emit_body(out, indent)
  -- Emit exec fragments first
  for _, frag in ipairs(self.fragments or {}) do
    out[#out + 1] = indent .. "/* exec fragment */"
  end

  for _, block in ipairs(self.blocks or {}) do block:c_emit_block(out, indent) end
end

----------------------------------------------------------------------
-- C.CBackendBlock → c_emit_block
----------------------------------------------------------------------

function C.CBackendBlock:c_emit_block(out, indent)
  -- Label
  out[#out + 1] = indent .. self.label.text .. ":"

  -- Block params: these become local declarations on entry
  for _, bp in ipairs(self.params or {}) do
    out[#out + 1] = indent .. "  " .. bp.ty:c_emit_decl(bp.local_id.text) .. ";"
  end

  -- Statements
  for _, stmt in ipairs(self.stmts or {}) do
    stmt:c_emit_stmt(out, indent)
  end

  -- Terminator
  self.term:c_emit_term(out, indent)
end

----------------------------------------------------------------------
-- C.CBackendBlockParam → c_emit_block_param_decl (helper)
----------------------------------------------------------------------

----------------------------------------------------------------------
-- C.CBackendStmt → c_emit_stmt
----------------------------------------------------------------------

function C.CBackendStmt:c_emit_stmt(out, indent)
  out[#out + 1] = indent .. "  /* unhandled: " .. tostring(self) .. " */;"
end

function C.CBackendAssign:c_emit_stmt(out, indent)
  local rhs_str = self.rhs:c_emit_rvalue()
  out[#out + 1] = indent .. "  " .. self.dst.text .. " = " .. rhs_str .. ";"
end

function C.CBackendHelperCall:c_emit_stmt(out, indent)
  local args = {}
  for _, a in ipairs(self.args or {}) do
    args[#args + 1] = a:c_emit_atom()
  end
  local call = self.helper.text .. "(" .. table.concat(args, ", ") .. ")"
  if self.dst then
    out[#out + 1] = indent .. "  " .. self.dst.text .. " = " .. call .. ";"
  else
    out[#out + 1] = indent .. "  " .. call .. ";"
  end
end

function C.CBackendLoad:c_emit_stmt(out, indent)
  local addr = self.addr:c_emit_atom()
  out[#out + 1] = indent .. "  memcpy(&" .. self.dst.text .. ", " .. addr .. ", sizeof(" .. self.dst.text .. "));"
end

function C.CBackendStore:c_emit_stmt(out, indent)
  local addr = self.addr:c_emit_atom()
  local val = self.value:c_emit_atom()
  out[#out + 1] = indent .. "  memcpy(" .. addr .. ", &" .. val .. ", sizeof(" .. val .. "));"
end

function C.CBackendPlaceLoad:c_emit_stmt(out, indent)
  local place_str = self.place:c_emit_place()
  out[#out + 1] = indent .. "  " .. self.dst.text .. " = " .. place_str .. ";"
end

function C.CBackendPlaceStore:c_emit_stmt(out, indent)
  local place_str = self.place:c_emit_place()
  local val_str = self.value:c_emit_atom()
  out[#out + 1] = indent .. "  " .. place_str .. " = " .. val_str .. ";"
end

function C.CBackendZeroInit:c_emit_stmt(out, indent)
  local place_str = self.place:c_emit_place()
  out[#out + 1] = indent .. "  memset(&" .. place_str .. ", 0, (size_t)" .. tostring(self.size) .. ");"
end

function C.CBackendAggregateInit:c_emit_stmt(out, indent)
  for _, f in ipairs(self.fields or {}) do
    local place_str = self.place:c_emit_place()
    out[#out + 1] = indent .. "  " .. place_str .. "." .. f.field.text .. " = " .. f.value:c_emit_atom() .. ";"
  end
end

function C.CBackendArrayInit:c_emit_stmt(out, indent)
  for _, e in ipairs(self.elems or {}) do
    local place_str = self.place:c_emit_place()
    out[#out + 1] = indent .. "  " .. place_str .. "[" .. tostring(e.index) .. "] = " .. e.value:c_emit_atom() .. ";"
  end
end

function C.CBackendCall:c_emit_stmt(out, indent)
  local callee = self.target:c_emit_callee()
  local args = {}
  for _, a in ipairs(self.args or {}) do
    args[#args + 1] = a:c_emit_atom()
  end
  local call = callee .. "(" .. table.concat(args, ", ") .. ")"
  if self.dst then
    out[#out + 1] = indent .. "  " .. self.dst.text .. " = " .. call .. ";"
  else
    out[#out + 1] = indent .. "  " .. call .. ";"
  end
end

function C.CBackendComment:c_emit_stmt(out, indent)
  out[#out + 1] = indent .. "  /* " .. self.text:gsub("%*/", "* /") .. " */"
end

----------------------------------------------------------------------
-- C.CBackendCallTarget → c_emit_callee
----------------------------------------------------------------------

function C.CBackendCallTarget:c_emit_callee()
  error("missing c_emit_callee leaf method", 2)
end
function C.CBackendCallDirect:c_emit_callee() return self.func.text end
function C.CBackendCallExtern:c_emit_callee() return self.extern.text end
function C.CBackendCallIndirect:c_emit_callee() return self.callee:c_emit_atom() end
function C.CBackendCallClosure:c_emit_callee()
  return self.closure:c_emit_atom() .. ".fn"
end

----------------------------------------------------------------------
-- C.CBackendTerminator → c_emit_term
----------------------------------------------------------------------

function C.CBackendTerminator:c_emit_term(out, indent)
  out[#out + 1] = indent .. "  /* unhandled terminator */"
end

function C.CBackendGoto:c_emit_term(out, indent)
  out[#out + 1] = indent .. "  goto " .. self.dest.text .. ";"
end

function C.CBackendIfGoto:c_emit_term(out, indent)
  local cond = self.cond:c_emit_atom()
  out[#out + 1] = indent .. "  if (" .. cond .. ") goto " .. self.then_dest.text .. ";"
  out[#out + 1] = indent .. "  else goto " .. self.else_dest.text .. ";"
end

function C.CBackendSwitchGoto:c_emit_term(out, indent)
  local val = self.value:c_emit_atom()
  out[#out + 1] = indent .. "  switch (" .. val .. ") {"
  for _, c in ipairs(self.cases or {}) do
    out[#out + 1] = indent .. "  case " .. c.literal:c_emit_literal_value() .. ": goto " .. c.dest.text .. ";"
  end
  out[#out + 1] = indent .. "  default: goto " .. self.default_dest.text .. ";"
  out[#out + 1] = indent .. "  }"
end

function C.CBackendReturnVoid:c_emit_term(out, indent)
  out[#out + 1] = indent .. "  return;"
end

function C.CBackendReturn:c_emit_term(out, indent)
  out[#out + 1] = indent .. "  return " .. self.value:c_emit_atom() .. ";"
end

function C.CBackendTrap:c_emit_term(out, indent)
  out[#out + 1] = indent .. "  abort();"
end

----------------------------------------------------------------------
-- C.CBackendAtom → c_emit_atom
----------------------------------------------------------------------

function C.CBackendAtom:c_emit_atom()
  error("missing c_emit_atom leaf method", 2)
end
function C.CBackendAtomLocal:c_emit_atom() return self.local_id.text end
function C.CBackendAtomGlobal:c_emit_atom() return self.global.text end
function C.CBackendAtomLiteral:c_emit_atom()
  local raw_lit = self.literal:c_emit_literal_value()
  local ty_name = self.ty:c_emit_type()
  return "((" .. ty_name .. ")" .. raw_lit .. ")"
end
function C.CBackendAtomNull:c_emit_atom() return "NULL" end

----------------------------------------------------------------------
-- C.CBackendRValue → c_emit_rvalue
----------------------------------------------------------------------

function C.CBackendRValue:c_emit_rvalue()
  error("missing c_emit_rvalue leaf method", 2)
end
function C.CBackendRAtom:c_emit_rvalue() return self.atom:c_emit_atom() end
function C.CBackendRCompare:c_emit_rvalue()
  return "(" .. self.lhs:c_emit_atom() .. " " .. self.op:c_emit_cmp_op() .. " " .. self.rhs:c_emit_atom() .. ")"
end
function C.CBackendRCast:c_emit_rvalue()
  return "((" .. self.to:c_emit_type() .. ")(" .. self.value:c_emit_atom() .. "))"
end
function C.CBackendRSelect:c_emit_rvalue()
  return "((" .. self.cond:c_emit_atom() .. ") ? " .. self.then_value:c_emit_atom() .. " : " .. self.else_value:c_emit_atom() .. ")"
end
function C.CBackendRFuncAddr:c_emit_rvalue() return self.func.text end
function C.CBackendRExternAddr:c_emit_rvalue() return self.extern.text end
function C.CBackendRPtrOffset:c_emit_rvalue()
  return "(void*)((char*)" .. self.base:c_emit_atom() .. " + (" .. self.index:c_emit_atom() .. ") * " .. tostring(self.elem_size) .. " + " .. tostring(self.const_offset) .. ")"
end
function C.CBackendRAddrOfPlace:c_emit_rvalue()
  return "&" .. self.place:c_emit_place()
end
function C.CBackendRValueBuiltin:c_emit_rvalue()
  -- Builtins are helpers; for now emit as if it's a call
  local args = {}
  for _, a in ipairs(self.args or {}) do
    args[#args + 1] = a:c_emit_rvalue()
  end
  return tostring(self.builtin) .. "(" .. table.concat(args, ", ") .. ")"
end

----------------------------------------------------------------------
-- C.CBackendPlace → c_emit_place
----------------------------------------------------------------------

function C.CBackendPlace:c_emit_place()
  error("missing c_emit_place leaf method", 2)
end
function C.CBackendPlaceLocal:c_emit_place() return self.local_id.text end
function C.CBackendPlaceGlobal:c_emit_place() return self.global.text end
function C.CBackendPlaceDeref:c_emit_place()
  return "(*(" .. self.ty:c_emit_type() .. "*)" .. self.addr:c_emit_atom() .. ")"
end
function C.CBackendPlaceField:c_emit_place()
  return self.base:c_emit_place() .. "." .. self.field.text
end
function C.CBackendPlaceIndex:c_emit_place()
  return self.base:c_emit_place() .. "[" .. self.index:c_emit_atom() .. "]"
end
function C.CBackendPlacePtrIndex:c_emit_place()
  return self.base:c_emit_atom() .. "[" .. self.index:c_emit_atom() .. "]"
end
function C.CBackendPlaceBytes:c_emit_place()
  return "(*(" .. self.ty:c_emit_type() .. "*)((unsigned char*)" .. self.base:c_emit_atom() .. " + " .. tostring(self.offset) .. "))"
end

----------------------------------------------------------------------
-- C.CBackendHelperUse → c_emit_helper_lines
----------------------------------------------------------------------

-- Compute helper function id from spec
function C.CBackendHelperSpec:c_helper_id()
  error("missing c_helper_id leaf method", 2)
end

function C.CBackendHelperIntBinary:c_helper_id()
  local ty_suffix = self.ty:c_helper_suffix()
  local op_suffix = self.op:c_helper_suffix()
  return C.CBackendHelperId("ml_" .. ty_suffix .. "_" .. op_suffix)
end

function C.CBackendHelperUnary:c_helper_id()
  return C.CBackendHelperId("ml_" .. self.ty:c_helper_suffix() .. "_" .. self.op:c_helper_suffix())
end

function C.CBackendHelperCast:c_helper_id()
  return C.CBackendHelperId("ml_cast_from_" .. self.from:c_helper_suffix() .. "_to_" .. self.to:c_helper_suffix())
end

function C.CBackendHelperPtrOffset:c_helper_id()
  return C.CBackendHelperId("ml_ptroff_" .. self.pointee:c_helper_suffix() .. "_" .. tostring(self.elem_size))
end

function C.CBackendHelperFloatBinary:c_helper_id()
  return C.CBackendHelperId("ml_" .. self.ty:c_helper_suffix() .. "_" .. self.op:c_helper_suffix())
end

function C.CBackendHelperDivRem:c_helper_id()
  return C.CBackendHelperId("ml_" .. self.ty:c_helper_suffix() .. "_" .. self.op:c_helper_suffix())
end

function C.CBackendHelperShift:c_helper_id()
  return C.CBackendHelperId("ml_" .. self.ty:c_helper_suffix() .. "_" .. self.op:c_helper_suffix())
end

function C.CBackendHelperIntrinsic:c_helper_id()
  return C.CBackendHelperId("ml_" .. self.ty:c_helper_suffix() .. "_" .. self.intrinsic:c_helper_suffix())
end

function C.CBackendHelperLoad:c_helper_id()
  return C.CBackendHelperId("ml_load_" .. self.access.ty:c_helper_suffix())
end

function C.CBackendHelperStore:c_helper_id()
  return C.CBackendHelperId("ml_store_" .. self.access.ty:c_helper_suffix())
end

-- Generate the helper function signature lines
local function helper_header(id, sig)
  local ret = sig.result:c_emit_type()
  local params = {}
  for i = 1, #sig.params do
    params[i] = sig.params[i]:c_emit_type() .. " a" .. tostring(i)
  end
  return { "static inline " .. ret .. " " .. id.text .. "(" .. table.concat(params, ", ") .. ") {" }, ret
end

function C.CBackendHelperSpec:c_helper_signature()
  error("missing c_helper_signature leaf method", 2)
end
function C.CBackendHelperUse:c_helper_signature() return self.spec:c_helper_signature() end
function C.CBackendHelperIntBinary:c_helper_signature()
  return C.CBackendHelperSignature({ self.ty, self.ty }, self.ty)
end
function C.CBackendHelperUnary:c_helper_signature()
  return C.CBackendHelperSignature({ self.ty }, self.ty)
end
function C.CBackendHelperBoolNormalize:c_helper_signature()
  return C.CBackendHelperSignature({ self.ty }, C.CBackendBool8)
end
function C.CBackendHelperCast:c_helper_signature()
  return C.CBackendHelperSignature({ self.from }, self.to)
end
function C.CBackendHelperPtrOffset:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(nil), C.CBackendIndex }, C.CBackendDataPtr(nil))
end
function C.CBackendHelperFloatBinary:c_helper_signature()
  return C.CBackendHelperSignature({ self.ty, self.ty }, self.ty)
end
function C.CBackendHelperDivRem:c_helper_signature()
  return C.CBackendHelperSignature({ self.ty, self.ty }, self.ty)
end
function C.CBackendHelperShift:c_helper_signature()
  return C.CBackendHelperSignature({ self.ty, self.ty }, self.ty)
end
function Core.Intrinsic:c_typed_helper_signature(ty) return C.CBackendHelperSignature({ ty }, ty) end
function Core.IntrinsicTrap:c_typed_helper_signature(ty) return C.CBackendHelperSignature({}, C.CBackendVoid) end
function Core.IntrinsicAssume:c_typed_helper_signature(ty) return C.CBackendHelperSignature({ C.CBackendBool8 }, C.CBackendVoid) end
function Core.IntrinsicFma:c_typed_helper_signature(ty) return C.CBackendHelperSignature({ ty, ty, ty }, ty) end
function Core.IntrinsicRotl:c_typed_helper_signature(ty) return C.CBackendHelperSignature({ ty, ty }, ty) end
function Core.IntrinsicRotr:c_typed_helper_signature(ty) return C.CBackendHelperSignature({ ty, ty }, ty) end
function C.CBackendHelperIntrinsic:c_helper_signature() return self.intrinsic:c_typed_helper_signature(self.ty) end
function C.CBackendHelperLoad:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(nil) }, self.access.ty)
end
function C.CBackendHelperStore:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(nil), self.access.ty }, C.CBackendVoid)
end
function C.CBackendHelperAtomicLoad:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(self.access.ty) }, self.access.ty)
end
function C.CBackendHelperAtomicStore:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(self.access.ty), self.access.ty }, C.CBackendVoid)
end
function C.CBackendHelperAtomicRmw:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(self.access.ty), self.access.ty }, self.access.ty)
end
function C.CBackendHelperAtomicCas:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(self.access.ty), C.CBackendDataPtr(self.access.ty), self.access.ty }, self.access.ty)
end
function C.CBackendHelperAtomicFence:c_helper_signature()
  return C.CBackendHelperSignature({}, C.CBackendVoid)
end
function C.CBackendHelperMemcpy:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(nil), C.CBackendDataPtr(nil), C.CBackendIndex }, C.CBackendVoid)
end
function C.CBackendHelperTypedMemcpy:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(nil), C.CBackendDataPtr(nil) }, C.CBackendVoid)
end
function C.CBackendHelperMemset:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(nil), C.CBackendScalar(Core.ScalarI32), C.CBackendIndex }, C.CBackendVoid)
end
function C.CBackendHelperTypedMemset:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(nil), C.CBackendScalar(Core.ScalarI32) }, C.CBackendVoid)
end
function C.CBackendHelperMemcmp:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(nil), C.CBackendDataPtr(nil), C.CBackendIndex }, C.CBackendScalar(Core.ScalarI32))
end
function C.CBackendHelperLayoutAssert:c_helper_signature()
  return C.CBackendHelperSignature({}, C.CBackendVoid)
end
function C.CBackendHelperRequireFeature:c_helper_signature()
  return C.CBackendHelperSignature({}, C.CBackendVoid)
end
function C.CBackendHelperScan:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(self.ty), C.CBackendDataPtr(self.ty), C.CBackendIndex }, C.CBackendVoid)
end
function C.CBackendHelperFind:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(self.ty), C.CBackendIndex, self.ty }, C.CBackendIndex)
end
function C.CBackendHelperReduce:c_helper_signature()
  return C.CBackendHelperSignature({ C.CBackendDataPtr(self.ty), C.CBackendIndex }, self.ty)
end
function C.CBackendHelperTrap:c_helper_signature()
  return C.CBackendHelperSignature({}, C.CBackendVoid)
end

function C.CBackendHelperSpec:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    return a1;"
end

function C.CBackendHelperIntBinary:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    return (" .. ret .. ")(" .. self.op:c_helper_expr("a1", "a2") .. ");"
end

function C.CBackendHelperFloatBinary:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    return (" .. ret .. ")(" .. self.op:c_helper_expr("a1", "a2") .. ");"
end

function Core.UnaryNeg:c_emit_unary_expression(value) return "-" .. value end
function Core.UnaryNot:c_emit_unary_expression(value) return "!" .. value end
function Core.UnaryBitNot:c_emit_unary_expression(value) return "~" .. value end

function C.CBackendHelperUnary:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    return (" .. ret .. ")(" .. self.op:c_emit_unary_expression("a1") .. ");"
end

function C.CBackendHelperCast:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    return (" .. ret .. ")a1;"
end

function C.CBackendHelperPtrOffset:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    return (void*)((unsigned char*)a1 + ((intptr_t)a2 * (intptr_t)" .. tostring(self.elem_size) .. "));"
end

function C.CBackendHelperLoad:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    " .. ret .. " v;"
  lines[#lines + 1] = "    memcpy(&v, a1, sizeof(v));"
  lines[#lines + 1] = "    return v;"
end

function C.CBackendHelperStore:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    memcpy(a1, &a2, sizeof(a2));"
end

function C.CBackendHelperMemcpy:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    memcpy(a1, a2, (size_t)a3);"
end

function C.CBackendHelperMemset:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    memset(a1, a2, (size_t)a3);"
end

function C.CBackendHelperMemcmp:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    return memcmp(a1, a2, (size_t)a3);"
end

function C.CBackendHelperTrap:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "    abort();"
end

function C.CBackendHelperSpec:c_emit_helper_lines()
  local id = self:c_helper_id()
  local sig = self:c_helper_signature()
  local lines, ret = helper_header(id, sig)
  self:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "}"
  return lines
end

function C.CBackendHelperUse:c_emit_helper_lines()
  local sig = self.spec:c_helper_signature()
  local lines, ret = helper_header(self.id, sig)
  self.spec:c_emit_helper_body(lines, ret)
  lines[#lines + 1] = "}"
  return lines
end