-- impl/cemit_emit.lua
-- Methods on Cemit.*, Core.*, and C.* types for final C text emission.
-- Ported from emit_c_lower.lua.

require("lalin.schema_v2")

local Cemit = require("lalin.schema_v2.cemit")
local C     = require("lalin.schema_v2.c")
local Core  = require("lalin.schema_v2.core")
local Code  = require("lalin.schema_v2.code")

----------------------------------------------------------------------
-- CEmitMachine → emit_module / emit_source / emit_header / emit_combined
----------------------------------------------------------------------

function Cemit.CEmitMachine:emit_module(code_module, lower_module)
  local source = self:emit_source(code_module, lower_module)
  local header = self:emit_header(code_module)
  return Cemit.CEmitArtifact(source, header, "", source .. "\n" .. header)
end

function Cemit.CEmitMachine:emit_source(code_module, lower_module)
  local lines = {}

  -- Emit includes
  lines[#lines + 1] = '#include <stdint.h>'
  lines[#lines + 1] = '#include <stddef.h>'
  lines[#lines + 1] = '#include <stdbool.h>'
  lines[#lines + 1] = ''

  -- Emit each function from the C backend unit
  if lower_module and lower_module.c_unit then
    local c_unit = lower_module.c_unit
    for _, func in ipairs(c_unit.funcs or {}) do
      -- function signature
      if func.sig then
        lines[#lines + 1] = func.sig:c_emit_signature() .. ' {'
      else
        lines[#lines + 1] = '/* function ' .. (func.name or 'unknown') .. ' */'
        lines[#lines + 1] = '{'
      end
      -- function body blocks
      for _, block in ipairs(func.blocks or {}) do
        for _, stmt in ipairs(block.stmts or {}) do
          lines[#lines + 1] = '  ' .. stmt:c_emit_stmt()
        end
      end
      lines[#lines + 1] = '}'
      lines[#lines + 1] = ''
    end
  end

  return table.concat(lines, '\n')
end

function Cemit.CEmitMachine:emit_header(code_module)
  local lines = {}
  lines[#lines + 1] = '/* Auto-generated by Lalin C emitter */'
  lines[#lines + 1] = '#ifndef LALIN_EMIT_H'
  lines[#lines + 1] = '#define LALIN_EMIT_H'
  lines[#lines + 1] = ''
  lines[#lines + 1] = '#include <stdint.h>'
  lines[#lines + 1] = '#include <stddef.h>'
  lines[#lines + 1] = '#include <stdbool.h>'
  lines[#lines + 1] = ''
  -- emit function declarations
  if code_module then
    for _, func in ipairs(code_module.funcs or {}) do
      if func.sig then
        lines[#lines + 1] = func.sig:c_emit_signature() .. ';'
      end
    end
  end
  lines[#lines + 1] = ''
  lines[#lines + 1] = '#endif /* LALIN_EMIT_H */'
  return table.concat(lines, '\n')
end

function Cemit.CEmitMachine:emit_combined(code_module, lower_module)
  local header = self:emit_header(code_module)
  local source = self:emit_source(code_module, lower_module)
  return header .. '\n' .. source
end

----------------------------------------------------------------------
-- Core.Scalar → c_emit_scalar_name
----------------------------------------------------------------------

function Core.Scalar:c_emit_scalar_name()
  error("missing c_emit_scalar_name leaf method", 2)
end
function Core.ScalarBool:c_emit_scalar_name() return "uint8_t" end
function Core.ScalarI8:c_emit_scalar_name() return "int8_t" end
function Core.ScalarI16:c_emit_scalar_name() return "int16_t" end
function Core.ScalarI32:c_emit_scalar_name() return "int32_t" end
function Core.ScalarI64:c_emit_scalar_name() return "int64_t" end
function Core.ScalarU8:c_emit_scalar_name() return "uint8_t" end
function Core.ScalarU16:c_emit_scalar_name() return "uint16_t" end
function Core.ScalarU32:c_emit_scalar_name() return "uint32_t" end
function Core.ScalarU64:c_emit_scalar_name() return "uint64_t" end
function Core.ScalarF32:c_emit_scalar_name() return "float" end
function Core.ScalarF64:c_emit_scalar_name() return "double" end
function Core.ScalarRawPtr:c_emit_scalar_name() return "void*" end
function Core.ScalarIndex:c_emit_scalar_name() return "size_t" end
function Core.ScalarVoid:c_emit_scalar_name() return "void" end

----------------------------------------------------------------------
-- C.CBackendType → c_emit_type / c_emit_decl
----------------------------------------------------------------------

function C.CBackendType:c_emit_type()
  error("missing c_emit_type leaf method for " .. tostring(self), 2)
end
function C.CBackendVoid:c_emit_type() return "void" end
function C.CBackendBool8:c_emit_type() return "bool" end
function C.CBackendScalar:c_emit_type() return self.scalar:c_emit_scalar_name() end
function C.CBackendIndex:c_emit_type() return "size_t" end
function C.CBackendDataPtr:c_emit_type()
  if self.pointee then return self.pointee:c_emit_type() .. "*" end
  return "void*"
end
function C.CBackendQualifiedDataPtr:c_emit_type()
  local base = self.pointee and self.pointee:c_emit_type() or "void"
  local quals = self.qualifiers or ""
  return base .. "* " .. quals
end
function C.CBackendCodePtr:c_emit_type() return "void(*)(void)" end
function C.CBackendImportedCodePtr:c_emit_type()
  return self.sig and self.sig:c_emit_type() or "void(*)(void)"
end
function C.CBackendNamed:c_emit_type() return self.id.spelling end
function C.CBackendArray:c_emit_type()
  return self.elem:c_emit_type() .. "[" .. tostring(self.count) .. "]"
end
function C.CBackendSliceDescriptor:c_emit_type() return "lalin_slice_t" end
function C.CBackendByteSpanDescriptor:c_emit_type() return "lalin_bytespan_t" end
function C.CBackendViewDescriptor:c_emit_type() return "lalin_view_t" end
function C.CBackendClosureDescriptor:c_emit_type() return "lalin_closure_t" end
function C.CBackendAbiHiddenOutPtr:c_emit_type()
  if self.pointee then return self.pointee:c_emit_type() .. "*" end
  return "void*"
end
function C.CBackendVector:c_emit_type()
  local elem = self.elem:c_emit_type()
  return elem .. " __attribute__((vector_size(" .. tostring(self.lanes * 4) .. ")))"
end

function C.CBackendType:c_emit_decl(name)
  return self:c_emit_type() .. " " .. (name or "")
end

----------------------------------------------------------------------
-- C.CBackendStmt → c_emit_stmt
----------------------------------------------------------------------

function C.CBackendStmt:c_emit_stmt()
  return "/* " .. tostring(self) .. " */;"
end

----------------------------------------------------------------------
-- C.CBackendAtom / C.CBackendPlace → c_emit_atom / c_emit_place
----------------------------------------------------------------------

function C.CBackendAtom:c_emit_atom() return tostring(self) end
function C.CBackendPlace:c_emit_place() return tostring(self) end

----------------------------------------------------------------------
-- CodeSig / CFuncSig → c_emit_signature
----------------------------------------------------------------------

function C.CFuncSig:c_emit_signature()
  local ret = self.result and self.result:c_emit_type() or "void"
  local params = {}
  for _, p in ipairs(self.params or {}) do
    params[#params + 1] = p:c_emit_type()
  end
  return ret .. " " .. (self.name or "fn") .. "(" .. table.concat(params, ", ") .. ")"
end
