local S = require("lalin.schema.dsl")
S.use()

return schema. LalinCMat {
  product. CMatKernelId { interned, text [str], },
  product. CMatLocalId { interned, text [str], },

  sum. CMatConstCapability {
    CMatConstEligible,
    CMatConstIneligible { variant_unique, reason [str], },
  },
  sum. CMatRestrictCapability {
    CMatRestrictEligible,
    CMatRestrictIneligible { variant_unique, reason [str], },
  },
  sum. CMatLaneCapability {
    CMatLaneFromTarget,
    CMatLaneNative,
    CMatLaneFixed { variant_unique, lanes [number], },
  },
  sum. CMatAccessMutability {
    CMatAccessReadOnly,
    CMatAccessWriteOnly,
    CMatAccessReadWrite,
    CMatAccessReduce,
  },

  product. CMatAccessBinding {
    interned,
    access [LalinStencil.StencilAccessRef],
    source [LalinStencil.StencilAccess],
    local_id [LalinCMat.CMatLocalId],
    field. ty [LalinCode.CodeType],
    layout [LalinStencil.StencilAccessLayout],
    mutability [LalinCMat.CMatAccessMutability],
    restrict_capability [LalinCMat.CMatRestrictCapability],
    const_capability [LalinCMat.CMatConstCapability],
    alignment [LalinStencil.StencilAlignmentFact],
  },
  product. CMatAccessBindingInput {
    interned,
    local_id [LalinCMat.CMatLocalId],
    restrict [LalinStencil.StencilAccessRestrictDecision],
  },
  sum. CMatAccessBindingResult {
    CMatAccessBound { variant_unique, binding [LalinCMat.CMatAccessBinding], },
    CMatAccessBindingRejected { variant_unique, issue [LalinCMat.CMatMaterializationIssue], },
  },
  sum. CMatAccessCollection {
    CMatAccessCollectionReady { variant_unique, bindings [many [LalinCMat.CMatAccessBinding]], },
    CMatAccessCollectionRejected { variant_unique, issues [many [LalinCMat.CMatMaterializationIssue]], },
  },

  sum. CMatLoopOrder { CMatLoopForward, CMatLoopBackward, },
  product. CMatLoopAxis {
    interned,
    axis [LalinStencil.StencilAxisRef],
    index [LalinCMat.CMatLocalId],
    index_ty [LalinCode.CodeType],
    step [number],
    order [LalinCMat.CMatLoopOrder],
  },
  sum. CMatTailPolicy { CMatTailScalar, CMatTailMask, CMatTailOverreadProvenSafe, },
  sum. CMatVectorPolicy {
    CMatVectorNone,
    CMatVectorAutovec { variant_unique, lanes [LalinCMat.CMatLaneCapability], tail [LalinCMat.CMatTailPolicy], },
    CMatVectorExplicit { variant_unique, lanes [LalinCMat.CMatLaneCapability], tail [LalinCMat.CMatTailPolicy], },
  },
  product. CMatSchedulePolicy {
    interned,
    unroll [number],
    interleave [number],
    vector [LalinCMat.CMatVectorPolicy],
  },
  product. CMatLoopNest {
    interned,
    axes [many [LalinCMat.CMatLoopAxis]],
    policy [LalinCMat.CMatSchedulePolicy],
  },
  sum. CMatLoopPlan {
    CMatLoopPlanned { variant_unique, axes [many [LalinCMat.CMatLoopAxis]], },
    CMatLoopRejected { variant_unique, issue [LalinCMat.CMatMaterializationIssue], },
  },

  sum. CMatStreamMaterialization {
    CMatStreamInline { variant_unique, stream [LalinStencil.StencilStreamRef], field. ty [LalinCode.CodeType], },
    CMatStreamLocal {
      variant_unique,
      stream [LalinStencil.StencilStreamRef],
      local_id [LalinCMat.CMatLocalId],
      field. ty [LalinCode.CodeType],
    },
  },
  sum. CMatSinkMaterialization {
    CMatSinkInline { variant_unique, sink [LalinStencil.StencilSinkRef], },
    CMatSinkValueResult {
      variant_unique,
      sink [LalinStencil.StencilSinkRef],
      local_id [LalinCMat.CMatLocalId],
      field. ty [LalinCode.CodeType],
    },
    CMatSinkStoreResult { variant_unique, sink [LalinStencil.StencilSinkRef], dst [LalinStencil.StencilAccessRef], },
    CMatSinkControlResult { variant_unique, sink [LalinStencil.StencilSinkRef], },
  },

  product. CMatFusedKernel {
    interned,
    field. id [LalinCMat.CMatKernelId],
    computation [LalinStencil.StencilComputation],
    loop [LalinCMat.CMatLoopNest],
    accesses [many [LalinCMat.CMatAccessBinding]],
    streams [many [LalinCMat.CMatStreamMaterialization]],
    sinks [many [LalinCMat.CMatSinkMaterialization]],
    schedule [LalinStencil.StencilSchedule],
    proofs [many [LalinKernel.KernelProof]],
  },
  sum. CMatMaterializationIssue {
    CMatIssueUnsupportedProducer { variant_unique, producer [LalinStencil.StencilProducerShape], reason [str], },
    CMatIssueUnsupportedAccess { variant_unique, access [LalinStencil.StencilAccess], reason [str], },
    CMatIssueUnsupportedSchedule { variant_unique, schedule [LalinStencil.StencilSchedule], reason [str], },
    CMatIssueUnsupportedSink { variant_unique, sink [LalinStencil.StencilSinkDef], reason [str], },
    CMatIssueMissingProof { variant_unique, requirement [LalinStencil.StencilProofRequirement], reason [str], },
  },
  product. CMatMaterializationInput { interned, kernel [LalinCMat.CMatKernelId], },
  product. CMatKernelMaterializationInput { interned, kernel [LalinCMat.CMatKernelId], },
  sum. CMatMaterialization {
    CMatMaterializedFused { variant_unique, kernel [LalinCMat.CMatFusedKernel], },
    CMatMaterializedKernelFragment {
      variant_unique,
      kernel [LalinCMat.CMatFusedKernel],
      provenance [LalinStencil.StencilKernelProvenanceFacet],
    },
    CMatRejectedComputation {
      variant_unique,
      computation [LalinStencil.StencilComputation],
      issues [many [LalinCMat.CMatMaterializationIssue]],
    },
    CMatRejectedKernelFragment {
      variant_unique,
      computation [LalinStencil.StencilComputation],
      provenance [LalinStencil.StencilKernelProvenanceFacet],
      issues [many [LalinCMat.CMatMaterializationIssue]],
    },
  },
  product. CMatCEmissionInput {
    interned,
    module_name [str],
    symbol [str],
    target [LalinC.CBackendTarget],
  },
  sum. CMatCEmissionIssue {
    CMatCEmissionMaterializationIssue { variant_unique, issue [LalinCMat.CMatMaterializationIssue], },
    CMatCEmissionUnsupportedProducer { variant_unique, producer [LalinStencil.StencilProducerShape], reason [str], },
    CMatCEmissionUnsupportedAccess { variant_unique, access [LalinStencil.StencilAccess], reason [str], },
    CMatCEmissionUnsupportedStream { variant_unique, stream [LalinStencil.StencilStreamDef], reason [str], },
    CMatCEmissionUnsupportedSink { variant_unique, sink [LalinStencil.StencilSinkDef], reason [str], },
    CMatCEmissionUnsupportedPoint { variant_unique, field. expr [LalinStencil.StencilPointExpr], reason [str], },
    CMatCEmissionUnsupportedValue { variant_unique, field. value [LalinValue.ValueExpr], reason [str], },
    CMatCEmissionUnsupportedBinary {
      variant_unique,
      op [LalinCore.BinaryOp],
      field. ty [LalinCode.CodeType],
      reason [str],
    },
    CMatCEmissionInvalidKernel { variant_unique, reason [str], },
    CMatCEmissionInvalidWindow { variant_unique, stream [LalinStencil.StencilStreamDef], reason [str], },
    CMatCEmissionUnsupportedPredicate { variant_unique, pred [LalinStencil.StencilPredicate], reason [str], },
    CMatCEmissionInvalidControl { variant_unique, sink [LalinStencil.StencilSinkDef], reason [str], },
    CMatCEmissionMissingValue { variant_unique, field. value [LalinCode.CodeValueId], },
    CMatCEmissionMissingAccess { variant_unique, access [LalinStencil.StencilAccessRef], },
    CMatCEmissionMissingExit { variant_unique, role [LalinCMat.CMatCExitRole], },
    CMatCEmissionMissingStream { variant_unique, stream [LalinStencil.StencilStreamRef], },
    CMatCEmissionMissingTripCount { variant_unique, trip [LalinStencil.StencilKernelTripCount], },
    CMatCEmissionTypeMismatch {
      variant_unique,
      subject [str],
      expected [LalinC.CBackendType],
      actual [LalinC.CBackendType],
    },
    CMatCEmissionInvalidCoverage { variant_unique, block [LalinCode.CodeBlockId], reason [str], },
    CMatCEmissionInvalidExit { variant_unique, block [LalinCode.CodeBlockId], reason [str], },
    CMatCEmissionValidationRejected { variant_unique, issues [many [LalinC.CBackendValidationIssue]], },
  },
  sum. CMatCEmission {
    CMatCEmitted { variant_unique, field. unit [LalinC.CBackendUnit], },
    CMatCRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },

  product. CMatCAccessCEntry {
    interned,
    access [LalinStencil.StencilAccessRef],
    binding [LalinCMat.CMatAccessBinding],
    param [LalinC.CBackendLocal],
    stride [number],
  },
  product. CMatCAccessCProjection { interned, entries [many [LalinCMat.CMatCAccessCEntry]], },
  sum. CMatCAccessCLookup {
    CMatCAccessCFound { variant_unique, entry [LalinCMat.CMatCAccessCEntry], },
    CMatCAccessCMissing { variant_unique, access [LalinStencil.StencilAccessRef], },
  },
  sum. CMatCAccessCBindingResult {
    CMatCAccessCBindingReady { variant_unique, entry [LalinCMat.CMatCAccessCEntry], },
    CMatCAccessCBindingRejected { variant_unique, issue [LalinCMat.CMatCEmissionIssue], },
  },
  sum. CMatCAccessCCollection {
    CMatCAccessCCollectionReady { variant_unique, entries [many [LalinCMat.CMatCAccessCEntry]], },
    CMatCAccessCCollectionRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },

  product. CMatCStreamDefEntry { interned, stream [LalinStencil.StencilStreamRef], def [LalinStencil.StencilStreamDef], },
  product. CMatCStreamDefProjection { interned, entries [many [LalinCMat.CMatCStreamDefEntry]], },
  sum. CMatCStreamDefLookup {
    CMatCStreamDefFound { variant_unique, entry [LalinCMat.CMatCStreamDefEntry], },
    CMatCStreamDefMissing { variant_unique, stream [LalinStencil.StencilStreamRef], },
  },
  product. CMatCSinkDefEntry { interned, sink [LalinStencil.StencilSinkRef], def [LalinStencil.StencilSinkDef], },
  product. CMatCSinkDefProjection { interned, entries [many [LalinCMat.CMatCSinkDefEntry]], },
  sum. CMatCSinkDefLookup {
    CMatCSinkDefFound { variant_unique, entry [LalinCMat.CMatCSinkDefEntry], },
    CMatCSinkDefMissing { variant_unique, sink [LalinStencil.StencilSinkRef], },
  },
  product. CMatCStreamValueEntry {
    interned,
    field. name [str],
    stream [LalinStencil.StencilStreamRef],
    local_id [LalinC.CBackendLocalId],
    field. ty [LalinC.CBackendType],
  },
  product. CMatCStreamValueProjection { interned, entries [many [LalinCMat.CMatCStreamValueEntry]], },
  sum. CMatCStreamValueLookup {
    CMatCStreamValueFound { variant_unique, entry [LalinCMat.CMatCStreamValueEntry], },
    CMatCStreamValueMissing { variant_unique, field. name [str], },
  },

  product. CMatCFunctionState {
    interned,
    index [LalinC.CBackendLocalId],
    index_ty [LalinC.CBackendType],
    accesses [LalinCMat.CMatCAccessCProjection],
    stream_defs [LalinCMat.CMatCStreamDefProjection],
    sink_defs [LalinCMat.CMatCSinkDefProjection],
    values [LalinCMat.CMatCStreamValueProjection],
    locals [many [LalinC.CBackendLocal]],
    entry_stmts [many [LalinC.CBackendStmt]],
    body_stmts [many [LalinC.CBackendStmt]],
    helpers [many [LalinC.CBackendHelperUse]],
    next_local [number],
  },
  product. CMatCLocalAllocation { interned, state [LalinCMat.CMatCFunctionState], c_local [LalinC.CBackendLocal], },
  product. CMatCHelperAllocation { interned, state [LalinCMat.CMatCFunctionState], helper [LalinC.CBackendHelperId], },
  product. CMatCDefProjections {
    interned,
    streams [LalinCMat.CMatCStreamDefProjection],
    sinks [LalinCMat.CMatCSinkDefProjection],
  },
  sum. CMatCStateStep {
    CMatCStateReady { variant_unique, state [LalinCMat.CMatCFunctionState], },
    CMatCStateRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  sum. CMatCPointEmission {
    CMatCPointEmitted {
      variant_unique,
      state [LalinCMat.CMatCFunctionState],
      atom [LalinC.CBackendAtom],
      field. ty [LalinC.CBackendType],
    },
    CMatCPointRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  sum. CMatCAtomEmission {
    CMatCAtomEmitted { variant_unique, atom [LalinC.CBackendAtom], field. ty [LalinC.CBackendType], },
    CMatCAtomRejected { variant_unique, issue [LalinCMat.CMatCEmissionIssue], },
  },
  sum. CMatCBinarySelection {
    CMatCBinarySelected { variant_unique, spec [LalinC.CBackendHelperSpec], },
    CMatCBinaryRejected { variant_unique, reason [str], },
  },
  product. CMatCLoopDirectionPlan {
    interned,
    compare [LalinCore.CmpOp],
    step_op [LalinCore.BinaryOp],
  },
  sum. CMatCSinkEmission {
    CMatCSinkVoidEmitted { variant_unique, state [LalinCMat.CMatCFunctionState], },
    CMatCSinkValueEmitted {
      variant_unique,
      state [LalinCMat.CMatCFunctionState],
      atom [LalinC.CBackendAtom],
      field. ty [LalinC.CBackendType],
    },
    CMatCSinkRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },

  product. CMatCExternalValueBindingEntry {
    interned,
    field. value [LalinCode.CodeValueId],
    c_local [LalinC.CBackendLocal],
  },
  product. CMatCExternalValueBindingProjection {
    interned,
    entries [many [LalinCMat.CMatCExternalValueBindingEntry]],
  },
  sum. CMatCExternalValueBindingLookup {
    CMatCExternalValueBindingFound { variant_unique, entry [LalinCMat.CMatCExternalValueBindingEntry], },
    CMatCExternalValueBindingMissing { variant_unique, field. value [LalinCode.CodeValueId], },
  },
  sum. CMatCFragmentAccessSource {
    CMatCFragmentAccessDirect { variant_unique, base [LalinC.CBackendLocal], },
    CMatCFragmentAccessAddressProjected {
      variant_unique,
      address [LalinFlow.FlowAddressId],
      base [LalinC.CBackendLocal],
    },
  },
  product. CMatCFragmentAccessBindingEntry {
    interned,
    access [LalinStencil.StencilAccessRef],
    lane [LalinKernel.KernelLaneId],
    mem_access [LalinMem.MemAccessId],
    source [LalinCMat.CMatCFragmentAccessSource],
    elem_size [number],
    stride [number],
    alignment [LalinMem.MemAlignment],
  },
  product. CMatCFragmentAccessBindingProjection {
    interned,
    entries [many [LalinCMat.CMatCFragmentAccessBindingEntry]],
  },
  sum. CMatCFragmentAccessBindingLookup {
    CMatCFragmentAccessBindingFound { variant_unique, entry [LalinCMat.CMatCFragmentAccessBindingEntry], },
    CMatCFragmentAccessBindingMissing { variant_unique, access [LalinStencil.StencilAccessRef], },
  },
  sum. CMatCExitRole {
    CMatCExitNormal,
    CMatCExitSuccess,
    CMatCExitFailure,
    CMatCExitFound,
    CMatCExitNotFound,
  },
  sum. CMatCExitArgument {
    CMatCExitArgumentAtom { variant_unique, atom [LalinC.CBackendAtom], field. ty [LalinC.CBackendType], },
    CMatCExitArgumentControlValue,
  },
  product. CMatCExitArgumentInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    control [LalinCMat.CMatCControlResult],
  },
  product. CMatCExitAtomInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    declared [LalinC.CBackendType],
    atom [LalinC.CBackendAtom],
  },
  product. CMatCExitBindingEntry {
    interned,
    role [LalinCMat.CMatCExitRole],
    destination [LalinCode.CodeBlockId],
    label [LalinC.CBackendLabel],
    args [many [LalinCMat.CMatCExitArgument]],
  },
  product. CMatCExitBindingProjection {
    interned,
    entries [many [LalinCMat.CMatCExitBindingEntry]],
  },
  sum. CMatCExitBindingLookup {
    CMatCExitBindingFound { variant_unique, entry [LalinCMat.CMatCExitBindingEntry], },
    CMatCExitBindingMissing { variant_unique, role [LalinCMat.CMatCExitRole], },
    CMatCExitBindingAmbiguous { variant_unique, role [LalinCMat.CMatCExitRole], count [number], },
  },
  sum. CMatCCodeBlockLookup {
    CMatCCodeBlockFound { variant_unique, block [LalinCode.CodeBlock], },
    CMatCCodeBlockMissing { variant_unique, block [LalinCode.CodeBlockId], },
  },
  product. CMatCFragmentNamespace { interned, prefix [str], },
  sum. CMatCBlockAlignment {
    CMatCBlockEliminated { variant_unique, source [LalinCode.CodeBlockId], },
    CMatCBlockReplacementEntry {
      variant_unique,
      source [LalinCode.CodeBlockId],
      replacement [LalinC.CBackendLabel],
    },
  },
  product. CMatCValueMapping { interned, field. value [LalinCode.CodeValueId], c_local [LalinC.CBackendLocal], },
  product. CMatCControlExitMapping {
    interned,
    role [LalinCMat.CMatCExitRole],
    destination [LalinCode.CodeBlockId],
    label [LalinC.CBackendLabel],
  },
  sum. CMatCControlResult {
    CMatCControlNone,
    CMatCControlValue { variant_unique, atom [LalinC.CBackendAtom], field. ty [LalinC.CBackendType], },
    CMatCControlAll {
      variant_unique,
      condition [LalinC.CBackendAtom],
      success [LalinCMat.CMatCControlExitMapping],
      failure [LalinCMat.CMatCControlExitMapping],
    },
    CMatCControlAllCompare {
      variant_unique,
      condition [LalinC.CBackendAtom],
      success [LalinCMat.CMatCControlExitMapping],
      failure [LalinCMat.CMatCControlExitMapping],
    },
    CMatCControlAny {
      variant_unique,
      condition [LalinC.CBackendAtom],
      success [LalinCMat.CMatCControlExitMapping],
      failure [LalinCMat.CMatCControlExitMapping],
    },
    CMatCControlFind {
      variant_unique,
      condition [LalinC.CBackendAtom],
      found [LalinCMat.CMatCControlExitMapping],
      not_found [LalinCMat.CMatCControlExitMapping],
      found_value [LalinC.CBackendAtom],
      not_found_value [LalinC.CBackendAtom],
      field. ty [LalinC.CBackendType],
    },
  },
  product. CMatCFragmentValueEntry {
    interned,
    field. value [LalinCode.CodeValueId],
    atom [LalinC.CBackendAtom],
    field. ty [LalinC.CBackendType],
  },
  product. CMatCFragmentValueProjection { interned, entries [many [LalinCMat.CMatCFragmentValueEntry]], },
  sum. CMatCFragmentValueLookup {
    CMatCFragmentValueFound { variant_unique, entry [LalinCMat.CMatCFragmentValueEntry], },
    CMatCFragmentValueMissing { variant_unique, field. value [LalinCode.CodeValueId], },
  },
  product. CMatCFragmentStreamEntry {
    interned,
    stream [LalinStencil.StencilStreamRef],
    source [LalinCode.CodeValueId],
    atom [LalinC.CBackendAtom],
    field. ty [LalinC.CBackendType],
  },
  product. CMatCFragmentStreamProjection { interned, entries [many [LalinCMat.CMatCFragmentStreamEntry]], },
  sum. CMatCFragmentStreamLookup {
    CMatCFragmentStreamFound { variant_unique, entry [LalinCMat.CMatCFragmentStreamEntry], },
    CMatCFragmentStreamMissing { variant_unique, stream [LalinStencil.StencilStreamRef], },
  },
  product. CMatCOpenBlock {
    interned,
    label [LalinC.CBackendLabel],
    params [many [LalinC.CBackendBlockParam]],
    stmts [many [LalinC.CBackendStmt]],
  },
  product. CMatCFragmentCFG {
    interned,
    completed [many [LalinC.CBackendBlock]],
    open [LalinCMat.CMatCOpenBlock],
    next_block [number],
  },
  sum. CMatCFragmentWindowContext {
    CMatCFragmentNoWindow,
    CMatCFragmentWindow1D {
      variant_unique,
      axis [LalinStencil.StencilProducerAxis],
      window [LalinStencil.StencilWindowAxis],
      start [LalinC.CBackendAtom],
      trip [LalinC.CBackendAtom],
      index_ty [LalinC.CBackendType],
    },
  },
  product. CMatCFragmentState {
    interned,
    request [LalinCMat.CMatCFragmentInput],
    provenance [LalinStencil.StencilKernelProvenanceFacet],
    index [LalinC.CBackendLocal],
    ordinal [LalinC.CBackendLocal],
    values [LalinCMat.CMatCFragmentValueProjection],
    streams [LalinCMat.CMatCFragmentStreamProjection],
    window [LalinCMat.CMatCFragmentWindowContext],
    locals [many [LalinC.CBackendLocal]],
    entry_stmts [many [LalinC.CBackendStmt]],
    cfg [LalinCMat.CMatCFragmentCFG],
    helpers [many [LalinC.CBackendHelperUse]],
    next_local [number],
  },
  product. CMatCFragmentLocalAllocation { interned, state [LalinCMat.CMatCFragmentState], c_local [LalinC.CBackendLocal], },
  product. CMatCFragmentHelperAllocation { interned, state [LalinCMat.CMatCFragmentState], helper [LalinC.CBackendHelperId], },
  sum. CMatCFragmentExprEmission {
    CMatCFragmentExprEmitted { variant_unique, state [LalinCMat.CMatCFragmentState], atom [LalinC.CBackendAtom], field. ty [LalinC.CBackendType], },
    CMatCFragmentExprRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  sum. CMatCFragmentStateStep {
    CMatCFragmentStateReady { variant_unique, state [LalinCMat.CMatCFragmentState], },
    CMatCFragmentStateRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  sum. CMatCFragmentSinkEmission {
    CMatCFragmentSinkEmitted {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      control [LalinCMat.CMatCControlResult],
      value_mappings [many [LalinCMat.CMatCValueMapping]],
    },
    CMatCFragmentControlSinkEmitted {
      variant_unique,
      body [LalinCMat.CMatCFragmentBodyPlan],
    },
    CMatCFragmentSinkRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  sum. CMatCFragmentBodyPlan {
    CMatCFragmentBodyContinue {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      control [LalinCMat.CMatCControlResult],
      value_mappings [many [LalinCMat.CMatCValueMapping]],
    },
    CMatCFragmentBodyAll {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      condition [LalinC.CBackendAtom],
      success [LalinCMat.CMatCExitBindingFound],
      failure [LalinCMat.CMatCExitBindingFound],
    },
    CMatCFragmentBodyAllCompare {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      condition [LalinC.CBackendAtom],
      success [LalinCMat.CMatCExitBindingFound],
      failure [LalinCMat.CMatCExitBindingFound],
    },
    CMatCFragmentBodyAny {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      condition [LalinC.CBackendAtom],
      success [LalinCMat.CMatCExitBindingFound],
      failure [LalinCMat.CMatCExitBindingFound],
    },
    CMatCFragmentBodyFind {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      condition [LalinC.CBackendAtom],
      found [LalinCMat.CMatCExitBindingFound],
      not_found [LalinCMat.CMatCExitBindingFound],
      found_value [LalinC.CBackendAtom],
      not_found_value [LalinC.CBackendAtom],
      field. ty [LalinC.CBackendType],
    },
  },
  sum. CMatCFragmentBoundEmission {
    CMatCFragmentBoundEmitted {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      atom [LalinC.CBackendAtom],
      field. ty [LalinC.CBackendType],
    },
    CMatCFragmentBoundRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  sum. CMatCIntegerSemantics {
    CMatCIntegerSemanticsMissing { variant_unique, reason [str], },
    CMatCIntegerSemanticsExplicit { variant_unique, semantics [LalinCode.CodeIntSemantics], },
  },
  product. CMatCFragmentBinaryContinuation {
    interned,
    right [LalinValue.ValueExpr],
    op [LalinCore.BinaryOp],
    result_ty [LalinCode.CodeType],
    semantics [LalinCMat.CMatCIntegerSemantics],
  },
  product. CMatCFragmentBinaryApplyInput {
    interned,
    left [LalinCMat.CMatCFragmentExprEmitted],
    continuation [LalinCMat.CMatCFragmentBinaryContinuation],
  },
  product. CMatCFragmentBinaryEmissionInput {
    interned,
    left [LalinCMat.CMatCFragmentExprEmitted],
    right [LalinCMat.CMatCFragmentExprEmitted],
    op [LalinCore.BinaryOp],
    result_ty [LalinCode.CodeType],
  },
  product. CMatCFragmentLoadInput {
    interned,
    index [LalinCMat.CMatCFragmentExprEmitted],
    stream [LalinStencil.StencilStreamByKernelValueEntry],
    access [LalinStencil.StencilAccessRef],
  },
  product. CMatCFragmentPlaceInput {
    interned,
    base [LalinC.CBackendAtom],
    index [LalinC.CBackendAtom],
    field. ty [LalinC.CBackendType],
    stride [number],
  },
  product. CMatCFragmentAccessPlaceInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    index [LalinC.CBackendAtom],
    index_ty [LalinC.CBackendType],
    field. ty [LalinC.CBackendType],
  },
  sum. CMatCFragmentPlaceEmission {
    CMatCFragmentPlaceEmitted {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      place [LalinC.CBackendPlace],
    },
    CMatCFragmentPlaceRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  product. CMatCFragmentStoreRequest {
    interned,
    state [LalinCMat.CMatCFragmentState],
    sink [LalinStencil.StencilSinkDef],
    dst [LalinStencil.StencilAccessRef],
  },
  product. CMatCFragmentStoreInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    sink [LalinStencil.StencilSinkDef],
    dst [LalinStencil.StencilAccessRef],
    stream [LalinCMat.CMatCFragmentStreamEntry],
  },
  product. CMatCFragmentFoldRequest {
    interned,
    state [LalinCMat.CMatCFragmentState],
    sink [LalinStencil.StencilSinkDef],
    operation [LalinStencil.StencilSinkOpFold],
  },
  product. CMatCFragmentFoldInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    sink [LalinStencil.StencilSinkDef],
    operation [LalinStencil.StencilSinkOpFold],
    stream [LalinCMat.CMatCFragmentStreamEntry],
  },
  product. CMatCFragmentReductionSpecInput {
    interned,
    reduction [LalinValue.ReductionOp],
    result_ty [LalinCode.CodeType],
  },
  product. CMatCIntegerReductionInput {
    interned,
    reduction [LalinValue.ReductionOp],
    semantics [LalinCode.CodeIntSemantics],
  },
  product. CMatCFloatReductionInput {
    interned,
    reduction [LalinValue.ReductionOp],
    mode [LalinCode.CodeFloatMode],
  },
  product. CMatCFragmentFoldFinishInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    sink [LalinStencil.StencilSinkDef],
    operation [LalinStencil.StencilSinkOpFold],
    stream [LalinCMat.CMatCFragmentStreamEntry],
    accumulator [LalinC.CBackendLocal],
    field. ty [LalinC.CBackendType],
  },
  product. CMatCFragmentStartContinuation {
    interned,
    plan [LalinCMat.CMatCFragmentProducerPlan],
    start [LalinCMat.CMatCFragmentBoundEmitted],
  },
  product. CMatCFragmentTripContinuation {
    interned,
    plan [LalinCMat.CMatCFragmentProducerPlan],
    start [LalinCMat.CMatCFragmentBoundEmitted],
    trip [LalinCMat.CMatCFragmentBoundEmitted],
  },
  product. CMatCFragmentBodyInput {
    interned,
    plan [LalinCMat.CMatCFragmentProducerPlan],
    state [LalinCMat.CMatCFragmentState],
    start [LalinCMat.CMatCFragmentBoundEmitted],
    trip [LalinCMat.CMatCFragmentBoundEmitted],
  },
  product. CMatCFragmentSinkFoldInput {
    interned,
    sinks [many [LalinStencil.StencilSinkDef]],
    next_index [number],
    body [LalinCMat.CMatCFragmentBodyInput],
  },
  product. CMatCFragmentSinkMergeInput {
    interned,
    accumulated [LalinCMat.CMatCFragmentSinkEmitted],
    fold [LalinCMat.CMatCFragmentSinkFoldInput],
  },
  product. CMatCFragmentControlMergeInput {
    interned,
    current [LalinCMat.CMatCFragmentSinkEmitted],
    accumulated [LalinCMat.CMatCFragmentSinkEmitted],
    fold [LalinCMat.CMatCFragmentSinkFoldInput],
  },
  product. CMatCExitArgumentValue {
    interned,
    atom [LalinC.CBackendAtom],
    field. ty [LalinC.CBackendType],
  },
  sum. CMatCExitArgumentCollection {
    CMatCExitArgumentCollectionReady { variant_unique, values [many [LalinCMat.CMatCExitArgumentValue]], },
    CMatCExitArgumentCollectionRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  sum. CMatCControlContinuePolarity {
    CMatCControlContinueWhenTrue,
    CMatCControlContinueWhenFalse,
  },
  sum. CMatCControlAssemblyValidation {
    CMatCControlAssemblyValid {
      variant_unique,
      assembly [LalinCMat.CMatCControlLoopAssemblyInput],
    },
    CMatCControlAssemblyRejected {
      variant_unique,
      issues [many [LalinCMat.CMatCEmissionIssue]],
    },
  },
  product. CMatCControlExitValidationInput {
    interned,
    arguments [many [LalinCMat.CMatCExitArgumentValue]],
  },
  sum. CMatCControlExitValidation {
    CMatCControlExitValid,
    CMatCControlExitRejected {
      variant_unique,
      issue [LalinCMat.CMatCEmissionIssue],
    },
  },
  product. CMatCControlLoopAssemblyInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    start [LalinCMat.CMatCFragmentBoundEmitted],
    trip [LalinCMat.CMatCFragmentBoundEmitted],
    condition [LalinC.CBackendAtom],
    polarity [LalinCMat.CMatCControlContinuePolarity],
    early [LalinCMat.CMatCExitBindingFound],
    exhausted [LalinCMat.CMatCExitBindingFound],
    early_args [many [LalinCMat.CMatCExitArgumentValue]],
    exhausted_args [many [LalinCMat.CMatCExitArgumentValue]],
    control [LalinCMat.CMatCControlResult],
  },
  product. CMatCControlExitPairValidationInput {
    interned,
    assembly [LalinCMat.CMatCControlLoopAssemblyInput],
    exhausted [LalinCMat.CMatCControlExitValidation],
  },
  product. CMatCFindExitCollectionInput {
    interned,
    body [LalinCMat.CMatCFragmentBodyFind],
    start [LalinCMat.CMatCFragmentBoundEmitted],
    trip [LalinCMat.CMatCFragmentBoundEmitted],
    found [LalinCMat.CMatCExitArgumentCollectionReady],
  },
  product. CMatCFindLoopAssemblyInput {
    interned,
    body [LalinCMat.CMatCFragmentBodyFind],
    start [LalinCMat.CMatCFragmentBoundEmitted],
    trip [LalinCMat.CMatCFragmentBoundEmitted],
    found [LalinCMat.CMatCExitArgumentCollectionReady],
    not_found [LalinCMat.CMatCExitArgumentCollectionReady],
  },
  product. CMatCControlBodyTermInput {
    interned,
    condition [LalinC.CBackendAtom],
    advance [LalinC.CBackendLabel],
    early [LalinC.CBackendLabel],
    early_args [many [LalinC.CBackendAtom]],
  },
  product. CMatCCountedLoopAssemblyInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    start [LalinCMat.CMatCFragmentBoundEmitted],
    trip [LalinCMat.CMatCFragmentBoundEmitted],
    body [LalinCMat.CMatCFragmentBodyPlan],
  },
  product. CMatCExitAssemblyInput {
    interned,
    loop [LalinCMat.CMatCCountedLoopAssemblyInput],
    exit [LalinCMat.CMatCExitBindingFound],
  },
  product. CMatCTypedExitAssemblyInput {
    interned,
    assembly [LalinCMat.CMatCExitAssemblyInput],
    arguments [LalinCMat.CMatCExitArgumentCollectionReady],
  },
  product. CMatCFragmentInput {
    interned,
    materialization [LalinCMat.CMatMaterialization],
    code_func [LalinCode.CodeFunc],
    covered_blocks [many [LalinCode.CodeBlockId]],
    replacement_source [LalinCode.CodeBlockId],
    target [LalinC.CBackendTarget],
    values [LalinCMat.CMatCExternalValueBindingProjection],
    accesses [LalinCMat.CMatCFragmentAccessBindingProjection],
    exits [LalinCMat.CMatCExitBindingProjection],
    namespace [LalinCMat.CMatCFragmentNamespace],
    reserved_labels [many [LalinC.CBackendLabel]],
  },
  product. CMatCMaterializationIssueCollection {
    interned,
    issues [many [LalinCMat.CMatCEmissionIssue]],
  },
  product. CMatCMaterializationSinkValidationInput {
    interned,
    computation [LalinStencil.StencilComputation],
    collection [LalinCMat.CMatCMaterializationIssueCollection],
  },
  product. CMatCMaterializationStreamValidationInput {
    interned,
    streams [LalinStencil.StencilStreamByKernelValueProjection],
    collection [LalinCMat.CMatCMaterializationIssueCollection],
  },
  sum. CMatCExpectedResultSink {
    CMatCResultSinkNotRequired,
    CMatCResultSinkRequired {
      variant_unique,
      sink [LalinStencil.StencilSinkDef],
    },
  },
  sum. CMatCFragmentMaterializationValidation {
    CMatCFragmentMaterializationValid {
      variant_unique,
      materialization [LalinCMat.CMatMaterializedKernelFragment],
    },
    CMatCFragmentMaterializationRejected {
      variant_unique,
      issues [many [LalinCMat.CMatCEmissionIssue]],
    },
  },
  sum. CMatCFragmentInputValidation {
    CMatCFragmentInputValid { variant_unique, input [LalinCMat.CMatCFragmentInput], },
    CMatCFragmentInputRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  product. CMatCFragment {
    interned,
    entry [LalinC.CBackendLabel],
    blocks [many [LalinC.CBackendBlock]],
    locals [many [LalinC.CBackendLocal]],
    helpers [many [LalinC.CBackendHelperUse]],
    block_alignments [many [LalinCMat.CMatCBlockAlignment]],
    value_mappings [many [LalinCMat.CMatCValueMapping]],
    control [LalinCMat.CMatCControlResult],
  },
  sum. CMatCFragmentEmission {
    CMatCFragmentEmitted { variant_unique, fragment [LalinCMat.CMatCFragment], },
    CMatCFragmentRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  sum. CMatCFragmentProducerPlan {
    CMatCFragmentCountedPlan {
      variant_unique,
      materialization [LalinCMat.CMatMaterializedKernelFragment],
    },
    CMatCFragmentWindowPlan {
      variant_unique,
      materialization [LalinCMat.CMatMaterializedKernelFragment],
      axis [LalinStencil.StencilProducerAxis],
      window [LalinStencil.StencilWindowAxis],
    },
  },
  product. CMatCFragmentWindowPlanInput {
    interned,
    materialization [LalinCMat.CMatMaterializedKernelFragment],
    state [LalinCMat.CMatCFragmentState],
    shape [LalinStencil.StencilProduceCountedWindow1D],
  },
  product. CMatCFragmentPlanBodyInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    start [LalinCMat.CMatCFragmentBoundEmitted],
    trip [LalinCMat.CMatCFragmentBoundEmitted],
  },
  product. CMatCFragmentWindowInstallInput {
    interned,
    plan [LalinCMat.CMatCFragmentWindowPlan],
    body [LalinCMat.CMatCFragmentPlanBodyInput],
  },
  product. CMatCFragmentCFGSealInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    term [LalinC.CBackendTerminator],
    next_label [LalinC.CBackendLabel],
    next_params [many [LalinC.CBackendBlockParam]],
  },
  sum. CMatCWindowOffsetResolution {
    CMatCWindowOffsetResolved { variant_unique, offset [number], },
    CMatCWindowOffsetRejected { variant_unique, issue [LalinCMat.CMatCEmissionIssue], },
  },
  sum. CMatCWindowOffsetValidation {
    CMatCWindowOffsetValid {
      variant_unique,
      request [LalinCMat.CMatCWindowLoadInput],
    },
    CMatCWindowOffsetInvalid {
      variant_unique,
      issue [LalinCMat.CMatCEmissionIssue],
    },
  },
  product. CMatCWindowBinaryInput {
    interned,
    stem [str],
    op [LalinCore.BinaryOp],
    left [LalinC.CBackendAtom],
    right [LalinC.CBackendAtom],
    field. ty [LalinC.CBackendType],
  },
  product. CMatCWindowCompareInput {
    interned,
    stem [str],
    cmp [LalinCore.CmpOp],
    left [LalinC.CBackendAtom],
    right [LalinC.CBackendAtom],
    operand_ty [LalinC.CBackendType],
  },
  product. CMatCWindowSelectInput {
    interned,
    stem [str],
    condition [LalinC.CBackendAtom],
    then_value [LalinC.CBackendAtom],
    else_value [LalinC.CBackendAtom],
    field. ty [LalinC.CBackendType],
  },
  product. CMatCWindowLoadRequest {
    interned,
    state [LalinCMat.CMatCFragmentState],
    stream [LalinStencil.StencilStreamByKernelValueEntry],
    access [LalinStencil.StencilAccessRef],
  },
  product. CMatCWindowLoadInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    stream [LalinStencil.StencilStreamByKernelValueEntry],
    access [LalinStencil.StencilAccessRef],
    offset [number],
  },
  product. CMatCWindowPosition {
    interned,
    state [LalinCMat.CMatCFragmentState],
    condition [LalinC.CBackendAtom],
    target_ordinal [LalinC.CBackendAtom],
  },
  product. CMatCWindowResolvedLoadInput {
    interned,
    request [LalinCMat.CMatCWindowLoadInput],
    index [LalinC.CBackendAtom],
  },
  product. CMatCWindowGuardedLoadInput {
    interned,
    request [LalinCMat.CMatCWindowLoadInput],
    index [LalinC.CBackendAtom],
    condition [LalinC.CBackendAtom],
  },
  product. CMatCWindowGuardedPlaceInput {
    interned,
    guarded [LalinCMat.CMatCWindowGuardedLoadInput],
    result [LalinC.CBackendLocal],
    zero_label [LalinC.CBackendLabel],
    join_label [LalinC.CBackendLabel],
  },
  sum. CMatCWindowLoadEmission {
    CMatCWindowLoadEmitted {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      atom [LalinC.CBackendAtom],
      field. ty [LalinC.CBackendType],
    },
    CMatCWindowLoadRejected { variant_unique, issues [many [LalinCMat.CMatCEmissionIssue]], },
  },
  product. CMatCFragmentPredicateCompareInput {
    interned,
    source [LalinCMat.CMatCFragmentPredicateInput],
    cmp [LalinCore.CmpOp],
  },
  product. CMatCControlSinkInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    sink [LalinStencil.StencilSinkDef],
  },
  product. CMatCControlExitInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    sink [LalinStencil.StencilSinkDef],
    condition [LalinC.CBackendAtom],
    provenance [LalinStencil.StencilKernelResultProvenance],
  },
  product. CMatCControlSecondExitInput {
    interned,
    control [LalinCMat.CMatCControlExitInput],
    first [LalinCMat.CMatCExitBindingFound],
  },
  product. CMatCControlPredicateRequest {
    interned,
    control [LalinCMat.CMatCControlSinkInput],
    pred [LalinStencil.StencilPredicate],
  },
  product. CMatCControlPredicateInput {
    interned,
    control [LalinCMat.CMatCControlSinkInput],
    stream [LalinCMat.CMatCFragmentStreamFound],
    pred [LalinStencil.StencilPredicate],
  },
  product. CMatCControlResolvedExitsInput {
    interned,
    control [LalinCMat.CMatCControlExitInput],
    first [LalinCMat.CMatCExitBindingFound],
    second [LalinCMat.CMatCExitBindingFound],
  },
  product. CMatCControlFindValueInput {
    interned,
    control [LalinCMat.CMatCControlExitInput],
    found [LalinCMat.CMatCExitBindingFound],
    not_found [LalinCMat.CMatCExitBindingFound],
  },
  product. CMatCControlAllCompareRequest {
    interned,
    control [LalinCMat.CMatCControlSinkInput],
    operation [LalinStencil.StencilSinkOpAllCompare],
  },
  product. CMatCControlAllCompareInput {
    interned,
    control [LalinCMat.CMatCControlSinkInput],
    operation [LalinStencil.StencilSinkOpAllCompare],
    left [LalinCMat.CMatCFragmentStreamFound],
  },
  product. CMatCFragmentPredicateInput {
    interned,
    state [LalinCMat.CMatCFragmentState],
    source [LalinC.CBackendAtom],
    source_ty [LalinC.CBackendType],
  },
  sum. CMatCFragmentPredicateEmission {
    CMatCFragmentPredicateEmitted {
      variant_unique,
      state [LalinCMat.CMatCFragmentState],
      condition [LalinC.CBackendAtom],
    },
    CMatCFragmentPredicateRejected {
      variant_unique,
      issues [many [LalinCMat.CMatCEmissionIssue]],
    },
  },

  product. CMatModule {
    interned,
    field. module [LalinCode.CodeModuleId],
    kernels [many [LalinCMat.CMatMaterialization]],
  },
}
