local S = require("lalin.schema.dsl")
S.use()

return schema. LalinKernel {
  product. KernelId { interned, text [str], },
  product. KernelValueId { interned, text [str], },
  product. KernelLaneId { interned, text [str], },
  sum. KernelSubject {
    KernelSubjectFunction { variant_unique, func [LalinCode.CodeFuncId], },
    KernelSubjectLoop { variant_unique, loop [LalinGraph.GraphLoopId], },
    KernelSubjectDomain { variant_unique, domain [LalinFlow.FlowDomain], },
    KernelSubjectFragment {
      variant_unique,
      func [LalinCode.CodeFuncId],
      entry [LalinCode.CodeBlockId],
      exit [LalinCode.CodeBlockId],
    },
  },
  sum. KernelReject {
    KernelRejectNoFacts { variant_unique, subject [LalinKernel.KernelSubject], reason [str], },
    KernelRejectUnsupportedSubject {
      variant_unique,
      subject [LalinKernel.KernelSubject],
      reason [str],
    },
    KernelRejectUnsupportedExpr {
      variant_unique,
      field. value [LalinCode.CodeValueId],
      reason [str],
    },
    KernelRejectUnsupportedMemory {
      variant_unique,
      access [LalinMem.MemAccessId],
      reason [str],
    },
    KernelRejectEffect { variant_unique, effect [LalinEffect.OpEffect], reason [str], },
    KernelRejectIncompleteFunction {
      variant_unique,
      func [LalinCode.CodeFuncId],
      reason [str],
    },
  },
  sum. KernelProof {
    KernelProofFlow { variant_unique, domain [LalinFlow.FlowDomain], reason [str], },
    KernelProofValue { variant_unique, proof [LalinValue.AlgebraProof], reason [str], },
    KernelProofMemory { variant_unique, proof [LalinMem.MemProof], reason [str], },
    KernelProofEffect { variant_unique, effect [LalinEffect.OpEffect], reason [str], },
    KernelProofFunctionEquivalence { variant_unique, reason [str], },
  },
  sum. KernelDomain {
    KernelDomainFlow {
      variant_unique,
      domain [LalinFlow.FlowDomain],
      trip_count [LalinFlow.FlowTripCount],
      counter [optional [LalinCode.CodeValueId]],
    },
  },
  product. KernelLane {
    interned,
    field. id [LalinKernel.KernelLaneId],
    object [LalinMem.MemObjectId],
    accesses [many [LalinMem.MemAccessId]],
    base [LalinMem.MemBase],
    elem_ty [LalinCode.CodeType],
    pattern [LalinMem.MemAccessPattern],
    backend_info [many [LalinMem.MemBackendAccessInfo]],
  },
  sum. KernelExpr {
    KernelExprValue { variant_unique, field. value [LalinCode.CodeValueId], },
    KernelExprAlgebra { variant_unique, field. expr [LalinValue.ValueExpr], },
    KernelExprLaneLoad {
      variant_unique,
      field. lane [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
    },
    KernelExprKernelValue { variant_unique, field. value [LalinKernel.KernelValueId], },
  },
  product. KernelBinding {
    interned,
    field. id [LalinKernel.KernelValueId],
    field. ty [LalinCode.CodeType],
    field. expr [LalinKernel.KernelExpr],
  },
  product. KernelBindingByValueEntry {
    interned,
    kernel_value_name [str],
    binding [LalinKernel.KernelBinding],
  },
  product. KernelAliasByValueEntry {
    interned,
    value_name [str],
    aliased_value [LalinCode.CodeValueId],
  },
  product. KernelExprProjection {
    binding_by_kernel_value [many [LalinKernel.KernelBindingByValueEntry]],
    alias_by_value [many [LalinKernel.KernelAliasByValueEntry]],
  },
  sum. KernelEffect {
    KernelEffectStore {
      variant_unique,
      dst [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
      field. value [LalinKernel.KernelExpr],
    },
    KernelEffectScan {
      variant_unique,
      dst [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
      reduction [LalinValue.ReductionFact],
      mode [LalinStencil.StencilScanMode],
      axis [optional [LalinStencil.StencilAxisRef]],
    },
    KernelEffectPartition {
      variant_unique,
      dst [LalinKernel.KernelLane],
      src [LalinKernel.KernelExpr],
      pred [LalinStencil.StencilPredicate],
      semantics [LalinStencil.StencilPartitionSemantics],
    },
    KernelEffectCopy {
      variant_unique,
      dst [LalinKernel.KernelLane],
      src [LalinKernel.KernelExpr],
      semantics [LalinStencil.StencilCopySemantics],
    },
    KernelEffectScatterReduce {
      variant_unique,
      dst [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
      field. value [LalinKernel.KernelExpr],
      reducer [LalinStencil.StencilReducer],
    },
    KernelEffectFold { variant_unique, reduction [LalinValue.ReductionFact], },
    KernelEffectCall { variant_unique, call [LalinEffect.CallSummary], },
  },
  sum. KernelResult {
    KernelResultVoid,
    KernelResultValue { variant_unique, field. expr [LalinKernel.KernelExpr], },
    KernelResultFind {
      variant_unique,
      src [LalinKernel.KernelExpr],
      pred [LalinStencil.StencilPredicate],
      not_found [LalinValue.ValueExpr],
    },
    KernelResultAll {
      variant_unique,
      src [LalinKernel.KernelExpr],
      pred [LalinStencil.StencilPredicate],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    KernelResultAllCompare {
      variant_unique,
      left [LalinKernel.KernelExpr],
      right [LalinKernel.KernelExpr],
      cmp [LalinCore.CmpOp],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    KernelResultAny {
      variant_unique,
      src [LalinKernel.KernelExpr],
      pred [LalinStencil.StencilPredicate],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    KernelResultReduction { variant_unique, reduction [LalinValue.ReductionFact], },
    KernelResultClosedForm { variant_unique, closed_form [LalinValue.ClosedFormFact], },
    KernelResultOriginalControl { variant_unique, reject [LalinKernel.KernelResultOriginalControlReject], },
  },
  sum. KernelResultOriginalControlReject {
    KernelOriginalNoCountedLoop,
    KernelOriginalNonReducibleCFG { reason [str] },
    KernelOriginalUnsupportedMemoryPattern { access [LalinMem.MemAccessId] },
    KernelOriginalNoAlgebraicForm { field. value [LalinCode.CodeValueId], },
  },
  sum. KernelSkeletonKind {
    KernelSkeletonKindScan,
    KernelSkeletonKindCopy,
    KernelSkeletonKindScatterReduce,
    KernelSkeletonKindFind,
  },
  product. KernelSkeletonSelectionResult {
    interned,
    kind [LalinKernel.KernelSkeletonKind],
    effects [many [LalinKernel.KernelEffect]],
    result [LalinKernel.KernelResult],
  },
  sum. KernelSkeletonSelection {
    KernelSkeletonSelection { skeleton [LalinKernel.KernelSkeletonSelectionResult] },
    KernelSkeletonNoSelection { rejects [many [LalinKernel.KernelReject]] },
  },
  sum. KernelFunctionSkeletonSelection {
    KernelFunctionSkeletonPartition { variant_unique, plan [LalinKernel.KernelPlanned], },
    KernelFunctionSkeletonNoSelection {
      variant_unique,
      subject [LalinKernel.KernelSubject],
      rejects [many [LalinKernel.KernelReject]],
    },
  },
  sum. KernelEquivalenceFailure {
    KernelEquivLoopNotCounted { loop [LalinGraph.GraphLoopId] },
    KernelEquivMemoryEffectMismatch { expected [LalinEffect.OpEffect], actual [LalinEffect.OpEffect] },
    KernelEquivValueNotEquivalent { field. value [LalinCode.CodeValueId], reason_description [str], },
    KernelEquivAliasUnknown { a [LalinMem.MemAccessId], b [LalinMem.MemAccessId] },
  },
  sum. KernelEquivalence {
    KernelEquivalenceProof { variant_unique, proofs [many [LalinKernel.KernelProof]], },
    KernelEquivalenceRejected { variant_unique, failures [many [LalinKernel.KernelEquivalenceFailure]], },
  },
  sum. KernelLoopCandidate {
    KernelLoopNotCounted { variant_unique, rejects [many [LalinKernel.KernelReject]], },
    KernelLoopMissingOwner { variant_unique, rejects [many [LalinKernel.KernelReject]], },
    KernelLoopRejectedFacts { variant_unique, rejects [many [LalinKernel.KernelReject]], },
    KernelLoopClosedFormCandidate {
      variant_unique,
      closed_form [LalinValue.ClosedFormFact],
      trip_count [LalinFlow.FlowTripCount],
    },
    KernelLoopReductionCandidate { variant_unique, reduction [LalinValue.ReductionFact], },
    KernelLoopSkeletonCandidate { variant_unique, result [LalinKernel.KernelResult], },
    KernelLoopOriginalControlCandidate,
  },
  sum. KernelLoopPlanSelection {
    KernelLoopNoPlan { variant_unique, rejects [many [LalinKernel.KernelReject]], },
    KernelLoopPlanClosedForm {
      variant_unique,
      closed_form [LalinValue.ClosedFormFact],
      add_trip_unknown_proof [bool],
    },
    KernelLoopPlanReduction { variant_unique, reduction [LalinValue.ReductionFact], },
    KernelLoopPlanSkeleton { variant_unique, result [LalinKernel.KernelResult], },
    KernelLoopPlanOriginalControl,
  },
  sum. KernelRewriteKind {
    KernelRewriteClosedForm {
      variant_unique,
      expression [LalinValue.ValueExpr],
      accumulator [optional [LalinKernel.KernelExpr]],
    },
    KernelRewriteMemcpy {
      variant_unique,
      dst_base [LalinCode.CodeValueId],
      src_base [LalinCode.CodeValueId],
      elem_size [number],
      semantics [LalinMem.MemDependenceFact],
    },
    KernelRewriteScan {
      variant_unique,
      dst [LalinKernel.KernelLane],
      src [LalinKernel.KernelLane],
      reduction [LalinValue.ReductionFact],
      mode [LalinStencil.StencilScanMode],
      trip_count [LalinValue.ValueExpr],
    },
    KernelRewriteFind {
      variant_unique,
      src [LalinKernel.KernelLane],
      predicate [LalinKernel.KernelExpr],
      result_local [LalinCode.CodeValueId],
      trip_count [LalinValue.ValueExpr],
    },
    KernelRewriteReduce {
      variant_unique,
      reduction [LalinValue.ReductionFact],
      field. identity [LalinValue.ValueExpr],
      result_local [LalinCode.CodeValueId],
      trip_count [LalinValue.ValueExpr],
    },
    KernelRewriteKeepOriginal,
    KernelRewriteCouldNotPlan { rejects [many [LalinKernel.KernelReject]] },
  },
  product. KernelRewritePlan {
    interned,
    kind [LalinKernel.KernelRewriteKind],
    loop_header_block [LalinCode.CodeBlockId],
    loop_exit_blocks [many [LalinCode.CodeBlockId]],
    covered_blocks [many [LalinCode.CodeBlockId]],
    proofs [many [LalinKernel.KernelProof]],
  },
  product. KernelLoopPlanBuild {
    interned,
    domain [LalinFlow.FlowDomain],
    trip_count [LalinFlow.FlowTripCount],
    counter [optional [LalinCode.CodeValueId]],
    lanes [many [LalinKernel.KernelLane]],
    bindings [many [LalinKernel.KernelBinding]],
    effects [many [LalinKernel.KernelEffect]],
    proofs [many [LalinKernel.KernelProof]],
  },
  product. KernelBody {
    interned,
    domain [LalinKernel.KernelDomain],
    lanes [many [LalinKernel.KernelLane]],
    bindings [many [LalinKernel.KernelBinding]],
    effects [many [LalinKernel.KernelEffect]],
    result [LalinKernel.KernelResult],
    equivalence [LalinKernel.KernelEquivalence],
  },
  sum. KernelPlan {
    KernelNoPlan {
      variant_unique,
      subject [LalinKernel.KernelSubject],
      rejects [many [LalinKernel.KernelReject]],
    },
    KernelPlanned {
      variant_unique,
      field. id [LalinKernel.KernelId],
      subject [LalinKernel.KernelSubject],
      body [LalinKernel.KernelBody],
    },
  },
  product. KernelModulePlan {
    interned,
    field. module [LalinCode.CodeModuleId],
    flow [LalinFlow.FlowFactSet],
    field. value [LalinValue.ValueFactSet],
    mem [LalinMem.MemSemanticFactSet],
    effect [LalinEffect.EffectFactSet],
    plans [many [LalinKernel.KernelPlan]],
  },
}