local S = require("lalin.schema.dsl")
S.use()

return schema. LalinKernel {
  product. KernelId { interned, text [str], },
  product. KernelValueId { interned, text [str], },
  product. KernelLaneId { interned, text [str], },
  product. KernelIndexExprProjectionInput {
    interned,
    values [LalinValue.ValueFactSet],
    field. value [LalinCode.CodeValueId],
  },
  sum. KernelSubject {
    KernelSubjectFunction { variant_unique, func [LalinCode.CodeFuncId], },
    KernelSubjectLoop { variant_unique, loop [LalinGraph.GraphLoopId], },
    KernelSubjectDomain { variant_unique, domain [LalinFlow.FlowDomain], },
    KernelSubjectFragment {
      variant_unique,
      func [LalinCode.CodeFuncId],
      entry [LalinCode.CodeBlockId],
      exit [LalinCode.CodeBlockId],
    },
  },
  sum. KernelReject {
    KernelRejectNoFacts { variant_unique, subject [LalinKernel.KernelSubject], reason [str], },
    KernelRejectUnsupportedSubject {
      variant_unique,
      subject [LalinKernel.KernelSubject],
      reason [str],
    },
    KernelRejectUnsupportedExpr {
      variant_unique,
      field. value [LalinCode.CodeValueId],
      reason [str],
    },
    KernelRejectUnsupportedMemory {
      variant_unique,
      access [LalinMem.MemAccessId],
      reason [str],
    },
    KernelRejectEffect { variant_unique, effect [LalinEffect.OpEffect], reason [str], },
    KernelRejectIncompleteFunction {
      variant_unique,
      func [LalinCode.CodeFuncId],
      reason [str],
    },
  },
  sum. KernelProof {
    KernelProofFlow { variant_unique, domain [LalinFlow.FlowDomain], reason [str], },
    KernelProofValue { variant_unique, proof [LalinValue.AlgebraProof], reason [str], },
    KernelProofMemory { variant_unique, proof [LalinMem.MemProof], reason [str], },
    KernelProofEffect { variant_unique, effect [LalinEffect.OpEffect], reason [str], },
    KernelProofFunctionEquivalence { variant_unique, reason [str], },
  },
  sum. KernelTripEvidence {
    KernelTripKnown { variant_unique, trip_count [LalinFlow.FlowTripCount], },
    KernelTripUnavailable {
      variant_unique,
      trip_count [LalinFlow.FlowTripCount],
      reject [LalinKernel.KernelReject],
    },
  },
  sum. KernelCounter {
    KernelCounterAbsent,
    KernelCounterValue { variant_unique, field. value [LalinCode.CodeValueId], },
  },
  sum. KernelCounterContribution {
    KernelCounterIgnored,
    KernelCounterCandidate { variant_unique, counter [LalinKernel.KernelCounterValue], },
  },
  sum. KernelCounterSelection {
    KernelCounterSelected { variant_unique, counter [LalinKernel.KernelCounterValue], },
    KernelCounterMissing { variant_unique, reject [LalinKernel.KernelReject], },
    KernelCounterAmbiguous { variant_unique, counters [many [LalinKernel.KernelCounterValue]], reject [LalinKernel.KernelReject], },
  },
  sum. KernelDomain {
    KernelDomainFlow {
      variant_unique,
      domain [LalinFlow.FlowDomain],
      trip [LalinKernel.KernelTripEvidence],
      counter [LalinKernel.KernelCounter],
    },
  },
  product. KernelLane {
    interned,
    field. id [LalinKernel.KernelLaneId],
    object [LalinMem.MemObjectId],
    accesses [many [LalinMem.MemAccessId]],
    base [LalinMem.MemBase],
    elem_ty [LalinCode.CodeType],
    pattern [LalinMem.MemAccessPattern],
    backend_info [many [LalinMem.MemBackendAccessInfo]],
  },
  product. KernelLaneByAccessEntry { interned, access [LalinMem.MemAccessId], field. lane [LalinKernel.KernelLane], },
  product. KernelLaneProjection { interned, entries [many [LalinKernel.KernelLaneByAccessEntry]], },
  sum. KernelLaneLookup {
    KernelLaneFound { variant_unique, entry [LalinKernel.KernelLaneByAccessEntry], },
    KernelLaneMissing { variant_unique, access [LalinMem.MemAccessId], },
  },
  sum. KernelExpr {
    KernelExprValue { variant_unique, field. value [LalinCode.CodeValueId], },
    KernelExprAlgebra { variant_unique, field. expr [LalinValue.ValueExpr], },
    KernelExprLaneLoad {
      variant_unique,
      field. lane [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
    },
    KernelExprKernelValue { variant_unique, field. value [LalinKernel.KernelValueId], },
  },
  product. KernelBinding {
    interned,
    field. id [LalinKernel.KernelValueId],
    field. ty [LalinCode.CodeType],
    field. expr [LalinKernel.KernelExpr],
  },
  product. KernelBindingByCodeValueEntry { interned, field. value [LalinCode.CodeValueId], binding [LalinKernel.KernelBinding], },
  product. KernelBindingProjection { interned, entries [many [LalinKernel.KernelBindingByCodeValueEntry]], },
  sum. KernelBindingLookup {
    KernelBindingFound { variant_unique, entry [LalinKernel.KernelBindingByCodeValueEntry], },
    KernelBindingMissing { variant_unique, field. value [LalinCode.CodeValueId], },
  },
  product. KernelBindingByValueEntry {
    interned,
    kernel_value_name [str],
    binding [LalinKernel.KernelBinding],
  },
  product. KernelAliasByValueEntry {
    interned,
    value_name [str],
    aliased_value [LalinCode.CodeValueId],
  },
  product. KernelExprProjection {
    binding_by_kernel_value [many [LalinKernel.KernelBindingByValueEntry]],
    alias_by_value [many [LalinKernel.KernelAliasByValueEntry]],
  },
  sum. KernelEffect {
    KernelEffectStore {
      variant_unique,
      dst [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
      field. value [LalinKernel.KernelExpr],
    },
    KernelEffectScan {
      variant_unique,
      dst [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
      reduction [LalinValue.ReductionFact],
      mode [LalinStencil.StencilScanMode],
      axis [LalinKernel.KernelScanAxis],
    },
    KernelEffectScatterReduce {
      variant_unique,
      dst [LalinKernel.KernelLane],
      index [LalinValue.ValueExpr],
      field. value [LalinKernel.KernelExpr],
      reducer [LalinStencil.StencilReducer],
    },
    KernelEffectFold { variant_unique, reduction [LalinValue.ReductionFact], },
    KernelEffectCall { variant_unique, call [LalinEffect.CallSummary], },
  },
  sum. KernelScanAxis {
    KernelScanLinear,
    KernelScanAlongAxis { variant_unique, axis [LalinStencil.StencilAxisRef], },
  },
  product. KernelEffectByInstructionEntry { interned, inst [LalinGraph.GraphInstRef], effect [LalinKernel.KernelEffect], },
  product. KernelEffectProjection { interned, entries [many [LalinKernel.KernelEffectByInstructionEntry]], },
  sum. KernelEffectLookup {
    KernelEffectFound { variant_unique, entry [LalinKernel.KernelEffectByInstructionEntry], },
    KernelEffectMissing { variant_unique, inst [LalinGraph.GraphInstRef], },
  },
  product. KernelProofProjection { interned, proofs [many [LalinKernel.KernelProof]], },
  sum. KernelResult {
    KernelResultVoid,
    KernelResultValue { variant_unique, field. expr [LalinKernel.KernelExpr], },
    KernelResultFind {
      variant_unique,
      src [LalinKernel.KernelExpr],
      src_value [LalinCode.CodeValueId],
      pred [LalinStencil.StencilPredicate],
      found_value [LalinCode.CodeValueId],
      found [LalinCode.CodeBlockId],
      not_found [LalinCode.CodeBlockId],
      not_found_value [LalinValue.ValueExpr],
    },
    KernelResultAll {
      variant_unique,
      src [LalinKernel.KernelExpr],
      src_value [LalinCode.CodeValueId],
      pred [LalinStencil.StencilPredicate],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    KernelResultAllCompare {
      variant_unique,
      left [LalinKernel.KernelExpr],
      left_value [LalinCode.CodeValueId],
      right [LalinKernel.KernelExpr],
      right_value [LalinCode.CodeValueId],
      cmp [LalinCore.CmpOp],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    KernelResultAny {
      variant_unique,
      src [LalinKernel.KernelExpr],
      src_value [LalinCode.CodeValueId],
      pred [LalinStencil.StencilPredicate],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    KernelResultReduction { variant_unique, reduction [LalinValue.ReductionFact], },
    KernelResultClosedForm { variant_unique, closed_form [LalinValue.ClosedFormFact], },
    KernelResultOriginalControl { variant_unique, reject [LalinKernel.KernelResultOriginalControlReject], },
  },
  sum. KernelResultOriginalControlReject {
    KernelOriginalNoCountedLoop,
    KernelOriginalNonReducibleCFG { reason [str] },
    KernelOriginalUnsupportedMemoryPattern { access [LalinMem.MemAccessId] },
    KernelOriginalNoAlgebraicForm { field. value [LalinCode.CodeValueId], },
  },
  sum. KernelSkeletonSelection {
    KernelSkeletonScanSelected { variant_unique, effects [LalinKernel.KernelEffectProjection], result [LalinKernel.KernelResult], },
    KernelSkeletonCopySelected { variant_unique, effects [LalinKernel.KernelEffectProjection], result [LalinKernel.KernelResult], },
    KernelSkeletonScatterReduceSelected { variant_unique, effects [LalinKernel.KernelEffectProjection], result [LalinKernel.KernelResult], },
    KernelSkeletonFindSelected { variant_unique, effects [LalinKernel.KernelEffectProjection], result [LalinKernel.KernelResult], },
    KernelSkeletonAllSelected { variant_unique, effects [LalinKernel.KernelEffectProjection], result [LalinKernel.KernelResult], },
    KernelSkeletonAllCompareSelected { variant_unique, effects [LalinKernel.KernelEffectProjection], result [LalinKernel.KernelResult], },
    KernelSkeletonAnySelected { variant_unique, effects [LalinKernel.KernelEffectProjection], result [LalinKernel.KernelResult], },
    KernelSkeletonNoSelection { variant_unique, rejects [many [LalinKernel.KernelReject]], },
  },
  product. KernelScanSelectionInput {
    interned,
    reduction [LalinValue.ReductionFact],
    build [LalinKernel.KernelLoopPlanBuild],
    entry [LalinKernel.KernelEffectByInstructionEntry],
  },
  product. KernelScanIndexInput {
    interned,
    selection [LalinKernel.KernelScanSelectionInput],
    counter [LalinCode.CodeValueId],
  },
  product. KernelScanMaterializationInput {
    interned,
    request [LalinKernel.KernelLoopPlanRequest],
    build [LalinKernel.KernelLoopPlanBuild],
    reduction [LalinValue.ReductionFact],
  },
  sum. KernelFunctionSkeletonSelection {
    KernelFunctionSkeletonPartition { variant_unique, plan [LalinKernel.KernelPlanned], },
    KernelFunctionSkeletonNoSelection {
      variant_unique,
      subject [LalinKernel.KernelSubject],
      rejects [many [LalinKernel.KernelReject]],
    },
  },
  sum. KernelEquivalenceFailure {
    KernelEquivLoopNotCounted { loop [LalinGraph.GraphLoopId] },
    KernelEquivMemoryEffectMismatch { expected [LalinEffect.OpEffect], actual [LalinEffect.OpEffect] },
    KernelEquivValueNotEquivalent { field. value [LalinCode.CodeValueId], reason_description [str], },
    KernelEquivAliasUnknown { a [LalinMem.MemAccessId], b [LalinMem.MemAccessId] },
  },
  sum. KernelEquivalence {
    KernelEquivalenceProof { variant_unique, proofs [many [LalinKernel.KernelProof]], },
    KernelEquivalenceRejected { variant_unique, failures [many [LalinKernel.KernelEquivalenceFailure]], },
  },
  product. KernelReductionByLoopEntry {
    interned,
    loop [LalinGraph.GraphLoopId],
    reduction [LalinValue.ReductionFact],
  },
  product. KernelClosedFormByLoopEntry {
    interned,
    loop [LalinGraph.GraphLoopId],
    closed_form [LalinValue.ClosedFormFact],
  },
  product. KernelTripByLoopEntry {
    interned,
    loop [LalinGraph.GraphLoopId],
    trip_count [LalinFlow.FlowTripCount],
  },
  product. KernelTripProjection { entries [many [LalinKernel.KernelTripByLoopEntry]], },
  sum. KernelTripLookup {
    KernelTripFound { variant_unique, entry [LalinKernel.KernelTripByLoopEntry], },
    KernelTripMissing { variant_unique, loop [LalinGraph.GraphLoopId], },
  },
  sum. KernelLoopCountEvidence {
    KernelLoopCounted { variant_unique, domain [LalinFlow.FlowCountedDomain], },
    KernelLoopNotCountedEvidence { variant_unique, reject [LalinKernel.KernelReject], },
  },
  product. KernelLoopFactEntry {
    interned,
    loop [LalinGraph.GraphLoopId],
    domain [LalinFlow.FlowDomain],
    count [LalinKernel.KernelLoopCountEvidence],
    counter [LalinKernel.KernelCounterSelection],
    trip [LalinKernel.KernelTripEvidence],
  },
  product. KernelLoopFactProjection {
    loops [many [LalinKernel.KernelLoopFactEntry]],
    reductions [many [LalinKernel.KernelReductionByLoopEntry]],
    closed_forms [many [LalinKernel.KernelClosedFormByLoopEntry]],
  },
  sum. KernelReductionContribution {
    KernelReductionForLoop { variant_unique, entry [LalinKernel.KernelReductionByLoopEntry], },
    KernelReductionOutsideLoop { variant_unique, reduction [LalinValue.ReductionFact], },
  },
  sum. KernelClosedFormContribution {
    KernelClosedFormForLoop { variant_unique, entry [LalinKernel.KernelClosedFormByLoopEntry], },
    KernelClosedFormOutsideLoop { variant_unique, closed_form [LalinValue.ClosedFormFact], },
  },
  sum. KernelReductionLookup {
    KernelReductionFound { variant_unique, entries [many [LalinKernel.KernelReductionByLoopEntry]], },
    KernelReductionMissing { variant_unique, loop [LalinGraph.GraphLoopId], },
  },
  sum. KernelClosedFormLookup {
    KernelClosedFormFound { variant_unique, entries [many [LalinKernel.KernelClosedFormByLoopEntry]], },
    KernelClosedFormMissing { variant_unique, loop [LalinGraph.GraphLoopId], },
  },
  sum. KernelDomainAnalysis {
    KernelDomainAnalysisAllowed,
    KernelDomainAnalysisScalar { variant_unique, reject [LalinKernel.KernelReject], },
  },
  product. KernelLoopAnalysisInput {
    interned,
    field. module [LalinCode.CodeModule],
    graph [LalinGraph.CodeGraph],
    flow [LalinFlow.FlowFactSet],
    values [LalinValue.ValueFactSet],
    mem [LalinMem.MemSemanticFactSet],
    effects [LalinEffect.EffectFactSet],
    fact [LalinKernel.KernelLoopFactEntry],
    candidate [LalinKernel.KernelLoopCandidate],
  },
  sum. KernelLoopAnalysis {
    KernelLoopAnalysisReady { variant_unique, build [LalinKernel.KernelLoopPlanBuild], },
    KernelLoopAnalysisRejected { variant_unique, fact [LalinKernel.KernelLoopFactEntry], rejects [many [LalinKernel.KernelReject]], },
  },
  product. KernelLoopPlanRequest {
    interned,
    fact [LalinKernel.KernelLoopFactEntry],
    candidate [LalinKernel.KernelLoopCandidate],
    analysis [LalinKernel.KernelLoopAnalysis],
  },
  product. KernelModulePlanRequest {
    interned,
    field. module [LalinCode.CodeModule],
    graph [LalinGraph.CodeGraph],
    flow [LalinFlow.FlowFactSet],
    values [LalinValue.ValueFactSet],
    mem [LalinMem.MemSemanticFactSet],
    effects [LalinEffect.EffectFactSet],
    trips [LalinKernel.KernelTripProjection],
  },
  sum. KernelLoopCandidate {
    KernelLoopNotCounted { variant_unique, rejects [many [LalinKernel.KernelReject]], },
    KernelLoopMissingOwner { variant_unique, rejects [many [LalinKernel.KernelReject]], },
    KernelLoopRejectedFacts { variant_unique, rejects [many [LalinKernel.KernelReject]], },
    KernelLoopClosedFormCandidate { variant_unique, closed_form [LalinValue.ClosedFormFact], },
    KernelLoopReductionCandidate { variant_unique, reduction [LalinValue.ReductionFact], },
    KernelLoopSkeletonCandidate { variant_unique, result [LalinKernel.KernelResult], },
    KernelLoopOriginalControlCandidate { variant_unique, rejects [many [LalinKernel.KernelReject]], },
  },
  sum. KernelLoopPlanSelection {
    KernelLoopNoPlan { variant_unique, rejects [many [LalinKernel.KernelReject]], },
    KernelLoopPlanClosedForm { variant_unique, closed_form [LalinValue.ClosedFormFact], },
    KernelLoopPlanReduction { variant_unique, reduction [LalinValue.ReductionFact], },
    KernelLoopPlanSkeleton { variant_unique, result [LalinKernel.KernelResult], },
    KernelLoopPlanOriginalControl { variant_unique, rejects [many [LalinKernel.KernelReject]], },
  },
  sum. KernelScheduleEligibility {
    KernelScheduleEligible { variant_unique, plan [LalinKernel.KernelPlanned], },
    KernelScheduleIneligible {
      variant_unique,
      subject [LalinKernel.KernelSubject],
      rejects [many [LalinKernel.KernelReject]],
    },
  },
  sum. KernelClosedFormDestination {
    KernelClosedFormReturnsValue,
    KernelClosedFormUpdatesAccumulator { variant_unique, accumulator [LalinKernel.KernelExpr], },
  },
  sum. KernelRewriteKind {
    KernelRewriteClosedForm {
      variant_unique,
      expression [LalinValue.ValueExpr],
      destination [LalinKernel.KernelClosedFormDestination],
    },
    KernelRewriteMemcpy {
      variant_unique,
      dst_base [LalinCode.CodeValueId],
      src_base [LalinCode.CodeValueId],
      elem_size [number],
      semantics [LalinMem.MemDependenceFact],
    },
    KernelRewriteScan {
      variant_unique,
      dst [LalinKernel.KernelLane],
      src [LalinKernel.KernelLane],
      reduction [LalinValue.ReductionFact],
      mode [LalinStencil.StencilScanMode],
      trip_count [LalinValue.ValueExpr],
    },
    KernelRewriteFind {
      variant_unique,
      src [LalinKernel.KernelLane],
      predicate [LalinKernel.KernelExpr],
      result_local [LalinCode.CodeValueId],
      trip_count [LalinValue.ValueExpr],
    },
    KernelRewriteReduce {
      variant_unique,
      reduction [LalinValue.ReductionFact],
      field. identity [LalinValue.ValueExpr],
      result_local [LalinCode.CodeValueId],
      trip_count [LalinValue.ValueExpr],
    },
    KernelRewriteKeepOriginal,
    KernelRewriteCouldNotPlan { rejects [many [LalinKernel.KernelReject]] },
  },
  product. KernelRewritePlan {
    interned,
    kind [LalinKernel.KernelRewriteKind],
    loop_header_block [LalinCode.CodeBlockId],
    loop_exit_blocks [many [LalinCode.CodeBlockId]],
    covered_blocks [many [LalinCode.CodeBlockId]],
    proofs [many [LalinKernel.KernelProof]],
  },
  product. KernelLoopPlanBuild {
    interned,
    domain [LalinFlow.FlowDomain],
    trip [LalinKernel.KernelTripEvidence],
    counter [LalinKernel.KernelCounter],
    lanes [LalinKernel.KernelLaneProjection],
    bindings [LalinKernel.KernelBindingProjection],
    effects [LalinKernel.KernelEffectProjection],
    proofs [LalinKernel.KernelProofProjection],
  },
  product. KernelBody {
    interned,
    domain [LalinKernel.KernelDomain],
    lanes [LalinKernel.KernelLaneProjection],
    bindings [LalinKernel.KernelBindingProjection],
    effects [LalinKernel.KernelEffectProjection],
    result [LalinKernel.KernelResult],
    equivalence [LalinKernel.KernelEquivalence],
  },
  sum. KernelPlan {
    KernelNoPlan {
      variant_unique,
      subject [LalinKernel.KernelSubject],
      rejects [many [LalinKernel.KernelReject]],
    },
    KernelPlanned {
      variant_unique,
      field. id [LalinKernel.KernelId],
      subject [LalinKernel.KernelSubject],
      body [LalinKernel.KernelBody],
    },
  },
  product. KernelModulePlan {
    interned,
    field. module [LalinCode.CodeModuleId],
    flow [LalinFlow.FlowFactSet],
    field. value [LalinValue.ValueFactSet],
    mem [LalinMem.MemSemanticFactSet],
    effect [LalinEffect.EffectFactSet],
    plans [many [LalinKernel.KernelPlan]],
  },
}