local S = require("lalin.schema.dsl")
S.use()

return schema. LalinSem {
  sum. FieldRef {
    FieldByName { variant_unique, field_name [str], field. ty [LalinType.Type], },
    FieldByOffset {
      variant_unique,
      field_name [str],
      offset [number],
      field. ty [LalinType.Type],
      storage [LalinHost.HostFieldRep],
    },
  },
  product. FieldLayout {
    interned,
    field_name [str],
    offset [number],
    field. ty [LalinType.Type],
  },
  product. MemLayout { interned, size [number], align [number], },
  sum. TypeLayout {
    LayoutNamed {
      variant_unique,
      module_name [str],
      type_name [str],
      fields [many [LalinSem.FieldLayout]],
      size [number],
      align [number],
    },
    LayoutLocal {
      variant_unique,
      sym [LalinCore.TypeSym],
      fields [many [LalinSem.FieldLayout]],
      size [number],
      align [number],
    },
  },
  product. LayoutEnv { interned, layouts [many [LalinSem.TypeLayout]], },
  sum. TypeLayoutLookup {
    TypeLayoutMissing,
    TypeLayoutFound { variant_unique, layout [LalinSem.TypeLayout], },
  },
  sum. FieldLayoutLookup {
    FieldLayoutMissing,
    FieldLayoutFound { variant_unique, layout [LalinSem.FieldLayout], },
  },
  sum. LayoutValueType {
    LayoutValueUntyped,
    LayoutValueTyped { variant_unique, field. ty [LalinType.Type], },
  },
  product. ConstFieldValue {
    interned,
    field. name [str],
    field. value [LalinSem.ConstValue],
  },
  sum. ConstValue {
    ConstInt { variant_unique, field. ty [LalinType.Type], raw [str], },
    ConstFloat { variant_unique, field. ty [LalinType.Type], raw [str], },
    ConstBool { variant_unique, field. value [bool], },
    ConstNil { variant_unique, field. ty [LalinType.Type], },
    ConstAgg {
      variant_unique,
      field. ty [LalinType.Type],
      fields [many [LalinSem.ConstFieldValue]],
    },
    ConstArray {
      variant_unique,
      elem_ty [LalinType.Type],
      elems [many [LalinSem.ConstValue]],
    },
  },
  product. ConstLocalEntry {
    interned,
    binding [LalinBind.Binding],
    field. value [LalinSem.ConstValue],
  },
  product. ConstLocalEnv { interned, entries [many [LalinSem.ConstLocalEntry]], },
  product. ConstEvalInput {
    interned,
    const_env [LalinBind.ConstEnv],
    local_env [LalinSem.ConstLocalEnv],
  },
  sum. ConstExprResult {
    ConstKnown { variant_unique, field. value [LalinSem.ConstValue], },
    ConstNotFoldable { variant_unique, reason [str], },
    ConstRejected { variant_unique, reason [str], },
  },
  sum. ConstStmtFlow {
    ConstFallsThrough {
      variant_unique,
      env [LalinSem.ConstLocalEnv],
    },
    ConstReturnVoid {
      variant_unique,
      env [LalinSem.ConstLocalEnv],
    },
    ConstReturnValue {
      variant_unique,
      env [LalinSem.ConstLocalEnv],
      field. value [LalinSem.ConstValue],
    },
    ConstYieldVoid {
      variant_unique,
      env [LalinSem.ConstLocalEnv],
    },
    ConstYieldValue {
      variant_unique,
      env [LalinSem.ConstLocalEnv],
      field. value [LalinSem.ConstValue],
    },
    ConstJump {
      variant_unique,
      env [LalinSem.ConstLocalEnv],
      target [str],
    },
  },
  sum. FlowOutcome {
    FlowUnknown,
    FlowFallsThrough,
    FlowJumps,
    FlowYields,
    FlowReturns,
    FlowTerminates,
  },
  product. ClosureBinding { interned, binding [LalinBind.Binding], },
  product. ClosureScopeFrame { interned, bindings [many [LalinSem.ClosureBinding]], },
  product. ClosureScopeStack { interned, frames [many [LalinSem.ClosureScopeFrame]], },
  product. ClosureCaptureCandidate { interned, binding [LalinSem.ClosureBinding], },
  product. ClosureCaptureSet { interned, candidates [many [LalinSem.ClosureCaptureCandidate]], },
  product. ClosureCaptureSlot {
    interned,
    candidate [LalinSem.ClosureCaptureCandidate],
    offset [number],
    size [number],
    align [number],
  },
  product. ClosureCaptureLayout {
    interned,
    slots [many [LalinSem.ClosureCaptureSlot]],
    size [number],
    align [number],
  },
  product. ClosureEnvironmentEntry {
    interned,
    binding [LalinSem.ClosureBinding],
    slot [LalinSem.ClosureCaptureSlot],
  },
  product. ClosureEnvironment { interned, entries [many [LalinSem.ClosureEnvironmentEntry]], },
  product. ClosureNameSupply {
    interned,
    module_name [str],
    owner_name [str],
    next_index [number],
  },
  product. ClosureFreshName {
    interned,
    field. name [str],
    supply [LalinSem.ClosureNameSupply],
  },
  product. ClosureTraversalInput {
    interned,
    scopes [LalinSem.ClosureScopeStack],
    captures [LalinSem.ClosureCaptureSet],
  },
  sum. ClosureLookup {
    ClosureLookupFound { variant_unique, binding [LalinSem.ClosureBinding], },
    ClosureLookupMissing,
  },
  product. ClosureCollectInput {
    interned,
    scopes [LalinSem.ClosureScopeStack],
    captures [LalinSem.ClosureCaptureSet],
  },
  product. ClosureScopeTransition { interned, scopes [LalinSem.ClosureScopeStack], },
  sum. ClosureCollectResult {
    ClosureCollected { variant_unique, input [LalinSem.ClosureCollectInput], },
    ClosureCollectTransitioned {
      variant_unique,
      input [LalinSem.ClosureCollectInput],
      transition [LalinSem.ClosureScopeTransition],
    },
    ClosureCollectUnsupported { variant_unique, input [LalinSem.ClosureCollectInput], reason [str], },
  },
  product. ClosureCaptureLayoutInput {
    interned,
    candidate [LalinSem.ClosureCaptureCandidate],
    env [LalinSem.LayoutEnv],
    target [LalinHost.HostTargetModel],
    offset [number],
  },
  sum. ClosureCaptureLayoutResult {
    ClosureCaptureLaidOut { variant_unique, slot [LalinSem.ClosureCaptureSlot], },
    ClosureCaptureLayoutUnsupported {
      variant_unique,
      candidate [LalinSem.ClosureCaptureCandidate],
      reason [str],
    },
  },
  product. ClosureLayoutBuildState {
    interned,
    slots [many [LalinSem.ClosureCaptureSlot]],
    offset [number],
    align [number],
  },
  sum. ClosureLayoutBuildResult {
    ClosureLayoutBuilding { variant_unique, state [LalinSem.ClosureLayoutBuildState], },
    ClosureLayoutBuildFailed { variant_unique, reason [str], },
  },
  sum. ClosureEnvironmentLookup {
    ClosureEnvironmentFound { variant_unique, entry [LalinSem.ClosureEnvironmentEntry], },
    ClosureEnvironmentMissing,
  },
  product. ClosureHelperInsertion { interned, items [many [LalinTree.Item]], },
  product. ClosureRewriteInput {
    interned,
    scopes [LalinSem.ClosureScopeStack],
    environment [LalinSem.ClosureEnvironment],
    supply [LalinSem.ClosureNameSupply],
    helpers [LalinSem.ClosureHelperInsertion],
    layouts [LalinSem.LayoutEnv],
    target [LalinHost.HostTargetModel],
  },
  sum. ClosureRewriteStatus {
    ClosureRewriteReady,
    ClosureRewriteBlocked { variant_unique, reason [str], },
  },
  sum. ClosureExprRewriteResult {
    ClosureExprConverted { variant_unique, field. expr [LalinTree.Expr], input [LalinSem.ClosureRewriteInput], },
    ClosureExprUnchanged { variant_unique, field. expr [LalinTree.Expr], input [LalinSem.ClosureRewriteInput], },
    ClosureExprUnsupported { variant_unique, field. expr [LalinTree.Expr], input [LalinSem.ClosureRewriteInput], reason [str], },
  },
  product. ClosureSwitchKeyRewriteResult {
    interned,
    key [LalinTree.SwitchKey],
    input [LalinSem.ClosureRewriteInput],
    status [LalinSem.ClosureRewriteStatus],
  },
  sum. ClosurePlaceRewriteResult {
    ClosurePlaceConverted { variant_unique, place [LalinTree.Place], input [LalinSem.ClosureRewriteInput], },
    ClosurePlaceUnchanged { variant_unique, place [LalinTree.Place], input [LalinSem.ClosureRewriteInput], },
    ClosurePlaceUnsupported { variant_unique, place [LalinTree.Place], input [LalinSem.ClosureRewriteInput], reason [str], },
  },
  sum. ClosureIndexBaseRewriteResult {
    ClosureIndexBaseConverted { variant_unique, base [LalinTree.IndexBase], input [LalinSem.ClosureRewriteInput], },
    ClosureIndexBaseUnchanged { variant_unique, base [LalinTree.IndexBase], input [LalinSem.ClosureRewriteInput], },
    ClosureIndexBaseUnsupported { variant_unique, base [LalinTree.IndexBase], input [LalinSem.ClosureRewriteInput], reason [str], },
  },
  sum. ClosureViewRewriteResult {
    ClosureViewConverted { variant_unique, view [LalinTree.View], input [LalinSem.ClosureRewriteInput], },
    ClosureViewUnchanged { variant_unique, view [LalinTree.View], input [LalinSem.ClosureRewriteInput], },
    ClosureViewUnsupported { variant_unique, view [LalinTree.View], input [LalinSem.ClosureRewriteInput], reason [str], },
  },
  sum. ClosureStmtRewriteResult {
    ClosureStmtConverted { variant_unique, stmt [LalinTree.Stmt], input [LalinSem.ClosureRewriteInput], },
    ClosureStmtUnchanged { variant_unique, stmt [LalinTree.Stmt], input [LalinSem.ClosureRewriteInput], },
    ClosureStmtUnsupported { variant_unique, stmt [LalinTree.Stmt], input [LalinSem.ClosureRewriteInput], reason [str], },
  },
  product. ClosureExprListRewriteResult {
    interned,
    exprs [many [LalinTree.Expr]],
    input [LalinSem.ClosureRewriteInput],
    status [LalinSem.ClosureRewriteStatus],
  },
  product. ClosureStmtListRewriteResult {
    interned,
    stmts [many [LalinTree.Stmt]],
    input [LalinSem.ClosureRewriteInput],
    status [LalinSem.ClosureRewriteStatus],
  },
  product. ClosureJumpArgsRewriteResult {
    interned,
    args [many [LalinTree.JumpArg]],
    input [LalinSem.ClosureRewriteInput],
    status [LalinSem.ClosureRewriteStatus],
  },
  product. ClosureControlChildrenRewriteResult {
    interned,
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
    input [LalinSem.ClosureRewriteInput],
    status [LalinSem.ClosureRewriteStatus],
  },
  product. ClosureFuncInput {
    interned,
    module_name [str],
    supply [LalinSem.ClosureNameSupply],
    outer_scopes [LalinSem.ClosureScopeStack],
    layouts [LalinSem.LayoutEnv],
    target [LalinHost.HostTargetModel],
  },
  sum. ClosureFuncResult {
    ClosureFuncConverted {
      variant_unique,
      field. func [LalinTree.Func],
      helpers [LalinSem.ClosureHelperInsertion],
      supply [LalinSem.ClosureNameSupply],
    },
    ClosureFuncUnchanged { variant_unique, field. func [LalinTree.Func], supply [LalinSem.ClosureNameSupply], },
    ClosureFuncUnsupported { variant_unique, field. func [LalinTree.Func], supply [LalinSem.ClosureNameSupply], reason [str], },
  },
  product. ClosureItemInput {
    interned,
    module_name [str],
    supply [LalinSem.ClosureNameSupply],
    scopes [LalinSem.ClosureScopeStack],
    layouts [LalinSem.LayoutEnv],
    target [LalinHost.HostTargetModel],
  },
  sum. ClosureItemResult {
    ClosureItemConverted { variant_unique, items [many [LalinTree.Item]], supply [LalinSem.ClosureNameSupply], },
    ClosureItemUnchanged { variant_unique, item [LalinTree.Item], supply [LalinSem.ClosureNameSupply], },
    ClosureItemRejected { variant_unique, item [LalinTree.Item], supply [LalinSem.ClosureNameSupply], reason [str], },
  },
  product. ClosureModuleInput { interned, target [LalinHost.HostTargetModel], },
  product. ClosureModuleComposition {
    interned,
    items [many [LalinTree.Item]],
    supply [LalinSem.ClosureNameSupply],
    layouts [LalinSem.LayoutEnv],
    target [LalinHost.HostTargetModel],
  },
  sum. ClosureModuleComposeResult {
    ClosureModuleComposing { variant_unique, composition [LalinSem.ClosureModuleComposition], },
    ClosureModuleRejected { variant_unique, reason [str], },
  },
  sum. ClosureConvertResult {
    ClosureConverted { variant_unique, field. module [LalinTree.Module], },
    ClosureUnchanged { variant_unique, field. module [LalinTree.Module], },
    ClosureUnsupported { variant_unique, field. module [LalinTree.Module], reason [str], },
  },
  product. TreeModuleEntryInput { interned, mod_name [str], },
  product. TreeModuleLayoutInput {
    interned,
    mod_name [str],
    env [LalinSem.LayoutEnv],
    target [optional [LalinHost.HostTargetModel]],
  },
}