local S = require("lalin.schema.dsl")
S.use()

return schema. LalinStencil {
  product. StencilInstanceId { interned, text [str], },
  product. StencilSymbolId { interned, text [str], },
  product. StencilProviderId { interned, text [str], },
  sum. StencilProvider {
    StencilProviderC,
    StencilProviderLuaTrace,
    StencilProviderNamed {
      variant_unique,
      field. id [LalinStencil.StencilProviderId],
      field. name [str],
    },
  },
  sum. StencilSinkVocab { StencilStore, StencilReduce, StencilScan, StencilScatterReduce, },
  sum. StencilUnaryOp {
    StencilUnaryIdentity,
    StencilUnaryNeg,
    StencilUnaryBitNot,
    StencilUnaryBoolNot,
  },
  sum. StencilBinaryOp {
    StencilBinaryAdd,
    StencilBinarySub,
    StencilBinaryMul,
    StencilBinaryDiv,
    StencilBinaryMod,
    StencilBinaryAnd,
    StencilBinaryOr,
    StencilBinaryXor,
    StencilBinaryShl,
    StencilBinaryLShr,
    StencilBinaryAShr,
    StencilBinaryMin,
    StencilBinaryMax,
  },
  sum. StencilPredicate {
    StencilPredNonZero,
    StencilPredCompareConst {
      variant_unique,
      cmp [LalinCore.CmpOp],
      operand_ty [LalinCode.CodeType],
      field. value [LalinValue.ValueExpr],
    },
    StencilPredRange {
      variant_unique,
      operand_ty [LalinCode.CodeType],
      lower_cmp [LalinCore.CmpOp],
      lower [LalinValue.ValueExpr],
      upper_cmp [LalinCore.CmpOp],
      upper [LalinValue.ValueExpr],
    },
    StencilPredAnd { variant_unique, terms [many [LalinStencil.StencilPredicate]], },
    StencilPredOr { variant_unique, terms [many [LalinStencil.StencilPredicate]], },
    StencilPredNot { variant_unique, term [LalinStencil.StencilPredicate], },
    StencilPredIsNaN { variant_unique, operand_ty [LalinCode.CodeType], },
    StencilPredIsInf { variant_unique, operand_ty [LalinCode.CodeType], },
    StencilPredIsFinite { variant_unique, operand_ty [LalinCode.CodeType], },
  },
  sum. StencilScanMode { StencilScanInclusive, StencilScanExclusive, },
  sum. StencilCopySemantics {
    StencilCopyNoOverlap,
    StencilCopyMayOverlapForward,
    StencilCopyMayOverlapBackward,
    StencilCopyMemMove,
  },
  sum. StencilPartitionSemantics { StencilPartitionStable, StencilPartitionUnstable, },
  sum. StencilScatterConflictSemantics {
    StencilScatterUniqueIndices,
    StencilScatterLastWriteWins,
    StencilScatterConflictUndefined,
  },
  sum. StencilScatterReduceConflictSemantics {
    StencilScatterReduceSequential,
    StencilScatterReduceUniqueIndices,
    StencilScatterReduceAtomic { variant_unique, ordering [LalinCore.AtomicOrdering], },
    StencilScatterReducePrivatized,
  },
  sum. StencilProducerOrder { StencilProducerForward, StencilProducerBackward, },
  sum. StencilBound {
    StencilBoundDynamic,
    StencilBoundValue { variant_unique, field. value [LalinValue.ValueExpr], },
  },
  sum. StencilIndexName {
    StencilIndexAnonymous,
    StencilIndexNamed { variant_unique, field. name [str], },
  },
  sum. StencilProducerOrigin {
    StencilProducerOriginNone,
    StencilProducerOriginFlow { variant_unique, domain [LalinFlow.FlowDomain], },
  },
  sum. StencilScalarValue {
    StencilScalarValueNone,
    StencilScalarValueExpr { variant_unique, field. value [LalinValue.ValueExpr], },
  },
  sum. StencilOffsetValue {
    StencilOffsetZero,
    StencilOffsetExpr { variant_unique, field. value [LalinValue.ValueExpr], },
  },
  sum. StencilIndexSelection {
    StencilIndexProducer,
    StencilIndexExplicit { variant_unique, index [LalinStencil.StencilIndexExpr], },
  },
  sum. StencilArithmeticMode {
    StencilArithmeticInferred,
    StencilArithmeticInteger { variant_unique, semantics [LalinCode.CodeIntSemantics], },
    StencilArithmeticFloat { variant_unique, mode [LalinCode.CodeFloatMode], },
  },
  sum. StencilPointResult {
    StencilPointResultInferred,
    StencilPointResultTyped { variant_unique, field. ty [LalinCode.CodeType], arithmetic [LalinStencil.StencilArithmeticMode], },
  },
  sum. StencilProofEvidence {
    StencilProofUnproven,
    StencilProofProvided { variant_unique, proof [LalinKernel.KernelProof], },
  },
  sum. StencilReadonlyFact { StencilWritableAccess, StencilReadonlyAccess, },
  sum. StencilUnitStrideFact { StencilStrideNotUnit, StencilStrideUnit, },
  sum. StencilReassociationFact { StencilReassociationRejected, StencilReassociationProven, },
  sum. StencilAccessSite {
    StencilAccessSiteNone,
    StencilAccessSiteRef { variant_unique, access [LalinStencil.StencilAccessRef], },
  },
  sum. StencilScheduleRealization {
    StencilScheduleUnrealized,
    StencilScheduleRealized { variant_unique, schedule [LalinStencil.StencilRealizedSchedule], },
  },
  sum. StencilResultType {
    StencilResultVoid,
    StencilResultValue { variant_unique, field. ty [LalinCode.CodeType], },
  },
  sum. StencilArtifactStride {
    StencilArtifactNativeStride,
    StencilArtifactByteStride { variant_unique, bytes [number], },
  },
  sum. StencilScheduleCandidatePlan {
    StencilScheduleCandidateNoPlan,
    StencilScheduleCandidatePlanned { variant_unique, schedule [LalinStencil.StencilSchedule], },
  },
  sum. StencilFoldDestination {
    StencilFoldReturnsValue,
    StencilFoldStores { variant_unique, access [LalinStencil.StencilAccessRef], },
  },
  sum. StencilMetastencilNodeSelection {
    StencilMetastencilExternalNode,
    StencilMetastencilSelectedNode { variant_unique, node [LalinStencil.StencilMetastencilNodeId], },
  },
  product. StencilProducerAxis {
    interned,
    index_ty [LalinCode.CodeType],
    start [LalinStencil.StencilBound],
    stop [LalinStencil.StencilBound],
    step [number],
    order [LalinStencil.StencilProducerOrder],
    index_name [LalinStencil.StencilIndexName],
  },
  product. StencilAxisRef { interned, index [number], },
  sum. StencilWindowBoundary {
    StencilWindowBoundaryReject,
    StencilWindowBoundaryClamp,
    StencilWindowBoundaryWrap,
    StencilWindowBoundaryZero,
  },
  product. StencilWindowAxis {
    interned,
    before [number],
    after [number],
    boundary [LalinStencil.StencilWindowBoundary],
  },
  product. StencilWindowOffset {
    interned,
    axis [LalinStencil.StencilAxisRef],
    offset [number],
  },
  product. StencilAffineAxisTerm {
    interned,
    axis [LalinStencil.StencilAxisRef],
    coeff [LalinValue.ValueExpr],
  },
  sum. StencilProducerShape {
    StencilProduceRange1D {
      variant_unique,
      index_ty [LalinCode.CodeType],
      start [LalinStencil.StencilBound],
      stop [LalinStencil.StencilBound],
      step [number],
      order [LalinStencil.StencilProducerOrder],
    },
    StencilProduceCountedRange1D {
      variant_unique,
      index_ty [LalinCode.CodeType],
      start [LalinStencil.StencilBound],
      stop [LalinStencil.StencilBound],
      step [number],
      order [LalinStencil.StencilProducerOrder],
      stop_convention [LalinStencil.StencilIterationStopConvention],
      trip [LalinStencil.StencilKernelTripCount],
    },
    StencilProduceCountedWindow1D {
      variant_unique,
      index_ty [LalinCode.CodeType],
      start [LalinStencil.StencilBound],
      stop [LalinStencil.StencilBound],
      step [number],
      order [LalinStencil.StencilProducerOrder],
      stop_convention [LalinStencil.StencilIterationStopConvention],
      trip [LalinStencil.StencilKernelTripCount],
      window [LalinStencil.StencilWindowAxis],
    },
    StencilProduceRangeND { variant_unique, axes [many [LalinStencil.StencilProducerAxis]], },
    StencilProduceWindowND {
      variant_unique,
      axes [many [LalinStencil.StencilProducerAxis]],
      windows [many [LalinStencil.StencilWindowAxis]],
    },
    StencilProduceTiledND {
      variant_unique,
      axes [many [LalinStencil.StencilProducerAxis]],
      tile_sizes [many [number]],
    },
  },
  product. StencilProducer {
    interned,
    origin [LalinStencil.StencilProducerOrigin],
    shape [LalinStencil.StencilProducerShape],
  },
  sum. StencilProducerFactOrigin {
    StencilProducerCheckerDerived,
    StencilProducerAuthorAsserted { variant_unique, reason [str], },
    StencilProducerFrontendFact { variant_unique, reason [str], },
  },
  product. StencilProducerFact {
    interned,
    domain [LalinFlow.FlowDomain],
    producer [LalinStencil.StencilProducer],
    proofs [many [LalinKernel.KernelProof]],
    origin [LalinStencil.StencilProducerFactOrigin],
  },
  product. StencilProducerFactSet {
    interned,
    field. module [LalinCode.CodeModuleId],
    facts [many [LalinStencil.StencilProducerFact]],
  },
  sum. StencilAccessRole {
    StencilAccessRead,
    StencilAccessWrite,
    StencilAccessIndex,
    StencilAccessReadWrite,
    StencilAccessReduce,
    StencilAccessControlResult,
  },

  -- C-neutral access layout: direct and descriptor-backed states are distinct.
  sum. StencilAccessLayoutBase {
    StencilLayoutScalar { variant_unique, field. value [LalinStencil.StencilScalarValue], },
    StencilLayoutContiguous { variant_unique, stride [number], },
    StencilLayoutIndexed {
      variant_unique,
      parent [LalinStencil.StencilAccessLayoutBase],
      index [LalinStencil.StencilAccessRef],
      index_ty [LalinCode.CodeType],
      stride [number],
    },
    StencilLayoutAffine1D {
      variant_unique,
      parent [LalinStencil.StencilAccessLayoutBase],
      scale [number],
      offset [LalinStencil.StencilOffsetValue],
    },
    StencilLayoutAffineND {
      variant_unique,
      parent [LalinStencil.StencilAccessLayoutBase],
      terms [many [LalinStencil.StencilAffineAxisTerm]],
      offset [LalinStencil.StencilOffsetValue],
    },
    StencilLayoutFieldProjection {
      variant_unique,
      parent [LalinStencil.StencilAccessLayoutBase],
      record_ty [LalinCode.CodeType],
      field_name [str],
      field_offset [number],
    },
    StencilLayoutSoAComponent {
      variant_unique,
      parent [LalinStencil.StencilAccessLayoutBase],
      record_ty [LalinCode.CodeType],
      field_name [str],
      component_index [number],
    },
  },

  sum. StencilStrideFact {
    StencilStrideDynamic,
    StencilStrideKnown { variant_unique, bytes [number], },
  },

  sum. StencilAccessDescriptor {
    StencilLayoutSliceDescriptor {
      variant_unique,
      slice [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    StencilLayoutByteSpanDescriptor {
      variant_unique,
      span [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
    StencilLayoutViewDescriptor {
      variant_unique,
      view [LalinCode.CodeValueId],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
      stride [LalinCode.CodeValueId],
      stride_fact [LalinStencil.StencilStrideFact],
    },
    StencilLayoutForeignBuffer {
      variant_unique,
      buffer_name [str],
      data [LalinCode.CodeValueId],
      len [LalinCode.CodeValueId],
    },
  },

  sum. StencilAccessLayout {
    StencilAccessDirect { variant_unique, base [LalinStencil.StencilAccessLayoutBase], },
    StencilAccessDescribed {
      variant_unique,
      base [LalinStencil.StencilAccessLayoutBase],
      descriptor [LalinStencil.StencilAccessDescriptor],
    },
  },

  product. StencilAccess {
    interned,
    field. name [str],
    role [LalinStencil.StencilAccessRole],
    ty [LalinCode.CodeType],
    layout [LalinStencil.StencilAccessLayout],
  },
  product. StencilAccessRef { interned, field. name [str], },
  product. StencilStreamId { interned, text [str], },
  product. StencilStreamRef { interned, stream [LalinStencil.StencilStreamId], },
  product. StencilSinkId { interned, text [str], },
  product. StencilSinkRef { interned, sink [LalinStencil.StencilSinkId], },
  sum. StencilIndexExpr {
    StencilIndexAxis { variant_unique, axis [LalinStencil.StencilAxisRef], },
    StencilIndexStream { variant_unique, stream [LalinStencil.StencilStreamRef], },
    StencilIndexPoint { variant_unique, field. expr [LalinValue.ValueExpr], },
  },
  product. StencilStreamParam {
    interned,
    field. name [str],
    stream [LalinStencil.StencilStreamRef],
  },
  sum. StencilStreamOp {
    StencilStreamIndex { variant_unique, axis [LalinStencil.StencilAxisRef], },
    StencilStreamAccess {
      variant_unique,
      access [LalinStencil.StencilAccessRef],
      index [LalinStencil.StencilIndexSelection],
    },
    StencilStreamWindowAccess {
      variant_unique,
      access [LalinStencil.StencilAccessRef],
      offsets [many [LalinStencil.StencilWindowOffset]],
    },
    StencilStreamConst {
      variant_unique,
      field. value [LalinValue.ValueExpr],
      ty [LalinCode.CodeType],
    },
    StencilStreamValueExpr {
      variant_unique,
      field. value [LalinValue.ValueExpr],
      ty [LalinCode.CodeType],
    },
    StencilStreamAlias { variant_unique, source [LalinStencil.StencilStreamRef], },
    StencilStreamMap {
      variant_unique,
      field. expr [LalinStencil.StencilPointExpr],
      inputs [many [LalinStencil.StencilStreamParam]],
    },
    StencilStreamZip { variant_unique, inputs [many [LalinStencil.StencilStreamRef]], },
    StencilStreamSelect {
      variant_unique,
      pred [LalinStencil.StencilStreamRef],
      then_stream [LalinStencil.StencilStreamRef],
      else_stream [LalinStencil.StencilStreamRef],
    },
    StencilStreamMask {
      variant_unique,
      pred [LalinStencil.StencilStreamRef],
      field. value [LalinStencil.StencilStreamRef],
      masked_value [LalinStencil.StencilStreamRef],
    },
    StencilStreamGather {
      variant_unique,
      source [LalinStencil.StencilAccessRef],
      index_stream [LalinStencil.StencilStreamRef],
    },
  },
  product. StencilStreamDef {
    interned,
    field. id [LalinStencil.StencilStreamId],
    field. ty [LalinCode.CodeType],
    op [LalinStencil.StencilStreamOp],
  },
  sum. StencilPointExpr {
    StencilPointInput { variant_unique, access [LalinStencil.StencilAccessRef], },
    StencilPointWindowInput {
      variant_unique,
      access [LalinStencil.StencilAccessRef],
      offsets [many [LalinStencil.StencilWindowOffset]],
    },
    StencilPointConst {
      variant_unique,
      field. value [LalinValue.ValueExpr],
      ty [LalinCode.CodeType],
    },
    StencilPointUnary {
      variant_unique,
      op [LalinStencil.StencilUnaryOp],
      field. arg [LalinStencil.StencilPointExpr],
      result [LalinStencil.StencilPointResult],
    },
    StencilPointBinary {
      variant_unique,
      op [LalinStencil.StencilBinaryOp],
      left [LalinStencil.StencilPointExpr],
      right [LalinStencil.StencilPointExpr],
      result [LalinStencil.StencilPointResult],
    },
    StencilPointCast {
      variant_unique,
      op [LalinCore.MachineCastOp],
      field. arg [LalinStencil.StencilPointExpr],
      from [LalinCode.CodeType],
      to [LalinCode.CodeType],
    },
    StencilPointPredicate {
      variant_unique,
      pred [LalinStencil.StencilPredicate],
      field. arg [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
    },
    StencilPointCompare {
      variant_unique,
      cmp [LalinCore.CmpOp],
      left [LalinStencil.StencilPointExpr],
      right [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
    },
    StencilPointSelect {
      variant_unique,
      pred [LalinStencil.StencilPredicate],
      cond [LalinStencil.StencilPointExpr],
      then_expr [LalinStencil.StencilPointExpr],
      else_expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
    },
  },
  product. StencilReducer {
    interned,
    reduction [LalinValue.ReductionOp],
    result_ty [LalinCode.CodeType],
    field. identity [LalinValue.ValueExpr],
    arithmetic [LalinStencil.StencilArithmeticMode],
  },
  sum. StencilStoreSemantics {
    StencilStoreElementwise,
    StencilStoreCopy { variant_unique, semantics [LalinStencil.StencilCopySemantics], },
    StencilStoreScatter {
      variant_unique,
      conflicts [LalinStencil.StencilScatterConflictSemantics],
    },
    StencilStorePartition { variant_unique, semantics [LalinStencil.StencilPartitionSemantics], },
  },
  sum. StencilReductionSemantics {
    StencilReduceFold { variant_unique, reducer [LalinStencil.StencilReducer], },
    StencilReduceCount { variant_unique, pred [LalinStencil.StencilPredicate], },
    StencilReduceFind {
      variant_unique,
      pred [LalinStencil.StencilPredicate],
      not_found [LalinValue.ValueExpr],
    },
  },
  sum. StencilReduceScope {
    StencilReduceScopeDomain,
    StencilReduceScopeAxes {
      variant_unique,
      axes [many [LalinStencil.StencilAxisRef]],
      dst [LalinStencil.StencilAccessRef],
    },
    StencilReduceScopeWindow {
      variant_unique,
      axes [many [LalinStencil.StencilAxisRef]],
      dst [LalinStencil.StencilAccessRef],
    },
  },
  sum. StencilCompiler { StencilCompilerGcc, StencilCompilerClang, StencilCompilerSystemC, },
  sum. StencilOptLevel {
    StencilOptO0,
    StencilOptO1,
    StencilOptO2,
    StencilOptO3,
    StencilOptOs,
    StencilOptOz,
  },
  sum. StencilMachineTarget {
    StencilMachineNative,
    StencilMachineBaseline,
    StencilMachineNamed { variant_unique, field. name [str], },
  },
  product. StencilCompilerPolicy {
    interned,
    compiler [LalinStencil.StencilCompiler],
    opt_level [LalinStencil.StencilOptLevel],
    machine [LalinStencil.StencilMachineTarget],
    flags [many [str]],
  },
  sum. StencilAliasFact { StencilAliasUnknown, StencilAliasNoAlias, StencilAliasMayAlias, },
  sum. StencilAlignmentFact {
    StencilAlignmentUnknown,
    StencilAlignmentKnown { variant_unique, bytes [number], },
  },
  sum. StencilTripCountFact {
    StencilTripCountUnknown,
    StencilTripCountDynamic,
    StencilTripCountMultipleOf { variant_unique, factor [number], },
    StencilTripCountExact { variant_unique, count [number], },
  },
  sum. StencilProofOrigin {
    StencilProofCheckerDerived,
    StencilProofBoundaryContract,
    StencilProofAuthorAsserted,
  },
  sum. StencilProofRequirement {
    StencilProofNoAlias {
      variant_unique,
      left [LalinStencil.StencilAccessRef],
      right [LalinStencil.StencilAccessRef],
    },
    StencilProofAlignment {
      variant_unique,
      access [LalinStencil.StencilAccessRef],
      alignment [LalinStencil.StencilAlignmentFact],
    },
    StencilProofTripCount { variant_unique, trip_count [LalinStencil.StencilTripCountFact], },
    StencilProofReductionReassociable,
    StencilProofUnitStride { variant_unique, access [LalinStencil.StencilAccessRef], },
  },
  product. StencilProofObligation {
    interned,
    requirement [LalinStencil.StencilProofRequirement],
    origin [LalinStencil.StencilProofOrigin],
    evidence [LalinStencil.StencilProofEvidence],
  },
  product. StencilAccessVectorFact {
    interned,
    access [LalinStencil.StencilAccessRef],
    alignment [LalinStencil.StencilAlignmentFact],
    readonly [LalinStencil.StencilReadonlyFact],
    unit_stride [LalinStencil.StencilUnitStrideFact],
  },
  product. StencilAccessAliasFact {
    interned,
    left [LalinStencil.StencilAccessRef],
    right [LalinStencil.StencilAccessRef],
    relation [LalinStencil.StencilAliasFact],
  },
  product. StencilArithmeticVectorFact {
    interned,
    reassociation [LalinStencil.StencilReassociationFact],
    arithmetic [LalinStencil.StencilArithmeticMode],
  },

  -- StencilVectorizationFacts decomposed into 4 facet products
  product. StencilAccessFacts {
    interned,
    facts [many [LalinStencil.StencilAccessVectorFact]],
  },
  product. StencilAliasFacts {
    interned,
    facts [many [LalinStencil.StencilAccessAliasFact]],
  },
  product. StencilArithmeticFacts {
    interned,
    reassociation [LalinStencil.StencilReassociationFact],
    arithmetic [LalinStencil.StencilArithmeticMode],
  },
  product. StencilTripCountFactSet {
    interned,
    trip_count [LalinStencil.StencilTripCountFact],
  },

  sum. StencilVectorFeatureRequirement {
    StencilVectorFeatureNative,
    StencilVectorFeatureSSE2,
    StencilVectorFeatureAVX2,
    StencilVectorFeatureAVX512F,
    StencilVectorFeatureNamed { variant_unique, field. name [str], },
  },
  sum. StencilLanePolicy {
    StencilLaneFromTarget,
    StencilLaneNative,
    StencilLaneFixed { variant_unique, lanes [number], },
  },
  sum. StencilVectorAlignmentPolicy {
    StencilVectorAlignmentUnknown,
    StencilVectorUnaligned,
    StencilVectorAligned { variant_unique, bytes [number], },
  },
  sum. StencilVectorTailPolicy {
    StencilVectorScalarTail,
    StencilVectorMaskTail,
    StencilVectorOverreadProvenSafe,
  },
  sum. StencilVectorReductionStrategy {
    StencilVectorReductionTree,
    StencilVectorReductionHorizontal,
    StencilVectorReductionScalarFinish,
  },
  sum. StencilVectorCompilerPolicy {
    StencilVectorCompilerGccAutovec,
    StencilVectorCompilerHandwritten,
    StencilVectorCompilerCompiledStencil,
  },
  sum. StencilMaterializer {
    StencilMaterializerResidualBC,
    StencilMaterializerResidualMC,
    StencilMaterializerNamed { variant_unique, field. name [str], },
  },
  sum. StencilRealizedScheduleEvidence {
    StencilRealizedByConstruction { variant_unique, reason [str], },
    StencilRealizedCompilerRemark { variant_unique, remark [str], },
    StencilRealizedDisassembly { variant_unique, classification [str], },
  },
  sum. StencilRealizedSchedule {
    StencilRealizedScalar {
      variant_unique,
      materializer [LalinStencil.StencilMaterializer],
      evidence [many [LalinStencil.StencilRealizedScheduleEvidence]],
    },
    StencilRealizedUnrolled {
      variant_unique,
      factor [number],
      materializer [LalinStencil.StencilMaterializer],
      evidence [many [LalinStencil.StencilRealizedScheduleEvidence]],
    },
    StencilRealizedVector {
      variant_unique,
      feature [LalinStencil.StencilVectorFeatureRequirement],
      lanes [number],
      unroll [number],
      interleave [number],
      tail [LalinStencil.StencilVectorTailPolicy],
      materializer [LalinStencil.StencilMaterializer],
      evidence [many [LalinStencil.StencilRealizedScheduleEvidence]],
    },
  },
  sum. StencilScheduleReject {
    StencilScheduleRejectUnsupportedFeature {
      variant_unique,
      feature [LalinStencil.StencilVectorFeatureRequirement],
      compiler [LalinStencil.StencilCompilerPolicy],
      reason [str],
    },
    StencilScheduleRejectIllegalLaneCount { variant_unique, lanes [number], reason [str], },
    StencilScheduleRejectUnprovableTail {
      variant_unique,
      tail [LalinStencil.StencilVectorTailPolicy],
      reason [str],
    },
    StencilScheduleRejectUnprovableAlignment {
      variant_unique,
      site [LalinStencil.StencilAccessSite],
      alignment [LalinStencil.StencilVectorAlignmentPolicy],
      reason [str],
    },
    StencilScheduleRejectCompilerMatrix {
      variant_unique,
      compiler [LalinStencil.StencilCompilerPolicy],
      vector_compiler [LalinStencil.StencilVectorCompilerPolicy],
      reason [str],
    },
    StencilScheduleRejectRequestedRealizedMismatch {
      variant_unique,
      requested [LalinStencil.StencilSchedule],
      realized [LalinStencil.StencilScheduleRealization],
      mismatch [LalinStencil.StencilScheduleMismatch],
    },
  },
  sum. StencilScheduleMismatch {
    StencilScheduleMismatchUnrollFactor { requested [number], realized [number] },
    StencilScheduleMismatchLaneCount { requested [number], realized [number] },
    StencilScheduleMismatchFeature { requested [LalinStencil.StencilVectorFeatureRequirement], realized [LalinStencil.StencilVectorFeatureRequirement] },
    StencilScheduleMismatchNoRealization,
    StencilScheduleMismatchUnquantified { reason [str] },
  },
  sum. StencilSchedule {
    StencilScheduleScalar { variant_unique, compiler [LalinStencil.StencilCompilerPolicy], },
    StencilScheduleAutoVector {
      variant_unique,
      compiler [LalinStencil.StencilCompilerPolicy],
      facts [LalinStencil.StencilAccessFacts],
    },
    StencilScheduleUnrolled {
      variant_unique,
      factor [number],
      compiler [LalinStencil.StencilCompilerPolicy],
      facts [LalinStencil.StencilAccessFacts],
    },
    StencilScheduleVector {
      variant_unique,
      feature [LalinStencil.StencilVectorFeatureRequirement],
      lane_policy [LalinStencil.StencilLanePolicy],
      required_alignment [LalinStencil.StencilVectorAlignmentPolicy],
      tail [LalinStencil.StencilVectorTailPolicy],
      reduction [LalinStencil.StencilVectorReductionStrategy],
      vector_compiler [LalinStencil.StencilVectorCompilerPolicy],
      vector_unroll [number],
      interleave [number],
      compiler [LalinStencil.StencilCompilerPolicy],
      facts [LalinStencil.StencilAccessFacts],
    },
  },
  sum. StencilBody {
    StencilBodyPoint {
      variant_unique,
      field. expr [LalinStencil.StencilPointExpr],
    },
  },
  sum. StencilSink {
    StencilSinkStore {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      semantics [LalinStencil.StencilStoreSemantics],
    },
    StencilSinkReduce {
      variant_unique,
      result_ty [LalinCode.CodeType],
      scope [LalinStencil.StencilReduceScope],
      semantics [LalinStencil.StencilReductionSemantics],
    },
    StencilSinkScan {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      axis [LalinStencil.StencilAxisRef],
      reducer [LalinStencil.StencilReducer],
      mode [LalinStencil.StencilScanMode],
      result_ty [LalinCode.CodeType],
    },
    StencilSinkScatterReduce {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      reducer [LalinStencil.StencilReducer],
      conflicts [LalinStencil.StencilScatterReduceConflictSemantics],
      result_ty [LalinCode.CodeType],
    },
  },
  product. StencilDescriptor {
    interned,
    producer [LalinStencil.StencilProducer],
    accesses [many [LalinStencil.StencilAccess]],
    body [LalinStencil.StencilBody],
    sink [LalinStencil.StencilSink],
  },
  sum. StencilSinkOp {
    StencilSinkOpStore {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      field. value [LalinStencil.StencilStreamRef],
      semantics [LalinStencil.StencilStoreSemantics],
    },
    StencilSinkOpFold {
      variant_unique,
      field. value [LalinStencil.StencilStreamRef],
      reducer [LalinStencil.StencilReducer],
      result_ty [LalinCode.CodeType],
      init [LalinStencil.StencilReduceInitMode],
      destination [LalinStencil.StencilFoldDestination],
    },
    StencilSinkOpScan {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      field. value [LalinStencil.StencilStreamRef],
      reducer [LalinStencil.StencilReducer],
      mode [LalinStencil.StencilScanMode],
      axis [LalinStencil.StencilAxisRef],
    },
    StencilSinkOpScatterStore {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      index [LalinStencil.StencilStreamRef],
      field. value [LalinStencil.StencilStreamRef],
      conflicts [LalinStencil.StencilScatterConflictSemantics],
    },
    StencilSinkOpScatterFold {
      variant_unique,
      dst [LalinStencil.StencilAccessRef],
      index [LalinStencil.StencilStreamRef],
      field. value [LalinStencil.StencilStreamRef],
      reducer [LalinStencil.StencilReducer],
      conflicts [LalinStencil.StencilScatterReduceConflictSemantics],
    },
    StencilSinkOpAll {
      variant_unique,
      src [LalinStencil.StencilStreamRef],
      pred [LalinStencil.StencilPredicate],
    },
    StencilSinkOpAny {
      variant_unique,
      src [LalinStencil.StencilStreamRef],
      pred [LalinStencil.StencilPredicate],
    },
    StencilSinkOpFind {
      variant_unique,
      src [LalinStencil.StencilStreamRef],
      pred [LalinStencil.StencilPredicate],
      not_found [LalinValue.ValueExpr],
    },
    StencilSinkOpAllCompare {
      variant_unique,
      left [LalinStencil.StencilStreamRef],
      right [LalinStencil.StencilStreamRef],
      cmp [LalinCore.CmpOp],
    },
  },
  product. StencilSinkDef {
    interned,
    field. id [LalinStencil.StencilSinkId],
    op [LalinStencil.StencilSinkOp],
  },
  sum. StencilNodeOp {
    StencilNodeStream { variant_unique, stream [LalinStencil.StencilStreamDef], },
    StencilNodeSink { variant_unique, sink [LalinStencil.StencilSinkDef], },
    StencilNodeBarrier { variant_unique, barrier [LalinStencil.StencilBarrier], },
  },
  sum. StencilBarrier {
    StencilBarrierScanDependency,
    StencilBarrierScatterDependency,
    StencilBarrierPermutation,
  },
  product. StencilNode {
    interned,
    field. id [LalinStencil.StencilMetastencilNodeId],
    op [LalinStencil.StencilNodeOp],
  },
  product. StencilComputation {
    interned,
    field. id [LalinStencil.StencilMetastencilId],
    producer [LalinStencil.StencilProducer],
    accesses [many [LalinStencil.StencilAccess]],
    streams [many [LalinStencil.StencilStreamDef]],
    sinks [many [LalinStencil.StencilSinkDef]],
    legality [LalinStencil.StencilFusionLegality],
    schedule [LalinStencil.StencilSchedule],
    proofs [many [LalinKernel.KernelProof]],
  },
  product. StencilAbi {
    interned,
    params [many [LalinCode.CodeType]],
    result [LalinStencil.StencilResultType],
  },
  product. StencilInstance {
    interned,
    field. id [LalinStencil.StencilInstanceId],
    descriptor [LalinStencil.StencilDescriptor],
    schedule [LalinStencil.StencilSchedule],
    abi [LalinStencil.StencilAbi],
    proofs [many [LalinKernel.KernelProof]],
  },
  sum. StencilReject {
    StencilRejectUnsupportedVocab {
      variant_unique,
      vocab [LalinStencil.StencilSinkVocab],
      reason [str],
    },
    StencilRejectUnsupportedType { variant_unique, ty [LalinCode.CodeType], reason [str], },
    StencilRejectUnsupportedReduction {
      variant_unique,
      reduction [LalinValue.ReductionOp],
      reason [str],
    },
    StencilRejectUnsupportedProducer {
      variant_unique,
      producer [LalinStencil.StencilProducer],
      reason [str],
    },
    StencilRejectUnsupportedSink {
      variant_unique,
      sink [LalinStencil.StencilSink],
      reason [str],
    },
    StencilRejectMissingProof {
      variant_unique,
      requirement [LalinStencil.StencilProofRequirement],
    },
    StencilRejectProvider { variant_unique, provider [LalinStencil.StencilProvider], reason [str], },
    StencilRejectSchedule { variant_unique, reject [LalinStencil.StencilScheduleReject], },
  },
  sum. StencilScheduleCandidateStatus {
    StencilScheduleCandidateSelected,
    StencilScheduleCandidateViable,
    StencilScheduleCandidateRejected,
  },
  sum. StencilScheduleSelectionOrigin {
    StencilScheduleSelectionHeuristic,
    StencilScheduleSelectionCostModel,
    StencilScheduleSelectionAuthorAnnotated,
    StencilScheduleSelectionFallback,
  },
  product. StencilScheduleCandidate {
    interned,
    field. name [str],
    plan [LalinStencil.StencilScheduleCandidatePlan],
    cost [number],
    status [LalinStencil.StencilScheduleCandidateStatus],
    rejects [many [LalinStencil.StencilScheduleReject]],
    reason [str],
  },
  product. StencilScheduleSelectionProvenance {
    interned,
    origin [LalinStencil.StencilScheduleSelectionOrigin],
    winner [str],
    candidates [many [LalinStencil.StencilScheduleCandidate]],
    reason [str],
  },
  sum. StencilSelection {
    StencilSelected {
      variant_unique,
      instance [LalinStencil.StencilInstance],
      provenance [LalinStencil.StencilScheduleSelectionProvenance],
    },
    StencilNoSelection {
      variant_unique,
      vocab [LalinStencil.StencilSinkVocab],
      rejects [many [LalinStencil.StencilReject]],
      provenance [LalinStencil.StencilScheduleSelectionProvenance],
    },
  },
  product. StencilPlanEntry {
    interned,
    kernel [LalinKernel.KernelId],
    selection [LalinStencil.StencilSelection],
  },
  product. StencilArtifactFingerprint { interned, text [str], },
  sum. StencilArtifactDiagnosticSeverity {
    StencilArtifactDiagnosticNote,
    StencilArtifactDiagnosticWarning,
    StencilArtifactDiagnosticRemark,
  },
  product. StencilArtifactDiagnostic {
    interned,
    severity [LalinStencil.StencilArtifactDiagnosticSeverity],
    source [str],
    message [str],
  },
  product. StencilArtifact {
    interned,
    instance [LalinStencil.StencilInstance],
    provider [LalinStencil.StencilProvider],
    symbol [LalinStencil.StencilSymbolId],
    c_signature [str],
    fingerprint [LalinStencil.StencilArtifactFingerprint],
    realization [LalinStencil.StencilScheduleRealization],
    diagnostics [many [LalinStencil.StencilArtifactDiagnostic]],
    schedule_rejects [many [LalinStencil.StencilScheduleReject]],
  },
  product. StencilProducerExecutionAxis {
    interned,
    index_ty [LalinCode.CodeType],
    step [number],
    start_param [str],
    stop_param [str],
  },
  sum. StencilProducerExecution {
    StencilProducerExecRange1D {
      variant_unique,
      stride [number],
      order [LalinStencil.StencilProducerOrder],
    },
    StencilProducerExecRangeND {
      variant_unique,
      rank [number],
      axes [many [LalinStencil.StencilProducerExecutionAxis]],
    },
    StencilProducerExecWindowND {
      variant_unique,
      rank [number],
      axes [many [LalinStencil.StencilProducerExecutionAxis]],
      windows [many [LalinStencil.StencilWindowAxis]],
    },
    StencilProducerExecTiledND {
      variant_unique,
      rank [number],
      axes [many [LalinStencil.StencilProducerExecutionAxis]],
      tile_sizes [many [number]],
    },
  },
  sum. StencilReduceExecutionScope {
    StencilReduceExecDomain,
    StencilReduceExecAxes {
      variant_unique,
      dst_name [str],
      axes [many [LalinStencil.StencilAxisRef]],
    },
    StencilReduceExecWindow {
      variant_unique,
      dst_name [str],
      axes [many [LalinStencil.StencilAxisRef]],
    },
  },
  sum. StencilReduceInitMode {
    StencilReduceInitExternal,
    StencilReduceInitIdentity,
  },
  sum. StencilArtifactShape {
    StencilArtifactStoreN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      result_ty [LalinCode.CodeType],
      dst_name [str],
      store_mode [LalinStencil.StencilStoreSemantics],
      field. expr [LalinStencil.StencilPointExpr],
      producer [LalinStencil.StencilProducerExecution],
      stride [LalinStencil.StencilArtifactStride],
    },
    StencilArtifactReduceN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      item_ty [LalinCode.CodeType],
      result_ty [LalinCode.CodeType],
      reduction [LalinValue.ReductionOp],
      arithmetic [LalinStencil.StencilArithmeticMode],
      field. identity [LalinValue.ValueExpr],
      scope [LalinStencil.StencilReduceScope],
      reduce_scope [LalinStencil.StencilReduceExecutionScope],
      init_mode [LalinStencil.StencilReduceInitMode],
      producer [LalinStencil.StencilProducerExecution],
      stride [LalinStencil.StencilArtifactStride],
    },
    StencilArtifactFindN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
      pred [LalinStencil.StencilPredicate],
      not_found [LalinValue.ValueExpr],
      producer [LalinStencil.StencilProducerExecution],
      stride [LalinStencil.StencilArtifactStride],
    },
    StencilArtifactPartitionN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
      dst_name [str],
      mode [LalinStencil.StencilPartitionSemantics],
      producer [LalinStencil.StencilProducerExecution],
      stride [LalinStencil.StencilArtifactStride],
    },
    StencilArtifactScanN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
      reduction [LalinValue.ReductionOp],
      arithmetic [LalinStencil.StencilArithmeticMode],
      field. identity [LalinValue.ValueExpr],
      mode [LalinStencil.StencilScanMode],
      axis [LalinStencil.StencilAxisRef],
      producer [LalinStencil.StencilProducerExecution],
      stride [LalinStencil.StencilArtifactStride],
    },
    StencilArtifactScatterReduceN {
      variant_unique,
      inputs [many [LalinStencil.StencilAccess]],
      field. expr [LalinStencil.StencilPointExpr],
      result_ty [LalinCode.CodeType],
      reduction [LalinValue.ReductionOp],
      arithmetic [LalinStencil.StencilArithmeticMode],
      field. identity [LalinValue.ValueExpr],
      dst_name [str],
      conflicts [LalinStencil.StencilScatterReduceConflictSemantics],
      producer [LalinStencil.StencilProducerExecution],
      stride [LalinStencil.StencilArtifactStride],
    },
  },
  product. StencilMetastencilId { interned, text [str], },
  product. StencilMetastencilNodeId { interned, text [str], },
  product. StencilMetastencilWireId { interned, text [str], },
  sum. StencilMetastencilPortFlow {
    StencilMetastencilPortInput,
    StencilMetastencilPortOutput,
    StencilMetastencilPortInOut,
  },
  product. StencilMetastencilPortRef {
    interned,
    node [LalinStencil.StencilMetastencilNodeSelection],
    field. name [str],
  },
  product. StencilMetastencilPort {
    interned,
    field. ref [LalinStencil.StencilMetastencilPortRef],
    flow [LalinStencil.StencilMetastencilPortFlow],
    ty [LalinCode.CodeType],
    access [LalinStencil.StencilAccessSite],
  },
  product. StencilMetastencilNode {
    interned,
    field. id [LalinStencil.StencilMetastencilNodeId],
    artifact [LalinStencil.StencilArtifact],
    inputs [many [LalinStencil.StencilMetastencilPort]],
    outputs [many [LalinStencil.StencilMetastencilPort]],
  },
  product. StencilMetastencilWire {
    interned,
    field. id [LalinStencil.StencilMetastencilWireId],
    src [LalinStencil.StencilMetastencilPortRef],
    dst [LalinStencil.StencilMetastencilPortRef],
    ty [LalinCode.CodeType],
  },
  sum. StencilFusionLegalityFact {
    StencilFusionSameProducer {
      variant_unique,
      left [LalinStencil.StencilMetastencilNodeId],
      right [LalinStencil.StencilMetastencilNodeId],
    },
    StencilFusionCompatibleAbi {
      variant_unique,
      wire [LalinStencil.StencilMetastencilWireId],
      ty [LalinCode.CodeType],
    },
    StencilFusionNoIntermediateMaterialization { variant_unique, wire [LalinStencil.StencilMetastencilWireId], },
    StencilFusionAliasRelation {
      variant_unique,
      left [LalinStencil.StencilMetastencilPortRef],
      right [LalinStencil.StencilMetastencilPortRef],
      relation [LalinStencil.StencilAliasFact],
    },
    StencilFusionAccessAliasRelation {
      variant_unique,
      left [LalinStencil.StencilAccessRef],
      right [LalinStencil.StencilAccessRef],
      relation [LalinStencil.StencilAliasFact],
    },
    StencilFusionProofObligation { variant_unique, obligation [LalinStencil.StencilProofObligation], },
  },
  sum. StencilFusionReject {
    StencilFusionRejectTypeMismatch {
      variant_unique,
      wire [LalinStencil.StencilMetastencilWireId],
      src_ty [LalinCode.CodeType],
      dst_ty [LalinCode.CodeType],
    },
    StencilFusionRejectMissingPort {
      variant_unique,
      port [LalinStencil.StencilMetastencilPortRef],
    },
    StencilFusionRejectCycle {
      variant_unique,
      wire [LalinStencil.StencilMetastencilWireId],
      reason [str],
    },
    StencilFusionRejectAliasConflict {
      variant_unique,
      left [LalinStencil.StencilMetastencilPortRef],
      right [LalinStencil.StencilMetastencilPortRef],
      relation [LalinStencil.StencilAliasFact],
      reason [str],
    },
    StencilFusionRejectMissingProof {
      variant_unique,
      requirement [LalinStencil.StencilProofRequirement],
    },
    StencilFusionRejectUnsupportedComposition {
      variant_unique,
      left [LalinStencil.StencilMetastencilNodeSelection],
      right [LalinStencil.StencilMetastencilNodeSelection],
      reason [str],
    },
  },
  product. StencilFusionLegality {
    interned,
    facts [many [LalinStencil.StencilFusionLegalityFact]],
    proof_obligations [many [LalinStencil.StencilProofObligation]],
    rejects [many [LalinStencil.StencilFusionReject]],
  },
  product. StencilMetastencilFingerprint { interned, text [str], },
  product. StencilMetastencilDescriptor {
    interned,
    field. id [LalinStencil.StencilMetastencilId],
    external_ports [many [LalinStencil.StencilMetastencilPort]],
    nodes [many [LalinStencil.StencilMetastencilNode]],
    wires [many [LalinStencil.StencilMetastencilWire]],
    abi [LalinStencil.StencilAbi],
    legality [LalinStencil.StencilFusionLegality],
  },
  sum. StencilMetastencilCandidateStatus {
    StencilMetastencilCandidateSelected,
    StencilMetastencilCandidateViable,
    StencilMetastencilCandidateRejected,
  },
  product. StencilMetastencilCandidate {
    interned,
    descriptor [LalinStencil.StencilMetastencilDescriptor],
    fingerprint [LalinStencil.StencilMetastencilFingerprint],
    covered_nodes [number],
    cost [number],
    status [LalinStencil.StencilMetastencilCandidateStatus],
    rejects [many [LalinStencil.StencilFusionReject]],
    reason [str],
  },
  product. StencilMetastencilCoverProvenance {
    interned,
    origin [LalinStencil.StencilScheduleSelectionOrigin],
    winner [str],
    candidates [many [LalinStencil.StencilMetastencilCandidate]],
    reason [str],
  },
  sum. StencilMetastencilCoverSelection {
    StencilMetastencilCoverSelected {
      variant_unique,
      candidate [LalinStencil.StencilMetastencilCandidate],
      provenance [LalinStencil.StencilMetastencilCoverProvenance],
    },
    StencilMetastencilNoCover {
      variant_unique,
      rejects [many [LalinStencil.StencilFusionReject]],
      provenance [LalinStencil.StencilMetastencilCoverProvenance],
    },
  },
  product. StencilModulePlan {
    interned,
    field. module [LalinCode.CodeModuleId],
    kernel [LalinKernel.KernelModulePlan],
    selections [many [LalinStencil.StencilPlanEntry]],
  },
  product. StencilProducerAnalysisInput {
    interned,
    producer [LalinStencil.StencilProducer],
  },
  sum. StencilProducerAnalysis {
    StencilProducerAnalysisRange1D { variant_unique, execution [LalinStencil.StencilProducerExecution], },
    StencilProducerAnalysisRangeND { variant_unique, execution [LalinStencil.StencilProducerExecution], },
    StencilProducerAnalysisWindowND { variant_unique, execution [LalinStencil.StencilProducerExecution], },
    StencilProducerAnalysisTiledND { variant_unique, execution [LalinStencil.StencilProducerExecution], },
    StencilProducerAnalysisRejected { variant_unique, producer [LalinStencil.StencilProducer], reason [str], },
  },

  product. StencilAccessValidationInput { interned, access [LalinStencil.StencilAccess], },
  sum. StencilValidationReject {
    StencilValidationInvalidStride { variant_unique, access [LalinStencil.StencilAccessRef], stride [number], },
    StencilValidationUnsupportedProducer { variant_unique, producer [LalinStencil.StencilProducer], reason [str], },
    StencilValidationUnsupportedSink { variant_unique, sink [LalinStencil.StencilSink], reason [str], },
  },
  sum. StencilValidationContribution {
    StencilValidationAccepted,
    StencilValidationRejected { variant_unique, reject [LalinStencil.StencilValidationReject], },
  },
  product. StencilDescriptorValidationInput { interned, provider [LalinStencil.StencilProvider], },
  sum. StencilDescriptorValidation {
    StencilDescriptorValid { variant_unique, descriptor [LalinStencil.StencilDescriptor], },
    StencilDescriptorInvalid {
      variant_unique,
      descriptor [LalinStencil.StencilDescriptor],
      rejects [many [LalinStencil.StencilValidationReject]],
    },
  },

  product. StencilDescriptorBuildInput {
    interned,
    producer [LalinStencil.StencilProducer],
    accesses [many [LalinStencil.StencilAccess]],
    body [LalinStencil.StencilBody],
  },
  sum. StencilDescriptorBuild {
    StencilDescriptorBuilt { variant_unique, descriptor [LalinStencil.StencilDescriptor], },
    StencilDescriptorBuildRejected { variant_unique, reject [LalinStencil.StencilValidationReject], },
  },

  sum. StencilAccessLookup {
    StencilAccessFound { variant_unique, access [LalinStencil.StencilAccess], },
    StencilAccessMissing { variant_unique, access [LalinStencil.StencilAccessRef], reason [str], },
  },
  sum. StencilDestination {
    StencilDestinationAccess { variant_unique, access [LalinStencil.StencilAccessRef], },
    StencilDestinationNone,
  },

  sum. StencilIterationStopConvention {
    StencilIterationStopExclusive,
    StencilIterationStopInclusive,
  },
  sum. StencilKernelTripCount {
    StencilKernelTripExact { variant_unique, trip_count [LalinFlow.FlowTripCountExact], },
    StencilKernelTripNonNegative { variant_unique, trip_count [LalinFlow.FlowTripCountNonNegative], },
  },
  sum. StencilKernelDomainProvenance {
    StencilKernelCountedDomain1D {
      variant_unique,
      source [LalinFlow.FlowDomainShapeFact],
    },
    StencilKernelCountedWindow1D {
      variant_unique,
      source [LalinFlow.FlowDomainShapeFact],
      window [LalinStencil.StencilWindowAxis],
    },
  },
  sum. StencilKernelDomainShapeLookup {
    StencilKernelDomainShapeFound { variant_unique, fact [LalinFlow.FlowDomainShapeFact], },
    StencilKernelDomainShapeMissing { variant_unique, domain [LalinFlow.FlowDomain], },
    StencilKernelDomainShapeAmbiguous {
      variant_unique,
      domain [LalinFlow.FlowDomain],
      facts [many [LalinFlow.FlowDomainShapeFact]],
    },
  },
  product. StencilKernelDomainProjectionInput {
    interned,
    iteration [LalinStencil.StencilKernelIteration],
    source [LalinFlow.FlowDomainShapeFact],
  },
  product. StencilKernelDomainContinuationInput {
    interned,
    projection [LalinStencil.StencilKernelProjectionInput],
    iteration [LalinStencil.StencilKernelIteration],
  },
  sum. StencilKernelDomainResolution {
    StencilKernelDomainResolved {
      variant_unique,
      domain [LalinStencil.StencilKernelDomainProvenance],
      producer [LalinStencil.StencilProducer],
    },
    StencilKernelDomainRejected {
      variant_unique,
      reject [LalinStencil.StencilKernelProjectionReject],
    },
  },
  product. StencilKernelWindowIndexInput {
    interned,
    iteration [LalinStencil.StencilKernelIteration],
    window [LalinStencil.StencilWindowAxis],
    field. index [LalinValue.ValueExpr],
  },
  sum. StencilKernelWindowIndexProjection {
    StencilKernelWindowIndexCenter,
    StencilKernelWindowIndexOffset { variant_unique, offset [number], },
    StencilKernelWindowIndexRejected {
      variant_unique,
      reject [LalinStencil.StencilKernelProjectionReject],
    },
  },
  sum. StencilKernelWindowOffsetDirection {
    StencilKernelWindowOffsetAdd,
    StencilKernelWindowOffsetSubtract,
  },
  product. StencilKernelWindowOffsetApplyInput {
    interned,
    field. expr [LalinValue.ValueExpr],
    direction [LalinStencil.StencilKernelWindowOffsetDirection],
    window [LalinStencil.StencilKernelWindowIndexInput],
  },
  product. StencilKernelIteration {
    interned,
    loop [LalinGraph.GraphLoopId],
    counter [LalinCode.CodeValueId],
    index_ty [LalinCode.CodeType],
    start [LalinCode.CodeValueId],
    stop [LalinCode.CodeValueId],
    step [LalinCode.CodeValueId],
    step_magnitude [number],
    stop_convention [LalinStencil.StencilIterationStopConvention],
    order [LalinStencil.StencilProducerOrder],
    trip [LalinStencil.StencilKernelTripCount],
  },

  sum. StencilKernelProjectionReject {
    StencilKernelModuleMismatch { variant_unique, expected [LalinCode.CodeModuleId], actual [LalinCode.CodeModuleId], },
    StencilKernelScheduleMismatch { variant_unique, expected [LalinKernel.KernelId], actual [LalinKernel.KernelId], },
    StencilKernelUnsupportedSubject { variant_unique, subject [LalinKernel.KernelSubject], },
    StencilKernelMissingCounter { variant_unique, kernel [LalinKernel.KernelId], },
    StencilKernelMissingPrimaryInduction { variant_unique, loop [LalinGraph.GraphLoopId], },
    StencilKernelAmbiguousPrimaryInduction { variant_unique, loop [LalinGraph.GraphLoopId], count [number], },
    StencilKernelEquivalenceRejected { variant_unique, failures [many [LalinKernel.KernelEquivalenceFailure]], },
    StencilKernelConstructionIncomplete { variant_unique, kernel [LalinKernel.KernelId], },
    StencilKernelMissingLoopFact { variant_unique, loop [LalinGraph.GraphLoopId], },
    StencilKernelMissingDomainShape { variant_unique, domain [LalinFlow.FlowDomain], },
    StencilKernelAmbiguousDomainShape { variant_unique, domain [LalinFlow.FlowDomain], count [number], },
    StencilKernelUnsupportedDomainShape { variant_unique, shape [LalinFlow.FlowDomainShape], reason [str], },
    StencilKernelUnsupportedWindowIndex { variant_unique, field. index [LalinValue.ValueExpr], reason [str], },
    StencilKernelAmbiguousLoopFact { variant_unique, loop [LalinGraph.GraphLoopId], count [number], },
    StencilKernelMissingLoopOwner { variant_unique, loop [LalinGraph.GraphLoopId], },
    StencilKernelAmbiguousLoopOwner { variant_unique, loop [LalinGraph.GraphLoopId], count [number], },
    StencilKernelMissingSemanticIteration { variant_unique, loop [LalinGraph.GraphLoopId], },
    StencilKernelAmbiguousSemanticIteration { variant_unique, loop [LalinGraph.GraphLoopId], count [number], },
    StencilKernelIterationFactMismatch { variant_unique, loop [LalinGraph.GraphLoopId], reason [str], },
    StencilKernelMissingInduction { variant_unique, counter [LalinCode.CodeValueId], },
    StencilKernelAmbiguousInduction { variant_unique, counter [LalinCode.CodeValueId], count [number], },
    StencilKernelRejectedTripCount { variant_unique, trip_count [LalinFlow.FlowTripCountRejected], },
    StencilKernelUnavailableTrip { variant_unique, trip [LalinKernel.KernelTripUnavailable], },
    StencilKernelUnsupportedDirection { variant_unique, direction [LalinFlow.FlowLoopDirection], },
    StencilKernelMissingStepDefinition { variant_unique, step [LalinCode.CodeValueId], },
    StencilKernelAmbiguousStepDefinition { variant_unique, step [LalinCode.CodeValueId], count [number], },
    StencilKernelNonIntegerStep { variant_unique, step [LalinCode.CodeValueId], constant [LalinCode.CodeConst], },
    StencilKernelZeroStep { variant_unique, step [LalinCode.CodeValueId], },
    StencilKernelStepDirectionMismatch { variant_unique, step [LalinCode.CodeValueId], direction [LalinFlow.FlowLoopDirection], },
    StencilKernelMissingLaneAccess { variant_unique, field. lane [LalinKernel.KernelLane], access [LalinMem.MemAccessId], },
    StencilKernelDuplicateLane { variant_unique, field. lane [LalinKernel.KernelLane], },
    StencilKernelDuplicateValue { variant_unique, field. value [LalinKernel.KernelValueId], },
    StencilKernelUnresolvedValue { variant_unique, field. value [LalinKernel.KernelValueId], },
    StencilKernelUnsupportedLane { variant_unique, field. lane [LalinKernel.KernelLane], reason [str], },
    StencilKernelUnsupportedBinding { variant_unique, binding [LalinKernel.KernelBinding], reason [str], },
    StencilKernelUnsupportedResultExpr { variant_unique, field. expr [LalinKernel.KernelExpr], reason [str], },
    StencilKernelFindValueMismatch {
      variant_unique,
      counter [LalinCode.CodeValueId],
      found [LalinCode.CodeValueId],
    },
    StencilKernelUnsupportedEffect { variant_unique, effect [LalinKernel.KernelEffect], reason [str], },
    StencilKernelDeferredReductionMismatch {
      variant_unique,
      deferred [many [LalinValue.ReductionFact]],
      result [LalinKernel.KernelResult],
    },
    StencilKernelMissingReductionArithmetic { variant_unique, reduction [LalinValue.ReductionFact], },
    StencilKernelAmbiguousReductionArithmetic { variant_unique, reduction [LalinValue.ReductionFact], },
    StencilKernelUnsupportedResult { variant_unique, result [LalinKernel.KernelResult], reason [str], },
    StencilKernelScheduleNotPlanned { variant_unique, schedule [LalinSchedule.KernelSchedule], reason [str], },
    StencilKernelScheduleMissing { variant_unique, kernel [LalinKernel.KernelId], },
    StencilKernelScheduleAmbiguous { variant_unique, kernel [LalinKernel.KernelId], count [number], },
    StencilKernelPlanningRejected { variant_unique, plan [LalinKernel.KernelNoPlan], },
    StencilKernelUnsupportedScheduleForm { variant_unique, form [LalinSchedule.ScheduleForm], reason [str], },
  },

  sum. StencilKernelLoopFactLookup {
    StencilKernelLoopFactFound { variant_unique, fact [LalinFlow.FlowLoopFacts], },
    StencilKernelLoopFactMissing { variant_unique, reject [LalinStencil.StencilKernelMissingLoopFact], },
    StencilKernelLoopFactAmbiguous { variant_unique, reject [LalinStencil.StencilKernelAmbiguousLoopFact], },
  },

  sum. StencilKernelLoopOwnerLookup {
    StencilKernelLoopOwnerFound { variant_unique, func [LalinCode.CodeFuncId], },
    StencilKernelLoopOwnerMissing { variant_unique, reject [LalinStencil.StencilKernelMissingLoopOwner], },
    StencilKernelLoopOwnerAmbiguous { variant_unique, reject [LalinStencil.StencilKernelAmbiguousLoopOwner], },
  },
  sum. StencilKernelSemanticIterationContribution {
    StencilKernelSemanticIterationIgnored,
    StencilKernelSemanticIterationMatched { variant_unique, fact [LalinFlow.FlowLoopNormalizedCounted], },
  },
  sum. StencilKernelSemanticIterationLookup {
    StencilKernelSemanticIterationFound { variant_unique, fact [LalinFlow.FlowLoopNormalizedCounted], },
    StencilKernelSemanticIterationMissing { variant_unique, reject [LalinStencil.StencilKernelMissingSemanticIteration], },
    StencilKernelSemanticIterationAmbiguous { variant_unique, reject [LalinStencil.StencilKernelAmbiguousSemanticIteration], },
  },
  sum. StencilKernelPrimaryInductionContribution {
    StencilKernelPrimaryInductionIgnored,
    StencilKernelPrimaryInductionSelected { variant_unique, induction [LalinFlow.FlowInduction], },
  },
  sum. StencilKernelInductionLookup {
    StencilKernelInductionFound { variant_unique, induction [LalinFlow.FlowInduction], },
    StencilKernelInductionMissing { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
    StencilKernelInductionAmbiguous { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
  },
  sum. StencilKernelStepLookup {
    StencilKernelStepDefinitionMissing { variant_unique, step [LalinCode.CodeValueId], },
    StencilKernelStepDefinitionFound { variant_unique, func [LalinCode.CodeFuncId], step [LalinCode.CodeValueId], constant [LalinCode.CodeConst], },
    StencilKernelStepDefinitionAmbiguous { variant_unique, step [LalinCode.CodeValueId], count [number], },
  },
  product. StencilKernelStepContributionInput {
    interned,
    lookup [LalinStencil.StencilKernelStepLookup],
    func [LalinCode.CodeFuncId],
    step [LalinCode.CodeValueId],
  },
  product. StencilKernelStepDefinitionInput {
    interned,
    contribution [LalinStencil.StencilKernelStepContributionInput],
    constant [LalinCode.CodeConst],
  },
  product. StencilKernelLiteralStepInput {
    interned,
    step [LalinCode.CodeValueId],
    constant [LalinCode.CodeConst],
  },
  product. StencilKernelStepConstant {
    interned,
    step [LalinCode.CodeValueId],
    magnitude [number],
  },
  sum. StencilKernelStepResolution {
    StencilKernelStepResolved { variant_unique, step [LalinStencil.StencilKernelStepConstant], },
    StencilKernelStepRejected { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
  },
  product. StencilKernelIterationBuildInput {
    interned,
    kernel [LalinKernel.KernelPlanned],
    semantic [LalinFlow.FlowLoopNormalizedCounted],
    induction [LalinFlow.FlowInduction],
    step [LalinStencil.StencilKernelStepConstant],
    trip [LalinKernel.KernelTripEvidence],
  },
  product. StencilKernelTripBuildInput {
    interned,
    iteration [LalinStencil.StencilKernelIterationBuildInput],
    order [LalinStencil.StencilProducerOrder],
  },
  product. StencilKernelIterationInput {
    interned,
    field. module [LalinCode.CodeModule],
    graph [LalinGraph.CodeGraph],
    kernel [LalinKernel.KernelPlanned],
    flow [LalinFlow.FlowFactSet],
    semantics [LalinFlow.FlowSemanticFactSet],
  },
  product. StencilKernelLoopFactContinuationInput {
    interned,
    request [LalinStencil.StencilKernelIterationInput],
    loop [LalinGraph.GraphLoopId],
  },
  product. StencilKernelSemanticContinuationInput {
    interned,
    request [LalinStencil.StencilKernelIterationInput],
    loop_fact [LalinFlow.FlowLoopFacts],
  },
  product. StencilKernelCounterInput {
    interned,
    request [LalinStencil.StencilKernelIterationInput],
    semantic [LalinStencil.StencilKernelSemanticIterationFound],
    loop_fact [LalinFlow.FlowLoopFacts],
  },
  product. StencilKernelInductionContinuationInput {
    interned,
    request [LalinStencil.StencilKernelIterationInput],
    semantic [LalinStencil.StencilKernelSemanticIterationFound],
  },
  product. StencilKernelCounterAlignmentInput {
    interned,
    continuation [LalinStencil.StencilKernelInductionContinuationInput],
    induction [LalinFlow.FlowInduction],
  },
  product. StencilKernelIterationCursor {
    interned,
    request [LalinStencil.StencilKernelIterationInput],
    semantic [LalinStencil.StencilKernelSemanticIterationFound],
    induction [LalinFlow.FlowInduction],
  },
  sum. StencilKernelIterationProjection {
    StencilKernelIterationProjected { variant_unique, iteration [LalinStencil.StencilKernelIteration], },
    StencilKernelIterationRejected { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
  },

  product. StencilAccessByKernelLaneEntry {
    interned,
    field. lane [LalinKernel.KernelLane],
    access [LalinStencil.StencilAccess],
  },
  product. StencilAccessByKernelLaneProjection {
    interned,
    entries [many [LalinStencil.StencilAccessByKernelLaneEntry]],
  },
  sum. StencilAccessByKernelLaneLookup {
    StencilAccessByKernelLaneFound { variant_unique, entry [LalinStencil.StencilAccessByKernelLaneEntry], },
    StencilAccessByKernelLaneMissing { variant_unique, field. lane [LalinKernel.KernelLane], },
  },
  product. StencilStreamByKernelValueEntry {
    interned,
    source [LalinCode.CodeValueId],
    binding [LalinKernel.KernelBinding],
    definition [LalinStencil.StencilStreamDef],
  },
  product. StencilStreamByKernelValueProjection {
    interned,
    entries [many [LalinStencil.StencilStreamByKernelValueEntry]],
  },
  sum. StencilStreamByKernelValueLookup {
    StencilStreamByKernelValueFound { variant_unique, entry [LalinStencil.StencilStreamByKernelValueEntry], },
    StencilStreamByKernelValueMissing { variant_unique, field. value [LalinKernel.KernelValueId], },
  },

  product. StencilKernelConstructionState {
    interned,
    kernel [LalinKernel.KernelPlanned],
    iteration [LalinStencil.StencilKernelIteration],
    domain [LalinStencil.StencilKernelDomainProvenance],
    producer [LalinStencil.StencilProducer],
    access_by_lane [LalinStencil.StencilAccessByKernelLaneProjection],
    stream_by_value [LalinStencil.StencilStreamByKernelValueProjection],
    result_streams [many [LalinStencil.StencilStreamByKernelValueEntry]],
    sinks [many [LalinStencil.StencilSinkDef]],
    deferred_reductions [many [LalinValue.ReductionFact]],
    legality [LalinStencil.StencilFusionLegality],
    proofs [many [LalinKernel.KernelProof]],
    next_stream_ordinal [number],
  },
  product. StencilKernelStateAccessInput {
    interned,
    field. lane [LalinKernel.KernelLane],
    access [LalinStencil.StencilAccess],
  },
  product. StencilKernelStateStreamInput {
    interned,
    source [LalinCode.CodeValueId],
    binding [LalinKernel.KernelBinding],
    definition [LalinStencil.StencilStreamDef],
  },
  sum. StencilKernelConstruction {
    StencilKernelConstructionCollecting { variant_unique, state [LalinStencil.StencilKernelConstructionState], },
    StencilKernelConstructionFinalizable { variant_unique, state [LalinStencil.StencilKernelConstructionState], },
    StencilKernelConstructionRejected { variant_unique, state [LalinStencil.StencilKernelConstructionState], rejects [many [LalinStencil.StencilKernelProjectionReject]], },
  },
  sum. StencilKernelReductionArithmeticResolution {
    StencilKernelReductionArithmeticResolved {
      variant_unique,
      arithmetic [LalinStencil.StencilArithmeticMode],
    },
    StencilKernelReductionArithmeticRejected {
      variant_unique,
      reject [LalinStencil.StencilKernelProjectionReject],
    },
  },
  product. StencilKernelReductionFinishInput {
    interned,
    state [LalinStencil.StencilKernelConstructionState],
    reduction [LalinValue.ReductionFact],
    stream [LalinStencil.StencilStreamId],
  },
  product. StencilKernelConstructionInitInput {
    interned,
    kernel [LalinKernel.KernelPlanned],
    iteration [LalinStencil.StencilKernelIteration],
    domain [LalinStencil.StencilKernelDomainProvenance],
    producer [LalinStencil.StencilProducer],
  },
  product. StencilKernelAccessContributionInput {
    interned,
    field. lane [LalinKernel.KernelLane],
    mem [LalinMem.MemSemanticFactSet],
  },
  product. StencilKernelAccessResolutionInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    contribution [LalinStencil.StencilKernelAccessContributionInput],
  },
  product. StencilKernelStrideInput {
    interned,
    layout [LalinStencil.StencilKernelAccessLayoutInput],
    stride_elems [number],
  },
  product. StencilKernelAccessFactInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    field. lane [LalinKernel.KernelLane],
    access [LalinMem.MemAccessFact],
  },
  sum. StencilKernelAccessRoleProjection {
    StencilKernelAccessRoleProjected { variant_unique, role [LalinStencil.StencilAccessRole], },
    StencilKernelAccessRoleRejected { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
  },
  product. StencilKernelAccessLayoutInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    field. lane [LalinKernel.KernelLane],
    access [LalinMem.MemAccessFact],
    role [LalinStencil.StencilAccessRole],
  },
  sum. StencilKernelAccessPreparation {
    StencilKernelAccessPrepared { variant_unique, field. lane [LalinKernel.KernelLane], access [LalinStencil.StencilAccess], },
    StencilKernelAccessPreparationRejected { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
  },
  product. StencilKernelResultStreamInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    field. id [LalinStencil.StencilStreamId],
    source [LalinCode.CodeValueId],
  },
  product. StencilKernelResultBindingInput {
    interned,
    result [LalinStencil.StencilKernelResultStreamInput],
    field. expr [LalinKernel.KernelExprValue],
  },
  product. StencilKernelResultBoundExprInput {
    interned,
    result [LalinStencil.StencilKernelResultStreamInput],
    binding [LalinKernel.KernelBinding],
  },
  product. StencilKernelResultLaneLookupInput {
    interned,
    result [LalinStencil.StencilKernelResultStreamInput],
    field. expr [LalinKernel.KernelExprLaneLoad],
  },
  product. StencilKernelResultLaneStreamInput {
    interned,
    result [LalinStencil.StencilKernelResultStreamInput],
    access [LalinStencil.StencilAccessByKernelLaneFound],
    field. expr [LalinKernel.KernelExprLaneLoad],
  },
  sum. StencilKernelResultStreamPreparation {
    StencilKernelResultStreamPrepared {
      variant_unique,
      entry [LalinStencil.StencilStreamByKernelValueEntry],
    },
    StencilKernelResultStreamRejected {
      variant_unique,
      reject [LalinStencil.StencilKernelProjectionReject],
    },
  },
  product. StencilKernelControlStreamUse {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    result [LalinKernel.KernelResult],
    sink [LalinStencil.StencilSinkId],
  },
  product. StencilKernelAllCompareLeftInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    result [LalinKernel.KernelResultAllCompare],
    sink [LalinStencil.StencilSinkId],
    right_id [LalinStencil.StencilStreamId],
  },
  product. StencilKernelAllCompareRightInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    result [LalinKernel.KernelResultAllCompare],
    sink [LalinStencil.StencilSinkId],
    left [LalinStencil.StencilStreamDef],
    right_id [LalinStencil.StencilStreamId],
  },
  product. StencilKernelControlFinishInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    sink [LalinStencil.StencilSinkId],
    stream [LalinStencil.StencilStreamDef],
  },
  product. StencilKernelStreamContributionInput {
    interned,
    entry [LalinKernel.KernelBindingByCodeValueEntry],
  },
  product. StencilKernelStreamContributionCursor {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    contribution [LalinStencil.StencilKernelStreamContributionInput],
  },
  product. StencilKernelBindingExprInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    source [LalinCode.CodeValueId],
    binding [LalinKernel.KernelBinding],
    field. id [LalinStencil.StencilStreamId],
  },
  product. StencilKernelLaneStreamInput {
    interned,
    stream [LalinStencil.StencilKernelBindingExprInput],
    access [LalinStencil.StencilAccessByKernelLaneFound],
  },
  sum. StencilKernelStreamPreparation {
    StencilKernelStreamPrepared {
      variant_unique,
      source [LalinCode.CodeValueId],
      binding [LalinKernel.KernelBinding],
      definition [LalinStencil.StencilStreamDef],
    },
    StencilKernelStreamPreparationRejected { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
  },
  product. StencilKernelSinkContributionInput {
    interned,
    effect [LalinKernel.KernelEffect],
  },
  product. StencilKernelEffectInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
    effect [LalinKernel.KernelEffect],
  },
  product. StencilKernelEffectStreamInput {
    interned,
    effect [LalinStencil.StencilKernelEffectInput],
    definition [LalinStencil.StencilStreamDef],
  },
  sum. StencilKernelSinkPreparation {
    StencilKernelSinkPrepared { variant_unique, sinks [many [LalinStencil.StencilSinkDef]], },
    StencilKernelSinkDeferredToResult { variant_unique, reduction [LalinValue.ReductionFact], },
    StencilKernelSinkPreparationRejected { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
  },
  product. StencilKernelResultContributionInput {
    interned,
    construction [LalinStencil.StencilKernelConstruction],
  },

  product. StencilKernelScheduleConversionInput {
    interned,
    kernel [LalinKernel.KernelPlanned],
    schedule [LalinSchedule.KernelSchedule],
    compiler [LalinStencil.StencilCompilerPolicy],
    target [LalinBackend.BackTargetModel],
    accesses [LalinStencil.StencilAccessByKernelLaneProjection],
    result [LalinKernel.KernelResult],
  },
  sum. StencilKernelScheduleConversion {
    StencilKernelScheduleConverted {
      variant_unique,
      source [LalinSchedule.SchedulePlanned],
      schedule [LalinStencil.StencilSchedule],
    },
    StencilKernelScheduleRejected { variant_unique, reject [LalinStencil.StencilKernelProjectionReject], },
  },
  product. StencilKernelFinalizationInput {
    interned,
    schedule [LalinStencil.StencilKernelScheduleConversion],
  },

  sum. StencilKernelResultProvenance {
    StencilKernelResultVoid,
    StencilKernelResultReduction {
      variant_unique,
      sink [LalinStencil.StencilSinkId],
      reduction [LalinValue.ReductionOp],
      accumulator [LalinCode.CodeValueId],
      stream [LalinStencil.StencilStreamRef],
    },
    StencilKernelResultAll {
      variant_unique,
      sink [LalinStencil.StencilSinkId],
      src [LalinStencil.StencilStreamRef],
      src_value [LalinCode.CodeValueId],
      pred [LalinStencil.StencilPredicate],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    StencilKernelResultAllCompare {
      variant_unique,
      sink [LalinStencil.StencilSinkId],
      left [LalinStencil.StencilStreamRef],
      left_value [LalinCode.CodeValueId],
      right [LalinStencil.StencilStreamRef],
      right_value [LalinCode.CodeValueId],
      cmp [LalinCore.CmpOp],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    StencilKernelResultAny {
      variant_unique,
      sink [LalinStencil.StencilSinkId],
      src [LalinStencil.StencilStreamRef],
      src_value [LalinCode.CodeValueId],
      pred [LalinStencil.StencilPredicate],
      success [LalinCode.CodeBlockId],
      failure [LalinCode.CodeBlockId],
    },
    StencilKernelResultFind {
      variant_unique,
      sink [LalinStencil.StencilSinkId],
      src [LalinStencil.StencilStreamRef],
      src_value [LalinCode.CodeValueId],
      pred [LalinStencil.StencilPredicate],
      found_value [LalinCode.CodeValueId],
      found [LalinCode.CodeBlockId],
      not_found [LalinCode.CodeBlockId],
      not_found_value [LalinValue.ValueExpr],
    },
  },
  product. StencilKernelProvenanceFacet {
    interned,
    kernel [LalinKernel.KernelPlanned],
    iteration [LalinStencil.StencilKernelIteration],
    domain [LalinStencil.StencilKernelDomainProvenance],
    accesses [LalinStencil.StencilAccessByKernelLaneProjection],
    streams [LalinStencil.StencilStreamByKernelValueProjection],
    result [LalinStencil.StencilKernelResultProvenance],
  },
  product. StencilKernelComputationProjection {
    interned,
    source_schedule [LalinSchedule.SchedulePlanned],
    provenance [LalinStencil.StencilKernelProvenanceFacet],
    computation [LalinStencil.StencilComputation],
  },

  product. StencilKernelProjectionInput {
    interned,
    field. module [LalinCode.CodeModule],
    graph [LalinGraph.CodeGraph],
    flow [LalinFlow.FlowFactSet],
    semantics [LalinFlow.FlowSemanticFactSet],
    kernel [LalinKernel.KernelPlanned],
    schedule [LalinSchedule.KernelSchedule],
    compiler [LalinStencil.StencilCompilerPolicy],
    target [LalinBackend.BackTargetModel],
    mem [LalinMem.MemSemanticFactSet],
    effects [LalinEffect.EffectFactSet],
  },
  sum. StencilKernelProjection {
    StencilKernelProjected { variant_unique, projection [LalinStencil.StencilKernelComputationProjection], },
    StencilKernelProjectionRejected { variant_unique, kernel [LalinKernel.KernelPlanned], rejects [many [LalinStencil.StencilKernelProjectionReject]], },
  },
  sum. StencilKernelScheduleLookup {
    StencilKernelScheduleFound { variant_unique, schedule [LalinSchedule.KernelSchedule], },
    StencilKernelScheduleLookupMissing { variant_unique, reject [LalinStencil.StencilKernelScheduleMissing], },
    StencilKernelScheduleLookupAmbiguous { variant_unique, reject [LalinStencil.StencilKernelScheduleAmbiguous], },
  },
  sum. StencilKernelScheduleContribution {
    StencilKernelScheduleIgnored,
    StencilKernelScheduleMatched { variant_unique, schedule [LalinSchedule.KernelSchedule], },
  },
  sum. StencilKernelModuleEntry {
    StencilKernelModuleProjectedEntry {
      variant_unique,
      kernel [LalinKernel.KernelId],
      result [LalinStencil.StencilKernelProjection],
    },
    StencilKernelModuleRejectedEntry { variant_unique, plan [LalinKernel.KernelNoPlan], },
  },
  product. StencilKernelModuleProjectionInput {
    interned,
    field. module [LalinCode.CodeModule],
    graph [LalinGraph.CodeGraph],
    flow [LalinFlow.FlowFactSet],
    semantics [LalinFlow.FlowSemanticFactSet],
    kernels [LalinKernel.KernelModulePlan],
    schedules [LalinSchedule.ScheduleModulePlan],
    compiler [LalinStencil.StencilCompilerPolicy],
  },
  product. StencilKernelModuleEntryInput {
    interned,
    projection [LalinStencil.StencilKernelModuleProjectionInput],
    kernel [LalinKernel.KernelPlanned],
  },
  product. StencilKernelModuleProjection {
    interned,
    field. module [LalinCode.CodeModuleId],
    entries [many [LalinStencil.StencilKernelModuleEntry]],
  },
  sum. StencilKernelModuleProjectionResult {
    StencilKernelModuleProjected { variant_unique, projection [LalinStencil.StencilKernelModuleProjection], },
    StencilKernelModuleProjectionRejected {
      variant_unique,
      expected [LalinCode.CodeModuleId],
      actual [LalinCode.CodeModuleId],
    },
    StencilKernelModuleFacetMismatch { variant_unique, reason [str], },
  },

  product. StencilCodegenPlanInput {
    interned,
    computation [LalinStencil.StencilComputation],
    materialization [LalinCMat.CMatMaterializationInput],
  },
  sum. StencilCodegenPlan {
    StencilCodegenCMat { variant_unique, materialization [LalinCMat.CMatMaterialization], },
    StencilCodegenRejected { variant_unique, rejects [many [LalinStencil.StencilReject]], },
  },
}