local S = require("lalin.schema.dsl")
S.use()

return schema. LalinTree {
  sum. ExprHeader {
    ExprSurface,
    ExprTyped { variant_unique, field. ty [LalinType.Type], },
  },
  sum. PlaceHeader {
    PlaceSurface,
    PlaceTyped { variant_unique, field. ty [LalinType.Type], },
  },
  sum. StmtHeader {
    StmtSurface,
    StmtFlow { variant_unique, flow [LalinSem.FlowOutcome], },
  },
  product. FieldInit {
    interned,
    field. name [str],
    field. value [LalinTree.Expr],
    offset [number],
  },
  product. VariantBind { interned, field. name [str], field. ty [LalinType.Type], },
  product. VariantBindSource { interned, field. name [str], },
  product. SwitchVariantSourceStmtArm {
    interned,
    variant_name [str],
    binds [many [LalinTree.VariantBindSource]],
    body [many [LalinTree.Stmt]],
  },
  sum. SwitchKey {
    SwitchKeyInt { variant_unique, raw [str], },
    SwitchKeyBool { variant_unique, field. value [bool], },
    SwitchKeyName { variant_unique, field. name [str], },
    SwitchKeyExpr { variant_unique, field. expr [LalinTree.Expr], },
  },
  -- SwitchKeyDecision DELETED — this was a delayed-control union with stringly reason.
  -- Replaced by leaf methods on Expr returning SwitchKeyClass (in LalinCheck).
  product. SwitchStmtArm { interned, key [LalinTree.SwitchKey], body [many [LalinTree.Stmt]], },
  product. SwitchExprArm {
    interned,
    key [LalinTree.SwitchKey],
    body [many [LalinTree.Stmt]],
    result [LalinTree.Expr],
  },
  product. SwitchVariantStmtArm {
    interned,
    variant_name [str],
    binds [many [LalinTree.VariantBind]],
    body [many [LalinTree.Stmt]],
  },
  product. SwitchVariantExprArm {
    interned,
    variant_name [str],
    binds [many [LalinTree.VariantBind]],
    body [many [LalinTree.Stmt]],
    result [LalinTree.Expr],
  },
  sum. View {
    ViewFromExpr { variant_unique, base [LalinTree.Expr], elem [LalinType.Type], },
    ViewContiguous {
      variant_unique,
      data [LalinTree.Expr],
      elem [LalinType.Type],
      len [LalinTree.Expr],
    },
    ViewStrided {
      variant_unique,
      data [LalinTree.Expr],
      elem [LalinType.Type],
      len [LalinTree.Expr],
      stride [LalinTree.Expr],
    },
    ViewRestrided {
      variant_unique,
      base [LalinTree.View],
      elem [LalinType.Type],
      stride [LalinTree.Expr],
    },
    ViewWindow {
      variant_unique,
      base [LalinTree.View],
      start [LalinTree.Expr],
      len [LalinTree.Expr],
    },
    ViewRowBase {
      variant_unique,
      base [LalinTree.View],
      row_offset [LalinTree.Expr],
      elem [LalinType.Type],
    },
    ViewInterleaved {
      variant_unique,
      data [LalinTree.Expr],
      elem [LalinType.Type],
      len [LalinTree.Expr],
      stride [LalinTree.Expr],
      lane [LalinTree.Expr],
    },
    ViewInterleavedView {
      variant_unique,
      base [LalinTree.View],
      elem [LalinType.Type],
      stride [LalinTree.Expr],
      lane [LalinTree.Expr],
    },
  },
  sum. Domain {
    DomainRange { variant_unique, stop [LalinTree.Expr], },
    DomainRange2 { variant_unique, start [LalinTree.Expr], stop [LalinTree.Expr], },
    DomainZipEqValues { variant_unique, values [many [LalinTree.Expr]], },
    DomainValue { variant_unique, field. value [LalinTree.Expr], },
    DomainView { variant_unique, view [LalinTree.View], },
    DomainZipEqViews { variant_unique, views [many [LalinTree.View]], },
  },
  sum. IndexBase {
    IndexBaseExpr { variant_unique, base [LalinTree.Expr], },
    IndexBasePlace { variant_unique, base [LalinTree.Place], elem [LalinType.Type], },
    IndexBaseView { variant_unique, view [LalinTree.View], },
  },
  sum. Place {
    PlaceRef {
      variant_unique,
      h [LalinTree.PlaceHeader],
      field. ref [LalinBind.ValueRef],
    },
    PlaceDeref { variant_unique, h [LalinTree.PlaceHeader], base [LalinTree.Expr], },
    PlaceDot {
      variant_unique,
      h [LalinTree.PlaceHeader],
      base [LalinTree.Place],
      field. name [str],
    },
    PlaceField {
      variant_unique,
      h [LalinTree.PlaceHeader],
      base [LalinTree.Place],
      field. field [LalinSem.FieldRef],
    },
    PlaceIndex {
      variant_unique,
      h [LalinTree.PlaceHeader],
      base [LalinTree.IndexBase],
      index [LalinTree.Expr],
    },
  },
  product. RegionProtocolKey { interned, text [str], },
  product. RegionResultTypeId { interned, text [str], },
  product. RegionFunctionId { interned, text [str], },
  product. RegionLocalNamespace { interned, text [str], },
  product. RegionExpansionId { interned, text [str], },
  product. RegionCont { interned, key [LalinTree.RegionProtocolKey], field. name [str], params [many [LalinTree.BlockParam]], },
  product. BlockLabel { interned, field. name [str], },
  product. BlockParam { interned, field. name [str], field. ty [LalinType.Type], },
  product. EntryBlockParam {
    interned,
    field. name [str],
    field. ty [LalinType.Type],
    init [LalinTree.Expr],
  },
  product. JumpArg { interned, field. name [str], field. value [LalinTree.Expr], },
  product. RegionInvokeTarget { interned, path [LalinCore.Path], },
  sum. RegionWireTarget {
    RegionWireBlock { variant_unique, label [LalinTree.BlockLabel], args [many [LalinTree.JumpArg]], },
    RegionWireCont { variant_unique, cont [LalinTree.RegionCont], args [many [LalinTree.JumpArg]], },
  },
  product. RegionContWire { interned, field. name [str], target [LalinTree.RegionWireTarget], },
  product. TypeRegionDef {
    interned,
    target [LalinTree.RegionInvokeTarget],
    region [LalinTree.Region],
  },
  product. RegionSealPayload {
    interned,
    cont [LalinTree.RegionCont],
    type_id [LalinTree.RegionResultTypeId],
  },
  product. RegionProtocol {
    interned,
    key [LalinTree.RegionProtocolKey],
    result_type [LalinTree.RegionResultTypeId],
    payloads [many [LalinTree.RegionSealPayload]],
  },
  product. RegionSeal {
    interned,
    target [LalinTree.RegionInvokeTarget],
    region [LalinTree.Region],
    function_id [LalinTree.RegionFunctionId],
    protocol [LalinTree.RegionProtocol],
  },
  product. RegionBundleMember {
    interned,
    seal [LalinTree.RegionSeal],
    entry_label [LalinTree.BlockLabel],
    local_namespace [LalinTree.RegionLocalNamespace],
  },
  product. RegionBundle {
    interned,
    root [LalinTree.RegionSeal],
    members [many [LalinTree.RegionBundleMember]],
  },

  product. RegionDefinitionEntry { interned, target [LalinTree.RegionInvokeTarget], definition [LalinTree.TypeRegionDef], },
  product. RegionDefinitionProjection { interned, entries [many [LalinTree.RegionDefinitionEntry]], },
  sum. RegionDefinitionLookup {
    RegionDefinitionFound { variant_unique, entry [LalinTree.RegionDefinitionEntry], },
    RegionDefinitionMissing { variant_unique, target [LalinTree.RegionInvokeTarget], },
  },
  product. RegionProtocolEntry { interned, key [LalinTree.RegionProtocolKey], protocol [LalinTree.RegionProtocol], },
  product. RegionProtocolProjection { interned, entries [many [LalinTree.RegionProtocolEntry]], },
  sum. RegionProtocolLookup {
    RegionProtocolFound { variant_unique, entry [LalinTree.RegionProtocolEntry], },
    RegionProtocolMissing { variant_unique, key [LalinTree.RegionProtocolKey], },
  },
  product. RegionSealEntry { interned, target [LalinTree.RegionInvokeTarget], seal [LalinTree.RegionSeal], },
  product. RegionSealProjection { interned, entries [many [LalinTree.RegionSealEntry]], },
  sum. RegionSealLookup {
    RegionSealFound { variant_unique, entry [LalinTree.RegionSealEntry], },
    RegionSealMissing { variant_unique, target [LalinTree.RegionInvokeTarget], },
  },
  product. RegionBundleEntry { interned, target [LalinTree.RegionInvokeTarget], bundle [LalinTree.RegionBundle], },
  product. RegionBundleProjection { interned, entries [many [LalinTree.RegionBundleEntry]], },
  sum. RegionBundleLookup {
    RegionBundleFound { variant_unique, entry [LalinTree.RegionBundleEntry], },
    RegionBundleMissing { variant_unique, target [LalinTree.RegionInvokeTarget], },
  },
  product. RegionFactProjection {
    interned,
    definitions [LalinTree.RegionDefinitionProjection],
    protocols [LalinTree.RegionProtocolProjection],
    seals [LalinTree.RegionSealProjection],
    bundles [LalinTree.RegionBundleProjection],
  },
  product. RegionWireEntry { interned, field. name [str], wire [LalinTree.RegionContWire], },
  product. RegionWireProjection { interned, entries [many [LalinTree.RegionWireEntry]], },
  sum. RegionWireLookup {
    RegionWireFound { variant_unique, entry [LalinTree.RegionWireEntry], },
    RegionWireMissing { variant_unique, field. name [str], },
  },
  product. RegionCallCaptureEntry { interned, field. name [str], field. ty [LalinType.Type], field. value [LalinTree.Expr], },
  product. RegionCallCaptureProjection { interned, entries [many [LalinTree.RegionCallCaptureEntry]], },

  sum. RegionInvokeReject {
    RegionInvokeMissingTarget { variant_unique, target [LalinTree.RegionInvokeTarget], },
    RegionInvokeArgCount { variant_unique, target [LalinTree.RegionInvokeTarget], expected [number], actual [number], },
    RegionInvokeMissingWire { variant_unique, target [LalinTree.RegionInvokeTarget], cont [LalinTree.RegionCont], },
    RegionInvokeExtraWire { variant_unique, target [LalinTree.RegionInvokeTarget], field. name [str], },
    RegionInvokeDuplicateWire { variant_unique, target [LalinTree.RegionInvokeTarget], field. name [str], },
    RegionInvokeCallFrameUnsupported { variant_unique, target [LalinTree.RegionInvokeTarget], frame_kind [str], reason [str], },
  },
  product. RegionInvokeExpandInput {
    interned,
    state [LalinCheck.TypeStmtInput],
    facts [LalinTree.RegionFactProjection],
    expansion [LalinTree.RegionExpansionId],
  },
  product. RegionInvokeSplice {
    interned,
    entry_stmt [LalinTree.Stmt],
    blocks [many [LalinTree.ControlBlock]],
    captures [LalinTree.RegionCallCaptureProjection],
    next_state [LalinCheck.TypeStmtInput],
  },
  sum. RegionInvokeExpandResult {
    RegionInvokeExpanded { variant_unique, splice [LalinTree.RegionInvokeSplice], },
    RegionInvokeRejected { variant_unique, reject [LalinTree.RegionInvokeReject], },
  },
  product. RegionStmtBody { interned, stmts [many [LalinTree.Stmt]], },
  product. RegionStmtExpansionInput {
    interned,
    state [LalinCheck.TypeStmtInput],
    facts [LalinTree.RegionFactProjection],
    expansion [LalinTree.RegionExpansionId],
  },
  product. RegionStmtExpansionResult {
    interned,
    next_state [LalinCheck.TypeStmtInput],
    stmts [many [LalinTree.Stmt]],
    blocks [many [LalinTree.ControlBlock]],
    issues [many [LalinCheck.TypeIssue]],
  },
  product. RegionBodyExpansionInput {
    interned,
    state [LalinCheck.TypeStmtInput],
    facts [LalinTree.RegionFactProjection],
    expansion [LalinTree.RegionExpansionId],
  },
  product. RegionBodyExpansionResult {
    interned,
    next_state [LalinCheck.TypeStmtInput],
    body [LalinTree.RegionStmtBody],
    blocks [many [LalinTree.ControlBlock]],
    issues [many [LalinCheck.TypeIssue]],
  },
  sum. RegionBlockNode {
    RegionEntryBlockNode { variant_unique, entry [LalinTree.EntryControlBlock], },
    RegionControlBlockNode { variant_unique, block [LalinTree.ControlBlock], },
  },
  product. RegionBlockExpansionInput {
    interned,
    state [LalinCheck.TypeStmtInput],
    facts [LalinTree.RegionFactProjection],
    expansion [LalinTree.RegionExpansionId],
  },
  product. RegionBlockExpansionResult {
    interned,
    node [LalinTree.RegionBlockNode],
    blocks [many [LalinTree.ControlBlock]],
    issues [many [LalinCheck.TypeIssue]],
  },
  product. RegionModuleExpansionInput { interned, facts [LalinTree.RegionFactProjection], },
  sum. RegionModuleExpansion {
    RegionModuleExpanded { variant_unique, field. module [LalinTree.Module], facts [LalinTree.RegionFactProjection], issues [many [LalinCheck.TypeIssue]], },
    RegionModuleRejected { variant_unique, field. module [LalinTree.Module], facts [LalinTree.RegionFactProjection], issues [many [LalinCheck.TypeIssue]], },
  },
  sum. FuncContract {
    ContractBounds { variant_unique, base [LalinTree.Expr], len [LalinTree.Expr], },
    ContractWindowBounds {
      variant_unique,
      base [LalinTree.Expr],
      base_len [LalinTree.Expr],
      start [LalinTree.Expr],
      len [LalinTree.Expr],
    },
    ContractDisjoint { variant_unique, a [LalinTree.Expr], b [LalinTree.Expr], },
    ContractSameLen { variant_unique, a [LalinTree.Expr], b [LalinTree.Expr], },
    ContractSoAComponent {
      variant_unique,
      base [LalinTree.Expr],
      record_ty [LalinType.Type],
      field_name [str],
      component_index [number],
    },
    ContractNoAlias { variant_unique, base [LalinTree.Expr], },
    ContractReadonly { variant_unique, base [LalinTree.Expr], },
    ContractWriteonly { variant_unique, base [LalinTree.Expr], },
    ContractInvalidate { variant_unique, base [LalinTree.Expr], },
    ContractPreserve { variant_unique, base [LalinTree.Expr], },
  },
  sum. ContractFact {
    ContractFactBounds {
      variant_unique,
      base [LalinBind.Binding],
      len [LalinBind.Binding],
    },
    ContractFactExprBounds {
      variant_unique,
      base [LalinTree.Expr],
      len [LalinTree.Expr],
    },
    ContractFactWindowBounds {
      variant_unique,
      base [LalinBind.Binding],
      base_len [LalinTree.Expr],
      start [LalinTree.Expr],
      len [LalinTree.Expr],
    },
    ContractFactDisjoint { variant_unique, a [LalinBind.Binding], b [LalinBind.Binding], },
    ContractFactSameLen { variant_unique, a [LalinBind.Binding], b [LalinBind.Binding], },
    ContractFactSoAComponent {
      variant_unique,
      base [LalinBind.Binding],
      record_ty [LalinType.Type],
      field_name [str],
      component_index [number],
    },
    ContractFactNoAlias { variant_unique, base [LalinBind.Binding], },
    ContractFactReadonly { variant_unique, base [LalinBind.Binding], },
    ContractFactWriteonly { variant_unique, base [LalinBind.Binding], },
    ContractFactExprReadonly { variant_unique, base [LalinTree.Expr], },
    ContractFactExprWriteonly { variant_unique, base [LalinTree.Expr], },
    ContractFactInvalidate { variant_unique, base [LalinBind.Binding], },
    ContractFactPreserve { variant_unique, base [LalinBind.Binding], },
    ContractFactRejected { variant_unique, issue [LalinCheck.TypeIssue], },
  },
  product. ContractFactSet { interned, facts [many [LalinTree.ContractFact]], },
  product. EntryControlBlock {
    interned,
    label [LalinTree.BlockLabel],
    params [many [LalinTree.EntryBlockParam]],
    body [many [LalinTree.Stmt]],
  },
  product. ControlBlock {
    interned,
    label [LalinTree.BlockLabel],
    params [many [LalinTree.BlockParam]],
    body [many [LalinTree.Stmt]],
  },
  product. ControlStmtRegion {
    interned,
    region_id [str],
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
  },
  product. ControlExprRegion {
    interned,
    region_id [str],
    result_ty [LalinType.Type],
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
  },
  product. Region {
    interned,
    field. name [str],
    params [many [LalinType.Param]],
    conts [many [LalinTree.RegionCont]],
    contracts [many [LalinTree.FuncContract]],
    entry [LalinTree.EntryControlBlock],
    blocks [many [LalinTree.ControlBlock]],
  },
  sum. ControlFact {
    ControlFactEntryBlock { variant_unique, region_id [str], label [LalinTree.BlockLabel], },
    ControlFactBlock { variant_unique, region_id [str], label [LalinTree.BlockLabel], },
    ControlFactEntryParam {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      index [number],
      field. name [str],
      field. ty [LalinType.Type],
    },
    ControlFactBlockParam {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      index [number],
      field. name [str],
      field. ty [LalinType.Type],
    },
    ControlFactJump {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      to_label [LalinTree.BlockLabel],
    },
    ControlFactJumpArg {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      to_label [LalinTree.BlockLabel],
      field. name [str],
      field. ty [LalinType.Type],
    },
    ControlFactYieldVoid { variant_unique, region_id [str], from_label [LalinTree.BlockLabel], },
    ControlFactYieldValue {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      field. ty [LalinType.Type],
    },
    ControlFactReturn { variant_unique, region_id [str], from_label [LalinTree.BlockLabel], },
    ControlFactBackedge {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      to_label [LalinTree.BlockLabel],
    },
    ControlFactVariantSwitch {
      variant_unique,
      region_id [str],
      from_label [LalinTree.BlockLabel],
      switch_on [str],
      arms [many [LalinTree.ControlVariantArmFact]],
      default_label [LalinTree.BlockLabel],
    },
  },
  product. ControlVariantArmFact {
    interned,
    variant_name [str],
    tag_value [number],
    label [LalinTree.BlockLabel],
    binds [many [LalinTree.BlockParam]],
  },
  product. ControlFactSet { interned, facts [many [LalinTree.ControlFact]], },
  -- ControlRejectReason: typed reasons for irreducible control rejections.
  -- Replaces bare `reason [str]` on ControlRejectIrreducible.
  -- ControlRejectIrreducibleBranch is the terminal catch-all for irreducible
  -- control flow with no further structured reason.
  sum. ControlRejectReason {
    ControlIrreducibleLoop { backedge_blocks [many [LalinTree.BlockLabel]], },
    ControlIrreducibleMultiEntry { header_blocks [many [LalinTree.BlockLabel]], },
    ControlIrreducibleBranch { reason [str], },
  },
  sum. ControlReject {
    ControlRejectDuplicateLabel {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
    },
    ControlRejectMissingLabel { variant_unique, region_id [str], label [LalinTree.BlockLabel], },
    ControlRejectMissingJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    ControlRejectExtraJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    ControlRejectDuplicateJumpArg {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
    },
    ControlRejectJumpType {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
      field. name [str],
      expected [LalinType.Type],
      actual [LalinType.Type],
    },
    ControlRejectYieldOutsideRegion { variant_unique, reason [str], },
    ControlRejectYieldType {
      variant_unique,
      region_id [str],
      expected [LalinType.Type],
      actual [LalinType.Type],
    },
    ControlRejectUnterminatedBlock {
      variant_unique,
      region_id [str],
      label [LalinTree.BlockLabel],
    },
    -- Fixed: reason [str] → reason [LalinTree.ControlRejectReason]
    ControlRejectIrreducible { variant_unique, region_id [str], reason [LalinTree.ControlRejectReason], },
    ControlRejectUnknownVariant { variant_unique, region_id [str], variant_name [str], },
  },
  product. ControlRejectExplanation {
    interned,
    code [str],
    primary [str],
    notes [many [str]],
    suggestions [many [str]],
  },
  sum. ControlDecision {
    ControlDecisionReducible {
      variant_unique,
      region_id [str],
      facts [many [LalinTree.ControlFact]],
    },
    ControlDecisionIrreducible {
      variant_unique,
      region_id [str],
      reject [LalinTree.ControlReject],
    },
  },
  sum. Expr {
    ExprLit { variant_unique, h [LalinTree.ExprHeader], field. value [LalinCore.Literal], },
    ExprRef { variant_unique, h [LalinTree.ExprHeader], field. ref [LalinBind.ValueRef], },
    ExprDot {
      variant_unique,
      h [LalinTree.ExprHeader],
      base [LalinTree.Expr],
      field. name [str],
    },
    ExprUnary {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.UnaryOp],
      field. value [LalinTree.Expr],
    },
    ExprBinary {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.BinaryOp],
      lhs [LalinTree.Expr],
      rhs [LalinTree.Expr],
    },
    ExprCompare {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.CmpOp],
      lhs [LalinTree.Expr],
      rhs [LalinTree.Expr],
    },
    ExprLogic {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.LogicOp],
      lhs [LalinTree.Expr],
      rhs [LalinTree.Expr],
    },
    ExprCast {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.SurfaceCastOp],
      field. ty [LalinType.Type],
      field. value [LalinTree.Expr],
    },
    ExprMachineCast {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.MachineCastOp],
      field. ty [LalinType.Type],
      field. value [LalinTree.Expr],
    },
    ExprIntrinsic {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.Intrinsic],
      args [many [LalinTree.Expr]],
    },
    ExprAddrOf { variant_unique, h [LalinTree.ExprHeader], place [LalinTree.Place], },
    ExprDeref { variant_unique, h [LalinTree.ExprHeader], field. value [LalinTree.Expr], },
    ExprCall {
      variant_unique,
      h [LalinTree.ExprHeader],
      callee [LalinTree.Expr],
      args [many [LalinTree.Expr]],
    },
    ExprLen { variant_unique, h [LalinTree.ExprHeader], field. value [LalinTree.Expr], },
    ExprField {
      variant_unique,
      h [LalinTree.ExprHeader],
      base [LalinTree.Expr],
      field. field [LalinSem.FieldRef],
    },
    ExprIndex {
      variant_unique,
      h [LalinTree.ExprHeader],
      base [LalinTree.IndexBase],
      index [LalinTree.Expr],
    },
    ExprAgg {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. ty [LalinType.Type],
      fields [many [LalinTree.FieldInit]],
    },
    ExprArray {
      variant_unique,
      h [LalinTree.ExprHeader],
      elem_ty [LalinType.Type],
      elems [many [LalinTree.Expr]],
    },
    ExprIf {
      variant_unique,
      h [LalinTree.ExprHeader],
      cond [LalinTree.Expr],
      then_expr [LalinTree.Expr],
      else_expr [LalinTree.Expr],
    },
    ExprSelect {
      variant_unique,
      h [LalinTree.ExprHeader],
      cond [LalinTree.Expr],
      then_expr [LalinTree.Expr],
      else_expr [LalinTree.Expr],
    },
    ExprSwitch {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. value [LalinTree.Expr],
      arms [many [LalinTree.SwitchExprArm]],
      variant_arms [many [LalinTree.SwitchVariantExprArm]],
      default_body [many [LalinTree.Stmt]],
      default_expr [LalinTree.Expr],
    },
    ExprControl {
      variant_unique,
      h [LalinTree.ExprHeader],
      region [LalinTree.ControlExprRegion],
    },
    ExprBlock {
      variant_unique,
      h [LalinTree.ExprHeader],
      stmts [many [LalinTree.Stmt]],
      result [LalinTree.Expr],
    },
    ExprClosure {
      variant_unique,
      h [LalinTree.ExprHeader],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      body [many [LalinTree.Stmt]],
    },
    ExprView { variant_unique, h [LalinTree.ExprHeader], view [LalinTree.View], },
    ExprLoad {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
    },
    ExprAtomicLoad {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
      ordering [LalinCore.AtomicOrdering],
    },
    ExprAtomicRmw {
      variant_unique,
      h [LalinTree.ExprHeader],
      op [LalinCore.AtomicRmwOp],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
      field. value [LalinTree.Expr],
      ordering [LalinCore.AtomicOrdering],
    },
    ExprAtomicCas {
      variant_unique,
      h [LalinTree.ExprHeader],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
      expected [LalinTree.Expr],
      replacement [LalinTree.Expr],
      ordering [LalinCore.AtomicOrdering],
    },
    ExprCtor {
      variant_unique,
      h [LalinTree.ExprHeader],
      type_name [str],
      variant_name [str],
      args [many [LalinTree.Expr]],
    },
    ExprNull { variant_unique, h [LalinTree.ExprHeader], elem [LalinType.Type], },
    ExprSizeOf { variant_unique, h [LalinTree.ExprHeader], field. ty [LalinType.Type], },
    ExprAlignOf { variant_unique, h [LalinTree.ExprHeader], field. ty [LalinType.Type], },
    ExprIsNull { variant_unique, h [LalinTree.ExprHeader], field. value [LalinTree.Expr], },
  },
  sum. Stmt {
    StmtLet {
      variant_unique,
      h [LalinTree.StmtHeader],
      binding [LalinBind.Binding],
      init [LalinTree.Expr],
    },
    StmtVar {
      variant_unique,
      h [LalinTree.StmtHeader],
      binding [LalinBind.Binding],
      init [LalinTree.Expr],
    },
    StmtSet {
      variant_unique,
      h [LalinTree.StmtHeader],
      place [LalinTree.Place],
      field. value [LalinTree.Expr],
    },
    StmtAtomicStore {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. ty [LalinType.Type],
      addr [LalinTree.Expr],
      field. value [LalinTree.Expr],
      ordering [LalinCore.AtomicOrdering],
    },
    StmtAtomicFence {
      variant_unique,
      h [LalinTree.StmtHeader],
      ordering [LalinCore.AtomicOrdering],
    },
    StmtExpr { variant_unique, h [LalinTree.StmtHeader], field. expr [LalinTree.Expr], },
    StmtAssert { variant_unique, h [LalinTree.StmtHeader], cond [LalinTree.Expr], },
    StmtIf {
      variant_unique,
      h [LalinTree.StmtHeader],
      cond [LalinTree.Expr],
      then_body [many [LalinTree.Stmt]],
      else_body [many [LalinTree.Stmt]],
    },
    StmtSwitch {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. value [LalinTree.Expr],
      arms [many [LalinTree.SwitchStmtArm]],
      variant_arms [many [LalinTree.SwitchVariantStmtArm]],
      default_body [many [LalinTree.Stmt]],
    },
    StmtVariantSwitchSource {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. value [LalinTree.Expr],
      arms [many [LalinTree.SwitchStmtArm]],
      variant_arms [many [LalinTree.SwitchVariantSourceStmtArm]],
      default_body [many [LalinTree.Stmt]],
    },
    StmtJump {
      variant_unique,
      h [LalinTree.StmtHeader],
      target [LalinTree.BlockLabel],
      args [many [LalinTree.JumpArg]],
    },
    StmtJumpCont {
      variant_unique,
      h [LalinTree.StmtHeader],
      cont [LalinTree.RegionCont],
      args [many [LalinTree.JumpArg]],
    },
    StmtRegionEmit {
      variant_unique,
      h [LalinTree.StmtHeader],
      invoke_id [str],
      target [LalinTree.RegionInvokeTarget],
      args [many [LalinTree.Expr]],
      wiring [many [LalinTree.RegionContWire]],
    },
    StmtRegionCall {
      variant_unique,
      h [LalinTree.StmtHeader],
      invoke_id [str],
      target [LalinTree.RegionInvokeTarget],
      args [many [LalinTree.Expr]],
      wiring [many [LalinTree.RegionContWire]],
    },
    StmtYieldVoid { variant_unique, h [LalinTree.StmtHeader], },
    StmtYieldValue {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. value [LalinTree.Expr],
    },
    StmtReturnVoid { variant_unique, h [LalinTree.StmtHeader], },
    StmtReturnValue {
      variant_unique,
      h [LalinTree.StmtHeader],
      field. value [LalinTree.Expr],
    },
    StmtControl {
      variant_unique,
      h [LalinTree.StmtHeader],
      region [LalinTree.ControlStmtRegion],
    },
    StmtTrap { variant_unique, h [LalinTree.StmtHeader], },
  },
  sum. Func {
    FuncLocal {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      body [many [LalinTree.Stmt]],
    },
    FuncExport {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      body [many [LalinTree.Stmt]],
    },
    FuncLocalContract {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      contracts [many [LalinTree.FuncContract]],
      body [many [LalinTree.Stmt]],
    },
    FuncExportContract {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
      contracts [many [LalinTree.FuncContract]],
      body [many [LalinTree.Stmt]],
    },
    FuncDecl {
      variant_unique,
      field. name [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
    },
  },
  sum. ExternFunc {
    ExternFunc {
      variant_unique,
      field. name [str],
      symbol [str],
      params [many [LalinType.Param]],
      result [LalinType.Type],
    },
  },
  sum. ConstItem {
    ConstItem {
      variant_unique,
      field. name [str],
      field. ty [LalinType.Type],
      field. value [LalinTree.Expr],
    },
  },
  sum. StaticItem {
    StaticItem {
      variant_unique,
      field. name [str],
      field. ty [LalinType.Type],
      field. value [LalinTree.Expr],
    },
  },
  product. ImportItem { interned, path [LalinCore.Path], },
  sum. TypeDecl {
    TypeDeclStruct { variant_unique, field. name [str], fields [many [LalinType.FieldDecl]], },
    TypeDeclUnion { variant_unique, field. name [str], fields [many [LalinType.FieldDecl]], },
    TypeDeclEnumSugar { variant_unique, field. name [str], variants [many [LalinCore.Name]], },
    TypeDeclTaggedUnionSugar {
      variant_unique,
      field. name [str],
      variants [many [LalinType.VariantDecl]],
    },
    TypeDeclHandle {
      variant_unique,
      field. name [str],
      repr [LalinType.HandleRepr],
      invalid [LalinType.HandleInvalid],
      facts [many [LalinType.HandleFact]],
    },
  },
  sum. Item {
    ItemFunc { variant_unique, func [LalinTree.Func], },
    ItemExtern { variant_unique, func [LalinTree.ExternFunc], },
    ItemConst { variant_unique, c [LalinTree.ConstItem], },
    ItemStatic { variant_unique, s [LalinTree.StaticItem], },
    ItemImport { variant_unique, imp [LalinTree.ImportItem], },
    ItemType { variant_unique, t [LalinTree.TypeDecl], },
    ItemRegion { variant_unique, region [LalinTree.Region], },
    ItemData { variant_unique, data [LalinTree.DataItem], },
  },
  product. DataItem {
    interned,
    field. id [LalinCore.DataId],
    size [number],
    align [number],
    bytes [str],
  },
  sum. ModuleHeader {
    ModuleSurface,
    ModuleTyped { variant_unique, module_name [str], },
    ModuleSem { variant_unique, module_name [str], },
    ModuleCode { variant_unique, module_name [str], },
  },
  product. Module { interned, h [LalinTree.ModuleHeader], items [many [LalinTree.Item]], },
}