-- Data-only schema specification for C text emission.

return {
  key = "c_emission",
  plan = "Phase 1.1-1.4 C emission",
  boundary = "C.Unit -> emitted C text",
  status = "in-progress",

  modules = { "C", "Target", "Types", "Source", "Semantic" },

  leaves = {
    "C.AbiResultSlot.DirectSlot",
    "C.AbiResultSlot.IndirectSlot",
    "C.AbiResultSlot.VoidSlot",
    "C.CallResult.ValueCall",
    "C.CallResult.VoidCall",
    "C.HelperSource.FragmentHelper",
    "C.HelperSource.IntrinsicHelper",
    "C.LabelSource.CodeLabel",
    "C.LabelSource.FragmentLabel",
    "C.LocalSource.CodeLocal",
    "C.LocalSource.CursorLocal",
    "C.LocalSource.FragmentLocal",
    "C.LocalSource.GeneratedLocal",
    "C.LocalSource.MemoryUseLocal",
    "C.Operation.AddressOp",
    "C.Operation.AggregateOp",
    "C.Operation.AliasOp",
    "C.Operation.ArrayOp",
    "C.Operation.AtomicCompareExchangeOp",
    "C.Operation.AtomicFenceOp",
    "C.Operation.AtomicLoadOp",
    "C.Operation.AtomicRmwOp",
    "C.Operation.AtomicStoreOp",
    "C.Operation.BinaryOp",
    "C.Operation.CastOp",
    "C.Operation.ClosureCallOp",
    "C.Operation.ClosureOp",
    "C.Operation.CompareOp",
    "C.Operation.ConstantOp",
    "C.Operation.DirectCallOp",
    "C.Operation.ExternalCallOp",
    "C.Operation.HelperCallOp",
    "C.Operation.IndirectCallOp",
    "C.Operation.IntrinsicOp",
    "C.Operation.LoadOp",
    "C.Operation.PointerOffsetOp",
    "C.Operation.SelectOp",
    "C.Operation.SliceDataOp",
    "C.Operation.SliceLengthOp",
    "C.Operation.SliceMakeOp",
    "C.Operation.StoreOp",
    "C.Operation.UnaryOp",
    "C.Operation.VariantConstructOp",
    "C.Operation.VariantPayloadOp",
    "C.Operation.VariantTagOp",
    "C.Operation.ViewDataOp",
    "C.Operation.ViewLengthOp",
    "C.Operation.ViewMakeOp",
    "C.Operation.ViewStrideOp",
    "C.ParameterSource.CodeParameter",
    "C.ParameterSource.FragmentParameter",
    "C.ParameterSource.GeneratedParameter",
    "C.Place.ByteRangePlace",
    "C.Place.DataPlace",
    "C.Place.DereferencePlace",
    "C.Place.FieldPlace",
    "C.Place.GlobalPlace",
    "C.Place.IndexPlace",
    "C.Place.LocalPlace",
    "C.Terminator.Branch",
    "C.Terminator.Jump",
    "C.Terminator.ReturnValue",
    "C.Terminator.ReturnVoid",
    "C.Terminator.Switch",
    "C.Terminator.Trap",
    "C.Terminator.Unreachable",
    "C.Terminator.VariantSwitch",
    "C.Value.ConstantValue",
    "C.Value.DataValue",
    "C.Value.ExternValue",
    "C.Value.FunctionValue",
    "C.Value.GlobalValue",
    "C.Value.LocalValue",
    "C.Value.ParameterValue",
    "Types.Type.Array",
    "Types.Type.Bool",
    "Types.Type.Closure",
    "Types.Type.Float",
    "Types.Type.Function",
    "Types.Type.Handle",
    "Types.Type.ImportedC",
    "Types.Type.Index",
    "Types.Type.Lease",
    "Types.Type.Owned",
    "Types.Type.Pointer",
    "Types.Type.Qualified",
    "Types.Type.RawPointer",
    "Types.Type.SignedInteger",
    "Types.Type.Slice",
    "Types.Type.Struct",
    "Types.Type.Union",
    "Types.Type.UniqueStruct",
    "Types.Type.UnsignedInteger",
    "Types.Type.View",
    "Types.Type.Void",
  },
  methods = {
    { owner = "Types.Type", method = "emit_c_type_spelling" },
    { owner = "C.Type", method = "emit_c_type" },
    { owner = "C.Signature", method = "emit_c_signature" },
    { owner = "C.Parameter", method = "emit_c_parameter" },
    { owner = "C.FunctionParameter", method = "emit_c_function_parameter" },
    { owner = "C.AbiResultSlot", method = "emit_c_abi_result_slot" },
    { owner = "C.Local", method = "emit_c_local_declaration" },
    { owner = "C.Label", method = "emit_c_label" },
    { owner = "C.Value", method = "emit_c_value" },
    { owner = "C.Place", method = "emit_c_place" },
    { owner = "C.CallResult", method = "emit_c_call_result" },
    { owner = "C.Operation", method = "emit_c_operation" },
    { owner = "C.Terminator", method = "emit_c_terminator" },
    { owner = "C.Statement", method = "emit_c_statement" },
    { owner = "C.Block", method = "emit_c_block" },
    { owner = "C.FunctionDefinition", method = "emit_c_function_definition" },
    { owner = "C.HelperDefinition", method = "emit_c_helper_definition" },
    { owner = "C.Unit", method = "emit_c_unit" },
  },

  implementation_order = {
    "Types.Type:emit_c_type_spelling",
    "C.Type:emit_c_type",
    "C.Signature:emit_c_signature",
    "C.Parameter:emit_c_parameter",
    "C.FunctionParameter:emit_c_function_parameter",
    "C.AbiResultSlot:emit_c_abi_result_slot",
    "C.Local:emit_c_local_declaration",
    "C.Label:emit_c_label",
    "C.Value:emit_c_value",
    "C.Place:emit_c_place",
    "C.CallResult:emit_c_call_result",
    "C.Operation:emit_c_operation",
    "C.Terminator:emit_c_terminator",
    "C.Statement:emit_c_statement",
    "C.Block:emit_c_block",
    "C.FunctionDefinition:emit_c_function_definition",
    "C.HelperDefinition:emit_c_helper_definition",
    "C.Unit:emit_c_unit",
  },

  excluded = {
  },

  fixtures = "next/tests/compiler/fixtures/c_emission/",
  golden = "next/tests/compiler/golden/c_emission/",

  risks = {
    ["view/slice C representation"] = "pin struct spelling before operation emission",
    ["aggregate/closure/variant representation"] = "emit only after layout/representation is pinned, otherwise typed rejection",
    ["sret ABI zipper"] = "hidden sret parameter must be represented by Types.SretResult and C.AbiResultSlot.IndirectSlot",
    ["operation decision table"] = "every C.Operation leaf gets an EMIT or REJECT fixture before green",
  },
}
