-- Data-only schema specification for lowering Code.Module to C.Unit.

return {
  key = "code_to_c_unit",
  plan = "Phase 1.6 Code module to C unit",
  boundary = "Code.Module + Target facts + selected fragments -> C.Unit",
  status = "planned",

  modules = { "Code", "C", "Target", "Types", "CMat", "Diagnostic" },

  leaves = {
    "Code.CallResult.ValueCall",
    "Code.CallResult.VoidCall",
    "Code.Callee.ClosureCallee",
    "Code.Callee.DirectCallee",
    "Code.Callee.ExternalCallee",
    "Code.Callee.IndirectCallee",
    "Code.Constant.SemanticConstant",
    "Code.Constant.UndefinedConstant",
    "Code.DataSource.ConstantData",
    "Code.DataSource.GeneratedData",
    "Code.DataSource.StaticData",
    "Code.DataSource.StringData",
    "Code.GlobalTarget.DataTarget",
    "Code.GlobalTarget.ExternTarget",
    "Code.GlobalTarget.FunctionTarget",
    "Code.GlobalTarget.GlobalTargetValue",
    "Code.Initializer.ConstantInitializer",
    "Code.Initializer.RelocatableInitializer",
    "Code.Initializer.ZeroInitializer",
    "Code.Instruction.AddressOfInstruction",
    "Code.Instruction.AggregateInstruction",
    "Code.Instruction.AliasInstruction",
    "Code.Instruction.ArrayInstruction",
    "Code.Instruction.AtomicCompareExchangeInstruction",
    "Code.Instruction.AtomicFenceInstruction",
    "Code.Instruction.AtomicLoadInstruction",
    "Code.Instruction.AtomicRmwInstruction",
    "Code.Instruction.AtomicStoreInstruction",
    "Code.Instruction.BinaryInstruction",
    "Code.Instruction.CallInstruction",
    "Code.Instruction.CastInstruction",
    "Code.Instruction.ClosureInstruction",
    "Code.Instruction.CompareInstruction",
    "Code.Instruction.ConstantInstruction",
    "Code.Instruction.GlobalReferenceInstruction",
    "Code.Instruction.IntrinsicInstruction",
    "Code.Instruction.LoadInstruction",
    "Code.Instruction.PointerOffsetInstruction",
    "Code.Instruction.SelectInstruction",
    "Code.Instruction.SliceDataInstruction",
    "Code.Instruction.SliceLengthInstruction",
    "Code.Instruction.SliceMakeInstruction",
    "Code.Instruction.StoreInstruction",
    "Code.Instruction.UnaryInstruction",
    "Code.Instruction.VariantConstructorInstruction",
    "Code.Instruction.VariantPayloadInstruction",
    "Code.Instruction.VariantTagInstruction",
    "Code.Instruction.ViewDataInstruction",
    "Code.Instruction.ViewLengthInstruction",
    "Code.Instruction.ViewMakeInstruction",
    "Code.Instruction.ViewStrideInstruction",
    "Code.LocalSource.BindingLocal",
    "Code.LocalSource.ExpressionLocal",
    "Code.LocalSource.GeneratedLocal",
    "Code.ParameterSource.GeneratedParameter",
    "Code.ParameterSource.SemanticParameter",
    "Code.Place.ByteRangePlace",
    "Code.Place.DataPlace",
    "Code.Place.DereferencePlace",
    "Code.Place.FieldPlace",
    "Code.Place.GlobalPlace",
    "Code.Place.IndexPlace",
    "Code.Place.LocalPlace",
    "Code.RelocationSource.DataRelocation",
    "Code.RelocationSource.GlobalRelocation",
    "Code.RelocationTarget.DataRelocationTarget",
    "Code.RelocationTarget.ExternRelocation",
    "Code.RelocationTarget.FunctionRelocation",
    "Code.RelocationTarget.GlobalRelocationTarget",
    "Code.Terminator.Branch",
    "Code.Terminator.Jump",
    "Code.Terminator.ReturnValue",
    "Code.Terminator.ReturnVoid",
    "Code.Terminator.Switch",
    "Code.Terminator.Trap",
    "Code.Terminator.Unreachable",
    "Code.Terminator.VariantSwitch",
    "Code.Value.ConstantValue",
    "Code.Value.LocalValue",
    "Code.Value.ParameterValue",
    "Code.VariantPayload.EmptyPayload",
    "Code.VariantPayload.PayloadValue",
  },

  excluded = {
  },

  fixtures = "next/tests/compiler/fixtures/code_to_c_unit/",
  golden = "next/tests/compiler/golden/code_to_c_unit/",

  risks = {
    ["layout/ABI dependency"] = "Phase 1 fixtures hand-construct Types.Layout and Types.CallableABI until Phase 8 derives them",
    ["fragment overlap"] = "baseline blocks and CMat fragment parts cannot overlap coverage",
    ["relocations"] = "Code.Relocation values are consumed; C must not recreate a duplicate relocation schema",
  },
}
