package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local lalin = require("lalin")
local session = lalin.use { scope = "env" }

local src = [[
return {
    fn. add
        { a [i32], b [i32] }
        [i32]
        {
            ret (a + b),
        },
}
]]

local decls = session:loadstring(src, "compiler_driver_test.lua")()
local decl = lalin.unit("DriverSmoke", decls)

local artifact = decl:emit_c()
assert(artifact.unit)
assert(artifact.kind == "CBackendArtifact")
assert(artifact.unit, "typed emit_c artifact must carry its CBackendUnit")
assert(type(artifact.source) == "string" and artifact.source:match("generated by lalin C backend"))
io.write("lalin compiler_driver ok\n")
