package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local lalin = require("lalin")
local session = lalin.use { scope = "env" }
local asdl = require("lalin.asdl")

local src = [[
return {
    fn. add
        { a [i32], b [i32] }
        [i32]
        {
            ret (a + b),
        },
}
]]

local decls = session:loadstring(src, "compiler_driver_test.lua")()
local decl = lalin.unit("DriverSmoke", decls)

local lowered = decl:lower()
assert(asdl.classof(lowered))
assert(tostring(asdl.classof(lowered)):match("LalinC%.CBackendUnit"))

local artifact = decl:emit_c()
assert(artifact.unit)
assert(artifact.kind == "CBackendArtifact")
assert(tostring(asdl.classof(artifact.unit)):match("LalinC%.CBackendUnit"))
assert(type(artifact.source) == "string" and artifact.source:match("generated by lalin C backend"))
io.write("lalin compiler_driver ok\n")
