package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path
local asdl = require("lalin.asdl")
require("lalin.schema")
require("lalin.impl.stencil_plan")
require("lalin.impl.lower_emit_c.materialize")
local Code = require("lalin.schema.code")
local Stencil = require("lalin.schema.stencil")
local CMat = require("lalin.schema.c_materialize")
local i32 = Code.CodeTyInt(32, Code.CodeSigned)
local compiler = Stencil.StencilCompilerPolicy(Stencil.StencilCompilerGcc, Stencil.StencilOptO3, {})
local schedule = Stencil.StencilScheduleScalar(compiler)
local producer = Stencil.StencilProducer(Stencil.StencilProducerOriginNone, Stencil.StencilProduceRange1D(i32, Stencil.StencilBoundDynamic, Stencil.StencilBoundDynamic, 1, Stencil.StencilProducerForward))
local input = Stencil.StencilAccess("xs", Stencil.StencilAccessRead, i32, Stencil.StencilAccessDirect(Stencil.StencilLayoutContiguous(4)))
local output = Stencil.StencilAccess("out", Stencil.StencilAccessWrite, i32, Stencil.StencilAccessDirect(Stencil.StencilLayoutContiguous(4)))
local stream_id = Stencil.StencilStreamId("x")
local stream = Stencil.StencilStreamDef(stream_id, i32, Stencil.StencilStreamAccess(Stencil.StencilAccessRef("xs"), Stencil.StencilIndexProducer))
local sink = Stencil.StencilSinkDef(Stencil.StencilSinkId("store"), Stencil.StencilSinkOpStore(Stencil.StencilAccessRef("out"), Stencil.StencilIndexProducer, Stencil.StencilStreamRef(stream_id), Stencil.StencilStoreElementwise))
local computation = Stencil.StencilComputation(Stencil.StencilComputationId("map"), producer, { input, output }, { stream }, { sink }, Stencil.StencilFusionLegality({}, {}, {}), schedule, {})
local result = computation:cmat_materialize(CMat.CMatMaterializationInput(CMat.CMatKernelId("map")))
assert(asdl.classof(result) == CMat.CMatMaterializedFused)
assert(#result.kernel.accesses == 2)
assert(result.kernel.accesses[1].const_capability == CMat.CMatConstEligible)
assert(asdl.classof(result.kernel.sinks[1]) == CMat.CMatSinkStoreResult)
io.write("test_cmat_materialize_methods: ok\n")
