-- tests/schema/test_cemit_source.lua
-- Test: CEmitMachine emits valid C source/header from a handcrafted CBackendUnit.
-- Covers scalar add (int32_t add).

package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

require("lalin.schema")
require("lalin.impl.cemit_emit")

local Cemit = require("lalin.schema.cemit")
local C     = require("lalin.schema.c")
local Core  = require("lalin.schema.core")
local Code  = require("lalin.schema.code")
local Graph = require("lalin.schema.graph")
local Lower = require("lalin.schema.lower")

-- ============================================================
-- Build a handcrafted CBackendUnit for: fn add(a: i32, b: i32) -> i32 return a + b
-- ============================================================

-- Types
local i32_ty = C.CBackendScalar(Core.ScalarI32)
assert(C.CBackendQualifiedDataPtr(i32_ty, true, true, false):c_emit_type()
  == "const int32_t* restrict")
assert(C.CBackendQualifiedDataPtr(i32_ty, false, false, true):c_emit_type()
  == "volatile int32_t*")

-- Function signature: (i32, i32) -> i32
local sig_id = C.CBackendFuncSigId("add_sig")
local func_sig = C.CBackendFuncSig(sig_id, {i32_ty, i32_ty}, i32_ty)

-- Function params
local param_a = C.CBackendLocal(
  C.CBackendLocalId("a"),
  C.CBackendName("a"),
  i32_ty
)
local param_b = C.CBackendLocal(
  C.CBackendLocalId("b"),
  C.CBackendName("b"),
  i32_ty
)

-- Local ids
local tmp_id = C.CBackendLocalId("tmp0")

-- Atoms
local atom_a = C.CBackendAtomLocal(C.CBackendLocalId("a"))
local atom_b = C.CBackendAtomLocal(C.CBackendLocalId("b"))
local atom_tmp = C.CBackendAtomLocal(tmp_id)

-- Helper: int binary add on i32
local helper_spec = C.CBackendHelperIntBinary(
  Core.BinAdd,
  i32_ty,
  C.CBackendIntWrap
)
local helper_id = C.CBackendHelperId("ml_i32_add")
local helper_use = C.CBackendHelperUse(helper_id, helper_spec)

-- Statement: tmp0 = ml_i32_add(a, b)
local stmt = C.CBackendHelperCall(
  tmp_id,
  helper_id,
  {atom_a, atom_b}
)

-- Terminator: return tmp0
local term = C.CBackendReturn(atom_tmp)

-- Block: entry block
local entry_label = C.CBackendLabel("entry")
local block = C.CBackendBlock(
  entry_label,
  {},           -- no block params (args are func params)
  {stmt},       -- statements
  term          -- terminator
)

-- Function body: blocks
local body = C.CBackendBodyBlocks(entry_label, {block})

-- Function
local func_name = C.CBackendName("add")
local func = C.CBackendFunc(
  func_name,
  "add",
  Core.VisibilityExport,
  sig_id,
  {param_a, param_b},
  {C.CBackendLocal(tmp_id, C.CBackendName("tmp0"), i32_ty)},
  body
)

-- Target
local target = C.CBackendTarget(
  C.CBackendC99,
  C.CBackendHostedNative,
  64, 64,
  C.CBackendLittleEndian,
  true
)

-- CBackendUnit
local c_unit = C.CBackendUnit(
  "test_cemit",
  target,
  {func_sig},     -- sigs
  {},             -- types
  {},             -- globals
  {},             -- externs
  {helper_use},   -- helpers
  {func}          -- funcs
)

-- ============================================================
-- CEmitMachine
-- ============================================================

-- Create a minimal spine for CEmitMachine
local dummy_module_id = Code.CodeModuleId("test_cemit")
local dummy_origin = Code.CodeOriginUnknown
local dummy_code_module = Code.CodeModule(dummy_module_id, {}, {}, {}, {}, {}, {}, dummy_origin)
local dummy_graph = Graph.CodeGraph(dummy_module_id, {})
local spine = Lower.LowerBackSpine(dummy_code_module, dummy_graph, target)
local machine = Cemit.CEmitMachine(spine, { Cemit.CEmitCSigEntry(sig_id.text, func_sig) }, { func_sig }, {}, {})

-- ============================================================
-- Emit
-- ============================================================

local artifact = machine:emit_module(c_unit)
local source = artifact.source
local header = artifact.header

-- ============================================================
-- Assertions
-- ============================================================

-- Source contains expected patterns
assert(type(source) == "string" and #source > 0, "source must be non-empty string")
assert(source:match("generated by lalin C backend"), "source must have generation header")
assert(source:match("#include <stdint%.h>"), "source must include stdint.h")
assert(source:match("#include <stddef%.h>"), "source must include stddef.h")
assert(source:match("#include <stdbool%.h>"), "source must include stdbool.h")

-- Helper function
assert(source:match("static inline int32_t ml_i32_add"), "must have helper function ml_i32_add")

-- Function signature
assert(source:match("int32_t add%(int32_t a, int32_t b%)"), "must have add function with correct args")

-- Function body
assert(source:match("entry:"), "must have entry label")
assert(source:match("tmp0 = ml_i32_add"), "must have helper call assigning tmp0")
assert(source:match("return tmp0;"), "must have return tmp0")

-- Header contains export
assert(type(header) == "string" and #header > 0, "header must be non-empty string")
assert(header:match("#ifndef TEST_CEMIT_H"), "header must have include guard")
assert(header:match("int32_t add%(int32_t a, int32_t b%);"), "header must have add prototype")

print("source:")
print(source)
print("---")
print("header:")
print(header)
print("---")
print("test_cemit_source: OK")
