package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local T = require("lalin.schema")
local asdl = require("lalin.asdl")
local Code, Core, Effect, Mem = T.LalinCode, T.LalinCore, T.LalinEffect, T.LalinMem
require("lalin.impl.code_mem")
require("lalin.impl.code_effect")

local origin = Code.CodeOriginGenerated("effect leaf test")
local mid, fid, bid = Code.CodeModuleId("m"), Code.CodeFuncId("f"), Code.CodeBlockId("entry")
local sig = Code.CodeSigId("sig")
local i32 = Code.CodeTyInt(32, Code.CodeSigned)
local lid, oid = Code.CodeLocalId("slot"), Mem.MemObjectId("object")
local place = Code.CodePlaceLocal(lid, i32)
local access = Code.CodeMemoryAccess(Code.CodeMemoryReadWrite, i32, 4, Code.CodeMustNotTrap, false, nil)
local term = Code.CodeTerm(Code.CodeTermId("ret"), Code.CodeTermReturn({}), origin)
local block = Code.CodeBlock(bid, "entry", {}, {}, term, origin)
local func = Code.CodeFunc(fid, "f", Code.CodeLinkageLocal, sig, {}, {}, bid, { block }, origin)
local module = Code.CodeModule(mid, {}, {}, {}, {}, {}, { func }, origin)
local aid = Mem.MemAccessId("access:f:entry:load")
local proof = Mem.MemProofBackend(aid, Mem.MemBackendNativeAlignment(4))
local backend = Mem.MemBackendAccessInfo(aid, Mem.MemNonTrapping("safe"), Mem.MemAlignKnown(4), Mem.MemBoundsInObject("safe"), Mem.MemDerefBytesKnown(4), Mem.MemMovementMovable("safe"), { proof })
local projection = Mem.MemAccessProjection({}, { Mem.MemObjectByAccessEntry(aid, oid) }, { Mem.MemBackendByAccessEntry(aid, backend) }, { Mem.MemProofByAccessEntry(aid, proof) })
local functions = Effect.FunctionEffectProjection({ Effect.FunctionEffectEntry(fid, Effect.FunctionEffectPure(Effect.EffectEvidenceDeclared("pure"))) })

local load = Code.CodeInstLoad(Code.CodeValueId("x"), place, access)
local load_inst = Code.CodeInst(Code.CodeInstId("load"), load, origin)
local load_result = load:compute_effect(Effect.EffectInstructionInput(module, func, block, load_inst, projection, functions))
assert(asdl.isa(load_result, Effect.EffectInstructionEffects))
assert(#load_result.effect.effects == 2 and asdl.isa(load_result.effect.effects[1], Effect.EffectRead))

local call = Code.CodeInstCall(nil, Code.CodeCallDirect(fid), sig, {})
local call_inst = Code.CodeInst(Code.CodeInstId("call"), call, origin)
assert(asdl.isa(call:compute_effect(Effect.EffectInstructionInput(module, func, block, call_inst, projection, functions)), Effect.EffectInstructionCall))
local fence = Code.CodeInstAtomicFence(Core.AtomicSeqCst)
local fence_inst = Code.CodeInst(Code.CodeInstId("fence"), fence, origin)
assert(asdl.isa(fence:compute_effect(Effect.EffectInstructionInput(module, func, block, fence_inst, projection, functions)), Effect.EffectInstructionEffects))
local unary = Code.CodeInstUnary(Code.CodeValueId("u"), Core.UnaryNeg, i32, Code.CodeValueId("x"))
local unary_inst = Code.CodeInst(Code.CodeInstId("u"), unary, origin)
assert(unary:compute_effect(Effect.EffectInstructionInput(module, func, block, unary_inst, projection, functions)) == Effect.EffectInstructionNone)

local term_input = Effect.EffectTermInput(func, block, term, Effect.ContractEffectProjection({}))
assert(Code.CodeTermJump(bid, {}):compute_term_effect(term_input) == Effect.EffectTermNone)
assert(Code.CodeTermBranch(Code.CodeValueId("c"), bid, {}, bid, {}):compute_term_effect(term_input) == Effect.EffectTermNone)
assert(Code.CodeTermSwitch(Code.CodeValueId("s"), {}, bid, {}):compute_term_effect(term_input) == Effect.EffectTermNone)
assert(Code.CodeTermVariantSwitch(Code.CodeValueId("t"), {}, bid, {}):compute_term_effect(term_input) == Effect.EffectTermNone)
assert(Code.CodeTermReturn({}):compute_term_effect(term_input) == Effect.EffectTermNone)
assert(asdl.isa(Code.CodeTermTrap("trap"):compute_term_effect(term_input), Effect.EffectTermEffects))
assert(asdl.isa(Code.CodeTermUnreachable("unreachable"):compute_term_effect(term_input), Effect.EffectTermEffects))
print("test_code_effect_instruction_leaves: ok")
