package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local T = require("lalin.schema")
local asdl = require("lalin.asdl")
local Code, Effect = T.LalinCode, T.LalinEffect
require("lalin.impl.code_graph")
require("lalin.impl.code_flow")
require("lalin.impl.code_mem")
require("lalin.impl.code_effect")

local origin = Code.CodeOriginGenerated("effect pipeline test")
local mid, fid, bid = Code.CodeModuleId("m"), Code.CodeFuncId("f"), Code.CodeBlockId("entry")
local sig, i32 = Code.CodeSigId("sig"), Code.CodeTyInt(32, Code.CodeSigned)
local lid = Code.CodeLocalId("slot")
local local_decl = Code.CodeLocal(lid, "slot", i32, Code.CodeResidenceAddressed, origin)
local place = Code.CodePlaceLocal(lid, i32)
local access = Code.CodeMemoryAccess(Code.CodeMemoryRead, i32, 4, Code.CodeMustNotTrap, false, nil)
local inst = Code.CodeInst(Code.CodeInstId("load"), Code.CodeInstLoad(Code.CodeValueId("x"), place, access), origin)
local term = Code.CodeTerm(Code.CodeTermId("ret"), Code.CodeTermReturn({}), origin)
local block = Code.CodeBlock(bid, "entry", {}, { inst }, term, origin)
local func = Code.CodeFunc(fid, "f", Code.CodeLinkageLocal, sig, {}, { local_decl }, bid, { block }, origin)
local module = Code.CodeModule(mid, {}, {}, {}, {}, {}, { func }, origin)
local contracts = Code.CodeContractFactSet(mid, {})
local graph = module:build_graph()
local flow = graph:compute_flow(module)
local mem = graph:compute_mem(module, flow, nil, contracts)
assert(#mem.accesses == 1 and #mem.backend_info == 1)
local analysis = graph:compute_effect_analysis(module, mem, contracts)
assert(asdl.isa(analysis, Effect.EffectAnalysisResult))
assert(#analysis.facts.insts == 1 and #analysis.facts.insts[1].effects >= 2)
assert(#analysis.functions.functions == 1 and asdl.isa(analysis.functions.functions[1].classification, Effect.FunctionEffectful))
assert(graph:compute_effects(module, mem, contracts) == analysis.facts, "interned analysis facts are stable")
print("test_code_effect_pipeline: ok")
