package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local T = require("lalin.schema")
local asdl = require("lalin.asdl")
local C, Ty, B, Sem, Tr, H = T.LalinCore, T.LalinType, T.LalinBind, T.LalinSem, T.LalinTree, T.LalinHost

local i32 = Ty.TScalar(C.ScalarI32)
local binding = B.Binding(C.Id("closure:x"), "x", i32, B.BindingRoleLocalValue)
local closure_binding = Sem.ClosureBinding(binding)
local frame = Sem.ClosureScopeFrame({ closure_binding })
local stack = Sem.ClosureScopeStack({ frame })
local candidate = Sem.ClosureCaptureCandidate(closure_binding)
local captures = Sem.ClosureCaptureSet({ candidate })
local slot = Sem.ClosureCaptureSlot(candidate, 0, 4, 4)
local layout = Sem.ClosureCaptureLayout({ slot }, 4, 4)
local environment = Sem.ClosureEnvironment({ Sem.ClosureEnvironmentEntry(closure_binding, slot) })
local traversal = Sem.ClosureTraversalInput(stack, captures)
local supply = Sem.ClosureNameSupply("demo", "f", 1)
local fresh = Sem.ClosureFreshName("__lalin_closure_demo_f_1", Sem.ClosureNameSupply("demo", "f", 2))
local module = Tr.Module(Tr.ModuleSurface, {})
local module_input = Sem.ClosureModuleInput(H.HostTargetModel(32, 32, H.HostEndianLittle))

assert(asdl.isa(closure_binding, Sem.ClosureBinding))
assert(asdl.isa(stack, Sem.ClosureScopeStack) and #stack.frames == 1)
assert(asdl.isa(captures, Sem.ClosureCaptureSet) and traversal.captures == captures)
assert(asdl.isa(layout, Sem.ClosureCaptureLayout) and layout.size == 4 and layout.align == 4)
assert(asdl.isa(environment, Sem.ClosureEnvironment))
assert(asdl.isa(supply, Sem.ClosureNameSupply) and asdl.isa(fresh, Sem.ClosureFreshName))
assert(asdl.isa(module_input, Sem.ClosureModuleInput) and module_input.target.pointer_bits == 32)
assert(asdl.isa(Sem.ClosureLookupFound(closure_binding), Sem.ClosureLookup))
assert(asdl.isa(Sem.ClosureLookupMissing, Sem.ClosureLookup))
assert(asdl.isa(Sem.ClosureConverted(module), Sem.ClosureConvertResult))
assert(asdl.isa(Sem.ClosureUnchanged(module), Sem.ClosureConvertResult))
assert(asdl.isa(Sem.ClosureUnsupported(module, "nested closure"), Sem.ClosureConvertResult))
assert(Sem.ClosureContext == nil, "broad ClosureContext is forbidden")

local ok = pcall(function() Sem.ClosureCaptureCandidate({ binding = binding }) end)
assert(not ok, "ClosureCaptureCandidate must reject a loose table")
ok = pcall(function() Sem.ClosureTraversalInput({ frames = {} }, captures) end)
assert(not ok, "ClosureTraversalInput must reject a loose scope table")
ok = pcall(function() Sem.ClosureModuleInput(nil) end)
assert(not ok, "ClosureModuleInput requires a typed target")
ok = pcall(function() Sem.ClosureConverted({ h = Tr.ModuleSurface, items = {} }) end)
assert(not ok, "ClosureConverted must reject a loose module table")

print("test_closure_semantic_schema: ok")
