local List = require("terralist")
local Compiler = require("lalin.compiler.schema")

local Source = Compiler.Source
local Types = Compiler.Types
local Semantic = Compiler.Semantic

assert(Source and Compiler.Provenance and Compiler.Target and Types and Semantic)
assert(Compiler.Code and Compiler.Control and Compiler.Memory and Compiler.Effect and Compiler.Ownership)
assert(Compiler.Kernel and Compiler.CMat and Compiler.C)
assert(Compiler.Host and Compiler.Diagnostic)
assert(Compiler.Analysis)

assert(Compiler.CompilerBase == nil)
assert(Compiler.CompilerSourceFact == nil)
assert(Compiler.CompilerResult == nil)
assert(Compiler.CompilerControl == nil)
assert(Source.SemanticOccurrence == nil)
assert(Source.ProgramInput == nil)
assert(Compiler.Code.CodeAccepted == nil)
assert(Compiler.CMat.MaterializedUseSpine == nil)
assert(Compiler.Source.SourceCast == nil)
assert(Compiler.Source.ScalarOperation == nil)
assert(Compiler.Source.ProgramSource == nil)
assert(Compiler.Kernel.Form == nil)
assert(Compiler.Kernel.ResultProtocol == nil)
assert(Compiler.CMat.SinkOperation == nil)
assert(Compiler.CMat.AddressEnvironment == nil)
assert(Compiler.CMat.CoveredBlock == nil)
assert(Compiler.Source.MachineCast == nil)
assert(Compiler.Source.AtomicOrdering == nil)
assert(Compiler.Semantic.ErasureKind == nil)
assert(Compiler.Control.Trip == nil)
assert(Compiler.Memory.StorageKind == nil)
assert(Compiler.CMat.Result == nil)
assert(Compiler.C.CPointerAccess == nil)
assert(Compiler.Source.Axis == nil)
assert(Compiler.Target.Vectorization == nil)
assert(Compiler.Target.PermitMaskedTail == nil)
assert(Compiler.Target.Vectors == nil)
assert(Compiler.Target.MaskedTails == nil)
assert(Compiler.Kernel.VectorSchedule == nil)
assert(Compiler.Kernel.TiledSchedule == nil)
assert(Compiler.Kernel.MaskedTail == nil)
assert(Compiler.CMat.UseIndex == nil)
assert(Compiler.CMat.Address == nil)
assert(Compiler.CMat.CursorKind == nil)
assert(Compiler.CMat.RestrictGroup == nil)
assert(Compiler.CMat.QualificationPair == nil)
assert(Compiler.Semantic.OwnershipSubject == nil)
assert(Compiler.Semantic.OwnershipEvidence == nil)
assert(Compiler.Kernel.ScheduleForm == nil)
assert(Compiler.Kernel.ScheduleTail == nil)
assert(Compiler.CMat.Producer == nil)
assert(Compiler.C.ParameterQualifier == nil)
assert(Compiler.Types.HiddenResult == nil)
assert(Compiler.Kernel.FindResult == nil)
assert(Compiler.Kernel.AllResult == nil)
assert(Compiler.Kernel.AnyResult == nil)
assert(Compiler.Kernel.AllCompareResult == nil)
assert(Compiler.C.ArtifactSymbol == nil)
assert(Compiler.Effect.VolatileEffect == nil)
assert(Compiler.Effect.AtomicEffect == nil)
assert(Compiler.Effect.TrapEffect == nil)
assert(Compiler.Effect.UnknownAccessEffect == nil)
assert(Compiler.Effect.ExternalEffect == nil)
assert(Compiler.Source.DeclaredEffect == nil)
assert(Compiler.Source.Reducer == nil)
assert(Compiler.Semantic.CallableReducer == nil)
assert(Compiler.Control.DeclaredAssociativity == nil)
assert(Compiler.Control.NoIdentity == nil)
assert(Compiler.Kernel.Binding == nil)
assert(Compiler.Kernel.WindowLane == nil)
assert(Compiler.Kernel.Equivalence == nil)
assert(Compiler.Target.Tail == nil)
assert(Compiler.C.AbiParameter == nil)
assert(Compiler.CMat.StreamBasis == nil)
assert(Compiler.CMat.SinkBasis == nil)
assert(Compiler.CMat.SinkAccess == nil)
assert(Compiler.Host.SymbolAbiMismatch == nil)
assert(Compiler.Diagnostic.FastMathConflictsExactFloat == nil)
assert(Compiler.Source.NamedReducer == nil)
assert(Compiler.Source.BuiltinReducerUse == nil)
assert(Compiler.Control.LoopAlgebra == nil)
assert(Compiler.Kernel.ScalarResult == nil)
assert(Compiler.Kernel.StoredResult == nil)
assert(Compiler.Kernel.ScanResult == nil)
assert(Compiler.CMat.AccessInput == nil)
assert(Compiler.Kernel.ExactEquivalence == nil)
assert(Compiler.Kernel.ReassociationEquivalence == nil)
assert(Compiler.Source.ImportedFunctionPointerType == nil)
assert(Compiler.Types.ImportedFunctionPointer == nil)
assert(Compiler.Semantic.MachineCastExpression == nil)
assert(Compiler.Source.YieldVoidStatement == nil)
assert(Compiler.Source.YieldValueStatement == nil)
assert(Compiler.Semantic.YieldVoid == nil)
assert(Compiler.Semantic.YieldValue == nil)
assert(Compiler.Semantic.StringReference == nil)
assert(Compiler.C.FunctionPart == nil)
assert(Compiler.C.Relocation == nil)
assert(Compiler.C.RelocationSource == nil)
assert(Compiler.C.RelocationTarget == nil)
assert(Compiler.Diagnostic.MissingAbiResultSlot == nil)
assert(Compiler.Memory.Relation == nil)
assert(Compiler.Control.Recurrence == nil)
assert(Compiler.Control.ClosedForm == nil)
assert(Compiler.C.Initializer == nil)
assert(Compiler.C.GlobalDefinition == nil)
assert(Compiler.CMat.Basis == nil)
assert(Compiler.Diagnostic.OverlappingFunctionParts == nil)

local file = Source.File(Source.Path("@schema-test.lln"), "")
local range = Source.Range(Source.ByteOffset(0), Source.ByteLength(0))
local origin = Source.Written(file, range)

assert(Source.Name("x") == Source.Name("x"))
assert(Source.File(Source.Path("@schema-test.lln"), "") == file)

local i32_form = Source.SignedIntegerType(32, origin)
local i32 = Types.SignedInteger(32)
assert(Source.TypeForm:isclassof(i32_form))
assert(Types.Type:isclassof(i32))
assert(Types.SignedInteger(32) == i32)
assert(Source.SignedIntegerType(32, origin) ~= i32_form)

local generation = Compiler.Provenance.Generation("schema-test")
local header = Source.DeclarationHeader(
  Source.QualifiedName(List { Source.Name("Pair") }),
  Source.ExportVisibility(),
  origin)
local pair_source = Source.StructDeclaration(header, List())
local source_program = Source.DocumentProgram(
  file,
  List { pair_source },
  generation)
local pair = Semantic.Struct(pair_source, List())
local semantic_program = Semantic.Program(source_program, List { pair }, generation)

assert(Source.Program:isclassof(source_program))
assert(Semantic.Program:isclassof(semantic_program))
assert(pair.source == pair_source)

local source_binding = Source.Binding(Source.Name("x"), origin)
local semantic_binding = Semantic.Binding(source_binding, i32, Semantic.Immutable())
assert(Semantic.Binding(source_binding, i32, Semantic.Immutable()) == semantic_binding)
local source_use = Source.ValueUse(
  Source.QualifiedName(List { Source.Name("x") }),
  origin)
local source_expression = Source.ValueReference(source_use, origin)
local semantic_expression = Semantic.BindingExpression(
  semantic_binding,
  Semantic.Copy(),
  source_expression,
  i32)

assert(Semantic.Expression:isclassof(semantic_expression))
assert(semantic_expression.source == source_expression)
assert(semantic_expression.type == i32)
assert(semantic_expression.binding == semantic_binding)

assert(type(Compiler.Code.FunctionDefinition.__fields) == "table")
assert(type(Compiler.Control.Graph.__fields) == "table")
assert(type(Compiler.Memory.Model.__fields) == "table")
assert(type(Compiler.Kernel.Kernel.__fields) == "table")
assert(type(Compiler.CMat.MemoryUse.__fields) == "table")
assert(type(Compiler.CMat.CursorRealization.__fields) == "table")
assert(type(Compiler.C.Unit.__fields) == "table")
assert(Compiler.Source.BinaryOperator:isclassof(Source.IntegerDivide()))
assert(Compiler.Source.WindowBoundary:isclassof(Source.ClampBoundary()))
assert(Compiler.Diagnostic.CheckError.members ~= nil)
assert(Compiler.Diagnostic.LayoutError.members ~= nil)
assert(Compiler.Diagnostic.AbiError.members ~= nil)

for name in pairs(Compiler.definitions) do
  assert(not name:match("%.A%d%d"), name)
  assert(not name:match("%.B%d%d"), name)
  assert(not name:match("%.F%d%d"), name)
  assert(not name:match("Site$"), name)
  assert(not name:match("Facet"), name)
  assert(not name:match("Spine"), name)
  assert(not name:match("Population"), name)
  assert(not name:match("Contribution"), name)
  assert(not name:match("Finalization"), name)
end

print("compiler ASDL schema: ok")
