package.path = "tests/?.lua;./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path
require("lalin.schema_v2")
local asdl = require("lalin.asdl")
local Schedule = require("lalin.schema_v2.schedule")
local Kernel = require("lalin.schema_v2.kernel")
local Graph = require("lalin.schema_v2.graph")
local Flow = require("lalin.schema_v2.flow")
local Code = require("lalin.schema_v2.code")
local Mem = require("lalin.schema_v2.mem")
local Backend = require("lalin.schema_v2.backend")
require("lalin.impl.kernel_plan")
require("lalin.impl.schedule_plan")

local loop = Graph.GraphLoopId("loop:schedule")
local trip = Kernel.KernelTripKnown(Flow.FlowTripCountExact(require("lalin.schema_v2.code").CodeValueId("trip"), nil, nil))
local body = Kernel.KernelBody(Kernel.KernelDomainFlow(Flow.FlowDomainLoop(loop), trip, nil), {}, {}, {}, Kernel.KernelResultVoid, Kernel.KernelEquivalenceProof({}))
local plan = Kernel.KernelPlanned(Kernel.KernelId("kernel:schedule"), Kernel.KernelSubjectLoop(loop), body)
local vector_reject = Schedule.ScheduleRejectTarget("vector emitter unavailable")
local vector = Schedule.ScheduleVector(Schedule.LaneVector(require("lalin.schema_v2.code").CodeTyIndex, 4), 1, 1, Schedule.TailScalar)
local candidates = {
  Schedule.ScheduleVectorCandidate(vector, Schedule.ScheduleEmitterRejected(Schedule.ScheduleEmitterVector(require("lalin.schema_v2.stencil").StencilVectorFeatureSSE2), { vector_reject })),
  Schedule.ScheduleScalarCandidate(Schedule.ScheduleScalarIndex, Schedule.ScheduleEmitterExecutable(Schedule.ScheduleEmitterScalar, "scalar", { Schedule.ScheduleProofTarget("scalar") })),
}
local selection = Schedule.SchedulePlanInput(plan, candidates):select_kernel_schedule()
assert(asdl.classof(selection) == Schedule.ScheduleSelectionPlanned)
assert(selection.form == Schedule.ScheduleScalarIndex)
assert(selection.rejected_alternatives[1] == vector_reject, "fallback must preserve vector rejection evidence")
assert(asdl.classof(selection.capability) == Schedule.ScheduleEmitterExecutable)
local scheduled = selection:to_kernel_schedule(plan)
assert(asdl.classof(scheduled) == Schedule.SchedulePlanned)
local all_rejected = Schedule.SchedulePlanInput(plan, { Schedule.ScheduleScalarCandidate(Schedule.ScheduleScalarIndex, Schedule.ScheduleEmitterRejected(Schedule.ScheduleEmitterScalar, { vector_reject })) }):select_kernel_schedule()
assert(asdl.classof(all_rejected) == Schedule.ScheduleSelectionNoPlan and all_rejected.rejects[1] == vector_reject)

local lane = Kernel.KernelLane(Kernel.KernelLaneId("lane"), Mem.MemObjectId("object"), {}, Mem.MemBaseValue(Code.CodeValueId("base")), Code.CodeTyInt(32, Code.CodeSigned), Mem.MemAccessContiguous, {})
local vector_body = Kernel.KernelBody(Kernel.KernelDomainFlow(Flow.FlowDomainLoop(loop), trip, nil), { lane }, {}, {}, Kernel.KernelResultVoid, Kernel.KernelEquivalenceProof({}))
local vector_plan = Kernel.KernelPlanned(Kernel.KernelId("kernel:vector_target"), Kernel.KernelSubjectLoop(loop), vector_body)
local vec = Backend.BackVec(Backend.BackI32, 4)
local target = Backend.BackTargetModel(Backend.BackTargetNative, { Backend.BackTargetSupportsShape(Backend.BackShapeVec(vec)), Backend.BackTargetPrefersUnroll(Backend.BackShapeVec(vec), 2, 1, Backend.TargetHeuristicUserOverride) })
local target_projection = target:project_schedule_target()
assert(#target_projection.contributions == 2 and asdl.classof(target_projection.contributions[1]) == Schedule.ScheduleTargetVectorShape)
local production = vector_plan:schedule_eligibility():schedule_contribution(target)
assert(asdl.classof(production) == Schedule.SchedulePlanned and production.form == Schedule.ScheduleScalarIndex)
assert(#production.rejected_alternatives == 1, "production scalar fallback must retain vector capability rejection")
local kernel_reject = Kernel.KernelRejectNoFacts(Kernel.KernelSubjectLoop(loop), "kernel rejected")
local rejected_schedule = Kernel.KernelNoPlan(Kernel.KernelSubjectLoop(loop), { kernel_reject }):schedule_eligibility():schedule_contribution(target)
assert(asdl.classof(rejected_schedule) == Schedule.ScheduleKernelRejected and rejected_schedule.rejects[1] == kernel_reject)
print("test_schedule_capability_leaves: ok")
