package.path = "tests/?.lua;./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path
require("lalin.schema_v2")
local asdl = require("lalin.asdl")
local Code = require("lalin.schema_v2.code")
local Graph = require("lalin.schema_v2.graph")
local Flow = require("lalin.schema_v2.flow")
local Value = require("lalin.schema_v2.value")
local Kernel = require("lalin.schema_v2.kernel")
local Schedule = require("lalin.schema_v2.schedule")
local Lower = require("lalin.schema_v2.lower")
require("lalin.impl.kernel_plan")
require("lalin.impl.schedule_plan")
require("lalin.impl.lower_plan")

local loop = Graph.GraphLoopId("loop:lower")
local kernel_id = Kernel.KernelId("kernel:lower")
local trip = Kernel.KernelTripKnown(Flow.FlowTripCountExact(Code.CodeValueId("trip"), nil, nil))
local body = Kernel.KernelBody(Kernel.KernelDomainFlow(Flow.FlowDomainLoop(loop), trip, Kernel.KernelCounterAbsent), Kernel.KernelLaneProjection({}), Kernel.KernelBindingProjection({}), Kernel.KernelEffectProjection({}), Kernel.KernelResultVoid, Kernel.KernelEquivalenceProof({}))
local plan = Kernel.KernelPlanned(kernel_id, Kernel.KernelSubjectLoop(loop), body)
local schedule = Schedule.SchedulePlanned(Schedule.ScheduleId("schedule:lower"), kernel_id, Schedule.ScheduleScalarIndex, {}, {})
local schedules = Schedule.ScheduleModulePlan(Code.CodeModuleId("m"), Schedule.ScheduleTarget(require("lalin.schema_v2.backend").BackTargetModel(require("lalin.schema_v2.backend").BackTargetNative, {})), { schedule })
local projection = schedules:lower_schedule_projection()
assert(asdl.classof(projection:lookup(kernel_id)) == Lower.LowerScheduleByKernelFound)
assert(asdl.classof(projection:lookup(Kernel.KernelId("missing"))) == Lower.LowerScheduleByKernelMissing)
local kernel_projection = Kernel.KernelModulePlan(Code.CodeModuleId("m"), Flow.FlowFactSet(Code.CodeModuleId("m"), {}, {}, {}, {}, {}, {}, {}, {}, {}, {}), Value.ValueFactSet(Code.CodeModuleId("m"), {}, {}, {}), require("lalin.schema_v2.mem").MemSemanticFactSet(Code.CodeModuleId("m"), {}, {}, {}, {}, {}, {}, {}, {}, {}, {}), require("lalin.schema_v2.effect").EffectFactSet(Code.CodeModuleId("m"), {}, {}, {}), { plan }):lower_kernel_projection()
local candidate = kernel_projection:lookup(loop):lower_fragment_candidate(projection)
assert(asdl.classof(candidate) == Lower.LowerFragmentKernelCandidate)
assert(candidate.kernel == plan and candidate.schedule == schedule)
print("test_lower_schedule_projection: ok")
