package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path
local asdl = require("lalin.asdl")
require("lalin.schema_v2")
require("lalin.impl.stencil_plan")
require("lalin.impl.stencil_metastencil")
local Core = require("lalin.schema_v2.core")
local Code = require("lalin.schema_v2.code")
local Stencil = require("lalin.schema_v2.stencil")
local Descriptor = require("lalin.schema_v2.stencil_descriptor")
local i32 = Code.CodeTyInt(32, Code.CodeSigned)
local compiler = Stencil.StencilCompilerPolicy(Stencil.StencilCompilerGcc, Stencil.StencilOptO2, Stencil.StencilMachineNative, {})
local schedule = Stencil.StencilScheduleScalar(compiler)
local producer = Stencil.StencilProducer(nil, Stencil.StencilProduceRange1D(i32, nil, nil, 1, Stencil.StencilProducerForward))
local access = Stencil.StencilAccess("out", Stencil.StencilAccessWrite, i32, Stencil.StencilAccessDirect(Stencil.StencilLayoutContiguous(4)))
local legality = Stencil.StencilFusionLegality({}, {}, {})
local spine = Descriptor.StencilDescriptorSpine(Stencil.StencilMetastencilId("d"), producer, { access }, {}, legality, {}, Descriptor.StencilDescriptorScheduled(schedule))
local sink = Stencil.StencilSinkDef(Stencil.StencilSinkId("store"), Stencil.StencilSinkOpStore(Stencil.StencilAccessRef("out"), Stencil.StencilStreamRef(Stencil.StencilStreamId("x")), Stencil.StencilStoreElementwise))
local descriptor = Descriptor.StencilDescriptorStore(spine, sink, Descriptor.StencilDescriptorStoreResult(Stencil.StencilAccessRef("out")))
local projected = descriptor:stencil_project_computation()
assert(asdl.classof(projected) == Descriptor.StencilDescriptorProjected)
local unscheduled_spine = Descriptor.StencilDescriptorSpine(Stencil.StencilMetastencilId("u"), producer, { access }, {}, legality, {}, Descriptor.StencilDescriptorExplicitlyUnscheduled("schedule pending"))
local rejected = Descriptor.StencilDescriptorStore(unscheduled_spine, sink, Descriptor.StencilDescriptorStoreResult(Stencil.StencilAccessRef("out"))):stencil_project_computation()
assert(asdl.classof(rejected) == Descriptor.StencilDescriptorProjectionRejected)
io.write("test_stencil_descriptor_alternatives: ok\n")
