return {
    runtime = {
        boxes = "streamed-mesh",
        rounded_boxes = false,
        capsules = false,
        clipping = "scissor",
        transforms = false,
        scrolling = true,
        layers = "canvas",
        cursors = false,
        density = "love-logical-and-pixel-sampled",
    },
    paint = {
        line = false,
        polyline = false,
        polygon_fill = false,
        circle_fill = false,
        arc = false,
        bezier = false,
        mesh = "dynamic-love-mesh",
        image = "numeric-resource-handle",
        shader = "numeric-resource-handle",
        stroke_width = false,
    },
    text = {
        measure = "love-font",
        draw = "retained-love-text",
        hit_test = false,
        ranges = false,
        ime = false,
        clipboard = false,
        shaping = "love-font",
    },
    host = {
        windows = "single-love-window",
        multi_window = false,
        events = "bounded-cps-driver-drain",
        authoritative_window_sampling = true,
        text_input_rect = false,
        clipboard = false,
        timers = "love-timer",
        metrics = "cdef-driver-facet",
        hidpi = "logical-pixel-dpi-reconciliation",
    },
}

