package.path = "./?.lua;./?/init.lua;./lua/?.lua;./lua/?/init.lua;" .. package.path

local lalin = require("lalin")

local function shell_quote(s)
    s = tostring(s)
    return "'" .. s:gsub("'", "'\\''") .. "'"
end

local function command_ok(cmd)
    local ok = os.execute(cmd)
    return ok == true or ok == 0
end

local function write_file(path, text)
    local f = assert(io.open(path, "wb"))
    f:write(text)
    f:close()
end

local src = [=[
fn zip_add(dst [ptr [i32]], lhs [ptr [i32]], rhs [ptr [i32]], n [index]) [void] do
  requires bounds(dst)(n), writeonly(dst), bounds(lhs)(n), readonly(lhs), bounds(rhs)(n), readonly(rhs)
  requires disjoint(dst)(lhs), disjoint(dst)(rhs), disjoint(lhs)(rhs)
  loop i in 0 .. n do
    dst[i] = lhs[i] + rhs[i]
  end
end
]=]

local parsed = assert(lalin.loadstring(src, "@test_emit_c_semantic_loop.lln"))
local dir = "target/test_emit_c_semantic_loop"
local artifact = lalin.emit_c(parsed, {
    name = "emit_c_semantic_loop",
    c_path = dir .. "/zip_add.c",
    h_path = dir .. "/zip_add.h",
})

assert(artifact.kind == "CBackendArtifact", "emit_c should use the semantic C backend")
assert(artifact.c_unit ~= nil, "semantic C artifact should expose its CBackendUnit")
assert(artifact.source:match("generated by lalin C backend"), "source should come from c_emit")
assert(artifact.source:match("void zip_add%("), "residual function should be emitted as C")
assert(not artifact.source:match("generated by lalin LuaJIT"), "emit_c must not use the old LuaJIT C emitter")
assert(not artifact.source:match("__lalin_luajit_stencil_symbols"), "emit_c must not route through a LuaJIT stencil symbol table")
assert(not artifact.source:match("LuaTrace"), "emit_c must not emit BC artifacts")

if command_ok("command -v gcc >/dev/null 2>&1") then
    write_file(dir .. "/main.c", [[
#include <stdint.h>
#include <stddef.h>
#include "zip_add.h"

int main(void) {
    int32_t lhs[5] = { 1, -2, 5, 0, 3 };
    int32_t rhs[5] = { 10, 20, -5, 7, 4 };
    int32_t dst[5] = { 0, 0, 0, 0, 0 };
    zip_add(dst, lhs, rhs, 5);
    return dst[0] == 11 && dst[1] == 18 && dst[2] == 0 && dst[3] == 7 && dst[4] == 7 ? 0 : 1;
}
]])
    assert(command_ok("gcc -std=c99 -O3 " .. shell_quote(dir .. "/zip_add.c") .. " " .. shell_quote(dir .. "/main.c") .. " -o " .. shell_quote(dir .. "/zip_add_test")), "gcc should compile emitted semantic C artifact")
    assert(command_ok(shell_quote(dir .. "/zip_add_test")), "emitted semantic C artifact should run correctly")
end

io.write("lalin emit_c semantic loop ok\n")
