local S = require("lalin.schema.dsl")
S.use()

return schema. LalinBackend {
  sum. BackScalar {
    BackVoid,
    BackBool,
    BackI8,
    BackI16,
    BackI32,
    BackI64,
    BackU8,
    BackU16,
    BackU32,
    BackU64,
    BackF32,
    BackF64,
    BackPtr,
    BackIndex,
  },
  product. BackSigId { interned, text [str], },
  product. BackFuncId { interned, text [str], },
  product. BackExternId { interned, text [str], },
  product. BackDataId { interned, text [str], },
  product. BackBlockId { interned, text [str], },
  product. BackValId { interned, text [str], },
  product. BackStackSlotId { interned, text [str], },
  product. BackSwitchCase { interned, raw [str], dest [LalinBackend.BackBlockId], },
  product. BackVec { interned, elem [LalinBackend.BackScalar], lanes [number], },
  sum. BackShape {
    BackShapeScalar { variant_unique, scalar [LalinBackend.BackScalar], },
    BackShapeVec { variant_unique, vec [LalinBackend.BackVec], },
  },
  sum. BackTarget {
    BackTargetNative,
    BackTargetDynasmJit,
    BackTargetNamed { variant_unique, field. name [str], },
  },
  sum. BackEndian { BackEndianLittle, BackEndianBig, },
  sum. BackTargetFeature {
    BackFeatureSSE2,
    BackFeatureAVX2,
    BackFeatureAVX512F,
    BackFeatureFMA,
    BackFeaturePOPCNT,
    BackFeatureBMI1,
    BackFeatureBMI2,
    BackFeatureUnknown { variant_unique, field. name [str], },
  },
  sum. TargetHeuristicReason {
    TargetHeuristicLoopSize { instruction_count [number] },
    TargetHeuristicCachePressure { estimated_bytes [number] },
    TargetHeuristicVectorizationBenefit { lanes [number] },
    TargetHeuristicUserOverride,
  },
  sum. BackTargetFact {
    BackTargetPointerBits { variant_unique, bits [number], },
    BackTargetIndexBits { variant_unique, bits [number], },
    BackTargetEndian { variant_unique, endian [LalinBackend.BackEndian], },
    BackTargetCacheLineBytes { variant_unique, bytes [number], },
    BackTargetFeature { variant_unique, feature [LalinBackend.BackTargetFeature], },
    BackTargetSupportsShape { variant_unique, shape [LalinBackend.BackShape], },
    BackTargetSupportsVectorOp { variant_unique, vec [LalinBackend.BackVec], op_class [str], },
    BackTargetSupportsMaskedTail,
    BackTargetPrefersUnroll {
      variant_unique,
      shape [LalinBackend.BackShape],
      unroll [number],
      rank [number],
      reason [LalinBackend.TargetHeuristicReason],
    },
  },
  product. BackTargetModel {
    interned,
    target [LalinBackend.BackTarget],
    facts [many [LalinBackend.BackTargetFact]],
  },
  sum. BackAddressBase {
    BackAddrValue { variant_unique, field. value [LalinBackend.BackValId], },
    BackAddrStack { variant_unique, slot [LalinBackend.BackStackSlotId], },
    BackAddrData { variant_unique, data [LalinBackend.BackDataId], },
  },
  sum. BackPointerProvenance {
    BackProvUnknown,
    BackProvStack { variant_unique, slot [LalinBackend.BackStackSlotId], },
    BackProvData { variant_unique, data [LalinBackend.BackDataId], },
    BackProvArg { variant_unique, field. name [str], },
    BackProvView { variant_unique, field. name [str], },
    BackProvDerived { variant_unique, reason [str], },
  },
  sum. BackPointerBounds {
    BackPtrBoundsUnknown,
    BackPtrInBounds { variant_unique, reason [str], },
    BackPtrMayLeaveObject { variant_unique, reason [str], },
  },
  product. BackAddress {
    interned,
    base [LalinBackend.BackAddressBase],
    byte_offset [LalinBackend.BackValId],
    provenance [LalinBackend.BackPointerProvenance],
    formation_bounds [LalinBackend.BackPointerBounds],
  },
  product. BackAccessId { interned, text [str], },
  sum. BackAlignment {
    BackAlignUnknown,
    BackAlignKnown { variant_unique, bytes [number], },
    BackAlignAtLeast { variant_unique, bytes [number], },
    BackAlignAssumed { variant_unique, bytes [number], reason [str], },
  },
  sum. BackDereference {
    BackDerefUnknown,
    BackDerefBytes { variant_unique, bytes [number], reason [str], },
    BackDerefAssumed { variant_unique, bytes [number], reason [str], },
  },
  sum. BackTrap {
    BackMayTrap,
    BackNonTrapping { variant_unique, reason [str], },
    BackChecked { variant_unique, reason [str], },
  },
  sum. BackMotion { BackMayNotMove, BackCanMove { variant_unique, reason [str], }, },
  sum. BackAccessEffect { BackAccessRead, BackAccessWrite, BackAccessReadWrite, BackAccessReadonly, },
  sum. BackAtomicOrdering { BackAtomicSeqCst, },
  sum. BackAtomicRmwOp {
    BackAtomicRmwAdd,
    BackAtomicRmwSub,
    BackAtomicRmwAnd,
    BackAtomicRmwOr,
    BackAtomicRmwXor,
    BackAtomicRmwXchg,
  },
  product. BackMemoryInfo {
    interned,
    access [LalinBackend.BackAccessId],
    alignment [LalinBackend.BackAlignment],
    dereference [LalinBackend.BackDereference],
    trap [LalinBackend.BackTrap],
    motion [LalinBackend.BackMotion],
    effect [LalinBackend.BackAccessEffect],
  },
  sum. BackIntOverflow {
    BackIntWrap,
    BackIntNoSignedWrap { variant_unique, reason [str], },
    BackIntNoUnsignedWrap { variant_unique, reason [str], },
    BackIntNoWrap { variant_unique, reason [str], },
  },
  sum. BackIntExact { BackIntMayLose, BackIntExact { variant_unique, reason [str], }, },
  product. BackIntSemantics {
    interned,
    overflow [LalinBackend.BackIntOverflow],
    exact [LalinBackend.BackIntExact],
  },
  sum. BackIntOp {
    BackIntAdd,
    BackIntSub,
    BackIntMul,
    BackIntSDiv,
    BackIntUDiv,
    BackIntSRem,
    BackIntURem,
  },
  sum. BackBitOp { BackBitAnd, BackBitOr, BackBitXor, },
  sum. BackShiftOp { BackShiftLeft, BackShiftLogicalRight, BackShiftArithmeticRight, },
  sum. BackRotateOp { BackRotateLeft, BackRotateRight, },
  sum. BackFloatSemantics {
    BackFloatStrict,
    BackFloatReassoc { variant_unique, reason [str], },
    BackFloatFastMath { variant_unique, reason [str], },
  },
  sum. BackFloatOp { BackFloatAdd, BackFloatSub, BackFloatMul, BackFloatDiv, },
  sum. BackLiteral {
    BackLitInt { variant_unique, raw [str], },
    BackLitFloat { variant_unique, raw [str], },
    BackLitBool { variant_unique, field. value [bool], },
    BackLitNull,
  },
  sum. BackUnaryOp { BackUnaryIneg, BackUnaryFneg, BackUnaryBnot, BackUnaryBoolNot, },
  sum. BackIntrinsicOp {
    BackIntrinsicPopcount,
    BackIntrinsicClz,
    BackIntrinsicCtz,
    BackIntrinsicBswap,
    BackIntrinsicSqrt,
    BackIntrinsicAbs,
    BackIntrinsicFloor,
    BackIntrinsicCeil,
    BackIntrinsicTruncFloat,
    BackIntrinsicRound,
  },
  sum. BackCompareOp {
    BackIcmpEq,
    BackIcmpNe,
    BackSIcmpLt,
    BackSIcmpLe,
    BackSIcmpGt,
    BackSIcmpGe,
    BackUIcmpLt,
    BackUIcmpLe,
    BackUIcmpGt,
    BackUIcmpGe,
    BackFCmpEq,
    BackFCmpNe,
    BackFCmpLt,
    BackFCmpLe,
    BackFCmpGt,
    BackFCmpGe,
  },
  sum. BackVecCompareOp {
    BackVecIcmpEq,
    BackVecIcmpNe,
    BackVecSIcmpLt,
    BackVecSIcmpLe,
    BackVecSIcmpGt,
    BackVecSIcmpGe,
    BackVecUIcmpLt,
    BackVecUIcmpLe,
    BackVecUIcmpGt,
    BackVecUIcmpGe,
  },
  sum. BackVecBinaryOp {
    BackVecIntAdd,
    BackVecIntSub,
    BackVecIntMul,
    BackVecBitAnd,
    BackVecBitOr,
    BackVecBitXor,
  },
  sum. BackVecMaskOp { BackVecMaskNot, BackVecMaskAnd, BackVecMaskOr, },
  sum. BackCastOp {
    BackBitcast,
    BackIreduce,
    BackSextend,
    BackUextend,
    BackFpromote,
    BackFdemote,
    BackSToF,
    BackUToF,
    BackFToS,
    BackFToU,
  },
  sum. BackCallTarget {
    BackCallDirect { variant_unique, func [LalinBackend.BackFuncId], },
    BackCallExtern { variant_unique, func [LalinBackend.BackExternId], },
    BackCallIndirect { variant_unique, callee [LalinBackend.BackValId], },
  },
  sum. BackCallResult {
    BackCallStmt,
    BackCallValue {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackScalar],
    },
  },
  sum. Cmd {
    CmdCreateSig {
      variant_unique,
      sig [LalinBackend.BackSigId],
      params [many [LalinBackend.BackScalar]],
      results [many [LalinBackend.BackScalar]],
    },
    CmdDeclareData {
      variant_unique,
      data [LalinBackend.BackDataId],
      size [number],
      align [number],
    },
    CmdDataInitZero {
      variant_unique,
      data [LalinBackend.BackDataId],
      offset [number],
      size [number],
    },
    CmdDataInit {
      variant_unique,
      data [LalinBackend.BackDataId],
      offset [number],
      field. ty [LalinBackend.BackScalar],
      field. value [LalinBackend.BackLiteral],
    },
    CmdDataAddr { variant_unique, dst [LalinBackend.BackValId], data [LalinBackend.BackDataId], },
    CmdFuncAddr { variant_unique, dst [LalinBackend.BackValId], func [LalinBackend.BackFuncId], },
    CmdExternAddr {
      variant_unique,
      dst [LalinBackend.BackValId],
      func [LalinBackend.BackExternId],
    },
    CmdDeclareFunc {
      variant_unique,
      visibility [LalinCore.Visibility],
      func [LalinBackend.BackFuncId],
      sig [LalinBackend.BackSigId],
    },
    CmdDeclareExtern {
      variant_unique,
      func [LalinBackend.BackExternId],
      symbol [str],
      sig [LalinBackend.BackSigId],
    },
    CmdBeginFunc { variant_unique, func [LalinBackend.BackFuncId], },
    CmdCreateBlock { variant_unique, block [LalinBackend.BackBlockId], },
    CmdSwitchToBlock { variant_unique, block [LalinBackend.BackBlockId], },
    CmdSealBlock { variant_unique, block [LalinBackend.BackBlockId], },
    CmdBindEntryParams {
      variant_unique,
      block [LalinBackend.BackBlockId],
      values [many [LalinBackend.BackValId]],
    },
    CmdAppendBlockParam {
      variant_unique,
      block [LalinBackend.BackBlockId],
      field. value [LalinBackend.BackValId],
      field. ty [LalinBackend.BackShape],
    },
    CmdCreateStackSlot {
      variant_unique,
      slot [LalinBackend.BackStackSlotId],
      size [number],
      align [number],
    },
    CmdAlias { variant_unique, dst [LalinBackend.BackValId], src [LalinBackend.BackValId], },
    CmdStackAddr {
      variant_unique,
      dst [LalinBackend.BackValId],
      slot [LalinBackend.BackStackSlotId],
    },
    CmdConst {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackScalar],
      field. value [LalinBackend.BackLiteral],
    },
    CmdUnary {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackUnaryOp],
      field. ty [LalinBackend.BackShape],
      field. value [LalinBackend.BackValId],
    },
    CmdIntrinsic {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackIntrinsicOp],
      field. ty [LalinBackend.BackShape],
      args [many [LalinBackend.BackValId]],
    },
    CmdCompare {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackCompareOp],
      field. ty [LalinBackend.BackShape],
      lhs [LalinBackend.BackValId],
      rhs [LalinBackend.BackValId],
    },
    CmdCast {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackCastOp],
      field. ty [LalinBackend.BackScalar],
      field. value [LalinBackend.BackValId],
    },
    CmdPtrOffset {
      variant_unique,
      dst [LalinBackend.BackValId],
      base [LalinBackend.BackAddressBase],
      index [LalinBackend.BackValId],
      elem_size [number],
      const_offset [number],
      provenance [LalinBackend.BackPointerProvenance],
      bounds [LalinBackend.BackPointerBounds],
    },
    CmdLoadInfo {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackShape],
      addr [LalinBackend.BackAddress],
      memory [LalinBackend.BackMemoryInfo],
    },
    CmdStoreInfo {
      variant_unique,
      field. ty [LalinBackend.BackShape],
      addr [LalinBackend.BackAddress],
      field. value [LalinBackend.BackValId],
      memory [LalinBackend.BackMemoryInfo],
    },
    CmdAtomicLoad {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackScalar],
      addr [LalinBackend.BackAddress],
      memory [LalinBackend.BackMemoryInfo],
      ordering [LalinBackend.BackAtomicOrdering],
    },
    CmdAtomicStore {
      variant_unique,
      field. ty [LalinBackend.BackScalar],
      addr [LalinBackend.BackAddress],
      field. value [LalinBackend.BackValId],
      memory [LalinBackend.BackMemoryInfo],
      ordering [LalinBackend.BackAtomicOrdering],
    },
    CmdAtomicRmw {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackAtomicRmwOp],
      field. ty [LalinBackend.BackScalar],
      addr [LalinBackend.BackAddress],
      field. value [LalinBackend.BackValId],
      memory [LalinBackend.BackMemoryInfo],
      ordering [LalinBackend.BackAtomicOrdering],
    },
    CmdAtomicCas {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackScalar],
      addr [LalinBackend.BackAddress],
      expected [LalinBackend.BackValId],
      replacement [LalinBackend.BackValId],
      memory [LalinBackend.BackMemoryInfo],
      ordering [LalinBackend.BackAtomicOrdering],
    },
    CmdAtomicFence { variant_unique, ordering [LalinBackend.BackAtomicOrdering], },
    CmdIntBinary {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackIntOp],
      scalar [LalinBackend.BackScalar],
      semantics [LalinBackend.BackIntSemantics],
      lhs [LalinBackend.BackValId],
      rhs [LalinBackend.BackValId],
    },
    CmdBitBinary {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackBitOp],
      scalar [LalinBackend.BackScalar],
      lhs [LalinBackend.BackValId],
      rhs [LalinBackend.BackValId],
    },
    CmdBitNot {
      variant_unique,
      dst [LalinBackend.BackValId],
      scalar [LalinBackend.BackScalar],
      field. value [LalinBackend.BackValId],
    },
    CmdShift {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackShiftOp],
      scalar [LalinBackend.BackScalar],
      lhs [LalinBackend.BackValId],
      rhs [LalinBackend.BackValId],
    },
    CmdRotate {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackRotateOp],
      scalar [LalinBackend.BackScalar],
      lhs [LalinBackend.BackValId],
      rhs [LalinBackend.BackValId],
    },
    CmdFloatBinary {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackFloatOp],
      scalar [LalinBackend.BackScalar],
      semantics [LalinBackend.BackFloatSemantics],
      lhs [LalinBackend.BackValId],
      rhs [LalinBackend.BackValId],
    },
    CmdMemcpy {
      variant_unique,
      dst [LalinBackend.BackValId],
      src [LalinBackend.BackValId],
      len [LalinBackend.BackValId],
    },
    CmdMemset {
      variant_unique,
      dst [LalinBackend.BackValId],
      byte [LalinBackend.BackValId],
      len [LalinBackend.BackValId],
    },
    CmdMemcmp {
      variant_unique,
      dst [LalinBackend.BackValId],
      left [LalinBackend.BackValId],
      right [LalinBackend.BackValId],
      len [LalinBackend.BackValId],
    },
    CmdSelect {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackShape],
      cond [LalinBackend.BackValId],
      then_value [LalinBackend.BackValId],
      else_value [LalinBackend.BackValId],
    },
    CmdFma {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackScalar],
      semantics [LalinBackend.BackFloatSemantics],
      a [LalinBackend.BackValId],
      b [LalinBackend.BackValId],
      c [LalinBackend.BackValId],
    },
    CmdVecSplat {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackVec],
      field. value [LalinBackend.BackValId],
    },
    CmdVecBinary {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackVecBinaryOp],
      field. ty [LalinBackend.BackVec],
      lhs [LalinBackend.BackValId],
      rhs [LalinBackend.BackValId],
    },
    CmdVecCompare {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackVecCompareOp],
      field. ty [LalinBackend.BackVec],
      lhs [LalinBackend.BackValId],
      rhs [LalinBackend.BackValId],
    },
    CmdVecSelect {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackVec],
      mask [LalinBackend.BackValId],
      then_value [LalinBackend.BackValId],
      else_value [LalinBackend.BackValId],
    },
    CmdVecMask {
      variant_unique,
      dst [LalinBackend.BackValId],
      op [LalinBackend.BackVecMaskOp],
      field. ty [LalinBackend.BackVec],
      args [many [LalinBackend.BackValId]],
    },
    CmdVecInsertLane {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackVec],
      field. value [LalinBackend.BackValId],
      lane_value [LalinBackend.BackValId],
      lane [number],
    },
    CmdVecExtractLane {
      variant_unique,
      dst [LalinBackend.BackValId],
      field. ty [LalinBackend.BackScalar],
      field. value [LalinBackend.BackValId],
      lane [number],
    },
    CmdCall {
      variant_unique,
      result [LalinBackend.BackCallResult],
      target [LalinBackend.BackCallTarget],
      sig [LalinBackend.BackSigId],
      args [many [LalinBackend.BackValId]],
    },
    CmdJump {
      variant_unique,
      dest [LalinBackend.BackBlockId],
      args [many [LalinBackend.BackValId]],
    },
    CmdBrIf {
      variant_unique,
      cond [LalinBackend.BackValId],
      then_block [LalinBackend.BackBlockId],
      then_args [many [LalinBackend.BackValId]],
      else_block [LalinBackend.BackBlockId],
      else_args [many [LalinBackend.BackValId]],
    },
    CmdSwitchInt {
      variant_unique,
      field. value [LalinBackend.BackValId],
      field. ty [LalinBackend.BackScalar],
      cases [many [LalinBackend.BackSwitchCase]],
      default_dest [LalinBackend.BackBlockId],
    },
    CmdReturnVoid,
    CmdReturnValue { variant_unique, field. value [LalinBackend.BackValId], },
    CmdTrap,
    CmdFinishFunc { variant_unique, func [LalinBackend.BackFuncId], },
    CmdFinalizeModule,
  },
  sum. BackShapeRequirement {
    BackShapeRequiresScalar,
    BackShapeRequiresVector,
    BackShapeAllowsScalarOrVector,
  },
  sum. BackProgramFact {
    BackFactCreateSig { variant_unique, index [number], sig [LalinBackend.BackSigId], },
    BackFactSigRef { variant_unique, index [number], sig [LalinBackend.BackSigId], },
    BackFactDeclareData { variant_unique, index [number], data [LalinBackend.BackDataId], },
    BackFactDataRef { variant_unique, index [number], data [LalinBackend.BackDataId], },
    BackFactDeclareFunc { variant_unique, index [number], func [LalinBackend.BackFuncId], },
    BackFactFuncRef { variant_unique, index [number], func [LalinBackend.BackFuncId], },
    BackFactDeclareExtern { variant_unique, index [number], func [LalinBackend.BackExternId], },
    BackFactExternRef { variant_unique, index [number], func [LalinBackend.BackExternId], },
    BackFactBeginFunc { variant_unique, index [number], func [LalinBackend.BackFuncId], },
    BackFactFinishFunc { variant_unique, index [number], func [LalinBackend.BackFuncId], },
    BackFactFinalizeModule { variant_unique, index [number], },
    BackFactCreateBlock { variant_unique, index [number], block [LalinBackend.BackBlockId], },
    BackFactBlockRef { variant_unique, index [number], block [LalinBackend.BackBlockId], },
    BackFactStackSlotDef { variant_unique, index [number], slot [LalinBackend.BackStackSlotId], },
    BackFactStackSlotRef { variant_unique, index [number], slot [LalinBackend.BackStackSlotId], },
    BackFactValueDef { variant_unique, index [number], field. value [LalinBackend.BackValId], },
    BackFactValueUse { variant_unique, index [number], field. value [LalinBackend.BackValId], },
    BackFactAccessDef { variant_unique, index [number], access [LalinBackend.BackAccessId], },
    BackFactAccessRef { variant_unique, index [number], access [LalinBackend.BackAccessId], },
    BackFactShapeUse {
      variant_unique,
      index [number],
      shape [LalinBackend.BackShape],
      requirement [LalinBackend.BackShapeRequirement],
    },
    BackFactFunctionBodyCommand { variant_unique, index [number], },
  },
  sum. BackValidationIssue {
    BackIssueEmptyProgram,
    BackIssueMissingFinalize,
    BackIssueCommandAfterFinalize { variant_unique, index [number], },
    BackIssueCommandOutsideFunction { variant_unique, index [number], },
    BackIssueNestedFunction {
      variant_unique,
      index [number],
      active [LalinBackend.BackFuncId],
      field. next [LalinBackend.BackFuncId],
    },
    BackIssueFinishWithoutBegin { variant_unique, index [number], func [LalinBackend.BackFuncId], },
    BackIssueFinishWrongFunction {
      variant_unique,
      index [number],
      expected [LalinBackend.BackFuncId],
      actual [LalinBackend.BackFuncId],
    },
    BackIssueUnfinishedFunction { variant_unique, func [LalinBackend.BackFuncId], },
    BackIssueDuplicateSig { variant_unique, index [number], sig [LalinBackend.BackSigId], },
    BackIssueDuplicateData { variant_unique, index [number], data [LalinBackend.BackDataId], },
    BackIssueDuplicateFunc { variant_unique, index [number], func [LalinBackend.BackFuncId], },
    BackIssueDuplicateExtern { variant_unique, index [number], func [LalinBackend.BackExternId], },
    BackIssueDuplicateBlock { variant_unique, index [number], block [LalinBackend.BackBlockId], },
    BackIssueDuplicateStackSlot {
      variant_unique,
      index [number],
      slot [LalinBackend.BackStackSlotId],
    },
    BackIssueDuplicateValue {
      variant_unique,
      index [number],
      field. value [LalinBackend.BackValId],
    },
    BackIssueMissingSig { variant_unique, index [number], sig [LalinBackend.BackSigId], },
    BackIssueMissingData { variant_unique, index [number], data [LalinBackend.BackDataId], },
    BackIssueMissingFunc { variant_unique, index [number], func [LalinBackend.BackFuncId], },
    BackIssueMissingExtern { variant_unique, index [number], func [LalinBackend.BackExternId], },
    BackIssueMissingBlock { variant_unique, index [number], block [LalinBackend.BackBlockId], },
    BackIssueMissingStackSlot {
      variant_unique,
      index [number],
      slot [LalinBackend.BackStackSlotId],
    },
    BackIssueMissingValue {
      variant_unique,
      index [number],
      field. value [LalinBackend.BackValId],
    },
    BackIssueDuplicateAccess {
      variant_unique,
      index [number],
      access [LalinBackend.BackAccessId],
    },
    BackIssueMissingAccess { variant_unique, index [number], access [LalinBackend.BackAccessId], },
    BackIssueInvalidAlignment { variant_unique, index [number], bytes [number], },
    BackIssueLoadAccessEffect { variant_unique, index [number], effect [LalinBackend.BackAccessEffect], },
    BackIssueStoreAccessEffect {
      variant_unique,
      index [number],
      effect [LalinBackend.BackAccessEffect],
    },
    BackIssueDereferenceTooSmall {
      variant_unique,
      index [number],
      dereference_bytes [number],
      access_bytes [number],
    },
    BackIssueIntScalarExpected {
      variant_unique,
      index [number],
      scalar [LalinBackend.BackScalar],
    },
    BackIssueFloatScalarExpected {
      variant_unique,
      index [number],
      scalar [LalinBackend.BackScalar],
    },
    BackIssueBitScalarExpected {
      variant_unique,
      index [number],
      scalar [LalinBackend.BackScalar],
    },
    BackIssueShiftScalarExpected {
      variant_unique,
      index [number],
      scalar [LalinBackend.BackScalar],
    },
    BackIssueNonTrappingWithoutDereference { variant_unique, index [number], },
    BackIssueCanMoveWithoutNonTrapping { variant_unique, index [number], },
    BackIssueShapeRequiresScalar {
      variant_unique,
      index [number],
      shape [LalinBackend.BackShape],
    },
    BackIssueShapeRequiresVector {
      variant_unique,
      index [number],
      shape [LalinBackend.BackShape],
    },
  },
  product. BackValidationReport { interned, issues [many [LalinBackend.BackValidationIssue]], },
  product. BackCommandCount { interned, command_kind [str], count [number], },
  product. BackMemoryInspection {
    interned,
    index [number],
    access [LalinBackend.BackAccessId],
    alignment [LalinBackend.BackAlignment],
    dereference [LalinBackend.BackDereference],
    trap [LalinBackend.BackTrap],
    motion [LalinBackend.BackMotion],
    effect [LalinBackend.BackAccessEffect],
  },
  product. BackAddressInspection { interned, index [number], address [LalinBackend.BackAddress], },
  product. BackPointerOffsetInspection {
    interned,
    index [number],
    dst [LalinBackend.BackValId],
    base [LalinBackend.BackAddressBase],
    index_value [LalinBackend.BackValId],
    elem_size [number],
    const_offset [number],
    provenance [LalinBackend.BackPointerProvenance],
    bounds [LalinBackend.BackPointerBounds],
  },
  product. BackIntSemanticsInspection {
    interned,
    index [number],
    dst [LalinBackend.BackValId],
    op [LalinBackend.BackIntOp],
    scalar [LalinBackend.BackScalar],
    semantics [LalinBackend.BackIntSemantics],
  },
  sum. BackFloatSemanticOp {
    BackFloatSemanticBinary { variant_unique, op [LalinBackend.BackFloatOp], },
    BackFloatSemanticFma,
  },
  product. BackFloatSemanticsInspection {
    interned,
    index [number],
    dst [LalinBackend.BackValId],
    op [LalinBackend.BackFloatSemanticOp],
    scalar [LalinBackend.BackScalar],
    semantics [LalinBackend.BackFloatSemantics],
  },
  product. BackInspectionReport {
    interned,
    command_counts [many [LalinBackend.BackCommandCount]],
    memory [many [LalinBackend.BackMemoryInspection]],
    addresses [many [LalinBackend.BackAddressInspection]],
    pointer_offsets [many [LalinBackend.BackPointerOffsetInspection]],
    int_semantics [many [LalinBackend.BackIntSemanticsInspection]],
    float_semantics [many [LalinBackend.BackFloatSemanticsInspection]],
  },
  product. BackDisasmInspection { interned, func [LalinBackend.BackFuncId], text [str], },
  product. BackDiagnosticsReport {
    interned,
    inspection [LalinBackend.BackInspectionReport],
    disassembly [many [LalinBackend.BackDisasmInspection]],
  },
  product. BackSigSpec {
    interned,
    params [many [LalinBackend.BackScalar]],
    results [many [LalinBackend.BackScalar]],
  },
  product. BackStackSlotSpec { interned, size [number], align [number], },
  product. BackProgram { interned, cmds [many [LalinBackend.Cmd]], },
  product. BackCommandTape { interned, version [number], command_count [number], payload [str], },
}
