local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonBind {
  sum. BindingClass {
    BindingClassLocalValue,
    BindingClassLocalCell,
    BindingClassArg { variant_unique, index [number], },
    BindingClassBlockParam { variant_unique, region_id [str], block_name [str], index [number], },
    BindingClassEntryBlockParam {
      variant_unique,
      region_id [str],
      block_name [str],
      index [number],
    },
    BindingClassContParam { variant_unique, region_id [str], cont_name [str], index [number], },
    BindingClassGlobalFunc { variant_unique, module_name [str], item_name [str], },
    BindingClassGlobalConst { variant_unique, module_name [str], item_name [str], },
    BindingClassGlobalStatic { variant_unique, module_name [str], item_name [str], },
    BindingClassExtern { variant_unique, symbol [str], },
    BindingClassOpenParam { variant_unique, param [ty. MoonOpen.OpenParam], },
    BindingClassImport { variant_unique, import [ty. MoonOpen.ValueImport], },
    BindingClassOpenSym { variant_unique, sym [ty. MoonCore.OpenSym], },
    BindingClassOpenSlot { variant_unique, slot [ty. MoonOpen.Slot], },
  },
  product. Binding {
    interned,
    field. id [ty. MoonCore.Id],
    field. name [str],
    field. ty [ty. MoonType.Type],
    class [ty. MoonBind.BindingClass],
  },
  sum. Residence { ResidenceUnknown, ResidenceValue, ResidenceStack, ResidenceCell, },
  sum. ResidenceReason {
    ResidenceBecauseDefault,
    ResidenceBecauseAddressTaken,
    ResidenceBecauseMutableCell,
    ResidenceBecauseNonScalarAbi,
    ResidenceBecauseMaterializedTemporary,
    ResidenceBecauseBackendRequired,
  },
  sum. ResidenceFact {
    ResidenceFactBinding { variant_unique, binding [ty. MoonBind.Binding], },
    ResidenceFactAddressTaken { variant_unique, binding [ty. MoonBind.Binding], },
    ResidenceFactMutableCell { variant_unique, binding [ty. MoonBind.Binding], },
    ResidenceFactNonScalarAbi { variant_unique, binding [ty. MoonBind.Binding], },
    ResidenceFactMaterializedTemporary { variant_unique, binding [ty. MoonBind.Binding], },
    ResidenceFactBackendRequired { variant_unique, binding [ty. MoonBind.Binding], },
  },
  product. ResidenceFactSet { interned, facts [many [ty. MoonBind.ResidenceFact]], },
  product. ResidenceDecision {
    interned,
    binding [ty. MoonBind.Binding],
    residence [ty. MoonBind.Residence],
    reason [ty. MoonBind.ResidenceReason],
  },
  product. ResidencePlan { interned, decisions [many [ty. MoonBind.ResidenceDecision]], },
  product. MachineBinding {
    interned,
    binding [ty. MoonBind.Binding],
    residence [ty. MoonBind.Residence],
  },
  product. MachineBindingSet { interned, bindings [many [ty. MoonBind.MachineBinding]], },
  sum. ValueRef {
    ValueRefName { variant_unique, field. name [str], },
    ValueRefPath { variant_unique, path [ty. MoonCore.Path], },
    ValueRefBinding { variant_unique, binding [ty. MoonBind.Binding], },
    ValueRefHole { variant_unique, slot [ty. MoonOpen.Slot], },
  },
  product. ValueEntry { interned, field. name [str], binding [ty. MoonBind.Binding], },
  product. TypeEntry { interned, field. name [str], field. ty [ty. MoonType.Type], },
  product. Env {
    interned,
    module_name [str],
    values [many [ty. MoonBind.ValueEntry]],
    types [many [ty. MoonBind.TypeEntry]],
    layouts [many [ty. MoonSem.TypeLayout]],
  },
  product. ConstEntry {
    interned,
    module_name [str],
    item_name [str],
    field. ty [ty. MoonType.Type],
    field. value [ty. MoonTree.Expr],
  },
  product. ConstEnv { interned, entries [many [ty. MoonBind.ConstEntry]], },
  sum. StmtEnvEffect {
    StmtEnvNoBinding,
    StmtEnvAddBinding { variant_unique, entry [ty. MoonBind.ValueEntry], },
    StmtEnvAddBindings { variant_unique, entries [many [ty. MoonBind.ValueEntry]], },
  },
}
