local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonC {
  product. CTypeId { interned, module_name [str], spelling [str], },
  sum. CTypeKind {
    CVoid,
    CScalar { variant_unique, scalar [ty "MoonBack.BackScalar"], },
    CPointer { variant_unique, pointee [ty "MoonC.CTypeId"], },
    CEnum { variant_unique, scalar [ty "MoonBack.BackScalar"], },
    CArray { variant_unique, elem [ty "MoonC.CTypeId"], count [number], },
    CStruct,
    CUnion,
    COpaque,
    CFuncPtr { variant_unique, sig [ty "MoonC.CFuncSigId"], },
  },
  product. CTypeFact {
    interned,
    field "id" [ty "MoonC.CTypeId"],
    kind [ty "MoonC.CTypeKind"],
    complete [bool],
    size [optional [number]],
    align [optional [number]],
  },
  product. CFieldLayout {
    interned,
    owner [ty "MoonC.CTypeId"],
    field "name" [str],
    field "type" [ty "MoonC.CTypeId"],
    offset [number],
    size [number],
    align [number],
    bit_offset [optional [number]],
    bit_width [optional [number]],
  },
  product. CLayoutFact {
    interned,
    field "type" [ty "MoonC.CTypeId"],
    size [number],
    align [number],
    fields [many [ty "MoonC.CFieldLayout"]],
  },
  product. CFuncSigId { interned, text [str], },
  product. CFuncSig {
    interned,
    field "id" [ty "MoonC.CFuncSigId"],
    params [many [ty "MoonC.CTypeId"]],
    result [ty "MoonC.CTypeId"],
  },
  product. CExternFunc {
    interned,
    moon_name [str],
    symbol [str],
    sig [ty "MoonC.CFuncSigId"],
    library [optional [str]],
  },
  product. CLibrary {
    interned,
    field "name" [str],
    link_name [optional [str]],
    path [optional [str]],
    symbols [many [str]],
  },
  product. CBackendName { interned, text [str], },
  product. CBackendLabel { interned, text [str], },
  product. CBackendLocalId { interned, text [str], },
  product. CBackendGlobalId { interned, text [str], },
  product. CBackendHelperId { interned, text [str], },
  product. CBackendFuncSigId { interned, text [str], },
  sum. CBackendDialect { CBackendC99, CBackendC11, CBackendGnuC, CBackendClangC, },
  sum. CBackendPlatform {
    CBackendHostedNative,
    CBackendFreestanding,
    CBackendWasmCapable,
    CBackendEmbedded,
  },
  sum. CBackendEndian { CBackendLittleEndian, CBackendBigEndian, },
  product. CBackendTarget {
    interned,
    dialect [ty "MoonC.CBackendDialect"],
    platform [ty "MoonC.CBackendPlatform"],
    pointer_bits [number],
    index_bits [number],
    endian [ty "MoonC.CBackendEndian"],
    hosted [bool],
  },
  sum. CBackendType {
    CBackendVoid,
    CBackendBool8,
    CBackendScalar { variant_unique, scalar [ty "MoonCore.Scalar"], },
    CBackendIndex,
    CBackendDataPtr { variant_unique, pointee [optional [ty "MoonC.CBackendType"]], },
    CBackendCodePtr { variant_unique, sig [ty "MoonC.CBackendFuncSigId"], },
    CBackendNamed { variant_unique, field "id" [ty "MoonC.CTypeId"], },
    CBackendArray { variant_unique, elem [ty "MoonC.CBackendType"], count [number], },
    CBackendSliceDescriptor { variant_unique, elem [ty "MoonC.CBackendType"], },
    CBackendViewDescriptor { variant_unique, elem [ty "MoonC.CBackendType"], },
    CBackendClosureDescriptor {
      variant_unique,
      sig [ty "MoonC.CBackendFuncSigId"],
      ctx [optional [ty "MoonC.CBackendType"]],
    },
    CBackendAbiHiddenOutPtr { variant_unique, result [ty "MoonC.CBackendType"], },
    CBackendImportedCodePtr { variant_unique, sig [ty "MoonC.CFuncSigId"], },
    CBackendVector { variant_unique, elem [ty "MoonC.CBackendType"], lanes [number], },
  },
  product. CBackendParam {
    interned,
    field "name" [ty "MoonC.CBackendName"],
    field "ty" [ty "MoonC.CBackendType"],
  },
  sum. CBackendFuncLinkage {
    CBackendLinkInternal,
    CBackendLinkExport,
    CBackendLinkExtern,
    CBackendLinkDecl,
    CBackendLinkWrapper,
    CBackendLinkIndirect,
  },
  sum. CBackendAbiParamRole {
    CBackendAbiParamDirect,
    CBackendAbiParamByAddress,
    CBackendAbiParamDescriptor,
    CBackendAbiParamHiddenOut,
  },
  sum. CBackendAbiResultRole {
    CBackendAbiResultVoid,
    CBackendAbiResultDirect,
    CBackendAbiResultByAddress,
    CBackendAbiResultHiddenOut,
    CBackendAbiResultDescriptor,
  },
  product. CBackendAbiParam {
    interned,
    field "name" [ty "MoonC.CBackendName"],
    source_ty [ty "MoonC.CBackendType"],
    lowered_ty [ty "MoonC.CBackendType"],
    role [ty "MoonC.CBackendAbiParamRole"],
  },
  product. CBackendAbiResult {
    interned,
    source_ty [ty "MoonC.CBackendType"],
    lowered_ty [ty "MoonC.CBackendType"],
    role [ty "MoonC.CBackendAbiResultRole"],
  },
  product. CBackendFuncAbi {
    interned,
    field "id" [ty "MoonC.CBackendFuncSigId"],
    linkage [ty "MoonC.CBackendFuncLinkage"],
    params [many [ty "MoonC.CBackendAbiParam"]],
    result [ty "MoonC.CBackendAbiResult"],
    imported_sig [optional [ty "MoonC.CFuncSigId"]],
  },
  product. CBackendFuncSig {
    interned,
    field "id" [ty "MoonC.CBackendFuncSigId"],
    params [many [ty "MoonC.CBackendType"]],
    result [ty "MoonC.CBackendType"],
  },
  product. CBackendField {
    interned,
    field "name" [ty "MoonC.CBackendName"],
    field "ty" [ty "MoonC.CBackendType"],
    offset [optional [number]],
    size [optional [number]],
    align [optional [number]],
  },
  sum. CBackendTypeDecl {
    CBackendTypedef {
      variant_unique,
      field "id" [ty "MoonC.CTypeId"],
      field "ty" [ty "MoonC.CBackendType"],
    },
    CBackendStructDecl {
      variant_unique,
      field "id" [ty "MoonC.CTypeId"],
      fields [many [ty "MoonC.CBackendField"]],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendUnionDecl {
      variant_unique,
      field "id" [ty "MoonC.CTypeId"],
      fields [many [ty "MoonC.CBackendField"]],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendOpaqueDecl { variant_unique, field "id" [ty "MoonC.CTypeId"], },
  },
  sum. CBackendResidence {
    CBackendResidenceValue,
    CBackendResidenceAddressed,
    CBackendResidenceAggregate,
    CBackendResidenceDescriptor,
  },
  sum. CBackendLocalInitState {
    CBackendLocalUninitialized,
    CBackendLocalZeroInitialized,
    CBackendLocalInitialized,
  },
  sum. CBackendPlace {
    CBackendPlaceLocal {
      variant_unique,
      field "local" [ty "MoonC.CBackendLocalId"],
      field "ty" [ty "MoonC.CBackendType"],
    },
    CBackendPlaceGlobal {
      variant_unique,
      global [ty "MoonC.CBackendGlobalId"],
      field "ty" [ty "MoonC.CBackendType"],
    },
    CBackendPlaceDeref {
      variant_unique,
      addr [ty "MoonC.CBackendAtom"],
      field "ty" [ty "MoonC.CBackendType"],
      align [optional [number]],
    },
    CBackendPlaceField {
      variant_unique,
      base [ty "MoonC.CBackendPlace"],
      field "field" [ty "MoonC.CBackendName"],
      field "ty" [ty "MoonC.CBackendType"],
      offset [number],
      size [optional [number]],
      align [optional [number]],
    },
    CBackendPlaceIndex {
      variant_unique,
      base [ty "MoonC.CBackendPlace"],
      index [ty "MoonC.CBackendAtom"],
      field "ty" [ty "MoonC.CBackendType"],
      elem_size [number],
    },
    CBackendPlaceBytes {
      variant_unique,
      base [ty "MoonC.CBackendAtom"],
      offset [number],
      field "ty" [ty "MoonC.CBackendType"],
      size [number],
      align [number],
    },
  },
  product. CBackendLocalStorage {
    interned,
    field "id" [ty "MoonC.CBackendLocalId"],
    field "name" [ty "MoonC.CBackendName"],
    field "ty" [ty "MoonC.CBackendType"],
    residence [ty "MoonC.CBackendResidence"],
    init_state [ty "MoonC.CBackendLocalInitState"],
    address_taken [bool],
  },
  sum. CBackendRelocTarget {
    CBackendRelocGlobal { variant_unique, global [ty "MoonC.CBackendGlobalId"], },
    CBackendRelocFunc { variant_unique, func [ty "MoonC.CBackendName"], },
    CBackendRelocExtern { variant_unique, extern [ty "MoonC.CBackendName"], },
  },
  sum. CBackendDataInit {
    CBackendDataZero { variant_unique, offset [number], size [number], },
    CBackendDataBytes { variant_unique, offset [number], bytes [str], },
    CBackendDataScalar {
      variant_unique,
      offset [number],
      field "ty" [ty "MoonC.CBackendType"],
      literal [ty "MoonCore.Literal"],
    },
    CBackendDataReloc {
      variant_unique,
      offset [number],
      target [ty "MoonC.CBackendRelocTarget"],
      addend [number],
    },
  },
  product. CBackendGlobal {
    interned,
    field "id" [ty "MoonC.CBackendGlobalId"],
    field "name" [ty "MoonC.CBackendName"],
    visibility [ty "MoonCore.Visibility"],
    field "ty" [ty "MoonC.CBackendType"],
    size [number],
    align [number],
    inits [many [ty "MoonC.CBackendDataInit"]],
  },
  product. CBackendExtern {
    interned,
    field "name" [ty "MoonC.CBackendName"],
    symbol [str],
    sig [ty "MoonC.CBackendFuncSigId"],
    header [optional [str]],
  },
  sum. CBackendAtom {
    CBackendAtomLocal { variant_unique, field "local" [ty "MoonC.CBackendLocalId"], },
    CBackendAtomGlobal { variant_unique, global [ty "MoonC.CBackendGlobalId"], },
    CBackendAtomLiteral {
      variant_unique,
      field "ty" [ty "MoonC.CBackendType"],
      literal [ty "MoonCore.Literal"],
    },
    CBackendAtomNull { variant_unique, field "ty" [ty "MoonC.CBackendType"], },
  },
  sum. CBackendRValue {
    CBackendRAtom { variant_unique, atom [ty "MoonC.CBackendAtom"], },
    CBackendRCompare {
      variant_unique,
      op [ty "MoonCore.CmpOp"],
      field "ty" [ty "MoonC.CBackendType"],
      lhs [ty "MoonC.CBackendAtom"],
      rhs [ty "MoonC.CBackendAtom"],
    },
    CBackendRCast {
      variant_unique,
      op [ty "MoonCore.MachineCastOp"],
      to [ty "MoonC.CBackendType"],
      field "value" [ty "MoonC.CBackendAtom"],
    },
    CBackendRSelect {
      variant_unique,
      field "ty" [ty "MoonC.CBackendType"],
      cond [ty "MoonC.CBackendAtom"],
      then_value [ty "MoonC.CBackendAtom"],
      else_value [ty "MoonC.CBackendAtom"],
    },
    CBackendRFuncAddr {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      sig [ty "MoonC.CBackendFuncSigId"],
    },
    CBackendRExternAddr {
      variant_unique,
      extern [ty "MoonC.CBackendName"],
      sig [ty "MoonC.CBackendFuncSigId"],
    },
    CBackendRPtrOffset {
      variant_unique,
      base [ty "MoonC.CBackendAtom"],
      index [ty "MoonC.CBackendAtom"],
      elem_size [number],
      const_offset [number],
    },
    CBackendRAddrOfPlace { variant_unique, place [ty "MoonC.CBackendPlace"], },
  },
  sum. CBackendTrapMode { CBackendMayTrap, CBackendMustNotTrap, CBackendCheckedTrap, },
  product. CBackendMemoryAccess {
    interned,
    field "ty" [ty "MoonC.CBackendType"],
    align [number],
    trap [ty "MoonC.CBackendTrapMode"],
    volatile [bool],
    ordering [optional [ty "MoonCore.AtomicOrdering"]],
  },
  sum. CBackendIntOverflow {
    CBackendIntWrap,
    CBackendIntTrapOnOverflow,
    CBackendIntAssumeNoOverflow,
  },
  sum. CBackendDivMode { CBackendDivTrapOnZero, CBackendDivTrapOnZeroOrOverflow, },
  sum. CBackendShiftMode { CBackendShiftMaskCount, CBackendShiftTrapOutOfRange, },
  sum. CBackendTargetFeature {
    CBackendFeatureC11Atomics,
    CBackendFeatureLibm,
    CBackendFeatureBuiltinOverflow,
    CBackendFeatureBuiltinBitops,
    CBackendFeatureUnalignedAccess,
    CBackendFeatureStaticAssert,
    CBackendFeatureHostedRuntime,
  },
  product. CBackendLayoutAssertion {
    interned,
    field "id" [ty "MoonC.CTypeId"],
    size [number],
    align [number],
  },
  sum. CBackendHelperKind {
    CBackendHelperUnary {
      variant_unique,
      op [ty "MoonCore.UnaryOp"],
      field "ty" [ty "MoonC.CBackendType"],
    },
    CBackendHelperBoolNormalize { variant_unique, field "ty" [ty "MoonC.CBackendType"], },
    CBackendHelperCast {
      variant_unique,
      op [ty "MoonCore.MachineCastOp"],
      from [ty "MoonC.CBackendType"],
      to [ty "MoonC.CBackendType"],
    },
    CBackendHelperPtrOffset {
      variant_unique,
      pointee [ty "MoonC.CBackendType"],
      elem_size [number],
      checked [bool],
    },
    CBackendHelperIntBinary {
      variant_unique,
      op [ty "MoonCore.BinaryOp"],
      field "ty" [ty "MoonC.CBackendType"],
      overflow [ty "MoonC.CBackendIntOverflow"],
    },
    CBackendHelperDivRem {
      variant_unique,
      op [ty "MoonCore.BinaryOp"],
      field "ty" [ty "MoonC.CBackendType"],
      mode [ty "MoonC.CBackendDivMode"],
    },
    CBackendHelperShift {
      variant_unique,
      op [ty "MoonCore.BinaryOp"],
      field "ty" [ty "MoonC.CBackendType"],
      mode [ty "MoonC.CBackendShiftMode"],
    },
    CBackendHelperIntrinsic {
      variant_unique,
      intrinsic [ty "MoonCore.Intrinsic"],
      field "ty" [ty "MoonC.CBackendType"],
    },
    CBackendHelperLoad { variant_unique, access [ty "MoonC.CBackendMemoryAccess"], },
    CBackendHelperStore { variant_unique, access [ty "MoonC.CBackendMemoryAccess"], },
    CBackendHelperAtomicLoad { variant_unique, access [ty "MoonC.CBackendMemoryAccess"], },
    CBackendHelperAtomicStore { variant_unique, access [ty "MoonC.CBackendMemoryAccess"], },
    CBackendHelperAtomicRmw {
      variant_unique,
      op [ty "MoonCore.AtomicRmwOp"],
      access [ty "MoonC.CBackendMemoryAccess"],
    },
    CBackendHelperAtomicCas {
      variant_unique,
      access [ty "MoonC.CBackendMemoryAccess"],
      success_ordering [ty "MoonCore.AtomicOrdering"],
      failure_ordering [ty "MoonCore.AtomicOrdering"],
    },
    CBackendHelperAtomicFence { variant_unique, ordering [ty "MoonCore.AtomicOrdering"], },
    CBackendHelperMemcpy,
    CBackendHelperTypedMemcpy {
      variant_unique,
      field "ty" [ty "MoonC.CBackendType"],
      size [number],
      align [number],
    },
    CBackendHelperMemset,
    CBackendHelperTypedMemset {
      variant_unique,
      field "ty" [ty "MoonC.CBackendType"],
      size [number],
      align [number],
    },
    CBackendHelperMemcmp,
    CBackendHelperLayoutAssert { variant_unique, assertion [ty "MoonC.CBackendLayoutAssertion"], },
    CBackendHelperRequireFeature {
      variant_unique,
      feature [ty "MoonC.CBackendTargetFeature"],
      reason [str],
    },
    CBackendHelperTrap,
  },
  product. CBackendHelperUse {
    interned,
    field "id" [ty "MoonC.CBackendHelperId"],
    kind [ty "MoonC.CBackendHelperKind"],
  },
  product. CBackendLocal {
    interned,
    field "id" [ty "MoonC.CBackendLocalId"],
    field "name" [ty "MoonC.CBackendName"],
    field "ty" [ty "MoonC.CBackendType"],
  },
  product. CBackendAggregateFieldInit {
    interned,
    field "field" [ty "MoonC.CBackendName"],
    field "value" [ty "MoonC.CBackendAtom"],
    offset [optional [number]],
  },
  product. CBackendArrayElemInit {
    interned,
    index [number],
    field "value" [ty "MoonC.CBackendAtom"],
  },
  sum. CBackendCallTarget {
    CBackendCallDirect { variant_unique, func [ty "MoonC.CBackendName"], },
    CBackendCallExtern { variant_unique, extern [ty "MoonC.CBackendName"], },
    CBackendCallIndirect {
      variant_unique,
      callee [ty "MoonC.CBackendAtom"],
      sig [ty "MoonC.CBackendFuncSigId"],
    },
    CBackendCallClosure {
      variant_unique,
      closure [ty "MoonC.CBackendAtom"],
      sig [ty "MoonC.CBackendFuncSigId"],
    },
  },
  sum. CBackendStmt {
    CBackendAssign {
      variant_unique,
      dst [ty "MoonC.CBackendLocalId"],
      rhs [ty "MoonC.CBackendRValue"],
    },
    CBackendHelperCall {
      variant_unique,
      dst [optional [ty "MoonC.CBackendLocalId"]],
      helper [ty "MoonC.CBackendHelperId"],
      args [many [ty "MoonC.CBackendAtom"]],
    },
    CBackendLoad {
      variant_unique,
      dst [ty "MoonC.CBackendLocalId"],
      addr [ty "MoonC.CBackendAtom"],
      access [ty "MoonC.CBackendMemoryAccess"],
    },
    CBackendStore {
      variant_unique,
      addr [ty "MoonC.CBackendAtom"],
      field "value" [ty "MoonC.CBackendAtom"],
      access [ty "MoonC.CBackendMemoryAccess"],
    },
    CBackendPlaceLoad {
      variant_unique,
      dst [ty "MoonC.CBackendLocalId"],
      place [ty "MoonC.CBackendPlace"],
    },
    CBackendPlaceStore {
      variant_unique,
      place [ty "MoonC.CBackendPlace"],
      field "value" [ty "MoonC.CBackendAtom"],
    },
    CBackendZeroInit {
      variant_unique,
      place [ty "MoonC.CBackendPlace"],
      field "ty" [ty "MoonC.CBackendType"],
      size [number],
    },
    CBackendAggregateInit {
      variant_unique,
      place [ty "MoonC.CBackendPlace"],
      field "ty" [ty "MoonC.CBackendType"],
      fields [many [ty "MoonC.CBackendAggregateFieldInit"]],
    },
    CBackendArrayInit {
      variant_unique,
      place [ty "MoonC.CBackendPlace"],
      field "ty" [ty "MoonC.CBackendType"],
      elems [many [ty "MoonC.CBackendArrayElemInit"]],
    },
    CBackendCall {
      variant_unique,
      dst [optional [ty "MoonC.CBackendLocalId"]],
      target [ty "MoonC.CBackendCallTarget"],
      args [many [ty "MoonC.CBackendAtom"]],
    },
    CBackendComment { variant_unique, text [str], },
  },
  product. CBackendSwitchCase {
    interned,
    literal [ty "MoonCore.Literal"],
    dest [ty "MoonC.CBackendLabel"],
    args [many [ty "MoonC.CBackendAtom"]],
  },
  sum. CBackendTerminator {
    CBackendGoto {
      variant_unique,
      dest [ty "MoonC.CBackendLabel"],
      args [many [ty "MoonC.CBackendAtom"]],
    },
    CBackendIfGoto {
      variant_unique,
      cond [ty "MoonC.CBackendAtom"],
      then_dest [ty "MoonC.CBackendLabel"],
      then_args [many [ty "MoonC.CBackendAtom"]],
      else_dest [ty "MoonC.CBackendLabel"],
      else_args [many [ty "MoonC.CBackendAtom"]],
    },
    CBackendSwitchGoto {
      variant_unique,
      field "value" [ty "MoonC.CBackendAtom"],
      cases [many [ty "MoonC.CBackendSwitchCase"]],
      default_dest [ty "MoonC.CBackendLabel"],
      default_args [many [ty "MoonC.CBackendAtom"]],
    },
    CBackendReturnVoid,
    CBackendReturn { variant_unique, field "value" [ty "MoonC.CBackendAtom"], },
    CBackendTrap,
  },
  product. CBackendBlockParam {
    interned,
    field "local" [ty "MoonC.CBackendLocalId"],
    field "ty" [ty "MoonC.CBackendType"],
  },
  product. CBackendBlock {
    interned,
    label [ty "MoonC.CBackendLabel"],
    params [many [ty "MoonC.CBackendBlockParam"]],
    stmts [many [ty "MoonC.CBackendStmt"]],
    term [ty "MoonC.CBackendTerminator"],
  },
  product. CBackendFunc {
    interned,
    field "name" [ty "MoonC.CBackendName"],
    symbol [str],
    visibility [ty "MoonCore.Visibility"],
    sig [ty "MoonC.CBackendFuncSigId"],
    params [many [ty "MoonC.CBackendLocal"]],
    locals [many [ty "MoonC.CBackendLocal"]],
    blocks [many [ty "MoonC.CBackendBlock"]],
  },
  product. CBackendUnit {
    interned,
    module_name [str],
    target [ty "MoonC.CBackendTarget"],
    sigs [many [ty "MoonC.CBackendFuncSig"]],
    types [many [ty "MoonC.CBackendTypeDecl"]],
    globals [many [ty "MoonC.CBackendGlobal"]],
    externs [many [ty "MoonC.CBackendExtern"]],
    helpers [many [ty "MoonC.CBackendHelperUse"]],
    funcs [many [ty "MoonC.CBackendFunc"]],
  },
  sum. CBackendValidationIssue {
    CBackendIssueDuplicateSig { variant_unique, sig [ty "MoonC.CBackendFuncSigId"], },
    CBackendIssueMissingSig { variant_unique, sig [ty "MoonC.CBackendFuncSigId"], },
    CBackendIssueDuplicateFunc { variant_unique, func [ty "MoonC.CBackendName"], },
    CBackendIssueMissingFunc { variant_unique, func [ty "MoonC.CBackendName"], },
    CBackendIssueDuplicateExtern { variant_unique, extern [ty "MoonC.CBackendName"], },
    CBackendIssueMissingExtern { variant_unique, extern [ty "MoonC.CBackendName"], },
    CBackendIssueDuplicateGlobal { variant_unique, global [ty "MoonC.CBackendGlobalId"], },
    CBackendIssueMissingGlobal { variant_unique, global [ty "MoonC.CBackendGlobalId"], },
    CBackendIssueDuplicateHelper { variant_unique, helper [ty "MoonC.CBackendHelperId"], },
    CBackendIssueMissingHelper { variant_unique, helper [ty "MoonC.CBackendHelperId"], },
    CBackendIssueDuplicateLocal {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      field "local" [ty "MoonC.CBackendLocalId"],
    },
    CBackendIssueMissingLocal {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      field "local" [ty "MoonC.CBackendLocalId"],
    },
    CBackendIssueDuplicateLabel {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      label [ty "MoonC.CBackendLabel"],
    },
    CBackendIssueMissingLabel {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      label [ty "MoonC.CBackendLabel"],
    },
    CBackendIssueInvalidCName {
      variant_unique,
      site [str],
      field "name" [ty "MoonC.CBackendName"],
    },
    CBackendIssueDuplicateCName {
      variant_unique,
      site [str],
      field "name" [ty "MoonC.CBackendName"],
    },
    CBackendIssueFuncSigMismatch {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      expected [ty "MoonC.CBackendType"],
      actual [ty "MoonC.CBackendType"],
    },
    CBackendIssueBlockArgCount {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      label [ty "MoonC.CBackendLabel"],
      expected [number],
      actual [number],
    },
    CBackendIssueBlockArgType {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      label [ty "MoonC.CBackendLabel"],
      index [number],
      expected [ty "MoonC.CBackendType"],
      actual [ty "MoonC.CBackendType"],
    },
    CBackendIssueCallArgCount {
      variant_unique,
      site [str],
      sig [ty "MoonC.CBackendFuncSigId"],
      expected [number],
      actual [number],
    },
    CBackendIssueCallArgType {
      variant_unique,
      site [str],
      sig [ty "MoonC.CBackendFuncSigId"],
      index [number],
      expected [ty "MoonC.CBackendType"],
      actual [ty "MoonC.CBackendType"],
    },
    CBackendIssueCallResultType {
      variant_unique,
      site [str],
      sig [ty "MoonC.CBackendFuncSigId"],
      expected [ty "MoonC.CBackendType"],
      actual [ty "MoonC.CBackendType"],
    },
    CBackendIssueIndirectCallNonCodePtr {
      variant_unique,
      site [str],
      actual [ty "MoonC.CBackendType"],
    },
    CBackendIssueDataCodePtrConfusion {
      variant_unique,
      site [str],
      field "ty" [ty "MoonC.CBackendType"],
    },
    CBackendIssueHelperMismatch {
      variant_unique,
      helper [ty "MoonC.CBackendHelperId"],
      message [str],
    },
    CBackendIssueInvalidAlignment { variant_unique, site [str], align [number], },
    CBackendIssueDataInitOutOfBounds {
      variant_unique,
      global [ty "MoonC.CBackendGlobalId"],
      offset [number],
      size [number],
      global_size [number],
    },
    CBackendIssueCoverageMissing { variant_unique, field "sum" [str], variant [str], },
    CBackendIssueInvalidTargetFeature {
      variant_unique,
      feature [ty "MoonC.CBackendTargetFeature"],
      reason [str],
    },
    CBackendIssueLayoutAssertionMissing { variant_unique, field "id" [ty "MoonC.CTypeId"], },
    CBackendIssueLayoutAssertionMismatch {
      variant_unique,
      field "id" [ty "MoonC.CTypeId"],
      expected_size [number],
      actual_size [number],
      expected_align [number],
      actual_align [number],
    },
    CBackendIssuePlaceTypeMismatch {
      variant_unique,
      site [str],
      place [ty "MoonC.CBackendPlace"],
      expected [ty "MoonC.CBackendType"],
      actual [ty "MoonC.CBackendType"],
    },
    CBackendIssueLoadStoreTypeMismatch {
      variant_unique,
      site [str],
      expected [ty "MoonC.CBackendType"],
      actual [ty "MoonC.CBackendType"],
    },
    CBackendIssueUnmaterializedAddressTakenValue {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      field "local" [ty "MoonC.CBackendLocalId"],
    },
    CBackendIssueUninitializedLocal {
      variant_unique,
      func [ty "MoonC.CBackendName"],
      field "local" [ty "MoonC.CBackendLocalId"],
    },
    CBackendIssueHelperSignatureMismatch {
      variant_unique,
      helper [ty "MoonC.CBackendHelperId"],
      expected [many [ty "MoonC.CBackendType"]],
      actual [many [ty "MoonC.CBackendType"]],
    },
    CBackendIssueDataInitPrecisionFailure {
      variant_unique,
      global [ty "MoonC.CBackendGlobalId"],
      offset [number],
      field "ty" [ty "MoonC.CBackendType"],
      literal [ty "MoonCore.Literal"],
      reason [str],
    },
    CBackendIssueDataRelocFailure {
      variant_unique,
      global [ty "MoonC.CBackendGlobalId"],
      offset [number],
      target [ty "MoonC.CBackendRelocTarget"],
      reason [str],
    },
    CBackendIssueAbiMismatch {
      variant_unique,
      site [str],
      sig [ty "MoonC.CBackendFuncSigId"],
      reason [str],
    },
    CBackendIssueUnsupportedConstruct {
      variant_unique,
      field "sum" [str],
      variant [str],
      reason [str],
    },
    CBackendIssueUnreachableConstruct {
      variant_unique,
      field "sum" [str],
      variant [str],
      reason [str],
    },
  },
  product. CBackendStorageRecord {
    interned,
    func [ty "MoonC.CBackendName"],
    storage [many [ty "MoonC.CBackendLocalStorage"]],
  },
  product. CBackendValidationInput {
    interned,
    unit [ty "MoonC.CBackendUnit"],
    storage [many [ty "MoonC.CBackendStorageRecord"]],
    abi_issues [many [ty "MoonC.CBackendValidationIssue"]],
  },
  product. CBackendValidationReport {
    interned,
    issues [many [ty "MoonC.CBackendValidationIssue"]],
  },
}
