local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonCAst {
  sum. CKeyword {
    CKwAuto,
    CKwBreak,
    CKwCase,
    CKwChar,
    CKwConst,
    CKwContinue,
    CKwDefault,
    CKwDo,
    CKwDouble,
    CKwElse,
    CKwEnum,
    CKwExtern,
    CKwFloat,
    CKwFor,
    CKwGoto,
    CKwIf,
    CKwInline,
    CKwInt,
    CKwLong,
    CKwRegister,
    CKwRestrict,
    CKwReturn,
    CKwShort,
    CKwSigned,
    CKwSizeof,
    CKwStatic,
    CKwStruct,
    CKwSwitch,
    CKwTypedef,
    CKwUnion,
    CKwUnsigned,
    CKwVoid,
    CKwVolatile,
    CKwWhile,
    CKwBool,
    CKwComplex,
    CKwInline2,
    CKwRestrict2,
  },
  sum. CDirectiveKind {
    CDirDefine,
    CDirUndef,
    CDirInclude,
    CDirIf,
    CDirIfdef,
    CDirIfndef,
    CDirElif,
    CDirElse,
    CDirEndif,
    CDirError,
    CDirPragma,
    CDirLine,
  },
  sum. CToken {
    CTokIdent { variant_unique, field "name" [str], },
    CTokKeyword { variant_unique, kw [ty "MoonCAst.CKeyword"], },
    CTokIntLiteral { variant_unique, raw [str], suffix [str], },
    CTokFloatLiteral { variant_unique, raw [str], suffix [str], },
    CTokCharLiteral { variant_unique, raw [str], },
    CTokStringLiteral { variant_unique, raw [str], prefix [str], },
    CTokPunct { variant_unique, text [str], },
    CTokDirective { variant_unique, kind [ty "MoonCAst.CDirectiveKind"], },
    CTokNewline,
    CTokEOF,
  },
  sum. CppDirective {
    CCppDefine { variant_unique, macro [ty "MoonCAst.CMacro"], },
    CCppUndef { variant_unique, field "name" [str], },
    CCppInclude { variant_unique, kind [ty "MoonCAst.CIncludeKind"], path [str], },
    CCppIf { variant_unique, tokens [many [ty "MoonCAst.CToken"]], },
    CCppIfdef { variant_unique, field "name" [str], },
    CCppIfndef { variant_unique, field "name" [str], },
    CCppElif { variant_unique, tokens [many [ty "MoonCAst.CToken"]], },
    CCppElse,
    CCppEndif,
    CCppError { variant_unique, message [str], },
    CCppPragma { variant_unique, tokens [many [ty "MoonCAst.CToken"]], },
    CCppLine { variant_unique, line [number], file [optional [str]], },
  },
  sum. CIncludeKind { CIncludeAngle, CIncludeQuoted, },
  sum. CMacroKind {
    CObjectLike,
    CFunctionLike { variant_unique, params [many [str]], variadic [bool], },
  },
  product. CMacro {
    interned,
    field "name" [str],
    kind [ty "MoonCAst.CMacroKind"],
    body [many [ty "MoonCAst.CToken"]],
    location [ty "MoonSource.SourceRange"],
  },
  product. TranslationUnit { interned, items [many [ty "MoonCAst.TopLevelItem"]], },
  sum. TopLevelItem {
    CATopDecl { variant_unique, decl [ty "MoonCAst.Decl"], },
    CATopFuncDef { variant_unique, func [ty "MoonCAst.FuncDef"], },
    CATopCpp { variant_unique, directive [ty "MoonCAst.CppDirective"], },
  },
  sum. StorageClass {
    CStorageTypedef,
    CStorageExtern,
    CStorageStatic,
    CStorageAuto,
    CStorageRegister,
  },
  sum. Qualifier { CQualConst, CQualRestrict, CQualVolatile, CQualInline, },
  sum. TypeSpec {
    CTyVoid,
    CTyChar,
    CTyShort,
    CTyInt,
    CTyLong,
    CTyLongLong,
    CTyFloat,
    CTyDouble,
    CTyLongDouble,
    CTySigned,
    CTyUnsigned,
    CTyBool,
    CTyComplex,
    CTyStructOrUnion {
      variant_unique,
      kind [ty "MoonCAst.StructKind"],
      field "name" [optional [str]],
      members [optional [many [ty "MoonCAst.FieldDecl"]]],
    },
    CTyEnum {
      variant_unique,
      field "name" [optional [str]],
      enumerators [optional [many [ty "MoonCAst.Enumerator"]]],
    },
    CTyNamed { variant_unique, field "name" [str], },
    CTyTypeof { variant_unique, field "expr" [ty "MoonCAst.Expr"], },
  },
  sum. StructKind { CStructKindStruct, CStructKindUnion, },
  product. Decl {
    interned,
    storage [optional [ty "MoonCAst.StorageClass"]],
    qualifiers [many [ty "MoonCAst.Qualifier"]],
    type_spec [ty "MoonCAst.TypeSpec"],
    declarators [many [ty "MoonCAst.Declarator"]],
  },
  product. Declarator {
    interned,
    field "name" [optional [str]],
    derived [many [ty "MoonCAst.DerivedType"]],
    initializer [optional [ty "MoonCAst.Initializer"]],
  },
  sum. DerivedType {
    CDerivedPointer { variant_unique, qualifiers [many [ty "MoonCAst.Qualifier"]], },
    CDerivedArray { variant_unique, size [optional [ty "MoonCAst.Expr"]], },
    CDerivedFunction { variant_unique, params [many [ty "MoonCAst.ParamDecl"]], variadic [bool], },
  },
  product. FieldDecl {
    interned,
    type_spec [ty "MoonCAst.TypeSpec"],
    declarators [many [ty "MoonCAst.FieldDeclarator"]],
  },
  product. FieldDeclarator {
    interned,
    declarator [optional [ty "MoonCAst.Declarator"]],
    bit_width [optional [ty "MoonCAst.Expr"]],
  },
  product. Enumerator {
    interned,
    field "name" [str],
    field "value" [optional [ty "MoonCAst.Expr"]],
  },
  product. ParamDecl {
    interned,
    type_spec [ty "MoonCAst.TypeSpec"],
    qualifiers [many [ty "MoonCAst.Qualifier"]],
    declarator [optional [ty "MoonCAst.Declarator"]],
  },
  product. FuncDef {
    interned,
    storage [optional [ty "MoonCAst.StorageClass"]],
    qualifiers [many [ty "MoonCAst.Qualifier"]],
    type_spec [ty "MoonCAst.TypeSpec"],
    declarator [ty "MoonCAst.Declarator"],
    body [ty "MoonCAst.Stmt"],
  },
  product. TypeName {
    interned,
    type_spec [ty "MoonCAst.TypeSpec"],
    derived [many [ty "MoonCAst.DerivedType"]],
  },
  sum. Expr {
    CEIntLit { variant_unique, raw [str], suffix [str], },
    CEFloatLit { variant_unique, raw [str], suffix [str], },
    CECharLit { variant_unique, raw [str], },
    CEStrLit { variant_unique, raw [str], },
    CEBoolLit { variant_unique, field "value" [bool], },
    CEIdent { variant_unique, field "name" [str], },
    CEParen { variant_unique, field "expr" [ty "MoonCAst.Expr"], },
    CEPreInc { variant_unique, operand [ty "MoonCAst.Expr"], },
    CEPreDec { variant_unique, operand [ty "MoonCAst.Expr"], },
    CEPostInc { variant_unique, operand [ty "MoonCAst.Expr"], },
    CEPostDec { variant_unique, operand [ty "MoonCAst.Expr"], },
    CEAddrOf { variant_unique, operand [ty "MoonCAst.Expr"], },
    CEDeref { variant_unique, operand [ty "MoonCAst.Expr"], },
    CEPlus { variant_unique, operand [ty "MoonCAst.Expr"], },
    CEMinus { variant_unique, operand [ty "MoonCAst.Expr"], },
    CEBitNot { variant_unique, operand [ty "MoonCAst.Expr"], },
    CENot { variant_unique, operand [ty "MoonCAst.Expr"], },
    CESizeofExpr { variant_unique, field "expr" [ty "MoonCAst.Expr"], },
    CESizeofType { variant_unique, type_name [ty "MoonCAst.TypeName"], },
    CECast {
      variant_unique,
      type_name [ty "MoonCAst.TypeName"],
      field "expr" [ty "MoonCAst.Expr"],
    },
    CEBinary {
      variant_unique,
      op [ty "MoonCAst.BinaryOp"],
      left [ty "MoonCAst.Expr"],
      right [ty "MoonCAst.Expr"],
    },
    CETernary {
      variant_unique,
      cond [ty "MoonCAst.Expr"],
      then_expr [ty "MoonCAst.Expr"],
      else_expr [ty "MoonCAst.Expr"],
    },
    CEAssign {
      variant_unique,
      op [ty "MoonCAst.AssignOp"],
      left [ty "MoonCAst.Expr"],
      right [ty "MoonCAst.Expr"],
    },
    CEDot { variant_unique, base [ty "MoonCAst.Expr"], field "field" [str], },
    CEArrow { variant_unique, base [ty "MoonCAst.Expr"], field "field" [str], },
    CESubscript { variant_unique, base [ty "MoonCAst.Expr"], index [ty "MoonCAst.Expr"], },
    CECall { variant_unique, callee [ty "MoonCAst.Expr"], args [many [ty "MoonCAst.Expr"]], },
    CECompoundLit {
      variant_unique,
      type_name [ty "MoonCAst.TypeName"],
      initializer [ty "MoonCAst.Initializer"],
    },
    CEStmtExpr {
      variant_unique,
      items [many [ty "MoonCAst.BlockItem"]],
      result [ty "MoonCAst.Expr"],
    },
    CEComma { variant_unique, left [ty "MoonCAst.Expr"], right [ty "MoonCAst.Expr"], },
  },
  sum. BinaryOp {
    CBinAdd,
    CBinSub,
    CBinMul,
    CBinDiv,
    CBinMod,
    CBinShl,
    CBinShr,
    CBinLt,
    CBinLe,
    CBinGt,
    CBinGe,
    CBinEq,
    CBinNe,
    CBinBitAnd,
    CBinBitXor,
    CBinBitOr,
    CBinLogAnd,
    CBinLogOr,
  },
  sum. AssignOp {
    CAssign,
    CAddAssign,
    CSubAssign,
    CMulAssign,
    CDivAssign,
    CModAssign,
    CShlAssign,
    CShrAssign,
    CAndAssign,
    CXorAssign,
    COrAssign,
  },
  sum. Stmt {
    CSLabeled { variant_unique, label [str], stmt [ty "MoonCAst.Stmt"], },
    CSCase { variant_unique, field "value" [ty "MoonCAst.Expr"], stmt [ty "MoonCAst.Stmt"], },
    CSDefault { variant_unique, stmt [ty "MoonCAst.Stmt"], },
    CSExpr { variant_unique, field "expr" [optional [ty "MoonCAst.Expr"]], },
    CSCompound { variant_unique, items [many [ty "MoonCAst.BlockItem"]], },
    CSIf {
      variant_unique,
      cond [ty "MoonCAst.Expr"],
      then_stmt [ty "MoonCAst.Stmt"],
      else_stmt [optional [ty "MoonCAst.Stmt"]],
    },
    CSSwitch { variant_unique, cond [ty "MoonCAst.Expr"], body [ty "MoonCAst.Stmt"], },
    CSWhile { variant_unique, cond [ty "MoonCAst.Expr"], body [ty "MoonCAst.Stmt"], },
    CSDoWhile { variant_unique, body [ty "MoonCAst.Stmt"], cond [ty "MoonCAst.Expr"], },
    CSFor {
      variant_unique,
      init [optional [ty "MoonCAst.ForInit"]],
      cond [optional [ty "MoonCAst.Expr"]],
      incr [optional [ty "MoonCAst.Expr"]],
      body [ty "MoonCAst.Stmt"],
    },
    CSGoto { variant_unique, label [str], },
    CSContinue,
    CSBreak,
    CSReturn { variant_unique, field "expr" [optional [ty "MoonCAst.Expr"]], },
  },
  sum. ForInit {
    CFInitExpr { variant_unique, field "expr" [ty "MoonCAst.Expr"], },
    CFInitDecl { variant_unique, decl [ty "MoonCAst.Decl"], },
  },
  sum. BlockItem {
    CBlockDecl { variant_unique, decl [ty "MoonCAst.Decl"], },
    CBlockStmt { variant_unique, stmt [ty "MoonCAst.Stmt"], },
  },
  sum. Initializer {
    CInitExpr { variant_unique, field "expr" [ty "MoonCAst.Expr"], },
    CInitList { variant_unique, items [many [ty "MoonCAst.InitItem"]], },
  },
  product. InitItem {
    interned,
    designator [optional [many [ty "MoonCAst.Designator"]]],
    field "value" [ty "MoonCAst.Initializer"],
  },
  sum. Designator {
    CDesigField { variant_unique, field "name" [str], },
    CDesigIndex { variant_unique, index [ty "MoonCAst.Expr"], },
    CDesigRange { variant_unique, lo [ty "MoonCAst.Expr"], hi [ty "MoonCAst.Expr"], },
  },
}
