local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonCode {
  product. CodeModuleId { interned, text [str], },
  product. CodeFuncId { interned, text [str], },
  product. CodeExternId { interned, text [str], },
  product. CodeGlobalId { interned, text [str], },
  product. CodeDataId { interned, text [str], },
  product. CodeRelocId { interned, text [str], },
  product. CodeSigId { interned, text [str], },
  product. CodeBlockId { interned, text [str], },
  product. CodeInstId { interned, text [str], },
  product. CodeTermId { interned, text [str], },
  product. CodeValueId { interned, text [str], },
  product. CodeLocalId { interned, text [str], },
  product. CodeTypeId { interned, text [str], },
  sum. CodeOrigin {
    CodeOriginUnknown,
    CodeOriginSource { variant_unique, label [str], },
    CodeOriginBinding { variant_unique, binding [ty. MoonBind.Binding], },
    CodeOriginGenerated { variant_unique, reason [str], },
  },
  sum. CodeIntSignedness { CodeSigned, CodeUnsigned, },
  sum. CodeType {
    CodeTyVoid,
    CodeTyBool8,
    CodeTyInt { variant_unique, bits [number], signedness [ty. MoonCode.CodeIntSignedness], },
    CodeTyFloat { variant_unique, bits [number], },
    CodeTyIndex,
    CodeTyDataPtr { variant_unique, pointee [optional [ty. MoonCode.CodeType]], },
    CodeTyCodePtr { variant_unique, sig [ty. MoonCode.CodeSigId], },
    CodeTyNamed {
      variant_unique,
      module_name [str],
      type_name [str],
      source_ty [ty. MoonType.Type],
    },
    CodeTyArray { variant_unique, elem [ty. MoonCode.CodeType], count [number], },
    CodeTySlice { variant_unique, elem [ty. MoonCode.CodeType], },
    CodeTyView { variant_unique, elem [ty. MoonCode.CodeType], },
    CodeTyHandle { variant_unique, repr [ty. MoonCode.CodeType], source_ty [ty. MoonType.Type], },
    CodeTyLease { variant_unique, base [ty. MoonCode.CodeType], source_ty [ty. MoonType.Type], },
    CodeTyClosure { variant_unique, sig [ty. MoonCode.CodeSigId], },
    CodeTyImportedC { variant_unique, field. id [ty. MoonC.CTypeId], },
    CodeTyImportedCFuncPtr { variant_unique, sig [ty. MoonC.CFuncSigId], },
    CodeTyVector { variant_unique, elem [ty. MoonCode.CodeType], lanes [number], },
  },
  product. CodeTypeDecl {
    interned,
    field. id [ty. MoonCode.CodeTypeId],
    field. name [str],
    field. ty [ty. MoonCode.CodeType],
    origin [ty. MoonCode.CodeOrigin],
  },
  product. CodeParam {
    interned,
    field. value [ty. MoonCode.CodeValueId],
    field. name [str],
    field. ty [ty. MoonCode.CodeType],
    origin [ty. MoonCode.CodeOrigin],
  },
  product. CodeSig {
    interned,
    field. id [ty. MoonCode.CodeSigId],
    params [many [ty. MoonCode.CodeType]],
    results [many [ty. MoonCode.CodeType]],
  },
  sum. CodeResidence {
    CodeResidenceValue,
    CodeResidenceAddressed,
    CodeResidenceAggregate,
    CodeResidenceDescriptor,
    CodeResidenceStatic,
  },
  product. CodeLocal {
    interned,
    field. id [ty. MoonCode.CodeLocalId],
    field. name [str],
    field. ty [ty. MoonCode.CodeType],
    residence [ty. MoonCode.CodeResidence],
    origin [ty. MoonCode.CodeOrigin],
  },
  sum. CodePlace {
    CodePlaceLocal {
      variant_unique,
      field. local_id [ty. MoonCode.CodeLocalId],
      field. ty [ty. MoonCode.CodeType],
    },
    CodePlaceGlobal {
      variant_unique,
      global [ty. MoonCode.CodeGlobalId],
      field. ty [ty. MoonCode.CodeType],
    },
    CodePlaceData {
      variant_unique,
      data [ty. MoonCode.CodeDataId],
      field. ty [ty. MoonCode.CodeType],
    },
    CodePlaceDeref {
      variant_unique,
      addr [ty. MoonCode.CodeValueId],
      field. ty [ty. MoonCode.CodeType],
      align [optional [number]],
    },
    CodePlaceField {
      variant_unique,
      base [ty. MoonCode.CodePlace],
      field. field [ty. MoonSem.FieldRef],
      field. ty [ty. MoonCode.CodeType],
      offset [number],
      size [optional [number]],
      align [optional [number]],
    },
    CodePlaceIndex {
      variant_unique,
      base [ty. MoonCode.CodePlace],
      index [ty. MoonCode.CodeValueId],
      field. ty [ty. MoonCode.CodeType],
      elem_size [number],
    },
    CodePlaceBytes {
      variant_unique,
      base [ty. MoonCode.CodeValueId],
      offset [number],
      field. ty [ty. MoonCode.CodeType],
      size [number],
      align [number],
    },
  },
  sum. CodeTrapMode { CodeMayTrap, CodeMustNotTrap, CodeCheckedTrap, },
  sum. CodeMemoryMode { CodeMemoryRead, CodeMemoryWrite, CodeMemoryReadWrite, },
  product. CodeMemoryAccess {
    interned,
    mode [ty. MoonCode.CodeMemoryMode],
    field. ty [ty. MoonCode.CodeType],
    align [number],
    trap [ty. MoonCode.CodeTrapMode],
    volatile [bool],
    ordering [optional [ty. MoonCore.AtomicOrdering]],
  },
  sum. CodeConst {
    CodeConstLiteral {
      variant_unique,
      field. ty [ty. MoonCode.CodeType],
      literal [ty. MoonCore.Literal],
    },
    CodeConstNull { variant_unique, field. ty [ty. MoonCode.CodeType], },
    CodeConstUndef { variant_unique, field. ty [ty. MoonCode.CodeType], reason [str], },
  },
  sum. CodeIntOverflow {
    CodeIntWrap,
    CodeIntTrapOnOverflow,
    CodeIntAssumeNoOverflow { variant_unique, reason [str], },
  },
  sum. CodeDivMode { CodeDivTrapOnZero, CodeDivTrapOnZeroOrOverflow, },
  sum. CodeShiftMode { CodeShiftMaskCount, CodeShiftTrapOutOfRange, },
  product. CodeIntSemantics {
    interned,
    overflow [ty. MoonCode.CodeIntOverflow],
    div [ty. MoonCode.CodeDivMode],
    shift [ty. MoonCode.CodeShiftMode],
  },
  sum. CodeFloatMode {
    CodeFloatStrict,
    CodeFloatReassoc { variant_unique, reason [str], },
    CodeFloatFastMath { variant_unique, reason [str], },
  },
  sum. CodeCallTarget {
    CodeCallDirect { variant_unique, func [ty. MoonCode.CodeFuncId], },
    CodeCallExtern { variant_unique, extern [ty. MoonCode.CodeExternId], },
    CodeCallIndirect {
      variant_unique,
      callee [ty. MoonCode.CodeValueId],
      sig [ty. MoonCode.CodeSigId],
    },
    CodeCallClosure {
      variant_unique,
      closure [ty. MoonCode.CodeValueId],
      sig [ty. MoonCode.CodeSigId],
    },
  },
  sum. CodeGlobalRef {
    CodeGlobalRefData { variant_unique, data [ty. MoonCode.CodeDataId], },
    CodeGlobalRefGlobal { variant_unique, global [ty. MoonCode.CodeGlobalId], },
    CodeGlobalRefFunc { variant_unique, func [ty. MoonCode.CodeFuncId], },
    CodeGlobalRefExtern { variant_unique, extern [ty. MoonCode.CodeExternId], },
  },
  product. CodeReloc {
    interned,
    field. id [ty. MoonCode.CodeRelocId],
    offset [number],
    target [ty. MoonCode.CodeGlobalRef],
    addend [number],
    origin [ty. MoonCode.CodeOrigin],
  },
  product. CodeFieldValue {
    interned,
    field. field [ty. MoonSem.FieldRef],
    field. value [ty. MoonCode.CodeValueId],
  },
  product. CodeArrayValue { interned, index [number], field. value [ty. MoonCode.CodeValueId], },
  product. CodeVariantRef {
    interned,
    owner_ty [ty. MoonCode.CodeType],
    variant_name [str],
    tag_value [number],
    payload_ty [optional [ty. MoonCode.CodeType]],
  },
  product. CodeVariantCase {
    interned,
    variant [ty. MoonCode.CodeVariantRef],
    dest [ty. MoonCode.CodeBlockId],
    args [many [ty. MoonCode.CodeValueId]],
  },
  product. CodeSwitchCase {
    interned,
    literal [ty. MoonCore.Literal],
    dest [ty. MoonCode.CodeBlockId],
    args [many [ty. MoonCode.CodeValueId]],
  },
  sum. CodeInstKind {
    CodeInstConst {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      const [ty. MoonCode.CodeConst],
    },
    CodeInstAlias {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      field. ty [ty. MoonCode.CodeType],
      src [ty. MoonCode.CodeValueId],
    },
    CodeInstUnary {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      op [ty. MoonCore.UnaryOp],
      field. ty [ty. MoonCode.CodeType],
      field. value [ty. MoonCode.CodeValueId],
    },
    CodeInstBinary {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      op [ty. MoonCore.BinaryOp],
      field. ty [ty. MoonCode.CodeType],
      semantics [ty. MoonCode.CodeIntSemantics],
      lhs [ty. MoonCode.CodeValueId],
      rhs [ty. MoonCode.CodeValueId],
    },
    CodeInstFloatBinary {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      op [ty. MoonCore.BinaryOp],
      field. ty [ty. MoonCode.CodeType],
      mode [ty. MoonCode.CodeFloatMode],
      lhs [ty. MoonCode.CodeValueId],
      rhs [ty. MoonCode.CodeValueId],
    },
    CodeInstCompare {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      op [ty. MoonCore.CmpOp],
      operand_ty [ty. MoonCode.CodeType],
      lhs [ty. MoonCode.CodeValueId],
      rhs [ty. MoonCode.CodeValueId],
    },
    CodeInstCast {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      op [ty. MoonCore.MachineCastOp],
      from [ty. MoonCode.CodeType],
      to [ty. MoonCode.CodeType],
      field. value [ty. MoonCode.CodeValueId],
    },
    CodeInstSelect {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      field. ty [ty. MoonCode.CodeType],
      cond [ty. MoonCode.CodeValueId],
      then_value [ty. MoonCode.CodeValueId],
      else_value [ty. MoonCode.CodeValueId],
    },
    CodeInstIntrinsic {
      variant_unique,
      dst [optional [ty. MoonCode.CodeValueId]],
      op [ty. MoonCore.Intrinsic],
      field. ty [ty. MoonCode.CodeType],
      args [many [ty. MoonCode.CodeValueId]],
    },
    CodeInstAddrOf {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      ptr_ty [ty. MoonCode.CodeType],
      place [ty. MoonCode.CodePlace],
    },
    CodeInstGlobalRef {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      field. ref [ty. MoonCode.CodeGlobalRef],
      ptr_ty [ty. MoonCode.CodeType],
    },
    CodeInstPtrOffset {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      ptr_ty [ty. MoonCode.CodeType],
      base [ty. MoonCode.CodeValueId],
      index [ty. MoonCode.CodeValueId],
      elem_size [number],
      const_offset [number],
    },
    CodeInstLoad {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      place [ty. MoonCode.CodePlace],
      access [ty. MoonCode.CodeMemoryAccess],
    },
    CodeInstStore {
      variant_unique,
      place [ty. MoonCode.CodePlace],
      field. value [ty. MoonCode.CodeValueId],
      access [ty. MoonCode.CodeMemoryAccess],
    },
    CodeInstAggregate {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      field. ty [ty. MoonCode.CodeType],
      fields [many [ty. MoonCode.CodeFieldValue]],
    },
    CodeInstArray {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      field. ty [ty. MoonCode.CodeType],
      elems [many [ty. MoonCode.CodeArrayValue]],
    },
    CodeInstViewMake {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      elem_ty [ty. MoonCode.CodeType],
      data [ty. MoonCode.CodeValueId],
      len [ty. MoonCode.CodeValueId],
      stride [ty. MoonCode.CodeValueId],
    },
    CodeInstViewData {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      view [ty. MoonCode.CodeValueId],
    },
    CodeInstViewLen {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      view [ty. MoonCode.CodeValueId],
    },
    CodeInstViewStride {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      view [ty. MoonCode.CodeValueId],
    },
    CodeInstClosure {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      field. ty [ty. MoonCode.CodeType],
      fn [ty. MoonCode.CodeValueId],
      ctx [ty. MoonCode.CodeValueId],
      sig [ty. MoonCode.CodeSigId],
    },
    CodeInstVariantCtor {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      field. ty [ty. MoonCode.CodeType],
      variant [ty. MoonCode.CodeVariantRef],
      payload [optional [ty. MoonCode.CodeValueId]],
    },
    CodeInstVariantTag {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      tag_ty [ty. MoonCode.CodeType],
      field. value [ty. MoonCode.CodeValueId],
    },
    CodeInstVariantPayload {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      variant [ty. MoonCode.CodeVariantRef],
      field. value [ty. MoonCode.CodeValueId],
    },
    CodeInstCall {
      variant_unique,
      dst [optional [ty. MoonCode.CodeValueId]],
      target [ty. MoonCode.CodeCallTarget],
      sig [ty. MoonCode.CodeSigId],
      args [many [ty. MoonCode.CodeValueId]],
    },
    CodeInstAtomicLoad {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      place [ty. MoonCode.CodePlace],
      access [ty. MoonCode.CodeMemoryAccess],
      ordering [ty. MoonCore.AtomicOrdering],
    },
    CodeInstAtomicStore {
      variant_unique,
      place [ty. MoonCode.CodePlace],
      field. value [ty. MoonCode.CodeValueId],
      access [ty. MoonCode.CodeMemoryAccess],
      ordering [ty. MoonCore.AtomicOrdering],
    },
    CodeInstAtomicRmw {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      op [ty. MoonCore.AtomicRmwOp],
      place [ty. MoonCode.CodePlace],
      field. value [ty. MoonCode.CodeValueId],
      access [ty. MoonCode.CodeMemoryAccess],
      ordering [ty. MoonCore.AtomicOrdering],
    },
    CodeInstAtomicCas {
      variant_unique,
      dst [ty. MoonCode.CodeValueId],
      place [ty. MoonCode.CodePlace],
      expected [ty. MoonCode.CodeValueId],
      replacement [ty. MoonCode.CodeValueId],
      access [ty. MoonCode.CodeMemoryAccess],
      ordering [ty. MoonCore.AtomicOrdering],
    },
    CodeInstAtomicFence { variant_unique, ordering [ty. MoonCore.AtomicOrdering], },
  },
  product. CodeInst {
    interned,
    field. id [ty. MoonCode.CodeInstId],
    kind [ty. MoonCode.CodeInstKind],
    origin [ty. MoonCode.CodeOrigin],
  },
  sum. CodeTermKind {
    CodeTermJump {
      variant_unique,
      dest [ty. MoonCode.CodeBlockId],
      args [many [ty. MoonCode.CodeValueId]],
    },
    CodeTermBranch {
      variant_unique,
      cond [ty. MoonCode.CodeValueId],
      then_dest [ty. MoonCode.CodeBlockId],
      then_args [many [ty. MoonCode.CodeValueId]],
      else_dest [ty. MoonCode.CodeBlockId],
      else_args [many [ty. MoonCode.CodeValueId]],
    },
    CodeTermSwitch {
      variant_unique,
      field. value [ty. MoonCode.CodeValueId],
      cases [many [ty. MoonCode.CodeSwitchCase]],
      default_dest [ty. MoonCode.CodeBlockId],
      default_args [many [ty. MoonCode.CodeValueId]],
    },
    CodeTermVariantSwitch {
      variant_unique,
      tag [ty. MoonCode.CodeValueId],
      cases [many [ty. MoonCode.CodeVariantCase]],
      default_dest [ty. MoonCode.CodeBlockId],
      default_args [many [ty. MoonCode.CodeValueId]],
    },
    CodeTermReturn { variant_unique, values [many [ty. MoonCode.CodeValueId]], },
    CodeTermTrap { variant_unique, reason [str], },
    CodeTermUnreachable { variant_unique, reason [str], },
  },
  product. CodeTerm {
    interned,
    field. id [ty. MoonCode.CodeTermId],
    kind [ty. MoonCode.CodeTermKind],
    origin [ty. MoonCode.CodeOrigin],
  },
  product. CodeBlock {
    interned,
    field. id [ty. MoonCode.CodeBlockId],
    field. name [str],
    params [many [ty. MoonCode.CodeParam]],
    insts [many [ty. MoonCode.CodeInst]],
    term [ty. MoonCode.CodeTerm],
    origin [ty. MoonCode.CodeOrigin],
  },
  sum. CodeLinkage {
    CodeLinkageLocal,
    CodeLinkageExport,
    CodeLinkageImport,
    CodeLinkageDeclaration,
  },
  sum. CodeDataInit {
    CodeDataZero { variant_unique, offset [number], size [number], },
    CodeDataBytes { variant_unique, offset [number], bytes [str], },
    CodeDataScalar {
      variant_unique,
      offset [number],
      field. ty [ty. MoonCode.CodeType],
      literal [ty. MoonCore.Literal],
    },
    CodeDataReloc { variant_unique, reloc [ty. MoonCode.CodeReloc], },
  },
  product. CodeData {
    interned,
    field. id [ty. MoonCode.CodeDataId],
    field. name [str],
    linkage [ty. MoonCode.CodeLinkage],
    size [number],
    align [number],
    inits [many [ty. MoonCode.CodeDataInit]],
    origin [ty. MoonCode.CodeOrigin],
  },
  product. CodeGlobal {
    interned,
    field. id [ty. MoonCode.CodeGlobalId],
    field. name [str],
    field. ty [ty. MoonCode.CodeType],
    linkage [ty. MoonCode.CodeLinkage],
    size [optional [number]],
    align [optional [number]],
    inits [many [ty. MoonCode.CodeDataInit]],
    origin [ty. MoonCode.CodeOrigin],
  },
  product. CodeExtern {
    interned,
    field. id [ty. MoonCode.CodeExternId],
    field. name [str],
    symbol [str],
    sig [ty. MoonCode.CodeSigId],
    origin [ty. MoonCode.CodeOrigin],
  },
  sum. CodeContractFact {
    CodeContractBounds {
      variant_unique,
      base [ty. MoonCode.CodeValueId],
      len [ty. MoonCode.CodeValueId],
    },
    CodeContractWindowBounds {
      variant_unique,
      base [ty. MoonCode.CodeValueId],
      base_len [ty. MoonCode.CodeValueId],
      start [ty. MoonCode.CodeValueId],
      len [ty. MoonCode.CodeValueId],
    },
    CodeContractDisjoint {
      variant_unique,
      a [ty. MoonCode.CodeValueId],
      b [ty. MoonCode.CodeValueId],
    },
    CodeContractSameLen {
      variant_unique,
      a [ty. MoonCode.CodeValueId],
      b [ty. MoonCode.CodeValueId],
    },
    CodeContractNoAlias { variant_unique, base [ty. MoonCode.CodeValueId], },
    CodeContractReadonly { variant_unique, base [ty. MoonCode.CodeValueId], },
    CodeContractWriteonly { variant_unique, base [ty. MoonCode.CodeValueId], },
    CodeContractInvalidate { variant_unique, base [ty. MoonCode.CodeValueId], },
    CodeContractPreserve { variant_unique, base [ty. MoonCode.CodeValueId], },
    CodeContractRejected { variant_unique, reason [str], },
  },
  product. CodeFuncContractFact {
    interned,
    func [ty. MoonCode.CodeFuncId],
    fact [ty. MoonCode.CodeContractFact],
    origin [ty. MoonCode.CodeOrigin],
  },
  product. CodeContractFactSet {
    interned,
    field. module [ty. MoonCode.CodeModuleId],
    facts [many [ty. MoonCode.CodeFuncContractFact]],
  },
  product. CodeFunc {
    interned,
    field. id [ty. MoonCode.CodeFuncId],
    field. name [str],
    linkage [ty. MoonCode.CodeLinkage],
    sig [ty. MoonCode.CodeSigId],
    params [many [ty. MoonCode.CodeParam]],
    locals [many [ty. MoonCode.CodeLocal]],
    entry [ty. MoonCode.CodeBlockId],
    blocks [many [ty. MoonCode.CodeBlock]],
    origin [ty. MoonCode.CodeOrigin],
  },
  product. CodeModule {
    interned,
    field. id [ty. MoonCode.CodeModuleId],
    sigs [many [ty. MoonCode.CodeSig]],
    types [many [ty. MoonCode.CodeTypeDecl]],
    data [many [ty. MoonCode.CodeData]],
    globals [many [ty. MoonCode.CodeGlobal]],
    externs [many [ty. MoonCode.CodeExtern]],
    funcs [many [ty. MoonCode.CodeFunc]],
    origin [ty. MoonCode.CodeOrigin],
  },
  sum. CodeIssue {
    CodeIssueMissingValue { variant_unique, field. value [ty. MoonCode.CodeValueId], },
    CodeIssueDuplicateValue { variant_unique, field. value [ty. MoonCode.CodeValueId], },
    CodeIssueMissingBlock { variant_unique, block [ty. MoonCode.CodeBlockId], },
    CodeIssueDuplicateBlock { variant_unique, block [ty. MoonCode.CodeBlockId], },
    CodeIssueMissingSig { variant_unique, sig [ty. MoonCode.CodeSigId], },
    CodeIssueMissingFunc { variant_unique, func [ty. MoonCode.CodeFuncId], },
    CodeIssueMissingExtern { variant_unique, extern [ty. MoonCode.CodeExternId], },
    CodeIssueMissingGlobal { variant_unique, global [ty. MoonCode.CodeGlobalId], },
    CodeIssueMissingData { variant_unique, data [ty. MoonCode.CodeDataId], },
    CodeIssueDuplicateSig { variant_unique, sig [ty. MoonCode.CodeSigId], },
    CodeIssueDuplicateFunc { variant_unique, func [ty. MoonCode.CodeFuncId], },
    CodeIssueDuplicateExtern { variant_unique, extern [ty. MoonCode.CodeExternId], },
    CodeIssueDuplicateGlobal { variant_unique, global [ty. MoonCode.CodeGlobalId], },
    CodeIssueDuplicateData { variant_unique, data [ty. MoonCode.CodeDataId], },
    CodeIssueDuplicateInst { variant_unique, inst [ty. MoonCode.CodeInstId], },
    CodeIssueDuplicateTerm { variant_unique, term [ty. MoonCode.CodeTermId], },
    CodeIssueJumpArity {
      variant_unique,
      block [ty. MoonCode.CodeBlockId],
      expected [number],
      actual [number],
    },
    CodeIssueCallArity {
      variant_unique,
      sig [ty. MoonCode.CodeSigId],
      expected [number],
      actual [number],
    },
    CodeIssueTypeMismatch {
      variant_unique,
      site [str],
      expected [ty. MoonCode.CodeType],
      actual [ty. MoonCode.CodeType],
    },
    CodeIssueBlockParamMismatch {
      variant_unique,
      block [ty. MoonCode.CodeBlockId],
      index [number],
      expected [ty. MoonCode.CodeType],
      actual [ty. MoonCode.CodeType],
    },
    CodeIssueUnterminatedBlock { variant_unique, block [ty. MoonCode.CodeBlockId], },
    CodeIssueInvalidTerminator { variant_unique, site [str], term [ty. MoonCode.CodeTermId], },
    CodeIssueInvalidMemoryAccess {
      variant_unique,
      site [str],
      access [ty. MoonCode.CodeMemoryAccess],
    },
    CodeIssueInvalidReloc { variant_unique, reloc [ty. MoonCode.CodeReloc], reason [str], },
    CodeIssueDataCodePointerConfusion {
      variant_unique,
      site [str],
      field. ty [ty. MoonCode.CodeType],
    },
    CodeIssueUnsupportedSource { variant_unique, site [str], reason [str], },
  },
  product. CodeValidationReport { interned, issues [many [ty. MoonCode.CodeIssue]], },
}
