local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonDasm {
  product. DModuleId { interned, text [str], },
  product. DBlockId { interned, text [str], },
  product. DValId { interned, text [str], },
  product. DLabelId { interned, text [str], },
  product. DVirtualRegId { interned, text [str], },
  product. DPhysRegId { interned, field. number [number], },
  sum. DRegClass { DGpr, DXmm, DFlags, },
  sum. DValueClass {
    DValueGpr { variant_unique, scalar [ty. MoonBack.BackScalar], },
    DValueXmm { variant_unique, scalar [ty. MoonBack.BackScalar], },
    DValueFlags,
    DValueVector { variant_unique, elem [ty. MoonBack.BackScalar], lanes [number], },
  },
  product. DSigEntry {
    interned,
    key [str],
    params [many [ty. MoonBack.BackScalar]],
    results [many [ty. MoonBack.BackScalar]],
  },
  product. DFuncEntry {
    interned,
    key [str],
    sig [str],
    visibility [str],
    body [many [ty. MoonBack.Cmd]],
  },
  product. DExternEntry { interned, key [str], symbol [str], sig [str], },
  product. DDataEntry { interned, key [str], buf [any], size [number], align [number], },
  product. DLabelPair { interned, key [str], label [str], },
  product. DLabelMap {
    interned,
    funcs [many [ty. MoonDasm.DLabelPair]],
    externs [many [ty. MoonDasm.DLabelPair]],
    datas [many [ty. MoonDasm.DLabelPair]],
  },
  product. DPhaseModule {
    interned,
    sigs [many [ty. MoonDasm.DSigEntry]],
    funcs [many [ty. MoonDasm.DFuncEntry]],
    externs [many [ty. MoonDasm.DExternEntry]],
    datas [many [ty. MoonDasm.DDataEntry]],
    func_order [many [str]],
    extern_order [many [str]],
    data_order [many [str]],
    labels [ty. MoonDasm.DLabelMap],
  },
  product. DTargetFacts {
    interned,
    target [ty. MoonBack.BackTargetModel],
    pointer_bits [number],
    index_bits [number],
    endianness [str],
    features [many [str]],
  },
  product. DFuncBody { interned, func [ty. MoonBack.BackFuncId], cmds [many [ty. MoonBack.Cmd]], },
  product. DPhaseFunc {
    interned,
    func [optional [ty. MoonBack.BackFuncId]],
    cmds [many [ty. MoonBack.Cmd]],
  },
  product. DScalarMapEntry { interned, key [str], scalar [str], },
  product. DTypedFunc {
    interned,
    func [ty. MoonBack.BackFuncId],
    cmds [many [ty. MoonBack.Cmd]],
    value_scalars [many [ty. MoonDasm.DScalarMapEntry]],
  },
  product. DBlockParam {
    interned,
    field. value [ty. MoonBack.BackValId],
    field. ty [ty. MoonBack.BackShape],
  },
  product. DEdgeArg {
    interned,
    src [ty. MoonBack.BackValId],
    dst_param [ty. MoonBack.BackValId],
  },
  product. DSwitchCase { interned, raw [str], dest [ty. MoonBack.BackBlockId], },
  sum. DTerminator {
    DTermJump {
      variant_unique,
      dest [ty. MoonBack.BackBlockId],
      args [many [ty. MoonDasm.DEdgeArg]],
    },
    DTermBrIf {
      variant_unique,
      cond [ty. MoonBack.BackValId],
      then_block [ty. MoonBack.BackBlockId],
      then_args [many [ty. MoonDasm.DEdgeArg]],
      else_block [ty. MoonBack.BackBlockId],
      else_args [many [ty. MoonDasm.DEdgeArg]],
    },
    DTermSwitch {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      field. ty [ty. MoonBack.BackScalar],
      cases [many [ty. MoonDasm.DSwitchCase]],
      default_dest [ty. MoonBack.BackBlockId],
    },
    DTermReturnVoid,
    DTermReturnValue { variant_unique, field. value [ty. MoonBack.BackValId], },
    DTermTrap,
  },
  product. DCfgBlock {
    interned,
    field. id [ty. MoonBack.BackBlockId],
    params [many [ty. MoonDasm.DBlockParam]],
    body [many [ty. MoonBack.Cmd]],
    term [ty. MoonDasm.DTerminator],
  },
  product. DFuncCFG {
    interned,
    func [ty. MoonBack.BackFuncId],
    sig [ty. MoonBack.BackSigId],
    entry [ty. MoonBack.BackBlockId],
    blocks [many [ty. MoonDasm.DCfgBlock]],
    stack_slots [many [ty. MoonBack.BackStackSlotId]],
  },
  sum. DValueFact {
    DValueShapeFact {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      shape [ty. MoonBack.BackShape],
    },
    DValueClassFact {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      class [ty. MoonDasm.DValueClass],
    },
    DValueDefFact {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      block [ty. MoonBack.BackBlockId],
      index [number],
    },
    DValueUseFact {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      block [ty. MoonBack.BackBlockId],
      index [number],
      slot [number],
    },
    DValueConstIntFact { variant_unique, field. value [ty. MoonBack.BackValId], raw [str], },
    DValueConstFloatFact { variant_unique, field. value [ty. MoonBack.BackValId], raw [str], },
  },
  sum. DEdgeKind {
    DEdgeEntry,
    DEdgeJump,
    DEdgeThen,
    DEdgeElse,
    DEdgeSwitchCase,
    DEdgeSwitchDefault,
    DEdgeCriticalSplit,
  },
  product. DEdgeRef {
    interned,
    pred [ty. MoonBack.BackBlockId],
    succ [ty. MoonBack.BackBlockId],
    kind [ty. MoonDasm.DEdgeKind],
    ordinal [number],
  },
  product. DParallelMove {
    interned,
    dst [ty. MoonBack.BackValId],
    src [ty. MoonBack.BackValId],
    class [ty. MoonDasm.DValueClass],
  },
  product. DParallelCopy {
    interned,
    edge [ty. MoonDasm.DEdgeRef],
    moves [many [ty. MoonDasm.DParallelMove]],
  },
  sum. DControlFact {
    DControlEdgeFact {
      variant_unique,
      edge [ty. MoonDasm.DEdgeRef],
      args [many [ty. MoonDasm.DEdgeArg]],
    },
    DParallelCopyFact { variant_unique, copy [ty. MoonDasm.DParallelCopy], },
  },
  sum. DMemoryFact {
    DMemoryLoadFact {
      variant_unique,
      dst [ty. MoonBack.BackValId],
      addr [ty. MoonBack.BackAddress],
      memory [ty. MoonBack.BackMemoryInfo],
      field. ty [ty. MoonBack.BackShape],
    },
    DMemoryStoreFact {
      variant_unique,
      addr [ty. MoonBack.BackAddress],
      field. value [ty. MoonBack.BackValId],
      memory [ty. MoonBack.BackMemoryInfo],
      field. ty [ty. MoonBack.BackShape],
    },
  },
  sum. DCallFact {
    DCallSiteFact {
      variant_unique,
      index [number],
      sig [ty. MoonBack.BackSigId],
      target [ty. MoonBack.BackCallTarget],
      args [many [ty. MoonBack.BackValId]],
      result [optional [ty. MoonBack.BackCallResult]],
    },
    DCallClobberFact { variant_unique, index [number], clobbers [many [ty. MoonDasm.DPhysRegId]], },
  },
  product. DFuncFacts {
    interned,
    cfg [ty. MoonDasm.DFuncCFG],
    value_facts [many [ty. MoonDasm.DValueFact]],
    control_facts [many [ty. MoonDasm.DControlFact]],
    memory_facts [many [ty. MoonDasm.DMemoryFact]],
    call_facts [many [ty. MoonDasm.DCallFact]],
  },
  sum. DConstKind {
    DConstUnknown,
    DConstInt { variant_unique, raw [str], },
    DConstFloat { variant_unique, raw [str], },
    DConstBool { variant_unique, field. value [bool], },
    DConstNull,
  },
  sum. DAddrBaseKind { DBaseValue, DBaseStack, DBaseData, DBaseUnknown, },
  sum. DFamilyKind {
    DFamilyCopy,
    DFamilyIntBin,
    DFamilyBitBin,
    DFamilyShiftRotate,
    DFamilyCompareBranch,
    DFamilyLoadStore,
    DFamilyAddress,
    DFamilyCall,
    DFamilyControl,
    DFamilyReturn,
    DFamilyOther,
  },
  sum. DFamilyKey {
    DKeyCopy {
      variant_unique,
      class [ty. MoonDasm.DValueClass],
      src_const [ty. MoonDasm.DConstKind],
      same_value [bool],
    },
    DKeyIntBin {
      variant_unique,
      op [str],
      scalar [ty. MoonBack.BackScalar],
      lhs_const [ty. MoonDasm.DConstKind],
      rhs_const [ty. MoonDasm.DConstKind],
      commutative [bool],
      rhs_pow2 [bool],
    },
    DKeyBitBin {
      variant_unique,
      op [str],
      scalar [ty. MoonBack.BackScalar],
      rhs_const [ty. MoonDasm.DConstKind],
    },
    DKeyShiftRotate {
      variant_unique,
      op [str],
      scalar [ty. MoonBack.BackScalar],
      rhs_const [ty. MoonDasm.DConstKind],
      rhs_small_imm [bool],
    },
    DKeyCompareBranch {
      variant_unique,
      op [str],
      scalar [ty. MoonBack.BackScalar],
      rhs_const [ty. MoonDasm.DConstKind],
      fused_branch [bool],
      rhs_is_zero [bool],
    },
    DKeyLoadStore {
      variant_unique,
      is_load [bool],
      shape [ty. MoonBack.BackShape],
      base_kind [ty. MoonDasm.DAddrBaseKind],
      has_index [bool],
      const_disp [bool],
      align_bytes [number],
      trap_kind [str],
    },
    DKeyAddress {
      variant_unique,
      base_kind [ty. MoonDasm.DAddrBaseKind],
      elem_size [number],
      const_offset [number],
    },
    DKeyCall {
      variant_unique,
      target_kind [str],
      argc [number],
      has_result [bool],
      result_class [ty. MoonDasm.DValueClass],
    },
    DKeyControl { variant_unique, kind [str], },
    DKeyReturn { variant_unique, has_value [bool], class [ty. MoonDasm.DValueClass], },
    DKeyOther { variant_unique, kind [str], },
  },
  product. DFamilyInstance {
    interned,
    cmd_index [number],
    block [optional [ty. MoonBack.BackBlockId]],
    family [ty. MoonDasm.DFamilyKind],
    key [ty. MoonDasm.DFamilyKey],
  },
  sum. DFactAtom {
    DFactCmdKind { variant_unique, cmd_index [number], kind [str], },
    DFactValueShape {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      shape [ty. MoonBack.BackShape],
    },
    DFactValueClass {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      class [ty. MoonDasm.DValueClass],
    },
    DFactValueConst {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      const_kind [ty. MoonDasm.DConstKind],
    },
    DFactUse {
      variant_unique,
      field. value [ty. MoonBack.BackValId],
      cmd_index [number],
      slot [number],
    },
    DFactDef { variant_unique, field. value [ty. MoonBack.BackValId], cmd_index [number], },
    DFactBlockAt { variant_unique, cmd_index [number], block [ty. MoonBack.BackBlockId], },
  },
  product. DFactSet {
    interned,
    func [optional [ty. MoonBack.BackFuncId]],
    cmds [many [ty. MoonBack.Cmd]],
    atoms [many [ty. MoonDasm.DFactAtom]],
    families [many [ty. MoonDasm.DFamilyInstance]],
  },
  product. DLowerDecision {
    interned,
    cmd_index [number],
    rule [str],
    cost [number],
    shape [ty. MoonDasm.DAsmShape],
  },
  product. DLoweredFunc {
    interned,
    func [optional [ty. MoonBack.BackFuncId]],
    cmds [many [ty. MoonBack.Cmd]],
    facts [ty. MoonDasm.DFactSet],
    decisions [many [ty. MoonDasm.DLowerDecision]],
    asm [ty. MoonDasm.DAsmFunc],
  },
  product. DAddress {
    interned,
    base [optional [ty. MoonDasm.DPhysRegId]],
    index [optional [ty. MoonDasm.DPhysRegId]],
    scale [number],
    disp [number],
  },
  sum. DOperand {
    DOpVReg { variant_unique, vreg [ty. MoonDasm.DVirtualRegId], },
    DOpPReg { variant_unique, preg [ty. MoonDasm.DPhysRegId], },
    DOpImmI64 { variant_unique, raw [str], },
    DOpLabel { variant_unique, label [ty. MoonDasm.DLabelId], },
    DOpMem { variant_unique, addr [ty. MoonDasm.DAddress], },
  },
  sum. DCondCode { DccE, DccNE, DccL, DccLE, DccG, DccGE, DccB, DccBE, DccA, DccAE, DccP, DccNP, },
  sum. DAsmShape {
    DAsmLabel { variant_unique, label [ty. MoonDasm.DLabelId], },
    DAsmMove {
      variant_unique,
      dst [ty. MoonDasm.DOperand],
      src [ty. MoonDasm.DOperand],
      class [ty. MoonDasm.DValueClass],
    },
    DAsmUnary {
      variant_unique,
      op [str],
      dst [ty. MoonDasm.DOperand],
      src [ty. MoonDasm.DOperand],
      scalar [ty. MoonBack.BackScalar],
    },
    DAsmBinary {
      variant_unique,
      op [str],
      dst [ty. MoonDasm.DOperand],
      lhs [ty. MoonDasm.DOperand],
      rhs [ty. MoonDasm.DOperand],
      scalar [ty. MoonBack.BackScalar],
    },
    DAsmCompareSet {
      variant_unique,
      cc [ty. MoonDasm.DCondCode],
      dst [ty. MoonDasm.DOperand],
      lhs [ty. MoonDasm.DOperand],
      rhs [ty. MoonDasm.DOperand],
      scalar [ty. MoonBack.BackScalar],
    },
    DAsmLoad {
      variant_unique,
      dst [ty. MoonDasm.DOperand],
      addr [ty. MoonDasm.DOperand],
      field. ty [ty. MoonBack.BackShape],
    },
    DAsmStore {
      variant_unique,
      addr [ty. MoonDasm.DOperand],
      field. value [ty. MoonDasm.DOperand],
      field. ty [ty. MoonBack.BackShape],
    },
    DAsmLea { variant_unique, dst [ty. MoonDasm.DOperand], addr [ty. MoonDasm.DOperand], },
    DAsmJump { variant_unique, dest [ty. MoonDasm.DLabelId], },
    DAsmBrIf {
      variant_unique,
      cond [ty. MoonDasm.DOperand],
      then_label [ty. MoonDasm.DLabelId],
      else_label [ty. MoonDasm.DLabelId],
    },
    DAsmCall {
      variant_unique,
      target [ty. MoonDasm.DOperand],
      args [many [ty. MoonDasm.DOperand]],
      result [optional [ty. MoonDasm.DOperand]],
    },
    DAsmRetVoid,
    DAsmRetValue { variant_unique, field. value [ty. MoonDasm.DOperand], },
    DAsmPrologue,
    DAsmEpilogue,
    DAsmTrap,
    DAsmComment { variant_unique, text [str], },
  },
  product. DAsmInst {
    interned,
    shape [ty. MoonDasm.DAsmShape],
    defs [many [ty. MoonDasm.DVirtualRegId]],
    uses [many [ty. MoonDasm.DVirtualRegId]],
    clobbers [many [ty. MoonDasm.DPhysRegId]],
  },
  product. DAsmBlock {
    interned,
    field. id [ty. MoonBack.BackBlockId],
    insts [many [ty. MoonDasm.DAsmInst]],
  },
  product. DAsmFunc {
    interned,
    func [ty. MoonBack.BackFuncId],
    blocks [many [ty. MoonDasm.DAsmBlock]],
  },
  sum. DAllocLoc {
    DLocReg { variant_unique, preg [ty. MoonDasm.DPhysRegId], },
    DLocStack { variant_unique, offset [number], size [number], align [number], },
  },
  product. DValueAlloc {
    interned,
    vreg [ty. MoonDasm.DVirtualRegId],
    loc [ty. MoonDasm.DAllocLoc],
    class [ty. MoonDasm.DValueClass],
  },
  product. DBankedRegalloc {
    interned,
    allocs [many [ty. MoonDasm.DValueAlloc]],
    used_callee_saved [many [ty. MoonDasm.DPhysRegId]],
    spill_size [number],
  },
  product. DFrameSlot {
    interned,
    slot [ty. MoonBack.BackStackSlotId],
    offset [number],
    size [number],
    align [number],
  },
  product. DFramePlan {
    interned,
    stack_size [number],
    spill_size [number],
    slot_size [number],
    callee_saved [many [ty. MoonDasm.DPhysRegId]],
    slots [many [ty. MoonDasm.DFrameSlot]],
  },
  product. DFragment { interned, offset [number], args [many [number]], bytes [str], },
  product. DFragmentBundle { interned, fragments [many [ty. MoonDasm.DFragment]], },
  product. DGlobalEntry { interned, kind [str], key [str], label [str], slot_index [number], },
  product. DFuncPtrEntry { interned, func [ty. MoonBack.BackFuncId], global_slot [number], },
  product. DEmitPlan {
    interned,
    globals [many [ty. MoonDasm.DGlobalEntry]],
    fragments [many [ty. MoonDasm.DFragment]],
    func_ptrs [many [ty. MoonDasm.DFuncPtrEntry]],
    code_size_hint [number],
  },
}
