local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonEditor {
  sum. ServerMode {
    ServerCreated,
    ServerInitializing,
    ServerReady,
    ServerShutdownRequested,
    ServerStopped,
  },
  sum. ClientCapability {
    ClientCapability { variant_unique, field "name" [str], field "value" [str], },
  },
  product. WorkspaceRoot { interned, uri [ty "MoonSource.DocUri"], },
  sum. WorkspaceFileOrigin { WorkspaceFileOpen, WorkspaceFileDisk, },
  product. WorkspaceFile {
    uri [ty "MoonSource.DocUri"],
    path [str],
    language [ty "MoonSource.LanguageId"],
    version [ty "MoonSource.DocVersion"],
    origin [ty "MoonEditor.WorkspaceFileOrigin"],
    fingerprint [str],
  },
  product. WorkspaceIndex { generation [number], files [many [ty "MoonEditor.WorkspaceFile"]], },
  product. WorkspaceState {
    mode [ty "MoonEditor.ServerMode"],
    roots [many [ty "MoonEditor.WorkspaceRoot"]],
    capabilities [many [ty "MoonEditor.ClientCapability"]],
    open_docs [many [ty "MoonSource.DocumentSnapshot"]],
    index [ty "MoonEditor.WorkspaceIndex"],
  },
  sum. RpcId {
    RpcIdNone,
    RpcIdNumber { variant_unique, field "value" [number], },
    RpcIdString { variant_unique, field "value" [str], },
  },
  product. PositionQuery {
    uri [ty "MoonSource.DocUri"],
    version [ty "MoonSource.DocVersion"],
    pos [ty "MoonSource.SourcePos"],
  },
  product. RangeQuery {
    uri [ty "MoonSource.DocUri"],
    version [ty "MoonSource.DocVersion"],
    range [ty "MoonSource.SourceRange"],
  },
  product. ReferenceQuery { position [ty "MoonEditor.PositionQuery"], include_declaration [bool], },
  product. RenameQuery { position [ty "MoonEditor.PositionQuery"], new_name [str], },
  product. CodeActionQuery {
    range [ty "MoonEditor.RangeQuery"],
    diagnostics [many [ty "MoonEditor.DiagnosticFact"]],
  },
  sum. ClientEvent {
    ClientInitialize {
      field "id" [ty "MoonEditor.RpcId"],
      roots [many [ty "MoonEditor.WorkspaceRoot"]],
      capabilities [many [ty "MoonEditor.ClientCapability"]],
    },
    ClientInitialized,
    ClientShutdown { field "id" [ty "MoonEditor.RpcId"], },
    ClientExit,
    ClientDidOpen { document [ty "MoonSource.DocumentSnapshot"], },
    ClientDidChange { edit [ty "MoonSource.DocumentEdit"], },
    ClientDidClose { uri [ty "MoonSource.DocUri"], },
    ClientDidSave { uri [ty "MoonSource.DocUri"], },
    ClientHover { field "id" [ty "MoonEditor.RpcId"], query [ty "MoonEditor.PositionQuery"], },
    ClientDefinition { field "id" [ty "MoonEditor.RpcId"], query [ty "MoonEditor.PositionQuery"], },
    ClientReferences { field "id" [ty "MoonEditor.RpcId"], query [ty "MoonEditor.ReferenceQuery"], },
    ClientDocumentHighlight {
      field "id" [ty "MoonEditor.RpcId"],
      query [ty "MoonEditor.PositionQuery"],
    },
    ClientDocumentSymbol { field "id" [ty "MoonEditor.RpcId"], uri [ty "MoonSource.DocUri"], },
    ClientWorkspaceSymbol { field "id" [ty "MoonEditor.RpcId"], query [str], },
    ClientDiagnostic { field "id" [ty "MoonEditor.RpcId"], uri [ty "MoonSource.DocUri"], },
    ClientCompletion { field "id" [ty "MoonEditor.RpcId"], query [ty "MoonEditor.PositionQuery"], },
    ClientSignatureHelp {
      field "id" [ty "MoonEditor.RpcId"],
      query [ty "MoonEditor.PositionQuery"],
    },
    ClientSemanticTokensFull { field "id" [ty "MoonEditor.RpcId"], uri [ty "MoonSource.DocUri"], },
    ClientSemanticTokensRange {
      field "id" [ty "MoonEditor.RpcId"],
      query [ty "MoonEditor.RangeQuery"],
    },
    ClientPrepareRename {
      field "id" [ty "MoonEditor.RpcId"],
      query [ty "MoonEditor.PositionQuery"],
    },
    ClientRename { field "id" [ty "MoonEditor.RpcId"], query [ty "MoonEditor.RenameQuery"], },
    ClientCodeAction {
      field "id" [ty "MoonEditor.RpcId"],
      query [ty "MoonEditor.CodeActionQuery"],
    },
    ClientFoldingRange { field "id" [ty "MoonEditor.RpcId"], uri [ty "MoonSource.DocUri"], },
    ClientSelectionRange {
      field "id" [ty "MoonEditor.RpcId"],
      positions [many [ty "MoonEditor.PositionQuery"]],
    },
    ClientInlayHint { field "id" [ty "MoonEditor.RpcId"], query [ty "MoonEditor.RangeQuery"], },
    ClientUnsupported { field "id" [ty "MoonEditor.RpcId"], method [str], },
    ClientIgnoredNotification { method [str], },
  },
  product. Transition {
    before [ty "MoonEditor.WorkspaceState"],
    event [ty "MoonEditor.ClientEvent"],
    after [ty "MoonEditor.WorkspaceState"],
  },
  sum. DiagnosticSeverity {
    DiagnosticError,
    DiagnosticWarning,
    DiagnosticInformation,
    DiagnosticHint,
  },
  sum. DiagnosticOrigin {
    DiagFromParse { variant_unique, issue [ty "MoonParse.ParseIssue"], },
    DiagFromHost { variant_unique, issue [ty "MoonHost.HostIssue"], },
    DiagFromOpen { variant_unique, issue [ty "MoonOpen.ValidationIssue"], },
    DiagFromType { variant_unique, issue [ty "MoonTree.TypeIssue"], },
    DiagFromBack { variant_unique, issue [ty "MoonBack.BackValidationIssue"], },
    DiagFromBindingResolution { variant_unique, resolution [ty "MoonEditor.BindingResolution"], },
    DiagFromSource { variant_unique, issue [ty "MoonSource.SourceApplyIssue"], },
    DiagFromTransport { variant_unique, code [str], message [str], },
  },
  product. DiagnosticFact {
    interned,
    severity [ty "MoonEditor.DiagnosticSeverity"],
    origin [ty "MoonEditor.DiagnosticOrigin"],
    code [str],
    message [str],
    range [ty "MoonSource.SourceRange"],
  },
  sum. Subject {
    SubjectKeyword { variant_unique, text [str], },
    SubjectScalar { variant_unique, scalar [ty "MoonCore.Scalar"], },
    SubjectType { variant_unique, field "ty" [ty "MoonType.Type"], },
    SubjectHostStruct { variant_unique, decl [ty "MoonHost.HostStructDecl"], },
    SubjectHostField {
      variant_unique,
      owner [ty "MoonHost.HostStructDecl"],
      field "field" [ty "MoonHost.HostFieldDecl"],
    },
    SubjectHostExpose { variant_unique, decl [ty "MoonHost.HostExposeDecl"], },
    SubjectHostAccessor { variant_unique, decl [ty "MoonHost.HostAccessorDecl"], },
    SubjectTreeFunc { variant_unique, func [ty "MoonTree.Func"], },
    SubjectTreeExtern { variant_unique, func [ty "MoonTree.ExternFunc"], },
    SubjectTreeModule { variant_unique, field "module" [ty "MoonTree.Module"], },
    SubjectRegionFrag { variant_unique, frag [ty "MoonOpen.RegionFrag"], },
    SubjectExprFrag { variant_unique, frag [ty "MoonOpen.ExprFrag"], },
    SubjectBinding { variant_unique, binding [ty "MoonBind.Binding"], },
    SubjectContinuation {
      variant_unique,
      scope [ty "MoonSource.AnchorId"],
      label [ty "MoonTree.BlockLabel"],
    },
    SubjectBuiltin { variant_unique, field "name" [str], },
    SubjectDiagnostic { variant_unique, diagnostic [ty "MoonEditor.DiagnosticFact"], },
    SubjectMissing { variant_unique, reason [str], },
  },
  product. SubjectPick {
    query [ty "MoonEditor.PositionQuery"],
    anchors [many [ty "MoonSource.AnchorSpan"]],
    subject [ty "MoonEditor.Subject"],
  },
  sum. SymbolKind {
    SymFile,
    SymModule,
    SymNamespace,
    SymPackage,
    SymClass,
    SymMethod,
    SymProperty,
    SymField,
    SymConstructor,
    SymEnum,
    SymInterface,
    SymFunction,
    SymVariable,
    SymConstant,
    SymString,
    SymNumber,
    SymBoolean,
    SymArray,
    SymObject,
    SymKey,
    SymNull,
    SymEnumMember,
    SymStruct,
    SymEvent,
    SymOperator,
    SymTypeParameter,
  },
  product. SymbolId { interned, text [str], },
  product. SymbolFact {
    interned,
    field "id" [ty "MoonEditor.SymbolId"],
    parent [ty "MoonEditor.SymbolId"],
    field "name" [str],
    kind [ty "MoonEditor.SymbolKind"],
    detail [str],
    range [ty "MoonSource.SourceRange"],
    selection_range [ty "MoonSource.SourceRange"],
    subject [ty "MoonEditor.Subject"],
  },
  product. SymbolTree { interned, symbols [many [ty "MoonEditor.SymbolFact"]], },
  sum. BindingRole {
    BindingDef,
    BindingUse,
    BindingRead,
    BindingWrite,
    BindingCall,
    BindingTypeUse,
  },
  product. BindingScopeId { interned, text [str], },
  sum. BindingScopeKind {
    BindingScopeDocument,
    BindingScopeIsland,
    BindingScopeFunction,
    BindingScopeRegion,
    BindingScopeExpr,
    BindingScopeControlBlock,
    BindingScopeBranch,
    BindingScopeModule,
    BindingScopeOpaque { variant_unique, field "name" [str], },
  },
  product. BindingScopeFact {
    interned,
    field "id" [ty "MoonEditor.BindingScopeId"],
    parent [ty "MoonEditor.BindingScopeId"],
    kind [ty "MoonEditor.BindingScopeKind"],
    range [ty "MoonSource.SourceRange"],
  },
  product. ScopedBinding {
    interned,
    binding [ty "MoonBind.Binding"],
    scope [ty "MoonEditor.BindingScopeId"],
    visible_range [ty "MoonSource.SourceRange"],
    anchor [ty "MoonSource.AnchorSpan"],
  },
  product. BindingUseSite {
    interned,
    anchor [ty "MoonSource.AnchorSpan"],
    role [ty "MoonEditor.BindingRole"],
    scope [ty "MoonEditor.BindingScopeId"],
  },
  sum. BindingResolution {
    BindingResolved {
      variant_unique,
      use [ty "MoonEditor.BindingUseSite"],
      binding [ty "MoonEditor.ScopedBinding"],
    },
    BindingUnresolved { variant_unique, use [ty "MoonEditor.BindingUseSite"], reason [str], },
  },
  product. BindingScopeReport {
    interned,
    scopes [many [ty "MoonEditor.BindingScopeFact"]],
    bindings [many [ty "MoonEditor.ScopedBinding"]],
    resolutions [many [ty "MoonEditor.BindingResolution"]],
  },
  product. BindingFact {
    interned,
    field "id" [ty "MoonEditor.SymbolId"],
    role [ty "MoonEditor.BindingRole"],
    subject [ty "MoonEditor.Subject"],
    anchor [ty "MoonSource.AnchorSpan"],
  },
  sum. DefinitionResult {
    DefinitionHit {
      variant_unique,
      subject [ty "MoonEditor.Subject"],
      ranges [many [ty "MoonSource.SourceRange"]],
    },
    DefinitionMiss { variant_unique, reason [str], },
  },
  sum. ReferenceResult {
    ReferenceHit {
      variant_unique,
      subject [ty "MoonEditor.Subject"],
      ranges [many [ty "MoonSource.SourceRange"]],
    },
    ReferenceMiss { variant_unique, reason [str], },
  },
  sum. DocumentHighlightKind { HighlightText, HighlightRead, HighlightWrite, },
  product. DocumentHighlight {
    interned,
    range [ty "MoonSource.SourceRange"],
    kind [ty "MoonEditor.DocumentHighlightKind"],
  },
  product. RenameEdit { interned, range [ty "MoonSource.SourceRange"], new_text [str], },
  sum. RenameResult {
    RenameOk { variant_unique, edits [many [ty "MoonEditor.RenameEdit"]], },
    RenameRejected { variant_unique, reason [str], },
  },
  sum. PrepareRenameResult {
    PrepareRenameOk { variant_unique, range [ty "MoonSource.SourceRange"], placeholder [str], },
    PrepareRenameRejected { variant_unique, reason [str], },
  },
  sum. MarkupKind { MarkupPlainText, MarkupMarkdown, },
  sum. HoverInfo {
    HoverInfo {
      variant_unique,
      kind [ty "MoonEditor.MarkupKind"],
      field "value" [str],
      range [ty "MoonSource.SourceRange"],
    },
    HoverMissing { variant_unique, reason [str], },
  },
  sum. CompletionContext {
    CompletionTopLevel,
    CompletionModuleItem,
    CompletionStructField,
    CompletionTypePosition,
    CompletionExprPosition,
    CompletionPlacePosition,
    CompletionExposeSubject,
    CompletionExposeTarget,
    CompletionExposeMode,
    CompletionRegionStatement,
    CompletionContinuationArgs,
    CompletionBuiltinPath,
    CompletionLuaOpaque,
    CompletionInvalid { variant_unique, reason [str], },
  },
  sum. CompletionKind {
    CompletionText,
    CompletionMethod,
    CompletionFunction,
    CompletionConstructor,
    CompletionField,
    CompletionVariable,
    CompletionClass,
    CompletionInterface,
    CompletionModule,
    CompletionProperty,
    CompletionUnit,
    CompletionValue,
    CompletionEnum,
    CompletionKeyword,
    CompletionSnippet,
    CompletionColor,
    CompletionFile,
    CompletionReference,
    CompletionFolder,
    CompletionEnumMember,
    CompletionConstant,
    CompletionStruct,
    CompletionEvent,
    CompletionOperator,
    CompletionTypeParameter,
  },
  sum. CompletionInsertFormat { CompletionInsertPlainText, CompletionInsertSnippet, },
  product. CompletionQuery {
    position [ty "MoonEditor.PositionQuery"],
    context [ty "MoonEditor.CompletionContext"],
  },
  product. CompletionItem {
    interned,
    label [str],
    kind [ty "MoonEditor.CompletionKind"],
    detail [str],
    documentation [str],
    insert_text [str],
    insert_format [ty "MoonEditor.CompletionInsertFormat"],
  },
  sum. SignatureContext {
    SignatureCall {
      variant_unique,
      callee [str],
      active_parameter [number],
      callee_range [ty "MoonSource.SourceRange"],
    },
    SignatureNoCall { variant_unique, reason [str], },
  },
  product. SignatureParameter { interned, label [str], documentation [str], },
  product. SignatureInfo {
    interned,
    label [str],
    documentation [str],
    params [many [ty "MoonEditor.SignatureParameter"]],
  },
  sum. SignatureHelp {
    SignatureHelp {
      variant_unique,
      signatures [many [ty "MoonEditor.SignatureInfo"]],
      active_signature [number],
      active_parameter [number],
    },
    SignatureHelpMissing { variant_unique, reason [str], },
  },
  sum. SemanticTokenType {
    TokNamespace,
    TokType,
    TokClass,
    TokEnum,
    TokInterface,
    TokStruct,
    TokTypeParameter,
    TokParameter,
    TokVariable,
    TokProperty,
    TokEnumMember,
    TokEvent,
    TokFunction,
    TokMethod,
    TokMacro,
    TokKeyword,
    TokModifier,
    TokComment,
    TokString,
    TokNumber,
    TokRegexp,
    TokOperator,
    TokDecorator,
  },
  sum. SemanticTokenModifier {
    TokModDeclaration,
    TokModDefinition,
    TokModReadonly,
    TokModStatic,
    TokModDeprecated,
    TokModAbstract,
    TokModAsync,
    TokModModification,
    TokModDocumentation,
    TokModDefaultLibrary,
    TokModMutable,
    TokModExported,
    TokModStorage,
    TokModDiagnostic,
  },
  product. SemanticTokenSpan {
    interned,
    range [ty "MoonSource.SourceRange"],
    token_type [ty "MoonEditor.SemanticTokenType"],
    modifiers [many [ty "MoonEditor.SemanticTokenModifier"]],
  },
  sum. CodeActionKind {
    CodeActionQuickFix,
    CodeActionRefactor,
    CodeActionSource,
    CodeActionOrganizeImports,
  },
  product. TextEdit { interned, range [ty "MoonSource.SourceRange"], new_text [str], },
  product. WorkspaceEdit { interned, edits [many [ty "MoonEditor.TextEdit"]], },
  product. CodeAction {
    interned,
    title [str],
    kind [ty "MoonEditor.CodeActionKind"],
    diagnostics [many [ty "MoonEditor.DiagnosticFact"]],
    edit [ty "MoonEditor.WorkspaceEdit"],
  },
  product. FoldingRange { interned, range [ty "MoonSource.SourceRange"], kind [str], },
  product. SelectionRange {
    interned,
    range [ty "MoonSource.SourceRange"],
    parents [many [ty "MoonSource.SourceRange"]],
  },
  product. InlayHint { interned, pos [ty "MoonSource.SourcePos"], label [str], kind [str], },
}
