local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonHost {
  sum. HostIssue {
    HostIssueInvalidName { variant_unique, site [str], field "name" [str], },
    HostIssueExpected { variant_unique, site [str], expected [str], actual [str], },
    HostIssueDuplicateField { variant_unique, type_name [str], field_name [str], },
    HostIssueDuplicateType { variant_unique, module_name [str], type_name [str], },
    HostIssueDuplicateDecl { variant_unique, field "name" [str], },
    HostIssueDuplicateFunc { variant_unique, module_name [str], func_name [str], },
    HostIssueUnsealedType { variant_unique, module_name [str], type_name [str], },
    HostIssueSealedMutation { variant_unique, type_name [str], },
    HostIssueAlreadySealed { variant_unique, type_name [str], },
    HostIssueUnknownBinding { variant_unique, site [str], field "name" [str], },
    HostIssueInvalidEmitFill { variant_unique, fragment_name [str], fill_name [str], },
    HostIssueMissingEmitFill { variant_unique, fragment_name [str], fill_name [str], },
    HostIssueInvalidPackedAlign { variant_unique, type_name [str], align [number], },
    HostIssueBareBoolInBoundaryStruct { variant_unique, type_name [str], field_name [str], },
    HostIssueArgCount { variant_unique, site [str], expected [number], actual [number], },
    HostIssueSpliceExpected { variant_unique, splice_id [str], expected [str], actual [str], },
    HostIssueSpliceEvalError { variant_unique, splice_id [str], message [str], },
    HostIssueLuaStepError { variant_unique, step_id [str], message [str], },
    HostIssueTemplateParseError { variant_unique, template_id [str], message [str], },
    HostIssueRegionComposeMissingExit { variant_unique, fragment_name [str], exit_name [str], },
    HostIssueRegionComposeIncompatibleCont {
      variant_unique,
      fragment_name [str],
      exit_name [str],
      expected [str],
      actual [str],
    },
    HostIssueRegionComposeIncompleteRoute { variant_unique, fragment_name [str], exit_name [str], },
    HostIssueRegionComposeContextMismatch { variant_unique, left [str], right [str], },
  },
  product. HostReport { interned, issues [many [ty "MoonHost.HostIssue"]], },
  product. HostLayoutId { interned, key [str], field "name" [str], },
  product. HostFieldId { interned, key [str], field "name" [str], },
  sum. HostEndian { HostEndianLittle, HostEndianBig, },
  product. HostTargetModel {
    interned,
    pointer_bits [number],
    index_bits [number],
    endian [ty "MoonHost.HostEndian"],
  },
  sum. HostLayoutKind {
    HostLayoutStruct,
    HostLayoutSlice,
    HostLayoutArray,
    HostLayoutViewDescriptor,
    HostLayoutOpaque,
  },
  sum. HostOwner {
    HostOwnerBufferView,
    HostOwnerHostSession,
    HostOwnerBorrowed,
    HostOwnerStatic,
    HostOwnerOpaque,
  },
  sum. HostBoolEncoding { HostBoolU8, HostBoolI32, HostBoolNative, },
  sum. HostRepr {
    HostReprC,
    HostReprPacked { variant_unique, align [number], },
    HostReprOpaque { variant_unique, field "name" [str], },
  },
  sum. HostFieldAttr {
    HostFieldReadonly,
    HostFieldMutable,
    HostFieldNoalias,
    HostFieldOpaque { variant_unique, field "name" [str], },
  },
  sum. HostStorageRep {
    HostStorageSame,
    HostStorageScalar { variant_unique, scalar [ty "MoonCore.Scalar"], },
    HostStorageBool {
      variant_unique,
      encoding [ty "MoonHost.HostBoolEncoding"],
      scalar [ty "MoonCore.Scalar"],
    },
    HostStoragePtr { variant_unique, pointee [ty "MoonType.Type"], },
    HostStorageSlice { variant_unique, elem [ty "MoonType.Type"], },
    HostStorageView { variant_unique, elem [ty "MoonType.Type"], },
    HostStorageOpaque { variant_unique, field "name" [str], },
  },
  product. HostStructDecl {
    interned,
    field "id" [ty "MoonHost.HostLayoutId"],
    field "name" [str],
    repr [ty "MoonHost.HostRepr"],
    fields [many [ty "MoonHost.HostFieldDecl"]],
  },
  product. HostFieldDecl {
    interned,
    field "id" [ty "MoonHost.HostFieldId"],
    field "name" [str],
    expose_ty [ty "MoonType.Type"],
    storage [ty "MoonHost.HostStorageRep"],
    attrs [many [ty "MoonHost.HostFieldAttr"]],
  },
  sum. HostAccessorDecl {
    HostAccessorField { variant_unique, owner_name [str], field "name" [str], field_name [str], },
    HostAccessorLua { variant_unique, owner_name [str], field "name" [str], lua_symbol [str], },
    HostAccessorMoonlift {
      variant_unique,
      owner_name [str],
      field "name" [str],
      func [ty "MoonTree.Func"],
    },
  },
  sum. HostDecl {
    HostDeclStruct { variant_unique, decl [ty "MoonHost.HostStructDecl"], },
    HostDeclExpose { variant_unique, decl [ty "MoonHost.HostExposeDecl"], },
    HostDeclAccessor { variant_unique, decl [ty "MoonHost.HostAccessorDecl"], },
  },
  product. HostDeclSet { interned, field "decls" [many [ty "MoonHost.HostDecl"]], },
  sum. HostDeclSource {
    HostDeclSourceSet { variant_unique, set [ty "MoonHost.HostDeclSet"], },
    HostDeclSourceDecls { variant_unique, field "decls" [many [ty "MoonHost.HostDecl"]], },
  },
  product. MluaSource { interned, field "name" [str], source [str], },
  product. MluaParseResult {
    interned,
    field "decls" [ty "MoonHost.HostDeclSet"],
    field "module" [ty "MoonTree.Module"],
    region_frags [many [ty "MoonOpen.RegionFrag"]],
    expr_frags [many [ty "MoonOpen.ExprFrag"]],
    issues [many [ty "MoonParse.ParseIssue"]],
  },
  product. MluaHostPipelineResult {
    interned,
    parsed [ty "MoonHost.MluaParseResult"],
    report [ty "MoonHost.HostReport"],
    layout_env [ty "MoonHost.HostLayoutEnv"],
  },
  product. HostValueId { interned, key [str], pretty [str], },
  sum. HostValueKind {
    HostValueRegionFrag,
    HostValueExprFrag,
    HostValueType,
    HostValueDecl,
    HostValueModule,
    HostValueLua,
  },
  product. HostValueRef {
    interned,
    field "id" [ty "MoonHost.HostValueId"],
    kind [ty "MoonHost.HostValueKind"],
  },
  product. ProtocolRole { interned, role [str], target [str], },
  product. RegionProtocol {
    interned,
    field "name" [str],
    roles [many [ty "MoonHost.ProtocolRole"]],
  },
  product. FragmentDeps {
    interned,
    region_frags [many [ty "MoonOpen.RegionFrag"]],
    expr_frags [many [ty "MoonOpen.ExprFrag"]],
  },
  product. RegionFragMeta {
    interned,
    field "name" [str],
    frag [ty "MoonOpen.RegionFrag"],
    protocol [optional [ty "MoonHost.RegionProtocol"]],
    deps [ty "MoonHost.FragmentDeps"],
  },
  product. MluaRegionTypeResult {
    interned,
    frag [ty "MoonOpen.RegionFrag"],
    issues [many [ty "MoonTree.TypeIssue"]],
  },
  product. MluaLoopExpandResult {
    interned,
    entry [ty "MoonTree.EntryControlBlock"],
    blocks [many [ty "MoonTree.ControlBlock"]],
    issues [many [ty "MoonTree.TypeIssue"]],
  },
  sum. MluaLoopSource {
    MluaLoopControlStmt { variant_unique, region [ty "MoonTree.ControlStmtRegion"], },
    MluaLoopControlExpr { variant_unique, region [ty "MoonTree.ControlExprRegion"], },
  },
  sum. HostFieldRep {
    HostRepScalar { variant_unique, scalar [ty "MoonCore.Scalar"], },
    HostRepBool {
      variant_unique,
      encoding [ty "MoonHost.HostBoolEncoding"],
      storage [ty "MoonCore.Scalar"],
    },
    HostRepPtr { variant_unique, pointee [ty "MoonType.Type"], },
    HostRepRef { variant_unique, layout [ty "MoonHost.HostLayoutId"], },
    HostRepSlice { variant_unique, elem [ty "MoonHost.HostFieldRep"], },
    HostRepView { variant_unique, elem [ty "MoonType.Type"], },
    HostRepStruct { variant_unique, layout [ty "MoonHost.HostLayoutId"], },
    HostRepOpaque { variant_unique, field "name" [str], },
  },
  product. HostFieldLayout {
    interned,
    field "id" [ty "MoonHost.HostFieldId"],
    field "name" [str],
    cfield [str],
    rep [ty "MoonHost.HostFieldRep"],
    offset [number],
    size [number],
    align [number],
  },
  product. HostTypeLayout {
    interned,
    field "id" [ty "MoonHost.HostLayoutId"],
    field "name" [str],
    ctype [str],
    kind [ty "MoonHost.HostLayoutKind"],
    size [number],
    align [number],
    fields [many [ty "MoonHost.HostFieldLayout"]],
  },
  product. HostLayoutEnv { interned, layouts [many [ty "MoonHost.HostTypeLayout"]], },
  product. HostCdef { interned, layout [ty "MoonHost.HostLayoutId"], source [str], },
  product. HostLuaFfiPlan {
    interned,
    module_name [str],
    cdefs [many [ty "MoonHost.HostCdef"]],
    access_plans [many [ty "MoonHost.HostAccessPlan"]],
  },
  product. HostTerraPlan {
    interned,
    module_name [str],
    source [str],
    layouts [many [ty "MoonHost.HostTypeLayout"]],
    views [many [ty "MoonHost.HostViewDescriptor"]],
  },
  product. HostCPlan {
    interned,
    header_name [str],
    source [str],
    layouts [many [ty "MoonHost.HostTypeLayout"]],
    views [many [ty "MoonHost.HostViewDescriptor"]],
  },
  sum. HostExportAbi {
    HostExportDescriptorPtr { variant_unique, descriptor [ty "MoonHost.HostViewDescriptor"], },
    HostExportExpandedScalars { variant_unique, field "ty" [ty "MoonType.Type"], },
  },
  sum. HostExposeSubject {
    HostExposeType { variant_unique, field "ty" [ty "MoonType.Type"], },
    HostExposePtr { variant_unique, pointee [ty "MoonType.Type"], },
    HostExposeView { variant_unique, elem [ty "MoonType.Type"], },
  },
  sum. HostStrideUnit { HostStrideElements, HostStrideBytes, },
  sum. HostViewAbi {
    HostViewAbiContiguous { variant_unique, elem_layout [ty "MoonHost.HostTypeLayout"], },
    HostViewAbiStrided {
      variant_unique,
      elem_layout [ty "MoonHost.HostTypeLayout"],
      stride_unit [ty "MoonHost.HostStrideUnit"],
    },
  },
  product. HostViewDescriptor {
    interned,
    field "id" [ty "MoonHost.HostLayoutId"],
    field "name" [str],
    abi [ty "MoonHost.HostViewAbi"],
    descriptor_layout [ty "MoonHost.HostTypeLayout"],
  },
  sum. HostExposeTarget { HostExposeLua, HostExposeTerra, HostExposeC, HostExposeMoonlift, },
  sum. HostMutability { HostReadonly, HostMutable, HostInteriorMutable, },
  sum. HostBoundsPolicy { HostBoundsChecked, HostBoundsUnchecked, },
  sum. HostProxyKind {
    HostProxyPtr,
    HostProxyView,
    HostProxyBufferView,
    HostProxyTypedRecord,
    HostProxyOpaque,
  },
  sum. HostProxyCachePolicy { HostProxyCacheNone, HostProxyCacheLazy, HostProxyCacheEager, },
  sum. HostMaterializePolicy {
    HostMaterializeProjectedFields,
    HostMaterializeFullCopy,
    HostMaterializeBorrowedView,
  },
  sum. HostExposeMode {
    HostExposeProxy {
      variant_unique,
      kind [ty "MoonHost.HostProxyKind"],
      cache [ty "MoonHost.HostProxyCachePolicy"],
      mutability [ty "MoonHost.HostMutability"],
      bounds [ty "MoonHost.HostBoundsPolicy"],
    },
    HostExposeEagerTable { variant_unique, policy [ty "MoonHost.HostMaterializePolicy"], },
    HostExposeScalar { variant_unique, rep [ty "MoonHost.HostFieldRep"], },
    HostExposeOpaque { variant_unique, reason [str], },
  },
  sum. HostExposeAbi {
    HostExposeAbiDefault,
    HostExposeAbiPointer,
    HostExposeAbiDescriptor,
    HostExposeAbiDataLenStride,
    HostExposeAbiExpandedScalars,
    HostExposeAbiOpaque { variant_unique, reason [str], },
  },
  product. HostExposeFacet {
    interned,
    target [ty "MoonHost.HostExposeTarget"],
    abi [ty "MoonHost.HostExposeAbi"],
    mode [ty "MoonHost.HostExposeMode"],
  },
  product. HostExposeDecl {
    interned,
    subject [ty "MoonHost.HostExposeSubject"],
    public_name [str],
    facets [many [ty "MoonHost.HostExposeFacet"]],
  },
  sum. HostLifetime {
    HostLifetimeStatic,
    HostLifetimeOwned,
    HostLifetimeBorrowed { variant_unique, owner_name [str], },
    HostLifetimeGeneration { variant_unique, session_id [number], generation [number], },
    HostLifetimeExternal { variant_unique, field "name" [str], },
  },
  sum. HostAccessSubject {
    HostAccessRecord { variant_unique, layout [ty "MoonHost.HostTypeLayout"], },
    HostAccessPtr { variant_unique, layout [ty "MoonHost.HostTypeLayout"], },
    HostAccessView { variant_unique, descriptor [ty "MoonHost.HostViewDescriptor"], },
  },
  sum. HostAccessKey {
    HostAccessField { variant_unique, field "name" [str], },
    HostAccessIndex,
    HostAccessLen,
    HostAccessData,
    HostAccessStride,
    HostAccessMethod { variant_unique, field "name" [str], },
    HostAccessPairs,
    HostAccessIpairs,
    HostAccessToTable,
  },
  sum. HostAccessOp {
    HostAccessDirectField { variant_unique, field "field" [ty "MoonHost.HostFieldLayout"], },
    HostAccessDecodeBool { variant_unique, field "field" [ty "MoonHost.HostFieldLayout"], },
    HostAccessEncodeBool { variant_unique, field "field" [ty "MoonHost.HostFieldLayout"], },
    HostAccessViewIndex { variant_unique, descriptor [ty "MoonHost.HostViewDescriptor"], },
    HostAccessViewFieldAt {
      variant_unique,
      descriptor [ty "MoonHost.HostViewDescriptor"],
      field "field" [ty "MoonHost.HostFieldLayout"],
    },
    HostAccessViewLen { variant_unique, descriptor [ty "MoonHost.HostViewDescriptor"], },
    HostAccessViewData { variant_unique, descriptor [ty "MoonHost.HostViewDescriptor"], },
    HostAccessViewStride { variant_unique, descriptor [ty "MoonHost.HostViewDescriptor"], },
    HostAccessPointerCast { variant_unique, layout [ty "MoonHost.HostTypeLayout"], },
    HostAccessIterateFields { variant_unique, layout [ty "MoonHost.HostLayoutId"], },
    HostAccessMaterializeTable { variant_unique, subject [ty "MoonHost.HostAccessSubject"], },
    HostAccessReject { variant_unique, reason [str], },
  },
  product. HostAccessEntry {
    interned,
    key [ty "MoonHost.HostAccessKey"],
    op [ty "MoonHost.HostAccessOp"],
  },
  product. HostAccessPlan {
    interned,
    subject [ty "MoonHost.HostAccessSubject"],
    entries [many [ty "MoonHost.HostAccessEntry"]],
  },
  product. HostViewPlan {
    interned,
    layout [ty "MoonHost.HostTypeLayout"],
    owner [ty "MoonHost.HostOwner"],
    expose [ty "MoonHost.HostExposeMode"],
    access [ty "MoonHost.HostAccessPlan"],
  },
  sum. HostProducerKind {
    HostProducerLowLevelMoonlift,
    HostProducerLuaFfi,
    HostProducerRustTypedRecordMemory,
    HostProducerExternal,
  },
  product. HostProducerPlan {
    interned,
    field "name" [str],
    kind [ty "MoonHost.HostProducerKind"],
    outputs [many [ty "MoonHost.HostTypeLayout"]],
  },
  sum. HostLayoutFact {
    HostFactTypeLayout { variant_unique, layout [ty "MoonHost.HostTypeLayout"], },
    HostFactCdef { variant_unique, cdef [ty "MoonHost.HostCdef"], },
    HostFactField {
      variant_unique,
      owner [ty "MoonHost.HostLayoutId"],
      field "field" [ty "MoonHost.HostFieldLayout"],
    },
    HostFactViewDescriptor { variant_unique, descriptor [ty "MoonHost.HostViewDescriptor"], },
    HostFactExpose {
      variant_unique,
      public_name [str],
      layout [ty "MoonHost.HostLayoutId"],
      facet [ty "MoonHost.HostExposeFacet"],
    },
    HostFactAccessPlan { variant_unique, plan [ty "MoonHost.HostAccessPlan"], },
    HostFactViewPlan { variant_unique, plan [ty "MoonHost.HostViewPlan"], },
    HostFactLuaFfi { variant_unique, plan [ty "MoonHost.HostLuaFfiPlan"], },
    HostFactTerra { variant_unique, plan [ty "MoonHost.HostTerraPlan"], },
    HostFactC { variant_unique, plan [ty "MoonHost.HostCPlan"], },
    HostFactProducer { variant_unique, plan [ty "MoonHost.HostProducerPlan"], },
  },
  product. HostFactSet { interned, facts [many [ty "MoonHost.HostLayoutFact"]], },
  sum. HostLayoutReject {
    HostRejectJsonInRust,
    HostRejectDynamicObjectArena { variant_unique, reason [str], },
    HostRejectUnknownFieldKind { variant_unique, kind [str], },
    HostRejectInvalidLayout { variant_unique, reason [str], },
    HostRejectBareBoolInBoundaryStruct { variant_unique, type_name [str], field_name [str], },
    HostRejectInvalidPackedAlign { variant_unique, type_name [str], align [number], },
    HostRejectConflictingCdef { variant_unique, layout [ty "MoonHost.HostLayoutId"], },
  },
}
