local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonLink {
  product. LinkPath { interned, text [str], },
  product. LinkSymbol { interned, field "name" [str], },
  product. LinkEnv { interned, key [str], field "value" [str], },
  sum. LinkPlatform {
    LinkPlatformLinux,
    LinkPlatformMacOS,
    LinkPlatformWindows,
    LinkPlatformWasm,
    LinkPlatformUnknown { variant_unique, field "name" [str], },
  },
  sum. LinkArch {
    LinkArchX86_64,
    LinkArchAArch64,
    LinkArchX86,
    LinkArchArm,
    LinkArchWasm32,
    LinkArchUnknown { variant_unique, field "name" [str], },
  },
  sum. LinkObjectFormat {
    LinkFormatElf,
    LinkFormatMachO,
    LinkFormatCoff,
    LinkFormatWasm,
    LinkFormatUnknown { variant_unique, field "name" [str], },
  },
  sum. LinkRelocationModel { LinkRelocStatic, LinkRelocPic, LinkRelocPie, },
  product. LinkTargetModel {
    interned,
    backend [ty "MoonBack.BackTargetModel"],
    platform [ty "MoonLink.LinkPlatform"],
    arch [ty "MoonLink.LinkArch"],
    object_format [ty "MoonLink.LinkObjectFormat"],
    relocation [ty "MoonLink.LinkRelocationModel"],
  },
  sum. LinkArtifactKind {
    LinkArtifactObject,
    LinkArtifactStaticArchive,
    LinkArtifactSharedLibrary,
    LinkArtifactExecutable,
  },
  sum. LinkerKind {
    LinkerSystemCc,
    LinkerCc,
    LinkerClang,
    LinkerGcc,
    LinkerLd,
    LinkerLld,
    LinkerAr,
    LinkerLibtool,
    LinkerCustom { variant_unique, field "name" [str], },
  },
  product. LinkTool { interned, kind [ty "MoonLink.LinkerKind"], path [ty "MoonLink.LinkPath"], },
  sum. LinkInput {
    LinkInputObject { variant_unique, path [ty "MoonLink.LinkPath"], },
    LinkInputStaticArchive { variant_unique, path [ty "MoonLink.LinkPath"], },
    LinkInputSharedLibrary { variant_unique, path [ty "MoonLink.LinkPath"], },
    LinkInputSystemLibrary { variant_unique, field "name" [str], },
    LinkInputFramework { variant_unique, field "name" [str], },
    LinkInputLibrarySearchPath { variant_unique, path [ty "MoonLink.LinkPath"], },
    LinkInputLinkerScript { variant_unique, path [ty "MoonLink.LinkPath"], },
  },
  sum. LinkExportPolicy {
    LinkExportAll,
    LinkExportNone,
    LinkExportSymbols { variant_unique, symbols [many [ty "MoonLink.LinkSymbol"]], },
    LinkExportVersionScript { variant_unique, path [ty "MoonLink.LinkPath"], },
  },
  sum. LinkExternPolicy { LinkExternRequireResolved, LinkExternAllowUnresolved, },
  sum. LinkDebugPolicy { LinkDebugDefault, LinkDebugKeep, LinkDebugStrip, },
  sum. LinkRuntimePath {
    LinkRpath { variant_unique, path [ty "MoonLink.LinkPath"], },
    LinkRunpath { variant_unique, path [ty "MoonLink.LinkPath"], },
  },
  sum. LinkOption {
    LinkOptRuntimePath { variant_unique, path [ty "MoonLink.LinkRuntimePath"], },
    LinkOptEntry { variant_unique, symbol [ty "MoonLink.LinkSymbol"], },
    LinkOptSoname { variant_unique, field "name" [str], },
    LinkOptInstallName { variant_unique, field "name" [str], },
    LinkOptOutputImplib { variant_unique, path [ty "MoonLink.LinkPath"], },
    LinkOptDebug { variant_unique, policy [ty "MoonLink.LinkDebugPolicy"], },
    LinkOptWholeArchiveBegin,
    LinkOptWholeArchiveEnd,
    LinkOptNoDefaultLibs,
    LinkOptStaticLibgcc,
    LinkOptCustomArg { variant_unique, },
  },
  product. LinkPlan {
    interned,
    target [ty "MoonLink.LinkTargetModel"],
    kind [ty "MoonLink.LinkArtifactKind"],
    tool [ty "MoonLink.LinkTool"],
    output [ty "MoonLink.LinkPath"],
    inputs [many [ty "MoonLink.LinkInput"]],
    exports [ty "MoonLink.LinkExportPolicy"],
    externs [ty "MoonLink.LinkExternPolicy"],
    options [many [ty "MoonLink.LinkOption"]],
  },
  sum. LinkIssue {
    LinkIssueMissingOutput,
    LinkIssueNoInputs,
    LinkIssueMissingInput { variant_unique, path [ty "MoonLink.LinkPath"], },
    LinkIssueUnsupportedPlatform {
      variant_unique,
      platform [ty "MoonLink.LinkPlatform"],
      kind [ty "MoonLink.LinkArtifactKind"],
    },
    LinkIssueUnsupportedInput { variant_unique, input [ty "MoonLink.LinkInput"], reason [str], },
    LinkIssueUnsupportedOption { variant_unique, option [ty "MoonLink.LinkOption"], reason [str], },
    LinkIssueUnresolvedSymbol { variant_unique, symbol [ty "MoonLink.LinkSymbol"], },
    LinkIssueDuplicateSymbol { variant_unique, symbol [ty "MoonLink.LinkSymbol"], },
    LinkIssueToolUnavailable { variant_unique, tool [ty "MoonLink.LinkTool"], },
    LinkIssueCommandFailed { variant_unique, index [number], code [number], stderr [str], },
  },
  product. LinkReport { interned, issues [many [ty "MoonLink.LinkIssue"]], },
  sum. LinkCommand {
    LinkCmdRun {
      variant_unique,
      tool [ty "MoonLink.LinkTool"],
      args [many [str]],
      env [many [ty "MoonLink.LinkEnv"]],
    },
    LinkCmdWriteFile { variant_unique, path [ty "MoonLink.LinkPath"], contents [str], },
    LinkCmdRemoveFile { variant_unique, path [ty "MoonLink.LinkPath"], },
  },
  product. LinkCommandPlan {
    interned,
    plan [ty "MoonLink.LinkPlan"],
    commands [many [ty "MoonLink.LinkCommand"]],
  },
  sum. LinkResult {
    LinkOk { variant_unique, output [ty "MoonLink.LinkPath"], },
    LinkFailed { variant_unique, report [ty "MoonLink.LinkReport"], },
  },
}
