local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonLsp {
  product. ProtocolPosition { line [number], character [number], },
  product. ProtocolRange {
    start [ty "MoonLsp.ProtocolPosition"],
    stop [ty "MoonLsp.ProtocolPosition"],
  },
  product. Location { uri [ty "MoonSource.DocUri"], range [ty "MoonLsp.ProtocolRange"], },
  product. InitializeResult {
    interned,
    server_name [str],
    position_encoding [str],
    capabilities_json [str],
  },
  product. DiagnosticPayload {
    range [ty "MoonLsp.ProtocolRange"],
    severity [number],
    code [str],
    message [str],
  },
  product. DiagnosticReport {
    uri [ty "MoonSource.DocUri"],
    version [ty "MoonSource.DocVersion"],
    diagnostics [many [ty "MoonLsp.DiagnosticPayload"]],
  },
  product. DiagnosticDocumentReport { kind [str], items [many [ty "MoonLsp.DiagnosticPayload"]], },
  sum. Hover {
    Hover {
      kind [ty "MoonEditor.MarkupKind"],
      field "value" [str],
      range [ty "MoonLsp.ProtocolRange"],
    },
    HoverNull,
  },
  product. CompletionPayload {
    label [str],
    kind [number],
    detail [str],
    documentation [str],
    insert_text [str],
    insert_text_format [number],
  },
  product. CompletionList { incomplete [bool], items [many [ty "MoonLsp.CompletionPayload"]], },
  product. DocumentSymbolPayload {
    field "name" [str],
    detail [str],
    kind [number],
    range [ty "MoonLsp.ProtocolRange"],
    selection_range [ty "MoonLsp.ProtocolRange"],
    children [many [ty "MoonLsp.DocumentSymbolPayload"]],
  },
  product. WorkspaceSymbolPayload {
    field "name" [str],
    detail [str],
    kind [number],
    location [ty "MoonLsp.Location"],
    container_name [str],
  },
  product. SignatureParameterPayload { label [str], documentation [str], },
  product. SignatureInformationPayload {
    label [str],
    documentation [str],
    params [many [ty "MoonLsp.SignatureParameterPayload"]],
  },
  product. SignatureHelpPayload {
    signatures [many [ty "MoonLsp.SignatureInformationPayload"]],
    active_signature [number],
    active_parameter [number],
  },
  product. SemanticTokens { data [many [number]], },
  product. DocumentHighlightPayload { range [ty "MoonLsp.ProtocolRange"], kind [number], },
  product. PrepareRenamePayload { range [ty "MoonLsp.ProtocolRange"], placeholder [str], },
  product. TextEditPayload { range [ty "MoonLsp.ProtocolRange"], new_text [str], },
  product. WorkspaceEditPayload {
    uri [ty "MoonSource.DocUri"],
    edits [many [ty "MoonLsp.TextEditPayload"]],
  },
  product. CodeActionPayload {
    title [str],
    kind [str],
    diagnostics [many [ty "MoonLsp.DiagnosticPayload"]],
    edits [many [ty "MoonLsp.WorkspaceEditPayload"]],
  },
  product. FoldingRangePayload {
    start_line [number],
    start_character [number],
    end_line [number],
    end_character [number],
    kind [str],
  },
  product. SelectionRangePayload {
    range [ty "MoonLsp.ProtocolRange"],
    parents [many [ty "MoonLsp.SelectionRangePayload"]],
  },
  product. InlayHintPayload { position [ty "MoonLsp.ProtocolPosition"], label [str], kind [str], },
  sum. Payload {
    PayloadNull,
    PayloadInitialize { result [ty "MoonLsp.InitializeResult"], },
    PayloadDiagnostics { report [ty "MoonLsp.DiagnosticReport"], },
    PayloadDiagnosticDocumentReport { report [ty "MoonLsp.DiagnosticDocumentReport"], },
    PayloadHover { hover [ty "MoonLsp.Hover"], },
    PayloadCompletion { completion [ty "MoonLsp.CompletionList"], },
    PayloadDocumentSymbols { symbols [many [ty "MoonLsp.DocumentSymbolPayload"]], },
    PayloadWorkspaceSymbols { symbols [many [ty "MoonLsp.WorkspaceSymbolPayload"]], },
    PayloadSignatureHelp { help [ty "MoonLsp.SignatureHelpPayload"], },
    PayloadLocations { locations [many [ty "MoonLsp.Location"]], },
    PayloadDocumentHighlights { highlights [many [ty "MoonLsp.DocumentHighlightPayload"]], },
    PayloadPrepareRename { result [ty "MoonLsp.PrepareRenamePayload"], },
    PayloadSemanticTokens { tokens [ty "MoonLsp.SemanticTokens"], },
    PayloadWorkspaceEdit { edits [many [ty "MoonLsp.WorkspaceEditPayload"]], },
    PayloadCodeActions { actions [many [ty "MoonLsp.CodeActionPayload"]], },
    PayloadFoldingRanges { ranges [many [ty "MoonLsp.FoldingRangePayload"]], },
    PayloadSelectionRanges { ranges [many [ty "MoonLsp.SelectionRangePayload"]], },
    PayloadInlayHints { hints [many [ty "MoonLsp.InlayHintPayload"]], },
    PayloadError { code [str], message [str], },
  },
}
