local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonMem {
  product. MemAccessId { interned, text [str], },
  product. MemObjectId { interned, text [str], },
  product. MemBaseId { interned, text [str], },
  product. MemScopeId { interned, text [str], },
  product. MemProofId { interned, text [str], },
  product. MemLeaseId { interned, text [str], },
  sum. MemAccessKind {
    MemLoad,
    MemStore,
    MemAtomicLoad,
    MemAtomicStore,
    MemAtomicRmw,
    MemAtomicCas,
  },
  sum. MemBase {
    MemBaseValue { variant_unique, field. value [ty. MoonCode.CodeValueId], },
    MemBaseLocal { variant_unique, field. local_id [ty. MoonCode.CodeLocalId], },
    MemBaseGlobal { variant_unique, global [ty. MoonCode.CodeGlobalId], },
    MemBaseData { variant_unique, data [ty. MoonCode.CodeDataId], },
    MemBaseArgument {
      variant_unique,
      field. name [str],
      field. value [ty. MoonCode.CodeValueId],
    },
    MemBaseProjection {
      variant_unique,
      base [ty. MoonMem.MemBase],
      projection [ty. MoonMem.MemProjectionKind],
      byte_offset [number],
    },
    MemBaseUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectKind {
    MemObjectParam,
    MemObjectLocal,
    MemObjectGlobal,
    MemObjectData,
    MemObjectView,
    MemObjectSlice,
    MemObjectContract,
    MemObjectDerived,
    MemObjectLease,
    MemObjectUnknown,
  },
  sum. MemProjectionKind {
    MemProjectField,
    MemProjectBytes,
    MemProjectPtrOffset,
    MemProjectViewData,
    MemProjectSlice,
    MemProjectWindow,
    MemProjectElement,
    MemProjectUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectProvenance {
    MemProvValue { variant_unique, field. value [ty. MoonCode.CodeValueId], },
    MemProvLocal { variant_unique, field. local_id [ty. MoonCode.CodeLocalId], },
    MemProvGlobal { variant_unique, global [ty. MoonCode.CodeGlobalId], },
    MemProvData { variant_unique, data [ty. MoonCode.CodeDataId], },
    MemProvView {
      variant_unique,
      view [ty. MoonCode.CodeValueId],
      data [ty. MoonCode.CodeValueId],
      len [ty. MoonCode.CodeValueId],
      stride [optional [ty. MoonCode.CodeValueId]],
    },
    MemProvContract { variant_unique, fact [ty. MoonCode.CodeFuncContractFact], },
    MemProvLease { variant_unique, lease [ty. MoonMem.MemLeaseId], },
    MemProvProjection {
      variant_unique,
      parent [ty. MoonMem.MemObjectId],
      projection [ty. MoonMem.MemProjectionKind],
      byte_offset [number],
    },
    MemProvUnknown { variant_unique, reason [str], },
  },
  sum. MemObjectExtent {
    MemExtentUnknown { variant_unique, reason [str], },
    MemExtentElements {
      variant_unique,
      len [ty. MoonCode.CodeValueId],
      elem_ty [ty. MoonCode.CodeType],
      reason [str],
    },
    MemExtentBytes { variant_unique, bytes [number], reason [str], },
    MemExtentContract { variant_unique, fact [ty. MoonCode.CodeFuncContractFact], reason [str], },
  },
  sum. MemObjectStride {
    MemStrideUnknown { variant_unique, reason [str], },
    MemStrideUnit,
    MemStrideConstElems { variant_unique, elems [number], },
    MemStrideValue { variant_unique, field. value [ty. MoonCode.CodeValueId], },
  },
  product. MemObjectFact {
    interned,
    field. id [ty. MoonMem.MemObjectId],
    func [optional [ty. MoonCode.CodeFuncId]],
    kind [ty. MoonMem.MemObjectKind],
    provenance [ty. MoonMem.MemObjectProvenance],
    elem_ty [optional [ty. MoonCode.CodeType]],
    extent [ty. MoonMem.MemObjectExtent],
    stride [ty. MoonMem.MemObjectStride],
  },
  product. MemLeaseGrant {
    interned,
    field. id [ty. MoonMem.MemLeaseId],
    domain [optional [ty. MoonFlow.FlowDomain]],
    lease_value [ty. MoonCode.CodeValueId],
    handle [optional [ty. MoonCode.CodeValueId]],
    object [ty. MoonMem.MemObjectId],
    base [ty. MoonMem.MemBase],
    extent [ty. MoonMem.MemObjectExtent],
    stride [ty. MoonMem.MemObjectStride],
    proof [ty. MoonMem.MemProof],
  },
  sum. MemIndex {
    MemIndexNone,
    MemIndexValue {
      variant_unique,
      field. value [ty. MoonCode.CodeValueId],
      elem_size [number],
      const_offset [number],
    },
    MemIndexInduction {
      variant_unique,
      induction [ty. MoonFlow.FlowInduction],
      elem_size [number],
      const_offset [number],
    },
  },
  sum. MemAccessPattern {
    MemAccessScalar,
    MemAccessContiguous,
    MemAccessStrided { variant_unique, stride_elems [number], },
    MemAccessGather,
    MemAccessScatter,
    MemAccessUnknown,
  },
  sum. MemAlignment {
    MemAlignUnknown,
    MemAlignKnown { variant_unique, bytes [number], },
    MemAlignAtLeast { variant_unique, bytes [number], },
    MemAlignAssumed { variant_unique, bytes [number], proof [ty. MoonMem.MemProof], },
  },
  sum. MemBounds {
    MemBoundsUnknown { variant_unique, reason [str], },
    MemBoundsInObject { variant_unique, reason [str], },
    MemBoundsRange {
      variant_unique,
      start [ty. MoonCode.CodeValueId],
      len [ty. MoonCode.CodeValueId],
      reason [str],
    },
    MemBoundsAssumed { variant_unique, proof [ty. MoonMem.MemProof], },
  },
  sum. MemTrap {
    MemMayTrap,
    MemNonTrapping { variant_unique, reason [str], },
    MemCheckedTrap { variant_unique, reason [str], },
  },
  product. MemAccessFact {
    interned,
    field. id [ty. MoonMem.MemAccessId],
    func [ty. MoonCode.CodeFuncId],
    block [ty. MoonGraph.GraphBlockId],
    inst [optional [ty. MoonCode.CodeInstId]],
    kind [ty. MoonMem.MemAccessKind],
    place [ty. MoonCode.CodePlace],
    access [ty. MoonCode.CodeMemoryAccess],
    base [ty. MoonMem.MemBase],
    index [ty. MoonMem.MemIndex],
    pattern [ty. MoonMem.MemAccessPattern],
    alignment [ty. MoonMem.MemAlignment],
    bounds [ty. MoonMem.MemBounds],
    trap [ty. MoonMem.MemTrap],
  },
  product. MemAccessInterval {
    interned,
    access [ty. MoonMem.MemAccessId],
    object [ty. MoonMem.MemObjectId],
    loop [optional [ty. MoonGraph.GraphLoopId]],
    start [ty. MoonMem.MemIndex],
    length_elems [ty. MoonFlow.FlowBound],
    elem_size [number],
    const_byte_offset [number],
    reason [str],
  },
  sum. MemAccessSafetyFact {
    MemAccessInBounds {
      variant_unique,
      interval [ty. MoonMem.MemAccessInterval],
      proof [ty. MoonMem.MemProof],
    },
    MemAccessNonTrap {
      variant_unique,
      access [ty. MoonMem.MemAccessId],
      proof [ty. MoonMem.MemProof],
    },
    MemAccessMovable {
      variant_unique,
      access [ty. MoonMem.MemAccessId],
      proof [ty. MoonMem.MemProof],
    },
    MemAccessDerefBytes {
      variant_unique,
      access [ty. MoonMem.MemAccessId],
      bytes [number],
      proof [ty. MoonMem.MemProof],
    },
    MemAccessAlignKnown {
      variant_unique,
      access [ty. MoonMem.MemAccessId],
      bytes [number],
      proof [ty. MoonMem.MemProof],
    },
  },
  sum. MemObjectEffectFact {
    MemObjectReadonly {
      variant_unique,
      object [ty. MoonMem.MemObjectId],
      proof [ty. MoonMem.MemProof],
    },
    MemObjectWriteonly {
      variant_unique,
      object [ty. MoonMem.MemObjectId],
      proof [ty. MoonMem.MemProof],
    },
  },
  sum. MemObjectRelation {
    MemObjectsSameLen {
      variant_unique,
      a [ty. MoonMem.MemObjectId],
      b [ty. MoonMem.MemObjectId],
      proof [ty. MoonMem.MemProof],
    },
    MemObjectWindowOf {
      variant_unique,
      window [ty. MoonMem.MemObjectId],
      parent [ty. MoonMem.MemObjectId],
      start [ty. MoonCode.CodeValueId],
      len [ty. MoonCode.CodeValueId],
      proof [ty. MoonMem.MemProof],
    },
    MemObjectSliceOf {
      variant_unique,
      slice [ty. MoonMem.MemObjectId],
      parent [ty. MoonMem.MemObjectId],
      start [ty. MoonCode.CodeValueId],
      len [ty. MoonCode.CodeValueId],
      proof [ty. MoonMem.MemProof],
    },
    MemObjectSameStore {
      variant_unique,
      a [ty. MoonMem.MemObjectId],
      b [ty. MoonMem.MemObjectId],
      proof [ty. MoonMem.MemProof],
    },
  },
  sum. MemAliasFact {
    MemAliasUnknown {
      variant_unique,
      a [ty. MoonMem.MemAccessId],
      b [ty. MoonMem.MemAccessId],
      reason [str],
    },
    MemMayAlias {
      variant_unique,
      a [ty. MoonMem.MemAccessId],
      b [ty. MoonMem.MemAccessId],
      reason [str],
    },
    MemNoAlias {
      variant_unique,
      a [ty. MoonMem.MemAccessId],
      b [ty. MoonMem.MemAccessId],
      proof [ty. MoonMem.MemProof],
    },
    MemSameBaseSameIndexSafe {
      variant_unique,
      a [ty. MoonMem.MemAccessId],
      b [ty. MoonMem.MemAccessId],
      proof [ty. MoonMem.MemProof],
    },
    MemAliasScope {
      variant_unique,
      access [ty. MoonMem.MemAccessId],
      scope [ty. MoonMem.MemScopeId],
    },
  },
  sum. MemDependenceFact {
    MemDependenceUnknown {
      variant_unique,
      before [ty. MoonMem.MemAccessId],
      after [ty. MoonMem.MemAccessId],
      reason [str],
    },
    MemReadReadIndependent {
      variant_unique,
      a [ty. MoonMem.MemAccessId],
      b [ty. MoonMem.MemAccessId],
      reason [str],
    },
    MemNoDependence {
      variant_unique,
      before [ty. MoonMem.MemAccessId],
      after [ty. MoonMem.MemAccessId],
      proof [ty. MoonMem.MemProof],
    },
    MemNoLoopCarriedDependence {
      variant_unique,
      before [ty. MoonMem.MemAccessId],
      after [ty. MoonMem.MemAccessId],
      loop [ty. MoonGraph.GraphLoopId],
      proof [ty. MoonMem.MemProof],
    },
    MemDependenceDistance {
      variant_unique,
      before [ty. MoonMem.MemAccessId],
      after [ty. MoonMem.MemAccessId],
      loop [ty. MoonGraph.GraphLoopId],
      distance_elems [str],
      proof [ty. MoonMem.MemProof],
    },
    MemLoopCarriedDependence {
      variant_unique,
      before [ty. MoonMem.MemAccessId],
      after [ty. MoonMem.MemAccessId],
      loop [ty. MoonGraph.GraphLoopId],
      reason [str],
    },
  },
  sum. MemProof {
    MemProofBounds { variant_unique, reason [str], },
    MemProofAlignment { variant_unique, reason [str], },
    MemProofAlias { variant_unique, fact [ty. MoonMem.MemAliasFact], reason [str], },
    MemProofNoDependence {
      variant_unique,
      accesses [many [ty. MoonMem.MemAccessId]],
      reason [str],
    },
    MemProofContract { variant_unique, fact [ty. MoonCode.CodeFuncContractFact], reason [str], },
    MemProofFlow { variant_unique, loop [ty. MoonGraph.GraphLoopId], reason [str], },
    MemProofObject { variant_unique, object [ty. MoonMem.MemObjectId], reason [str], },
    MemProofInterval { variant_unique, interval [ty. MoonMem.MemAccessInterval], reason [str], },
    MemProofBackend { variant_unique, access [ty. MoonMem.MemAccessId], reason [str], },
  },
  product. MemBackendAccessInfo {
    interned,
    access [ty. MoonMem.MemAccessId],
    trap [ty. MoonMem.MemTrap],
    alignment [ty. MoonMem.MemAlignment],
    bounds [ty. MoonMem.MemBounds],
    deref_bytes [optional [number]],
    movable [bool],
    proofs [many [ty. MoonMem.MemProof]],
  },
  product. MemSemanticFactSet {
    interned,
    field. module [ty. MoonCode.CodeModuleId],
    objects [many [ty. MoonMem.MemObjectFact]],
    leases [many [ty. MoonMem.MemLeaseGrant]],
    accesses [many [ty. MoonMem.MemAccessFact]],
    intervals [many [ty. MoonMem.MemAccessInterval]],
    safety [many [ty. MoonMem.MemAccessSafetyFact]],
    effects [many [ty. MoonMem.MemObjectEffectFact]],
    dependences [many [ty. MoonMem.MemDependenceFact]],
    relations [many [ty. MoonMem.MemObjectRelation]],
    backend_info [many [ty. MoonMem.MemBackendAccessInfo]],
    proofs [many [ty. MoonMem.MemProof]],
  },
  product. MemFactSet {
    interned,
    field. module [ty. MoonCode.CodeModuleId],
    accesses [many [ty. MoonMem.MemAccessFact]],
    aliases [many [ty. MoonMem.MemAliasFact]],
    dependences [many [ty. MoonMem.MemDependenceFact]],
    proofs [many [ty. MoonMem.MemProof]],
  },
}
