local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonOpen {
  product. TypeSlot { interned, key [str], pretty_name [str], },
  product. ValueSlot { interned, key [str], pretty_name [str], field. ty [ty. MoonType.Type], },
  product. ExprSlot {
    interned,
    key [str],
    pretty_name [str],
    field. ty [optional [ty. MoonType.Type]],
  },
  product. PlaceSlot {
    interned,
    key [str],
    pretty_name [str],
    field. ty [optional [ty. MoonType.Type]],
  },
  product. DomainSlot { interned, key [str], pretty_name [str], },
  product. RegionSlot { interned, key [str], pretty_name [str], },
  product. ContSlot {
    interned,
    key [str],
    pretty_name [str],
    params [many [ty. MoonTree.BlockParam]],
  },
  product. FuncSlot { interned, key [str], pretty_name [str], fn_ty [ty. MoonType.Type], },
  product. ConstSlot { interned, key [str], pretty_name [str], field. ty [ty. MoonType.Type], },
  product. StaticSlot { interned, key [str], pretty_name [str], field. ty [ty. MoonType.Type], },
  product. TypeDeclSlot { interned, key [str], pretty_name [str], },
  product. ItemsSlot { interned, key [str], pretty_name [str], },
  product. ModuleSlot { interned, key [str], pretty_name [str], },
  product. NameSlot { interned, key [str], pretty_name [str], },
  product. RegionFragSlot { interned, key [str], pretty_name [str], },
  product. ExprFragSlot { interned, key [str], pretty_name [str], },
  sum. RegionFragRef {
    RegionFragRefName { variant_unique, field. name [str], },
    RegionFragRefSlot { variant_unique, slot [ty. MoonOpen.RegionFragSlot], },
  },
  sum. ExprFragRef {
    ExprFragRefName { variant_unique, field. name [str], },
    ExprFragRefSlot { variant_unique, slot [ty. MoonOpen.ExprFragSlot], },
  },
  sum. NameRef {
    NameRefText { variant_unique, text [str], },
    NameRefSlot { variant_unique, slot [ty. MoonOpen.NameSlot], },
  },
  sum. Slot {
    SlotType { variant_unique, slot [ty. MoonOpen.TypeSlot], },
    SlotValue { variant_unique, slot [ty. MoonOpen.ValueSlot], },
    SlotExpr { variant_unique, slot [ty. MoonOpen.ExprSlot], },
    SlotPlace { variant_unique, slot [ty. MoonOpen.PlaceSlot], },
    SlotDomain { variant_unique, slot [ty. MoonOpen.DomainSlot], },
    SlotRegion { variant_unique, slot [ty. MoonOpen.RegionSlot], },
    SlotCont { variant_unique, slot [ty. MoonOpen.ContSlot], },
    SlotFunc { variant_unique, slot [ty. MoonOpen.FuncSlot], },
    SlotConst { variant_unique, slot [ty. MoonOpen.ConstSlot], },
    SlotStatic { variant_unique, slot [ty. MoonOpen.StaticSlot], },
    SlotTypeDecl { variant_unique, slot [ty. MoonOpen.TypeDeclSlot], },
    SlotItems { variant_unique, slot [ty. MoonOpen.ItemsSlot], },
    SlotModule { variant_unique, slot [ty. MoonOpen.ModuleSlot], },
    SlotRegionFrag { variant_unique, slot [ty. MoonOpen.RegionFragSlot], },
    SlotExprFrag { variant_unique, slot [ty. MoonOpen.ExprFragSlot], },
    SlotName { variant_unique, slot [ty. MoonOpen.NameSlot], },
  },
  sum. ModuleNameFacet { ModuleNameOpen, ModuleNameFixed { variant_unique, module_name [str], }, },
  product. OpenParam { interned, key [str], field. name [str], field. ty [ty. MoonType.Type], },
  sum. ValueImport {
    ImportValue { variant_unique, key [str], field. name [str], field. ty [ty. MoonType.Type], },
    ImportGlobalFunc {
      variant_unique,
      key [str],
      module_name [str],
      item_name [str],
      field. ty [ty. MoonType.Type],
    },
    ImportGlobalConst {
      variant_unique,
      key [str],
      module_name [str],
      item_name [str],
      field. ty [ty. MoonType.Type],
    },
    ImportGlobalStatic {
      variant_unique,
      key [str],
      module_name [str],
      item_name [str],
      field. ty [ty. MoonType.Type],
    },
    ImportExtern { variant_unique, key [str], symbol [str], field. ty [ty. MoonType.Type], },
  },
  product. TypeImport { interned, key [str], local_name [str], field. ty [ty. MoonType.Type], },
  product. OpenSet {
    interned,
    value_imports [many [ty. MoonOpen.ValueImport]],
    type_imports [many [ty. MoonOpen.TypeImport]],
    layouts [many [ty. MoonSem.TypeLayout]],
    slots [many [ty. MoonOpen.Slot]],
  },
  sum. SourceBinding {
    SourceParamBinding { variant_unique, param [ty. MoonOpen.OpenParam], },
    SourceValueImportBinding { variant_unique, import [ty. MoonOpen.ValueImport], },
    SourceExprSlotBinding { variant_unique, slot [ty. MoonOpen.ExprSlot], },
    SourceFuncSlotBinding { variant_unique, slot [ty. MoonOpen.FuncSlot], },
    SourceConstSlotBinding { variant_unique, slot [ty. MoonOpen.ConstSlot], },
    SourceStaticSlotBinding { variant_unique, slot [ty. MoonOpen.StaticSlot], },
  },
  product. SourceBindingEntry {
    interned,
    binding [ty. MoonBind.Binding],
    source [ty. MoonOpen.SourceBinding],
  },
  product. SourceTypeEntry {
    interned,
    field. ty [ty. MoonType.Type],
    meta_ty [ty. MoonType.Type],
  },
  product. HostPath { interned, path [ty. MoonCore.Path], },
  sum. HostFacet {
    HostFacetType { variant_unique, slot [ty. MoonOpen.TypeSlot], },
    HostFacetLocalType { variant_unique, local_name [str], },
    HostFacetExpr { variant_unique, slot [ty. MoonOpen.ExprSlot], },
    HostFacetFunc { variant_unique, slot [ty. MoonOpen.ExprSlot], },
    HostFacetRegionFrag { variant_unique, slot [ty. MoonOpen.RegionFragSlot], },
    HostFacetExprFrag { variant_unique, slot [ty. MoonOpen.ExprFragSlot], },
    HostFacetModule { variant_unique, slot [ty. MoonOpen.ModuleSlot], },
  },
  product. HostBinding {
    interned,
    path [ty. MoonOpen.HostPath],
    facets [many [ty. MoonOpen.HostFacet]],
  },
  product. SourceEnv {
    interned,
    module_name [str],
    bindings [many [ty. MoonOpen.SourceBindingEntry]],
    types [many [ty. MoonOpen.SourceTypeEntry]],
    host_bindings [many [ty. MoonOpen.HostBinding]],
  },
  product. FragId { interned, key [str], pretty_name [str], },
  product. UseId { interned, path [str], },
  sum. ContTarget {
    ContTargetLabel { variant_unique, label [ty. MoonTree.BlockLabel], },
    ContTargetSlot { variant_unique, slot [ty. MoonOpen.ContSlot], },
  },
  product. ContBinding { interned, field. name [str], target [ty. MoonOpen.ContTarget], },
  product. ParamBinding {
    interned,
    param [ty. MoonOpen.OpenParam],
    field. value [ty. MoonTree.Expr],
  },
  product. FillSet { interned, bindings [many [ty. MoonOpen.SlotBinding]], },
  product. ExpandEnv {
    interned,
    region_frags [many [ty. MoonOpen.RegionFrag]],
    expr_frags [many [ty. MoonOpen.ExprFrag]],
    fills [ty. MoonOpen.FillSet],
    conts [many [ty. MoonOpen.ContBinding]],
    params [many [ty. MoonOpen.ParamBinding]],
    rebase_prefix [str],
  },
  product. SealParamEntry { interned, param [ty. MoonOpen.OpenParam], index [number], },
  product. SealEnv { interned, module_name [str], params [many [ty. MoonOpen.SealParamEntry]], },
  product. ExprFrag {
    interned,
    field. name [ty. MoonOpen.NameRef],
    params [many [ty. MoonOpen.OpenParam]],
    open [ty. MoonOpen.OpenSet],
    body [ty. MoonTree.Expr],
    result [ty. MoonType.Type],
  },
  product. RegionFrag {
    interned,
    field. name [ty. MoonOpen.NameRef],
    params [many [ty. MoonOpen.OpenParam]],
    conts [many [ty. MoonOpen.ContSlot]],
    open [ty. MoonOpen.OpenSet],
    entry [ty. MoonTree.EntryControlBlock],
    blocks [many [ty. MoonTree.ControlBlock]],
  },
  product. RegionFragDecl {
    interned,
    field. name [ty. MoonOpen.NameRef],
    params [many [ty. MoonOpen.OpenParam]],
    conts [many [ty. MoonOpen.ContSlot]],
  },
  sum. SlotValue {
    SlotValueType { variant_unique, field. ty [ty. MoonType.Type], },
    SlotValueExpr { variant_unique, field. expr [ty. MoonTree.Expr], },
    SlotValueExprs { variant_unique, exprs [many [ty. MoonTree.Expr]], },
    SlotValueTypes { variant_unique, types [many [ty. MoonType.Type]], },
    SlotValueParams { variant_unique, params [many [ty. MoonType.Param]], },
    SlotValueFields { variant_unique, fields [many [ty. MoonType.FieldDecl]], },
    SlotValueVariants { variant_unique, variants [many [ty. MoonType.VariantDecl]], },
    SlotValueBlockParams { variant_unique, params [many [ty. MoonTree.BlockParam]], },
    SlotValueEntryParams { variant_unique, params [many [ty. MoonTree.EntryBlockParam]], },
    SlotValueOpenParams { variant_unique, params [many [ty. MoonOpen.OpenParam]], },
    SlotValueContSlots { variant_unique, conts [many [ty. MoonOpen.ContSlot]], },
    SlotValueControlBlocks { variant_unique, blocks [many [ty. MoonTree.ControlBlock]], },
    SlotValueSwitchStmtArms { variant_unique, arms [many [ty. MoonTree.SwitchStmtArm]], },
    SlotValueSwitchExprArms { variant_unique, arms [many [ty. MoonTree.SwitchExprArm]], },
    SlotValuePlace { variant_unique, place [ty. MoonTree.Place], },
    SlotValueDomain { variant_unique, domain [ty. MoonTree.Domain], },
    SlotValueRegion { variant_unique, body [many [ty. MoonTree.Stmt]], },
    SlotValueCont { variant_unique, label [ty. MoonTree.BlockLabel], },
    SlotValueContSlot { variant_unique, slot [ty. MoonOpen.ContSlot], },
    SlotValueFunc { variant_unique, func [ty. MoonTree.Func], },
    SlotValueConst { variant_unique, c [ty. MoonTree.ConstItem], },
    SlotValueStatic { variant_unique, s [ty. MoonTree.StaticItem], },
    SlotValueTypeDecl { variant_unique, t [ty. MoonTree.TypeDecl], },
    SlotValueItems { variant_unique, items [many [ty. MoonTree.Item]], },
    SlotValueModule { variant_unique, field. module [ty. MoonTree.Module], },
    SlotValueRegionFrag { variant_unique, frag [ty. MoonOpen.RegionFrag], },
    SlotValueExprFrag { variant_unique, frag [ty. MoonOpen.ExprFrag], },
    SlotValueName { variant_unique, text [str], },
  },
  product. SlotBinding {
    interned,
    slot [ty. MoonOpen.Slot],
    field. value [ty. MoonOpen.SlotValue],
  },
  sum. RewriteRule {
    RewriteType { variant_unique, from [ty. MoonType.Type], to [ty. MoonType.Type], },
    RewriteBinding { variant_unique, from [ty. MoonBind.Binding], to [ty. MoonBind.Binding], },
    RewritePlace { variant_unique, from [ty. MoonTree.Place], to [ty. MoonTree.Place], },
    RewriteDomain { variant_unique, from [ty. MoonTree.Domain], to [ty. MoonTree.Domain], },
    RewriteExpr { variant_unique, from [ty. MoonTree.Expr], to [ty. MoonTree.Expr], },
    RewriteStmt { variant_unique, from [ty. MoonTree.Stmt], to [many [ty. MoonTree.Stmt]], },
    RewriteItem { variant_unique, from [ty. MoonTree.Item], to [many [ty. MoonTree.Item]], },
  },
  product. RewriteSet { interned, rules [many [ty. MoonOpen.RewriteRule]], },
  sum. MetaFact {
    MetaFactSlot { variant_unique, slot [ty. MoonOpen.Slot], },
    MetaFactParamUse { variant_unique, param [ty. MoonOpen.OpenParam], },
    MetaFactValueImportUse { variant_unique, import [ty. MoonOpen.ValueImport], },
    MetaFactLocalValue { variant_unique, field. id [str], field. name [str], },
    MetaFactLocalCell { variant_unique, field. id [str], field. name [str], },
    MetaFactBlockParam {
      variant_unique,
      region_id [str],
      block_name [str],
      index [number],
      field. name [str],
    },
    MetaFactEntryBlockParam {
      variant_unique,
      region_id [str],
      block_name [str],
      index [number],
      field. name [str],
    },
    MetaFactGlobalFunc { variant_unique, module_name [str], item_name [str], },
    MetaFactGlobalConst { variant_unique, module_name [str], item_name [str], },
    MetaFactGlobalStatic { variant_unique, module_name [str], item_name [str], },
    MetaFactExtern { variant_unique, symbol [str], },
    MetaFactExprFragUse { variant_unique, use_id [str], },
    MetaFactRegionFragUse { variant_unique, use_id [str], },
    MetaFactRegionFragSlotUse { variant_unique, slot [ty. MoonOpen.RegionFragSlot], },
    MetaFactExprFragSlotUse { variant_unique, slot [ty. MoonOpen.ExprFragSlot], },
    MetaFactModuleUse { variant_unique, use_id [str], },
    MetaFactModuleSlotUse { variant_unique, use_id [str], slot [ty. MoonOpen.ModuleSlot], },
    MetaFactOpenModuleName,
    MetaFactLocalType { variant_unique, sym [ty. MoonCore.TypeSym], },
  },
  product. MetaFactSet { interned, facts [many [ty. MoonOpen.MetaFact]], },
  sum. ValidationIssue {
    IssueOpenSlot { variant_unique, slot [ty. MoonOpen.Slot], },
    IssueUnfilledTypeSlot { variant_unique, slot [ty. MoonOpen.TypeSlot], },
    IssueUnfilledExprSlot { variant_unique, slot [ty. MoonOpen.ExprSlot], },
    IssueUnfilledPlaceSlot { variant_unique, slot [ty. MoonOpen.PlaceSlot], },
    IssueUnfilledDomainSlot { variant_unique, slot [ty. MoonOpen.DomainSlot], },
    IssueUnfilledRegionSlot { variant_unique, slot [ty. MoonOpen.RegionSlot], },
    IssueUnfilledContSlot { variant_unique, slot [ty. MoonOpen.ContSlot], },
    IssueUnfilledFuncSlot { variant_unique, slot [ty. MoonOpen.FuncSlot], },
    IssueUnfilledConstSlot { variant_unique, slot [ty. MoonOpen.ConstSlot], },
    IssueUnfilledStaticSlot { variant_unique, slot [ty. MoonOpen.StaticSlot], },
    IssueUnfilledTypeDeclSlot { variant_unique, slot [ty. MoonOpen.TypeDeclSlot], },
    IssueUnfilledItemsSlot { variant_unique, slot [ty. MoonOpen.ItemsSlot], },
    IssueUnfilledModuleSlot { variant_unique, slot [ty. MoonOpen.ModuleSlot], },
    IssueUnexpandedExprFragUse { variant_unique, use_id [str], },
    IssueUnexpandedRegionFragUse { variant_unique, use_id [str], },
    IssueUnfilledRegionFragSlot { variant_unique, slot [ty. MoonOpen.RegionFragSlot], },
    IssueUnfilledExprFragSlot { variant_unique, slot [ty. MoonOpen.ExprFragSlot], },
    IssueUnfilledNameSlot { variant_unique, slot [ty. MoonOpen.NameSlot], },
    IssueUnexpandedModuleUse { variant_unique, use_id [str], },
    IssueOpenModuleName,
    IssueGenericValueImport { variant_unique, import [ty. MoonOpen.ValueImport], },
  },
  product. ValidationReport { interned, issues [many [ty. MoonOpen.ValidationIssue]], },
}
