local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonTree {
  sum. ExprHeader {
    ExprSurface,
    ExprTyped { variant_unique, field "ty" [ty "MoonType.Type"], },
    ExprOpen { variant_unique, field "ty" [ty "MoonType.Type"], open [ty "MoonOpen.OpenSet"], },
  },
  sum. PlaceHeader {
    PlaceSurface,
    PlaceTyped { variant_unique, field "ty" [ty "MoonType.Type"], },
    PlaceOpen { variant_unique, field "ty" [ty "MoonType.Type"], open [ty "MoonOpen.OpenSet"], },
  },
  sum. StmtHeader {
    StmtSurface,
    StmtOpen { variant_unique, open [ty "MoonOpen.OpenSet"], },
    StmtFlow { variant_unique, flow [ty "MoonSem.FlowClass"], },
  },
  sum. RegionUseMode { RegionUseEmit, RegionUseCall, },
  product. FieldInit {
    interned,
    field "name" [str],
    field "value" [ty "MoonTree.Expr"],
    offset [number],
  },
  product. VariantBind { interned, field "name" [str], field "ty" [ty "MoonType.Type"], },
  product. SwitchStmtArm { interned, raw_key [str], body [many [ty "MoonTree.Stmt"]], },
  product. SwitchExprArm {
    interned,
    raw_key [str],
    body [many [ty "MoonTree.Stmt"]],
    result [ty "MoonTree.Expr"],
  },
  product. SwitchVariantStmtArm {
    interned,
    variant_name [str],
    binds [many [ty "MoonTree.VariantBind"]],
    body [many [ty "MoonTree.Stmt"]],
  },
  product. SwitchVariantExprArm {
    interned,
    variant_name [str],
    binds [many [ty "MoonTree.VariantBind"]],
    body [many [ty "MoonTree.Stmt"]],
    result [ty "MoonTree.Expr"],
  },
  sum. View {
    ViewFromExpr { variant_unique, base [ty "MoonTree.Expr"], elem [ty "MoonType.Type"], },
    ViewContiguous {
      variant_unique,
      data [ty "MoonTree.Expr"],
      elem [ty "MoonType.Type"],
      len [ty "MoonTree.Expr"],
    },
    ViewStrided {
      variant_unique,
      data [ty "MoonTree.Expr"],
      elem [ty "MoonType.Type"],
      len [ty "MoonTree.Expr"],
      stride [ty "MoonTree.Expr"],
    },
    ViewRestrided {
      variant_unique,
      base [ty "MoonTree.View"],
      elem [ty "MoonType.Type"],
      stride [ty "MoonTree.Expr"],
    },
    ViewWindow {
      variant_unique,
      base [ty "MoonTree.View"],
      start [ty "MoonTree.Expr"],
      len [ty "MoonTree.Expr"],
    },
    ViewRowBase {
      variant_unique,
      base [ty "MoonTree.View"],
      row_offset [ty "MoonTree.Expr"],
      elem [ty "MoonType.Type"],
    },
    ViewInterleaved {
      variant_unique,
      data [ty "MoonTree.Expr"],
      elem [ty "MoonType.Type"],
      len [ty "MoonTree.Expr"],
      stride [ty "MoonTree.Expr"],
      lane [ty "MoonTree.Expr"],
    },
    ViewInterleavedView {
      variant_unique,
      base [ty "MoonTree.View"],
      elem [ty "MoonType.Type"],
      stride [ty "MoonTree.Expr"],
      lane [ty "MoonTree.Expr"],
    },
  },
  sum. Domain {
    DomainRange { variant_unique, stop [ty "MoonTree.Expr"], },
    DomainRange2 { variant_unique, start [ty "MoonTree.Expr"], stop [ty "MoonTree.Expr"], },
    DomainZipEqValues { variant_unique, values [many [ty "MoonTree.Expr"]], },
    DomainValue { variant_unique, field "value" [ty "MoonTree.Expr"], },
    DomainView { variant_unique, view [ty "MoonTree.View"], },
    DomainZipEqViews { variant_unique, views [many [ty "MoonTree.View"]], },
    DomainSlotValue { variant_unique, slot [ty "MoonOpen.DomainSlot"], },
  },
  sum. IndexBase {
    IndexBaseExpr { variant_unique, base [ty "MoonTree.Expr"], },
    IndexBasePlace { variant_unique, base [ty "MoonTree.Place"], elem [ty "MoonType.Type"], },
    IndexBaseView { variant_unique, view [ty "MoonTree.View"], },
  },
  sum. Place {
    PlaceRef {
      variant_unique,
      h [ty "MoonTree.PlaceHeader"],
      field "ref" [ty "MoonBind.ValueRef"],
    },
    PlaceDeref { variant_unique, h [ty "MoonTree.PlaceHeader"], base [ty "MoonTree.Expr"], },
    PlaceDot {
      variant_unique,
      h [ty "MoonTree.PlaceHeader"],
      base [ty "MoonTree.Place"],
      field "name" [str],
    },
    PlaceField {
      variant_unique,
      h [ty "MoonTree.PlaceHeader"],
      base [ty "MoonTree.Place"],
      field "field" [ty "MoonSem.FieldRef"],
    },
    PlaceIndex {
      variant_unique,
      h [ty "MoonTree.PlaceHeader"],
      base [ty "MoonTree.IndexBase"],
      index [ty "MoonTree.Expr"],
    },
    PlaceSlotValue {
      variant_unique,
      h [ty "MoonTree.PlaceHeader"],
      slot [ty "MoonOpen.PlaceSlot"],
    },
  },
  product. BlockLabel { interned, field "name" [str], },
  product. BlockParam { interned, field "name" [str], field "ty" [ty "MoonType.Type"], },
  product. EntryBlockParam {
    interned,
    field "name" [str],
    field "ty" [ty "MoonType.Type"],
    init [ty "MoonTree.Expr"],
  },
  product. JumpArg { interned, field "name" [str], field "value" [ty "MoonTree.Expr"], },
  sum. FuncContract {
    ContractBounds { variant_unique, base [ty "MoonTree.Expr"], len [ty "MoonTree.Expr"], },
    ContractWindowBounds {
      variant_unique,
      base [ty "MoonTree.Expr"],
      base_len [ty "MoonTree.Expr"],
      start [ty "MoonTree.Expr"],
      len [ty "MoonTree.Expr"],
    },
    ContractDisjoint { variant_unique, a [ty "MoonTree.Expr"], b [ty "MoonTree.Expr"], },
    ContractSameLen { variant_unique, a [ty "MoonTree.Expr"], b [ty "MoonTree.Expr"], },
    ContractNoAlias { variant_unique, base [ty "MoonTree.Expr"], },
    ContractReadonly { variant_unique, base [ty "MoonTree.Expr"], },
    ContractWriteonly { variant_unique, base [ty "MoonTree.Expr"], },
    ContractInvalidate { variant_unique, base [ty "MoonTree.Expr"], },
    ContractPreserve { variant_unique, base [ty "MoonTree.Expr"], },
  },
  sum. ContractFact {
    ContractFactBounds {
      variant_unique,
      base [ty "MoonBind.Binding"],
      len [ty "MoonBind.Binding"],
    },
    ContractFactWindowBounds {
      variant_unique,
      base [ty "MoonBind.Binding"],
      base_len [ty "MoonTree.Expr"],
      start [ty "MoonTree.Expr"],
      len [ty "MoonTree.Expr"],
    },
    ContractFactDisjoint { variant_unique, a [ty "MoonBind.Binding"], b [ty "MoonBind.Binding"], },
    ContractFactSameLen { variant_unique, a [ty "MoonBind.Binding"], b [ty "MoonBind.Binding"], },
    ContractFactNoAlias { variant_unique, base [ty "MoonBind.Binding"], },
    ContractFactReadonly { variant_unique, base [ty "MoonBind.Binding"], },
    ContractFactWriteonly { variant_unique, base [ty "MoonBind.Binding"], },
    ContractFactInvalidate { variant_unique, base [ty "MoonBind.Binding"], },
    ContractFactPreserve { variant_unique, base [ty "MoonBind.Binding"], },
    ContractFactRejected { variant_unique, issue [ty "MoonTree.TypeIssue"], },
  },
  product. ContractFactSet { interned, facts [many [ty "MoonTree.ContractFact"]], },
  product. EntryControlBlock {
    interned,
    label [ty "MoonTree.BlockLabel"],
    params [many [ty "MoonTree.EntryBlockParam"]],
    body [many [ty "MoonTree.Stmt"]],
  },
  product. ControlBlock {
    interned,
    label [ty "MoonTree.BlockLabel"],
    params [many [ty "MoonTree.BlockParam"]],
    body [many [ty "MoonTree.Stmt"]],
  },
  product. ControlStmtRegion {
    interned,
    region_id [str],
    entry [ty "MoonTree.EntryControlBlock"],
    blocks [many [ty "MoonTree.ControlBlock"]],
  },
  product. ControlExprRegion {
    interned,
    region_id [str],
    result_ty [ty "MoonType.Type"],
    entry [ty "MoonTree.EntryControlBlock"],
    blocks [many [ty "MoonTree.ControlBlock"]],
  },
  sum. ControlFact {
    ControlFactEntryBlock { variant_unique, region_id [str], label [ty "MoonTree.BlockLabel"], },
    ControlFactBlock { variant_unique, region_id [str], label [ty "MoonTree.BlockLabel"], },
    ControlFactEntryParam {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      index [number],
      field "name" [str],
      field "ty" [ty "MoonType.Type"],
    },
    ControlFactBlockParam {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      index [number],
      field "name" [str],
      field "ty" [ty "MoonType.Type"],
    },
    ControlFactJump {
      variant_unique,
      region_id [str],
      from_label [ty "MoonTree.BlockLabel"],
      to_label [ty "MoonTree.BlockLabel"],
    },
    ControlFactJumpArg {
      variant_unique,
      region_id [str],
      from_label [ty "MoonTree.BlockLabel"],
      to_label [ty "MoonTree.BlockLabel"],
      field "name" [str],
      field "ty" [ty "MoonType.Type"],
    },
    ControlFactYieldVoid { variant_unique, region_id [str], from_label [ty "MoonTree.BlockLabel"], },
    ControlFactYieldValue {
      variant_unique,
      region_id [str],
      from_label [ty "MoonTree.BlockLabel"],
      field "ty" [ty "MoonType.Type"],
    },
    ControlFactReturn { variant_unique, region_id [str], from_label [ty "MoonTree.BlockLabel"], },
    ControlFactBackedge {
      variant_unique,
      region_id [str],
      from_label [ty "MoonTree.BlockLabel"],
      to_label [ty "MoonTree.BlockLabel"],
    },
    ControlFactVariantSwitch {
      variant_unique,
      region_id [str],
      from_label [ty "MoonTree.BlockLabel"],
      switch_on [str],
      arms [many [ty "MoonTree.ControlVariantArmFact"]],
      default_label [ty "MoonTree.BlockLabel"],
    },
  },
  product. ControlVariantArmFact {
    interned,
    variant_name [str],
    tag_value [number],
    label [ty "MoonTree.BlockLabel"],
    binds [many [ty "MoonTree.BlockParam"]],
  },
  product. ControlFactSet { interned, facts [many [ty "MoonTree.ControlFact"]], },
  sum. ControlReject {
    ControlRejectDuplicateLabel {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
    },
    ControlRejectMissingLabel { variant_unique, region_id [str], label [ty "MoonTree.BlockLabel"], },
    ControlRejectMissingJumpArg {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      field "name" [str],
    },
    ControlRejectExtraJumpArg {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      field "name" [str],
    },
    ControlRejectDuplicateJumpArg {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      field "name" [str],
    },
    ControlRejectJumpType {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      field "name" [str],
      expected [ty "MoonType.Type"],
      actual [ty "MoonType.Type"],
    },
    ControlRejectYieldOutsideRegion { variant_unique, reason [str], },
    ControlRejectYieldType {
      variant_unique,
      region_id [str],
      expected [ty "MoonType.Type"],
      actual [ty "MoonType.Type"],
    },
    ControlRejectUnterminatedBlock {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
    },
    ControlRejectIrreducible { variant_unique, region_id [str], reason [str], },
    ControlRejectUnknownVariant { variant_unique, region_id [str], variant_name [str], },
  },
  sum. ControlDecision {
    ControlDecisionReducible {
      variant_unique,
      region_id [str],
      facts [many [ty "MoonTree.ControlFact"]],
    },
    ControlDecisionIrreducible {
      variant_unique,
      region_id [str],
      reject [ty "MoonTree.ControlReject"],
    },
  },
  sum. Expr {
    ExprLit { variant_unique, h [ty "MoonTree.ExprHeader"], field "value" [ty "MoonCore.Literal"], },
    ExprRef { variant_unique, h [ty "MoonTree.ExprHeader"], field "ref" [ty "MoonBind.ValueRef"], },
    ExprDot {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      base [ty "MoonTree.Expr"],
      field "name" [str],
    },
    ExprUnary {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      op [ty "MoonCore.UnaryOp"],
      field "value" [ty "MoonTree.Expr"],
    },
    ExprBinary {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      op [ty "MoonCore.BinaryOp"],
      lhs [ty "MoonTree.Expr"],
      rhs [ty "MoonTree.Expr"],
    },
    ExprCompare {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      op [ty "MoonCore.CmpOp"],
      lhs [ty "MoonTree.Expr"],
      rhs [ty "MoonTree.Expr"],
    },
    ExprLogic {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      op [ty "MoonCore.LogicOp"],
      lhs [ty "MoonTree.Expr"],
      rhs [ty "MoonTree.Expr"],
    },
    ExprCast {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      op [ty "MoonCore.SurfaceCastOp"],
      field "ty" [ty "MoonType.Type"],
      field "value" [ty "MoonTree.Expr"],
    },
    ExprMachineCast {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      op [ty "MoonCore.MachineCastOp"],
      field "ty" [ty "MoonType.Type"],
      field "value" [ty "MoonTree.Expr"],
    },
    ExprIntrinsic {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      op [ty "MoonCore.Intrinsic"],
      args [many [ty "MoonTree.Expr"]],
    },
    ExprAddrOf { variant_unique, h [ty "MoonTree.ExprHeader"], place [ty "MoonTree.Place"], },
    ExprDeref { variant_unique, h [ty "MoonTree.ExprHeader"], field "value" [ty "MoonTree.Expr"], },
    ExprCall {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      callee [ty "MoonTree.Expr"],
      args [many [ty "MoonTree.Expr"]],
    },
    ExprLen { variant_unique, h [ty "MoonTree.ExprHeader"], field "value" [ty "MoonTree.Expr"], },
    ExprField {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      base [ty "MoonTree.Expr"],
      field "field" [ty "MoonSem.FieldRef"],
    },
    ExprIndex {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      base [ty "MoonTree.IndexBase"],
      index [ty "MoonTree.Expr"],
    },
    ExprAgg {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      field "ty" [ty "MoonType.Type"],
      fields [many [ty "MoonTree.FieldInit"]],
    },
    ExprArray {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      elem_ty [ty "MoonType.Type"],
      elems [many [ty "MoonTree.Expr"]],
    },
    ExprIf {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      cond [ty "MoonTree.Expr"],
      then_expr [ty "MoonTree.Expr"],
      else_expr [ty "MoonTree.Expr"],
    },
    ExprSelect {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      cond [ty "MoonTree.Expr"],
      then_expr [ty "MoonTree.Expr"],
      else_expr [ty "MoonTree.Expr"],
    },
    ExprSwitch {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      field "value" [ty "MoonTree.Expr"],
      arms [many [ty "MoonTree.SwitchExprArm"]],
      variant_arms [many [ty "MoonTree.SwitchVariantExprArm"]],
      default_body [many [ty "MoonTree.Stmt"]],
      default_expr [ty "MoonTree.Expr"],
    },
    ExprControl {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      region [ty "MoonTree.ControlExprRegion"],
    },
    ExprBlock {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      stmts [many [ty "MoonTree.Stmt"]],
      result [ty "MoonTree.Expr"],
    },
    ExprClosure {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      params [many [ty "MoonType.Param"]],
      result [ty "MoonType.Type"],
      body [many [ty "MoonTree.Stmt"]],
    },
    ExprView { variant_unique, h [ty "MoonTree.ExprHeader"], view [ty "MoonTree.View"], },
    ExprLoad {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      field "ty" [ty "MoonType.Type"],
      addr [ty "MoonTree.Expr"],
    },
    ExprAtomicLoad {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      field "ty" [ty "MoonType.Type"],
      addr [ty "MoonTree.Expr"],
      ordering [ty "MoonCore.AtomicOrdering"],
    },
    ExprAtomicRmw {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      op [ty "MoonCore.AtomicRmwOp"],
      field "ty" [ty "MoonType.Type"],
      addr [ty "MoonTree.Expr"],
      field "value" [ty "MoonTree.Expr"],
      ordering [ty "MoonCore.AtomicOrdering"],
    },
    ExprAtomicCas {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      field "ty" [ty "MoonType.Type"],
      addr [ty "MoonTree.Expr"],
      expected [ty "MoonTree.Expr"],
      replacement [ty "MoonTree.Expr"],
      ordering [ty "MoonCore.AtomicOrdering"],
    },
    ExprSlotValue { variant_unique, h [ty "MoonTree.ExprHeader"], slot [ty "MoonOpen.ExprSlot"], },
    ExprUseExprFrag {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      use_id [str],
      frag [ty "MoonOpen.ExprFragRef"],
      args [many [ty "MoonTree.Expr"]],
      fills [many [ty "MoonOpen.SlotBinding"]],
    },
    ExprCtor {
      variant_unique,
      h [ty "MoonTree.ExprHeader"],
      type_name [str],
      variant_name [str],
      args [many [ty "MoonTree.Expr"]],
    },
    ExprNull { variant_unique, h [ty "MoonTree.ExprHeader"], elem [ty "MoonType.Type"], },
    ExprSizeOf { variant_unique, h [ty "MoonTree.ExprHeader"], field "ty" [ty "MoonType.Type"], },
    ExprAlignOf { variant_unique, h [ty "MoonTree.ExprHeader"], field "ty" [ty "MoonType.Type"], },
    ExprIsNull { variant_unique, h [ty "MoonTree.ExprHeader"], field "value" [ty "MoonTree.Expr"], },
  },
  sum. Stmt {
    StmtLet {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      binding [ty "MoonBind.Binding"],
      init [ty "MoonTree.Expr"],
    },
    StmtVar {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      binding [ty "MoonBind.Binding"],
      init [ty "MoonTree.Expr"],
    },
    StmtSet {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      place [ty "MoonTree.Place"],
      field "value" [ty "MoonTree.Expr"],
    },
    StmtAtomicStore {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      field "ty" [ty "MoonType.Type"],
      addr [ty "MoonTree.Expr"],
      field "value" [ty "MoonTree.Expr"],
      ordering [ty "MoonCore.AtomicOrdering"],
    },
    StmtAtomicFence {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      ordering [ty "MoonCore.AtomicOrdering"],
    },
    StmtExpr { variant_unique, h [ty "MoonTree.StmtHeader"], field "expr" [ty "MoonTree.Expr"], },
    StmtAssert { variant_unique, h [ty "MoonTree.StmtHeader"], cond [ty "MoonTree.Expr"], },
    StmtIf {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      cond [ty "MoonTree.Expr"],
      then_body [many [ty "MoonTree.Stmt"]],
      else_body [many [ty "MoonTree.Stmt"]],
    },
    StmtSwitch {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      field "value" [ty "MoonTree.Expr"],
      arms [many [ty "MoonTree.SwitchStmtArm"]],
      variant_arms [many [ty "MoonTree.SwitchVariantStmtArm"]],
      default_body [many [ty "MoonTree.Stmt"]],
    },
    StmtJump {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      target [ty "MoonTree.BlockLabel"],
      args [many [ty "MoonTree.JumpArg"]],
    },
    StmtJumpCont {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      slot [ty "MoonOpen.ContSlot"],
      args [many [ty "MoonTree.JumpArg"]],
    },
    StmtYieldVoid { variant_unique, h [ty "MoonTree.StmtHeader"], },
    StmtYieldValue {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      field "value" [ty "MoonTree.Expr"],
    },
    StmtReturnVoid { variant_unique, h [ty "MoonTree.StmtHeader"], },
    StmtReturnValue {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      field "value" [ty "MoonTree.Expr"],
    },
    StmtControl {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      region [ty "MoonTree.ControlStmtRegion"],
    },
    StmtUseRegionSlot {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      slot [ty "MoonOpen.RegionSlot"],
    },
    StmtUseRegionFrag {
      variant_unique,
      h [ty "MoonTree.StmtHeader"],
      mode [ty "MoonTree.RegionUseMode"],
      use_id [str],
      frag [ty "MoonOpen.RegionFragRef"],
      args [many [ty "MoonTree.Expr"]],
      fills [many [ty "MoonOpen.SlotBinding"]],
      cont_fills [many [ty "MoonOpen.ContBinding"]],
    },
    StmtTrap { variant_unique, h [ty "MoonTree.StmtHeader"], },
  },
  sum. Func {
    FuncLocal {
      variant_unique,
      field "name" [str],
      params [many [ty "MoonType.Param"]],
      result [ty "MoonType.Type"],
      body [many [ty "MoonTree.Stmt"]],
    },
    FuncExport {
      variant_unique,
      field "name" [str],
      params [many [ty "MoonType.Param"]],
      result [ty "MoonType.Type"],
      body [many [ty "MoonTree.Stmt"]],
    },
    FuncLocalContract {
      variant_unique,
      field "name" [str],
      params [many [ty "MoonType.Param"]],
      result [ty "MoonType.Type"],
      contracts [many [ty "MoonTree.FuncContract"]],
      body [many [ty "MoonTree.Stmt"]],
    },
    FuncExportContract {
      variant_unique,
      field "name" [str],
      params [many [ty "MoonType.Param"]],
      result [ty "MoonType.Type"],
      contracts [many [ty "MoonTree.FuncContract"]],
      body [many [ty "MoonTree.Stmt"]],
    },
    FuncDecl {
      variant_unique,
      field "name" [str],
      params [many [ty "MoonType.Param"]],
      result [ty "MoonType.Type"],
    },
    FuncOpen {
      variant_unique,
      sym [ty "MoonCore.FuncSym"],
      visibility [ty "MoonCore.Visibility"],
      params [many [ty "MoonOpen.OpenParam"]],
      open [ty "MoonOpen.OpenSet"],
      result [ty "MoonType.Type"],
      body [many [ty "MoonTree.Stmt"]],
    },
  },
  sum. ExternFunc {
    ExternFunc {
      variant_unique,
      field "name" [str],
      symbol [str],
      params [many [ty "MoonType.Param"]],
      result [ty "MoonType.Type"],
    },
    ExternFuncOpen {
      variant_unique,
      sym [ty "MoonCore.ExternSym"],
      params [many [ty "MoonOpen.OpenParam"]],
      result [ty "MoonType.Type"],
    },
  },
  sum. ConstItem {
    ConstItem {
      variant_unique,
      field "name" [str],
      field "ty" [ty "MoonType.Type"],
      field "value" [ty "MoonTree.Expr"],
    },
    ConstItemOpen {
      variant_unique,
      sym [ty "MoonCore.ConstSym"],
      open [ty "MoonOpen.OpenSet"],
      field "ty" [ty "MoonType.Type"],
      field "value" [ty "MoonTree.Expr"],
    },
  },
  sum. StaticItem {
    StaticItem {
      variant_unique,
      field "name" [str],
      field "ty" [ty "MoonType.Type"],
      field "value" [ty "MoonTree.Expr"],
    },
    StaticItemOpen {
      variant_unique,
      sym [ty "MoonCore.StaticSym"],
      open [ty "MoonOpen.OpenSet"],
      field "ty" [ty "MoonType.Type"],
      field "value" [ty "MoonTree.Expr"],
    },
  },
  product. ImportItem { interned, path [ty "MoonCore.Path"], },
  sum. TypeDecl {
    TypeDeclStruct { variant_unique, field "name" [str], fields [many [ty "MoonType.FieldDecl"]], },
    TypeDeclUnion { variant_unique, field "name" [str], fields [many [ty "MoonType.FieldDecl"]], },
    TypeDeclEnumSugar { variant_unique, field "name" [str], variants [many [ty "MoonCore.Name"]], },
    TypeDeclTaggedUnionSugar {
      variant_unique,
      field "name" [str],
      variants [many [ty "MoonType.VariantDecl"]],
    },
    TypeDeclHandle {
      variant_unique,
      field "name" [str],
      repr [ty "MoonType.HandleRepr"],
      invalid [ty "MoonType.HandleInvalid"],
      facts [many [ty "MoonType.HandleFact"]],
    },
    TypeDeclOpenStruct {
      variant_unique,
      sym [ty "MoonCore.TypeSym"],
      fields [many [ty "MoonType.FieldDecl"]],
    },
    TypeDeclOpenUnion {
      variant_unique,
      sym [ty "MoonCore.TypeSym"],
      fields [many [ty "MoonType.FieldDecl"]],
    },
  },
  sum. Item {
    ItemFunc { variant_unique, func [ty "MoonTree.Func"], },
    ItemExtern { variant_unique, func [ty "MoonTree.ExternFunc"], },
    ItemConst { variant_unique, c [ty "MoonTree.ConstItem"], },
    ItemStatic { variant_unique, s [ty "MoonTree.StaticItem"], },
    ItemImport { variant_unique, imp [ty "MoonTree.ImportItem"], },
    ItemType { variant_unique, t [ty "MoonTree.TypeDecl"], },
    ItemRegionFrag { variant_unique, frag [ty "MoonOpen.RegionFrag"], },
    ItemExprFrag { variant_unique, frag [ty "MoonOpen.ExprFrag"], },
    ItemUseTypeDeclSlot { variant_unique, slot [ty "MoonOpen.TypeDeclSlot"], },
    ItemUseItemsSlot { variant_unique, slot [ty "MoonOpen.ItemsSlot"], },
    ItemUseModule {
      variant_unique,
      use_id [str],
      field "module" [ty "MoonTree.Module"],
      fills [many [ty "MoonOpen.SlotBinding"]],
    },
    ItemUseModuleSlot {
      variant_unique,
      use_id [str],
      slot [ty "MoonOpen.ModuleSlot"],
      fills [many [ty "MoonOpen.SlotBinding"]],
    },
    ItemData { variant_unique, data [ty "MoonTree.DataItem"], },
  },
  product. DataItem {
    interned,
    field "id" [ty "MoonCore.DataId"],
    size [number],
    align [number],
    bytes [str],
  },
  sum. ModuleHeader {
    ModuleSurface,
    ModuleTyped { variant_unique, module_name [str], },
    ModuleOpen {
      variant_unique,
      field "name" [ty "MoonOpen.ModuleNameFacet"],
      open [ty "MoonOpen.OpenSet"],
    },
    ModuleSem { variant_unique, module_name [str], },
    ModuleCode { variant_unique, module_name [str], },
  },
  product. Module { interned, h [ty "MoonTree.ModuleHeader"], items [many [ty "MoonTree.Item"]], },
  sum. TypeIssue {
    TypeIssueUnresolvedValue { variant_unique, field "name" [str], },
    TypeIssueUnresolvedPath { variant_unique, path [ty "MoonCore.Path"], },
    TypeIssueExpected {
      variant_unique,
      site [str],
      expected [ty "MoonType.Type"],
      actual [ty "MoonType.Type"],
    },
    TypeIssueArgCount { variant_unique, site [str], expected [number], actual [number], },
    TypeIssueNotCallable { variant_unique, field "ty" [ty "MoonType.Type"], },
    TypeIssueNotIndexable { variant_unique, field "ty" [ty "MoonType.Type"], },
    TypeIssueNotPointer { variant_unique, field "ty" [ty "MoonType.Type"], },
    TypeIssueInvalidUnary { variant_unique, op [str], field "ty" [ty "MoonType.Type"], },
    TypeIssueInvalidBinary {
      variant_unique,
      op [str],
      lhs [ty "MoonType.Type"],
      rhs [ty "MoonType.Type"],
    },
    TypeIssueInvalidCompare {
      variant_unique,
      op [str],
      lhs [ty "MoonType.Type"],
      rhs [ty "MoonType.Type"],
    },
    TypeIssueInvalidLogic {
      variant_unique,
      op [str],
      lhs [ty "MoonType.Type"],
      rhs [ty "MoonType.Type"],
    },
    TypeIssueMissingJumpTarget {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
    },
    TypeIssueMissingJumpArg {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      field "name" [str],
    },
    TypeIssueExtraJumpArg {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      field "name" [str],
    },
    TypeIssueDuplicateJumpArg {
      variant_unique,
      region_id [str],
      label [ty "MoonTree.BlockLabel"],
      field "name" [str],
    },
    TypeIssueUnexpectedYield { variant_unique, site [str], },
    TypeIssueInvalidControl {
      variant_unique,
      region_id [str],
      reject [ty "MoonTree.ControlReject"],
    },
    TypeIssueUnknownVariant { variant_unique, type_name [str], variant_name [str], },
    TypeIssueVariantPayloadMismatch {
      variant_unique,
      type_name [str],
      variant_name [str],
      expected [ty "MoonType.Type"],
      actual [ty "MoonType.Type"],
    },
    TypeIssueDuplicateVariant { variant_unique, type_name [str], variant_name [str], },
  },
  sum. TypeYieldMode {
    TypeYieldNone,
    TypeYieldVoid,
    TypeYieldValue { variant_unique, field "ty" [ty "MoonType.Type"], },
  },
  product. TypeCheckEnv {
    interned,
    env [ty "MoonBind.Env"],
    return_ty [ty "MoonType.Type"],
    yield [ty "MoonTree.TypeYieldMode"],
    region_frags [many [ty "MoonOpen.RegionFrag"]],
  },
  sum. TypeViewResult {
    TypeViewResult {
      variant_unique,
      view [ty "MoonTree.View"],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypeIndexBaseResult {
    TypeIndexBaseResult {
      variant_unique,
      base [ty "MoonTree.IndexBase"],
      elem [ty "MoonType.Type"],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypeControlStmtRegionResult {
    TypeControlStmtRegionResult {
      variant_unique,
      region [ty "MoonTree.ControlStmtRegion"],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypeControlExprRegionResult {
    TypeControlExprRegionResult {
      variant_unique,
      region [ty "MoonTree.ControlExprRegion"],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypeExprResult {
    TypeExprResult {
      variant_unique,
      field "expr" [ty "MoonTree.Expr"],
      field "ty" [ty "MoonType.Type"],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypePlaceResult {
    TypePlaceResult {
      variant_unique,
      place [ty "MoonTree.Place"],
      field "ty" [ty "MoonType.Type"],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypeStmtResult {
    TypeStmtResult {
      variant_unique,
      env [ty "MoonTree.TypeCheckEnv"],
      stmts [many [ty "MoonTree.Stmt"]],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypeFuncResult {
    TypeFuncResult {
      variant_unique,
      func [ty "MoonTree.Func"],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypeItemResult {
    TypeItemResult {
      variant_unique,
      items [many [ty "MoonTree.Item"]],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TypeModuleResult {
    TypeModuleResult {
      variant_unique,
      field "module" [ty "MoonTree.Module"],
      issues [many [ty "MoonTree.TypeIssue"]],
    },
  },
  sum. TreeBackLocal {
    TreeBackScalarLocal {
      variant_unique,
      binding [ty "MoonBind.Binding"],
      field "value" [ty "MoonBack.BackValId"],
      field "ty" [ty "MoonBack.BackScalar"],
    },
    TreeBackStackLocal {
      variant_unique,
      binding [ty "MoonBind.Binding"],
      slot [ty "MoonBack.BackStackSlotId"],
      field "ty" [ty "MoonBack.BackScalar"],
    },
    TreeBackViewLocal {
      variant_unique,
      binding [ty "MoonBind.Binding"],
      data [ty "MoonBack.BackValId"],
      len [ty "MoonBack.BackValId"],
    },
    TreeBackStridedViewLocal {
      variant_unique,
      binding [ty "MoonBind.Binding"],
      data [ty "MoonBack.BackValId"],
      len [ty "MoonBack.BackValId"],
      stride [ty "MoonBack.BackValId"],
    },
  },
  sum. TreeBackReturn {
    TreeBackReturnScalar,
    TreeBackReturnView { variant_unique, out [ty "MoonBack.BackValId"], },
  },
  product. TreeBackEnv {
    interned,
    locals [many [ty "MoonTree.TreeBackLocal"]],
    next_value [number],
    next_block [number],
    ret [ty "MoonTree.TreeBackReturn"],
  },
  sum. TreeBackExprResult {
    TreeBackExprValue {
      variant_unique,
      env [ty "MoonTree.TreeBackEnv"],
      cmds [many [ty "MoonBack.Cmd"]],
      field "value" [ty "MoonBack.BackValId"],
      field "ty" [ty "MoonBack.BackScalar"],
    },
    TreeBackExprView {
      variant_unique,
      env [ty "MoonTree.TreeBackEnv"],
      cmds [many [ty "MoonBack.Cmd"]],
      data [ty "MoonBack.BackValId"],
      len [ty "MoonBack.BackValId"],
    },
    TreeBackExprStridedView {
      variant_unique,
      env [ty "MoonTree.TreeBackEnv"],
      cmds [many [ty "MoonBack.Cmd"]],
      data [ty "MoonBack.BackValId"],
      len [ty "MoonBack.BackValId"],
      stride [ty "MoonBack.BackValId"],
    },
    TreeBackExprUnsupported {
      variant_unique,
      env [ty "MoonTree.TreeBackEnv"],
      cmds [many [ty "MoonBack.Cmd"]],
      reason [str],
    },
  },
  sum. TreeBackStmtResult {
    TreeBackStmtResult {
      variant_unique,
      env [ty "MoonTree.TreeBackEnv"],
      cmds [many [ty "MoonBack.Cmd"]],
      flow [ty "MoonBack.BackFlow"],
    },
  },
  sum. TreeBackFuncResult {
    TreeBackFuncResult { variant_unique, cmds [many [ty "MoonBack.Cmd"]], },
  },
  sum. TreeBackItemResult {
    TreeBackItemResult { variant_unique, cmds [many [ty "MoonBack.Cmd"]], },
  },
}
