local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonType {
  sum. TypeRef {
    TypeRefPath { variant_unique, path [ty. MoonCore.Path], },
    TypeRefGlobal { variant_unique, module_name [str], type_name [str], },
    TypeRefLocal { variant_unique, sym [ty. MoonCore.TypeSym], },
    TypeRefSlot { variant_unique, slot [ty. MoonOpen.TypeSlot], },
  },
  sum. ArrayLen {
    ArrayLenExpr { variant_unique, field. expr [ty. MoonTree.Expr], },
    ArrayLenConst { variant_unique, count [number], },
    ArrayLenSlot { variant_unique, slot [ty. MoonOpen.ExprSlot], },
  },
  sum. HandleRepr { HandleReprScalar { variant_unique, scalar [ty. MoonCore.Scalar], }, },
  sum. HandleInvalid { HandleInvalidNone, HandleInvalidInt { variant_unique, raw [str], }, },
  sum. HandleFact {
    HandleDomain { variant_unique, domain [ty. MoonType.TypeRef], },
    HandleTarget { variant_unique, target [ty. MoonType.TypeRef], },
  },
  sum. LeaseOrigin { LeaseOriginUnknown, LeaseOriginParam { variant_unique, field. name [str], }, },
  sum. TypeAccess {
    TypeAccessNoAlias,
    TypeAccessReadonly,
    TypeAccessWriteonly,
    TypeAccessNoEscape,
    TypeAccessInvalidate,
    TypeAccessPreserve,
  },
  sum. Type {
    TScalar { variant_unique, scalar [ty. MoonCore.Scalar], },
    TPtr { variant_unique, elem [ty. MoonType.Type], },
    TArray { variant_unique, count [ty. MoonType.ArrayLen], elem [ty. MoonType.Type], },
    TSlice { variant_unique, elem [ty. MoonType.Type], },
    TView { variant_unique, elem [ty. MoonType.Type], },
    TLease { variant_unique, base [ty. MoonType.Type], origin [ty. MoonType.LeaseOrigin], },
    TOwned { variant_unique, base [ty. MoonType.Type], },
    TAccess { variant_unique, access [ty. MoonType.TypeAccess], base [ty. MoonType.Type], },
    THandle {
      variant_unique,
      field. ref [ty. MoonType.TypeRef],
      repr [ty. MoonType.HandleRepr],
    },
    TFunc { variant_unique, params [many [ty. MoonType.Type]], result [ty. MoonType.Type], },
    TClosure { variant_unique, params [many [ty. MoonType.Type]], result [ty. MoonType.Type], },
    TNamed { variant_unique, field. ref [ty. MoonType.TypeRef], },
    TSlot { variant_unique, slot [ty. MoonOpen.TypeSlot], },
    TCType { variant_unique, field. id [ty. MoonC.CTypeId], },
    TCFuncPtr { variant_unique, sig [ty. MoonC.CFuncSigId], },
  },
  sum. TypeClass {
    TypeClassScalar { variant_unique, scalar [ty. MoonCore.Scalar], },
    TypeClassPointer { variant_unique, elem [ty. MoonType.Type], },
    TypeClassArray { variant_unique, elem [ty. MoonType.Type], count [number], },
    TypeClassSlice { variant_unique, elem [ty. MoonType.Type], },
    TypeClassView { variant_unique, elem [ty. MoonType.Type], },
    TypeClassLease {
      variant_unique,
      base [ty. MoonType.Type],
      origin [ty. MoonType.LeaseOrigin],
    },
    TypeClassOwned { variant_unique, base [ty. MoonType.Type], },
    TypeClassHandle { variant_unique, repr [ty. MoonType.HandleRepr], },
    TypeClassCallable {
      variant_unique,
      params [many [ty. MoonType.Type]],
      result [ty. MoonType.Type],
    },
    TypeClassClosure {
      variant_unique,
      params [many [ty. MoonType.Type]],
      result [ty. MoonType.Type],
    },
    TypeClassAggregate { variant_unique, module_name [str], type_name [str], },
    TypeClassUnknown,
  },
  sum. TypeBackScalarResult {
    TypeBackScalarKnown { variant_unique, scalar [ty. MoonBack.BackScalar], },
    TypeBackScalarUnavailable {
      variant_unique,
      field. ty [ty. MoonType.Type],
      class [ty. MoonType.TypeClass],
    },
  },
  sum. TypeMemLayoutResult {
    TypeMemLayoutKnown { variant_unique, layout [ty. MoonSem.MemLayout], },
    TypeMemLayoutUnknown {
      variant_unique,
      field. ty [ty. MoonType.Type],
      class [ty. MoonType.TypeClass],
    },
  },
  sum. AbiClass {
    AbiIgnore,
    AbiDirect { variant_unique, scalar [ty. MoonBack.BackScalar], },
    AbiIndirect { variant_unique, layout [ty. MoonSem.MemLayout], },
    AbiDescriptor { variant_unique, layout [ty. MoonSem.MemLayout], },
    AbiUnknown { variant_unique, class [ty. MoonType.TypeClass], },
  },
  product. AbiDecision {
    interned,
    field. ty [ty. MoonType.Type],
    class [ty. MoonType.AbiClass],
  },
  sum. AbiParamPlan {
    AbiParamScalar {
      variant_unique,
      field. name [str],
      binding [ty. MoonBind.Binding],
      scalar [ty. MoonBack.BackScalar],
      field. value [ty. MoonBack.BackValId],
    },
    AbiParamView {
      variant_unique,
      field. name [str],
      binding [ty. MoonBind.Binding],
      data [ty. MoonBack.BackValId],
      len [ty. MoonBack.BackValId],
      stride [ty. MoonBack.BackValId],
    },
    AbiParamRejected {
      variant_unique,
      field. name [str],
      field. ty [ty. MoonType.Type],
      reason [str],
    },
  },
  sum. AbiResultPlan {
    AbiResultVoid,
    AbiResultScalar { variant_unique, scalar [ty. MoonBack.BackScalar], },
    AbiResultView { variant_unique, elem [ty. MoonType.Type], out [ty. MoonBack.BackValId], },
    AbiResultRejected { variant_unique, field. ty [ty. MoonType.Type], reason [str], },
  },
  product. FuncAbiPlan {
    interned,
    func_name [str],
    params [many [ty. MoonType.AbiParamPlan]],
    result [ty. MoonType.AbiResultPlan],
  },
  product. Param { interned, field. name [str], field. ty [ty. MoonType.Type], },
  product. FieldDecl { interned, field_name [str], field. ty [ty. MoonType.Type], },
  product. VariantDecl {
    interned,
    field. name [str],
    payload [ty. MoonType.Type],
    fields [many [ty. MoonType.FieldDecl]],
  },
}
