local S = require("moonlift.schema.dsl")
S.use()

return schema. MoonValue {
  product. ValueFactId { interned, text [str], },
  product. AlgebraFactId { interned, text [str], },
  sum. ValueExpr {
    ValueExprConst { variant_unique, const [ty. MoonCode.CodeConst], },
    ValueExprValue { variant_unique, field. value [ty. MoonCode.CodeValueId], },
    ValueExprAdd {
      variant_unique,
      a [ty. MoonValue.ValueExpr],
      b [ty. MoonValue.ValueExpr],
      field. ty [ty. MoonCode.CodeType],
      sem [optional [ty. MoonCode.CodeIntSemantics]],
    },
    ValueExprSub {
      variant_unique,
      a [ty. MoonValue.ValueExpr],
      b [ty. MoonValue.ValueExpr],
      field. ty [ty. MoonCode.CodeType],
      sem [optional [ty. MoonCode.CodeIntSemantics]],
    },
    ValueExprMul {
      variant_unique,
      a [ty. MoonValue.ValueExpr],
      b [ty. MoonValue.ValueExpr],
      field. ty [ty. MoonCode.CodeType],
      sem [optional [ty. MoonCode.CodeIntSemantics]],
    },
    ValueExprDiv {
      variant_unique,
      a [ty. MoonValue.ValueExpr],
      b [ty. MoonValue.ValueExpr],
      field. ty [ty. MoonCode.CodeType],
      sem [optional [ty. MoonCode.CodeIntSemantics]],
    },
    ValueExprSelect {
      variant_unique,
      cond [ty. MoonValue.ValueExpr],
      t [ty. MoonValue.ValueExpr],
      f [ty. MoonValue.ValueExpr],
    },
    ValueExprCmp {
      variant_unique,
      op [ty. MoonCore.CmpOp],
      field. ty [ty. MoonCode.CodeType],
      a [ty. MoonValue.ValueExpr],
      b [ty. MoonValue.ValueExpr],
    },
    ValueExprAffine { variant_unique, affine [ty. MoonValue.AffineExpr], },
  },
  product. AffineTerm { interned, field. value [ty. MoonCode.CodeValueId], coeff [str], },
  product. AffineExpr {
    interned,
    constant [str],
    terms [many [ty. MoonValue.AffineTerm]],
    field. ty [ty. MoonCode.CodeType],
    sem [optional [ty. MoonCode.CodeIntSemantics]],
  },
  sum. ValueRange {
    ValueRangeUnknown { variant_unique, reason [str], },
    ValueRangeInt {
      variant_unique,
      field. value [ty. MoonCode.CodeValueId],
      lo [ty. MoonValue.ValueExpr],
      hi [ty. MoonValue.ValueExpr],
      inclusive_hi [bool],
      proof [ty. MoonValue.AlgebraProof],
    },
  },
  sum. ReductionKind {
    ReductionAdd,
    ReductionMul,
    ReductionMin,
    ReductionMax,
    ReductionAnd,
    ReductionOr,
    ReductionXor,
  },
  product. ReductionFact {
    interned,
    field. id [ty. MoonValue.AlgebraFactId],
    domain [ty. MoonFlow.FlowDomain],
    accumulator [ty. MoonCode.CodeValueId],
    kind [ty. MoonValue.ReductionKind],
    init [ty. MoonValue.ValueExpr],
    contribution [ty. MoonValue.ValueExpr],
    field. ty [ty. MoonCode.CodeType],
    int_semantics [optional [ty. MoonCode.CodeIntSemantics]],
    float_mode [optional [ty. MoonCode.CodeFloatMode]],
    proof [ty. MoonValue.AlgebraProof],
  },
  product. ClosedFormFact {
    interned,
    field. id [ty. MoonValue.AlgebraFactId],
    reduction [ty. MoonValue.ReductionFact],
    field. expr [ty. MoonValue.ValueExpr],
    proof [ty. MoonValue.AlgebraProof],
  },
  sum. AlgebraProof {
    AlgebraProofFlow { variant_unique, domain [ty. MoonFlow.FlowDomain], reason [str], },
    AlgebraProofNoWrap { variant_unique, field. value [ty. MoonCode.CodeValueId], reason [str], },
    AlgebraProofIdentity { variant_unique, reason [str], },
    AlgebraProofReduction { variant_unique, fact [ty. MoonValue.ReductionFact], reason [str], },
    AlgebraProofComposite {
      variant_unique,
      proofs [many [ty. MoonValue.AlgebraProof]],
      reason [str],
    },
  },
  sum. ValueFact {
    ValueExprFact {
      variant_unique,
      field. value [ty. MoonCode.CodeValueId],
      field. expr [ty. MoonValue.ValueExpr],
      proof [ty. MoonValue.AlgebraProof],
    },
    ValueRangeFact { variant_unique, range [ty. MoonValue.ValueRange], },
    ValueNoWrapFact {
      variant_unique,
      field. value [ty. MoonCode.CodeValueId],
      sem [ty. MoonCode.CodeIntSemantics],
      proof [ty. MoonValue.AlgebraProof],
    },
    ValueFloatModeFact {
      variant_unique,
      field. value [ty. MoonCode.CodeValueId],
      mode [ty. MoonCode.CodeFloatMode],
      proof [ty. MoonValue.AlgebraProof],
    },
  },
  product. ValueFactSet {
    interned,
    field. module [ty. MoonCode.CodeModuleId],
    values [many [ty. MoonValue.ValueFact]],
    reductions [many [ty. MoonValue.ReductionFact]],
    closed_forms [many [ty. MoonValue.ClosedFormFact]],
  },
}
